### ISSUE TITLE
Feature: Paramter option using letters instead of numbers for easy rememebring

### ISSUE THREAD

**Issue by vdun** [hashcat/hashcat#1000]
e.g. for the parameter `-a, --attack-mode` :
```
0=Straight -> s
1=Combination -> c
3=Brute-force -> b
6=Hybrid Wordlist + Mask -> hwm
7=Hybrid Mask + Wordlist -> hmw
```
also keep the numbers for drawback compatibility.

**Comment by milzo247** [comment]
It can't be that difficult to remember all of 5 numbers and what they define.
Good luck getting that implemented.

**Comment by roycewilliams** [comment]
I've been using hashcat for a couple of years and I sometimes have to stop to think about it. :)  The current method is a relatively rare way to handle options.

I wouldn't mind seeing something like --attack-mode [straight|combination|bruteforce|wordlist-mask|mask-wordlist], with minimum-disambiguation strings (s,c,b,w,m) allowed. The mode numbers would also still be allowed, of course.

It would also make the examples self-documenting, and easier for new users to understand.

**Comment by jsteube** [comment]
The problem is the more ambiguation strings you allow (for whatever parameter) the lower the chance for getting help from non-developers. That is because most users, once they have an understanding of the option, do not care about changes that are added later to the option. 

If a new users steps into hashcat universe and needs help but then uses such ambiguation the people that maybe could know the answer get confused by the ambiguation and stop thinking about helping them.

**Comment by roycewilliams** [comment]
Playing devil's advocate for a moment ...

If the usability problem that you're describing was widespread and considered to not be worth the tradeoff, more projects would use numeric commandline options.

The disambiguation problem that you're describing is one that every other mature command-line utility that I'm aware of (outside of the hashcat family) manages. I don't know of any other mature project outside of the hashcat family that relies solely on numeric options.
