### ISSUE TITLE
HMAC-SHA512  salt 500 characters

### ISSUE THREAD

**Issue by lukasz1991a** [hashcat/hashcat#1004]
I need to recover password encoded using sha 512 (m1760) with salt having 500 characters

**Comment by jsteube** [comment]
Where is it used in?

**Comment by lukasz1991a** [comment]
It is a lot of interference in the system kernel to increase the salt to 500 characters?

**Comment by jsteube** [comment]
For a quick hack it's very simple but for permanent use it's too much
work to do it without a good reason.

**Comment by lukasz1991a** [comment]
I do not know the language in which it is written. I tried on intuition and I had a memory error. I could ask you how to do it for this one mode?

**Comment by jsteube** [comment]
The programming language is C. I'm not going to do any code change here
unless I know where this is used in and if other people could make use
of it as well. Please close the issue otherwise as Github issues is for
bugs and feature requests only.

If you want to patch it yourself: You only need to patch hash generation
before the ipad[] and opad[] is stored. If you need to crack only one
hash it should be pretty simple to do. Just push the salt as constants
in the kernel. Not host code changes required.

**Comment by lukasz1991a** [comment]
at which point I declare SALT statically. What file.

**Comment by lukasz1991a** [comment]
pleas help me. tell me where to look.

**Comment by lukasz1991a** [comment]
It's very important to me. But still I'm doing something wrong. I have a memory error. kernel switched off checking the length, the variable tmp designated with salt to stiff - changing its type in the file m01760 I had bad salt. What would you like for your help?
