### ISSUE TITLE
Longer hash length support

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#1023]
Getting a hash from a split 7-zip archive, is generally quite long and hashcat doesn't like that.

https://github.com/philsmd/7z2hashcat/issues/9#issuecomment-277545928

**Comment by magnumripper** [comment]
This applies to non-split vanilla archives too, the hash often ends up too long for Hashcat.

**Comment by philsmd** [comment]
I tried the hash you provided and it just works as it should (maybe you are just using an older version of hashcat?):

```
./hashcat -m 11600 -a 3 --quiet mega.txt wetwilly20?d?d
$7z$1$19$0$$8$f25e0c9dbe5f45910000000000000000$2892453778$512$510$e598324b3892f3774dcb7d5cb581ea341e86b103667c3b458e5e4351198c6efac3f6acfdd75311417653854f28652b6a5630ac9e4edaa809ffd5df9d0d3323fc18c27f5491795c58a8eacd01436e4b42b4ba868414598f29c1fdb42ce55a240c58df02fd01b9eff3e5c7c61db4e2deb802e7df17989f98895607741686acad12f6dee59d1efd0e0aaa19ee0b124d7f1c722e55b97e1929be26eee703cf3a6777a57219e1111390c069a8d74a44babcbd80eb0e6c92e67b743c3bdf03870b5486b1d4a1d89b3e01f49ffa12a1c738625eae3a5c7bd3106ef38eb4dd9deb1304f770563c049a9f732ed63eb752c384fbcab914caa9220c5e20cd9096c6fca29a3a088c07eb6d441295082e842154b522c6e54c0dbd25ef2294e2dc5bc718c733def90e15a7f7ee64dc7001720847216fd3f06f63b3f34331739b69afe2deb73844a0f424e387604090be88cb2d1328e56283ff0c63d150bb718a416ac155fe560812ecdcbb289377a9198d4551577aa6c2e8925227964c2e0035dece6045f54859fa03ab768b34e2444064bb413177c85a18950dc2cae40bfa1039f54432314e563fb6ea78f54363f118b172a62621f44636b93378536792208fcfb7e527ee08ff9e7d5bbe0e12dd97bd3851895a8bb8c58f0da2217719521b14f9ef2cf8cf1fc8cc523e117be753407f4574a5fa9399c8bde7da231dd8e3cd20dd34ab00885d36$922$5d00100000:wetwilly2016
```

Note: the release version of course is not up-to-date here, because we made some changes recently, for instance this one: https://github.com/hashcat/hashcat/issues/965

I would say we close this because for example the beta versions: https://hashcat.net/beta/ already supported this type of longer inputs for -m 11600 after we closed issue #965 
 
Remember: only @lavanoid and the repository admins (or whoever have full permission) can close the issue. So please test and don't forget to close the issue if it was "pebcak".

---

BTW: please consider giving the issues more meaningful names "longer hash length" could mean anything, If it still were a problem, which it is not, it would be something very specific to -m 11600 = 7-Zip and therefore you should mention it in the issue title. Thanks

**Comment by magnumripper** [comment]
Oh, that's great! Wasn't mentioned in commit description so I had no idea it was fixed. So is there virtually no limit now? Just OS/FS limits?

**Comment by philsmd** [comment]
For the time being it was just increased a little bit: https://github.com/philsmd/hashcat/commit/6fe0173a79fa9afcaf74bd2385a85c93f92df5bc#diff-e499f13732ab92b6ade223fa29cf9da3R1091 ( I actually also think we should make this a macro, not hard-code it). Yeah, it could be increased to whatever limit (or even no limit at all), but as we usually prefer to add some upper-limit in hashcat, the decision was to just increase it.
btw, 7z2hashcat.pl should always reflect this limit with the PASSWORD_RECOVERY_TOOL_DATA_LIMIT variable (I thought you were aware of this variable?).
Thanks

**Comment by jsteube** [comment]
I think it's fine as it is. Please reopen the issue if you can not live with it ;)
