### ISSUE TITLE
ADL_Overdrive6_FanSpeed_Reset(): -8 Error With RX 470 on Windows 10 

### ISSUE THREAD

**Issue by llazzaro** [hashcat/hashcat#1054]
I was testing hashcat 3.30 and I got this error:

ADL_Overdrive6_FanSpeed_Reset(): -8
Failed to restore default fan speed and policy for device #1
ADL_Overdrive6_FanSpeed_Reset(): -8
Failed to restore default fan speed and policy for device #3

My GPU is an Asus rx 470 4gb, in particular the model is ROG-STRIX-RX470-O4G-GAMING

**Comment by philsmd** [comment]
Hey,
I'm wondering why:

1. your post is formatted like this, e.g. why do you not just use a github "quote"/"code" section and use actual newlines instead of the "\r\n" strings?
2. why your output contains 2 errors and the topic is about the fan speed problem
3. therefore: are you sure that the "No hashes loaded" problem was expected and has nothing to do with your actual problem (it's just confusing why one would post 2 independent errors in a long line like this)?

The "No hashes loaded" should have something to do with your -m parameter and/or the format of the hashes (see https://hashcat.net/wiki/example_hashes).

Back to the fan speed problem, yeah, sometimes we get reports like this, often it has to do with non-reference design GPU(s): custom fan design, watercooled etc.... can you give more details about your GPU(s)?  The problem most of the time is, the non-reference design cards sometimes do not report the functionality/features of the card correctly... they tell hashcat something like this: "yeah, there is a fan and yeah you can monitor/control it", but actually (sometimes) there is no fan and no support for monitoring/controlling a fan.

More information is needed here
Thanks

**Comment by llazzaro** [comment]
I have updated my issue.
1. Updated. the error was copied from some log files
2. Forget about the No hashes loaded, the issue is about fan speed...the error was copied in the issue by mistake

**Comment by philsmd** [comment]
From reading the product description here: https://www.asus.com/Graphics-Cards/ROG-STRIX-RX470-O4G-GAMING/ ("and outperform reference designs", "Gaming" within the name etc), it seems that you are exactly in the situation described above, i.e. a non reference design with a custom cooler design... but probably they saved some cost on the firmware (and didn't change the feature list that the card supports).
BTW (from the include/adl_defines.h file of the ADL SDK) :

```
// Function  not supported by the driver
#define ADL_ERR_NOT_SUPPORTED     -8
```

Not sure if we can do anything about it, besides ignoring the error.

**Comment by llazzaro** [comment]
For now I will ignore the warning. I will try to check the code to see if I can do something to add support for this card.

**Comment by neheb** [comment]
You can't. I also have a card that errors on Nvapi. The issue is that your card is not a reference design

**Comment by jsteube** [comment]
As discussed, not a reference cooler
