### ISSUE TITLE
feature request: inverted Markov (least likely first)

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1058]
In some circumstances, I'd like to be able to try the least likely characters first. 

@epixoip semi-jokingly said that I should pitch this as a request for negative Markov thresholds. :)

**Comment by magnumripper** [comment]
Just out of curiosity, what is the use case? Hash collisions?

**Comment by roycewilliams** [comment]
I hadn't thought of that, but that seems interesting. I was thinking a few things, all of which basically boil down to "least likely is also interesting" :) :

1. For keyspaces small enough to exhaust on a given platform, the user can get a higher percentage of harder-to-crack plains first. Depending on your use case, that might be a feature.

2. For keyspaces too large to exhaust on a given platform, the user can explore parts of the "Markov keyspace" that would otherwise be inaccessible on that platform.

3. Now that we have display of candidates, the user can learn more about the far end of Markov.

Now that I think about it, "start the attack at this part of the Markov/keyspace" might be even better. It would provide a way to divide up the keyspace for distributed work, or a way to do a poor-man's resumption of work if the original work state was lost. If that would be easier than inverting it, that would be an interesting alternative.

**Comment by roycewilliams** [comment]
I don't actually understand enough about Markov to know whether it can be started/resumed at an arbitrary point in the keyspace without other session information. If it can't, my later idea above is nonsensical.

**Comment by jsteube** [comment]
Yes, hashcat can resume at an arbitrary point in the keyspace, because of the markov mode that hashcat is using.

The request itself would be doable, but would not do what you think it does, except in --stdout mode maybe. OTOH it requires to rewrite some of the core kernel which is not so easy to do (and then from the host to select the correct one).

In GPGPU, because of the high parallelization, there's no difference in the ording when you have small masks as they are using hybrid modes. This mean, for your usecase 1, this will not work. There are all started within a single kernel invocation and then it's up to the OpenCL runtime which thread is executed at which time. That means, we do not have a direct control over it. 

For large keyspace, like in BF, this is usecase 2, this would theoretically work, but for that case I don't see the advantage in this. It's not like the user runs hashcat with --stdout and then picks up the last password that comes out. And even if he would do that, it would be easier to make a wordlist of it and then hit it the same way.

For your usecase 3 I like that Idea if the markov mode would be a true markov mode. That is the total number of password candidates depend on the training data. But that's not the case in hashcat, because we can not reject candidates for fast hashes.

**Comment by roycewilliams** [comment]
I imagine that I could explore the far end of Markov for a given keyspace with the load-distribution features (--skip/--limit) and --stdout. I'll tinker with that. Thanks for the detailed explanation - should be informative for future searchers.

**Comment by roycewilliams** [comment]
For the curious, here's what (I think?) appears to be the other end of the current default markov for some sets of ?a:

```
$ hashcat --version
v3.5.0-76-gb924901b

$ hashcat -a 3 --skip=81450624 --limit=1 ?a?a?a?a?a?a?a --stdout | tail
'~}}~|~
)~}}~|~
:~}}~|~
{~}}~|~
\~}}~|~
]~}}~|~
>~}}~|~
|y}}~|~
}~}}~|~
 ~}}~|~


$ hashcat -a 3 --skip=7737809374 --limit=1 ?a?a?a?a?a?a?a?a --stdout | tail
'~}}~|~}
)~}}~|~}
:~}}~|~}
{~}}~|~}
\~}}~|~}
]~}}~|~}
>~}}~|~}
|y}}~|~}
}~}}~|~}
 ~}}~|~}

$ hashcat -a 3 --skip=735091890624 --limit=1 ?a?a?a?a?a?a?a?a?a --stdout | tail
'~}}~|~}~
)~}}~|~}~
:~}}~|~}~
{~}}~|~}~
\~}}~|~}~
]~}}~|~}~
>~}}~|~}~
|y}}~|~}~
}~}}~|~}~
 ~}}~|~}~
```

For more, see: https://gist.github.com/roycewilliams/68d7db44b60abddb707172b818d3b643

**Comment by roycewilliams** [comment]
FWIW, I also see this as an easy/lightweight way to get simple load-distribution effects without dividing up the keyspace, or in addition to dividing up the keyspace - even if only on a temporary basis, and quickly, since no calculations would be required. You can guess why I thought of this in the last 48 hours ;)

However, I now also think that the same effect could be achieved by having an option to the tool that creates the Markov stats file, to tell it to invert the Markov while creating it. This would provide more flexibility (and be much easier) than telling Hashcat itself to try to "invert" the Markov (which might be hard and it might not be clear how that would work anyway).

If it were simply a matter of inverting a basic frequency table, this could be simulated by inverting that table and then getting statistics from it. But Markov is obviously more complex than just frequency. :)

**Comment by roycewilliams** [comment]
Also useful if a defender is naively inverting Markov in order to maximize hashcat resistance:

https://twitter.com/jmgosney/status/1412421337591730184

**Comment by epixoip** [comment]
@roycewilliams you are a fucking visionary, haha.

This request should be reopened in light of Kaspersky password manager!

**Comment by RichiH** [comment]
![dis_gon_be_good](https://user-images.githubusercontent.com/754723/124635070-4f75bf00-de87-11eb-87aa-8eab4eaed9e4.gif)

(Tell me if the comment is too spammy; it just fits so well)

**Comment by jsteube** [comment]
Hey, what's the noise in this 3 year old thread? IIRC, the solution we discussed worked fine, does it not?

**Comment by RichiH** [comment]
Specific to Kaspersky, it might make sense to allow specifying a time range in which the passwords may have been generated to speed up cracking. That might fit better into a new issue, though.

**Comment by jsteube** [comment]
I mean this is really simple to add code like this. I'm a pragmatic guy. Instead of debating for years, I'll just add it. 

But just to double check with everyone, here's a small example of how it would affect the ordering:

- Have a close look!
- Think of a database trained with only a single password which is just a single letter 'b'.  So 'b' will be on top position.
- We use ?l mask for some attack

If you select --stdout, it would print:

```
b
a
c
d
e
f
...
z
```

With the negation you want, it would print:

```
a
c
d
e
f
...
z
b
```

Why is that? Because all letter have the weighting 0 assigned, but not the letter 'b' which has 1 assigned. After negation the weighting for letter 'a' and 'c' have changes, but both to the same value, so the ordering will not change. But this is an extreme example. With a real database, there will be no such collisions, but it's important to understand what's going on under the hood. 

With the default database the ?l mask would look like this (after negation):

```
x
u
q
z
y
o
v
w
e
i
n
f
g
h
k
r
t
d
j
l
p
a
b
c
m
s
```

Originally it is:

```
s
m
c
b
a
p
l
j
d
t
r
k
h
g
f
n
i
e
w
v
o
y
z
q
u
x
```

@roycewilliams @epixoip @RichiH Please confirm then I will send in the code change.

**Comment by epixoip** [comment]
Extreme example, indeed 🙂 I don't think that will cause much concern for the intended purpose, and I would say please proceed with implementing this. Perhaps with `--markov-inverse` switch, or as @yosignals suggested, `--vokram` 😆 

Just to catch you up, this request has gone from "curious" to "HIGHLY INTERESTING" in the past few hours, as it was discovered that the Kaspersky password manager appears to deliberately attempt to combat Hashcat's markov implementation. Rather than generating random passwords, it attempts to generate passwords that are likely to appear at the end of the keyspace when using markov mode, thus "thwarting" password crackers. Coincidentally (or perhaps not!), @roycewilliams's four-year-old idea makes these candidates appear at the beginning of the keyspace, rather than the end.

Keep in mind that Kaspersky also has other issues as well, but this could be useful just in case other generators are attempting to be similarly, erm, "clever."

**Comment by jsteube** [comment]
Added with commit https://github.com/hashcat/hashcat/commit/f146a05878f923b8c5d466214ff27257801c82e2

```
root@ht:~/hashcat# ./hashcat -a3 --stdout ?l
s
m
c
b
a
p
l
j
d
t
r
k
h
g
f
n
i
e
w
v
o
y
z
q
u
x
root@ht:~/hashcat# ./hashcat -a3 --stdout ?l --markov-inverse
x
u
q
z
y
o
v
w
e
i
n
f
g
h
k
r
t
d
j
l
p
a
b
c
m
s
```

**Comment by RichiH** [comment]
https://github.com/hashcat/hashcat/commit/f146a05878f923b8c5d466214ff27257801c82e2 is looking good, yes. Thank you for this!

**Comment by roycewilliams** [comment]
Works as advertised!
```
$ hashcat -m 0 -a 3 --markov-inverse test-last-markov-l13.hash ?l?l?l?l?l?l?l?l?l?l?l?l?l

2e55737f2d47d48b1eca284e193e7170:xqxqxqgxqjzwv

Session..........: hashcat
Status...........: Cracked
Hash.Name........: MD5
Hash.Target......: 2e55737f2d47d48b1eca284e193e7170
Time.Started.....: Wed Jul  7 12:58:34 2021 (0 secs)
Time.Estimated...: Wed Jul  7 12:58:34 2021 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Mask.......: ?l?l?l?l?l?l?l?l?l?l?l?l?l [13]
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:  3871.4 MH/s (9.61ms) @ Accel:32 Loops:128 Thr:1024 Vec:1
Speed.#2.........:        0 H/s (9.69ms) @ Accel:32 Loops:128 Thr:1024 Vec:1
Speed.#3.........:  3963.3 MH/s (8.95ms) @ Accel:32 Loops:128 Thr:1024 Vec:1
Speed.#4.........:  3985.4 MH/s (8.88ms) @ Accel:32 Loops:128 Thr:1024 Vec:1
Speed.#5.........:  3984.7 MH/s (8.81ms) @ Accel:32 Loops:128 Thr:1024 Vec:1
Speed.#*.........: 15804.8 MH/s
Recovered........: 1/1 (100.00%) Digests
Progress.........: 335544320/2481152873203736576 (0.00%)
Rejected.........: 0/335544320 (0.00%)
Restore.Point....: 0/141167095653376 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-128 Iteration:0-128
Restore.Sub.#2...: Salt:0 Amplifier:0-128 Iteration:0-128
Restore.Sub.#3...: Salt:0 Amplifier:128-256 Iteration:0-64
Restore.Sub.#4...: Salt:0 Amplifier:128-256 Iteration:0-128
Restore.Sub.#5...: Salt:0 Amplifier:128-256 Iteration:0-128
Candidate.Engine.: Device Generator
Candidates.#1....: xqxqxqgxqjzwv -> cvqwfjdvqjzwv
Candidates.#2....: xqxznjdvqjzwv -> cvqpaiaoqjzwv
Candidates.#3....: mwzbeiaoqjzwv -> avqhkyyhqjzwv
Candidates.#4....: mwzypexwvqvqc -> avqdoxoxqjzwv
Candidates.#5....: mwzkafuhqjzwv -> avqrbdnjqjzwv
Hardware.Mon.#1..: N/A
Hardware.Mon.#2..: N/A
Hardware.Mon.#3..: N/A
Hardware.Mon.#4..: N/A
Hardware.Mon.#5..: N/A

Started: Wed Jul  7 12:58:23 2021
Stopped: Wed Jul  7 12:58:36 2021
```

**Comment by Scanel-sys** [comment]
insanely need --stdout with --skip/--limit 
moved generation of BF pswds to cpu but skip limit works only with hashmodes, but I would like to have possibility to generate keyspace partly

**Comment by roycewilliams** [comment]
> insanely need --stdout with --skip/--limit moved generation of BF pswds to cpu but skip limit works only with hashmodes, but I would like to have possibility to generate keyspace partly

This seems unrelated to this issue. Please create a new one.
