### ISSUE TITLE
feature  request: Please add the ability to limit cpu usage

### ISSUE THREAD

**Issue by cardassian-tailor** [hashcat/hashcat#1069]
Im using the lastest beta of Hashcat with opencl on Windows 10. I can't find a way to limit the cpu usage, say to 70%. Having this ability would be a benefit to me. Please consider adding this feature.

**Comment by jsteube** [comment]
There's no way hashcat can do that, because it's the OpenCL runtime managing the thread count / cpu cores. Most OpenCL runtime however support an environment variable that lets you select a fixed number of core, that should help you.

**Comment by cardassian-tailor** [comment]
Hello jsteube. Thank you for your reply, I appreciate it. Any idea where I can look in the opencl documentation to find details on achieving that?

**Comment by jsteube** [comment]
Not sure if they are documented. Here's how I found them for AMD:

```
root@sf:~# strings /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so | grep CPU
CPU_WORKER_THREAD_STACK_SIZE
CPU_MAX_COMPUTE_UNITS
CPU_USE_ALIGNMENT_MAP
CPU_MAX_WORKGROUP_SIZE
CPU_MEMORY_GUARD_PAGES
CPU_MEMORY_GUARD_PAGE_SIZE
...
```

The CPU_MAX_COMPUTE_UNITS sounds good (for AMD).

**Comment by ThomasCr** [comment]
For Intel exists something like CL_DEVICE_MAX_COMPUTE_UNITS

But is it really a variable to set or to get?

I have also [found](https://stackoverflow.com/questions/50944257/set-number-of-compute-units-cpu) while I was searching - that you be able to set max theads in the code... but don't know how mush this matches to hashcat.

I also would like to see a possible way to limit the CPU usage, so that I can let this run on other systems too without slow them to mush down. Only setting the nice level is not enough.
