### ISSUE TITLE
Segfault in hm_NVML_nvmlDeviceGetPowerManagementLimit()

### ISSUE THREAD

**Issue by rhertzog** [hashcat/hashcat#1101]
A kali user reported a segfault with hashcat 3.30 in the function hm_NVML_nvmlDeviceGetPowerManagementLimit()

See https://bugs.kali.org/view.php?id=3835

```
root@kali:~# hashcat -b -m 1000
hashcat (v3.30) starting in benchmark mode...

* Device 0000001: Old CUDA compute capability 3.0 detected, OpenCL performance is reduced.
             For ideal hashcat performance on NVIDIA GPU you need CUDA compute capability 5.0 or higher (Maxwell)
Segmentation fault
```

I can ask the bug submitter further information if needed, just let me know what you need.

**Comment by philsmd** [comment]
This smells a lot like a faulty driver installation (OpenCL runtime, "clGetDeviceIDs(): CL_DEVICE_NOT_FOUND" wtf? It seems that not even "clinfo" works, right?).

Yeah, at least a gdb backtrack should be the very minimum, otherwise we do not even know where the crash occurs:
```
make clean
git pull
make DEBUG=1
gdb --args hashcat -b -m 1000
```

after that type "r" to start the gdb run... after the crash occurs type "bt" (for backtrack). You can exit gdb by typing "q" and "yes".
Thanks

**Comment by Faiz009** [comment]
The same issue here..

**Comment by philsmd** [comment]
@Faiz009 it would be nice if you test both "clinfo" and give the gdb output. Otherwise, we don't even know about what problem we are talking about in here.

**Comment by jsteube** [comment]
I think the problem here is a missing shared object which is part of the nvidia driver. @rhertzog Can you please make sure this file is part of Kalis nvidia drivers? Filename is "libnvidia-ml.so".

On my Ubuntu 16.04 this gets installed by the nvidia driver to 

```
root@et:~# ls -l /usr/lib/x86_64-linux-gnu/libnvidia-ml.so
lrwxrwxrwx 1 root root 17 Feb  2 11:01 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so -> libnvidia-ml.so.1
root@et:~# ls -l /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
lrwxrwxrwx 1 root root 22 Feb  2 11:01 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 -> libnvidia-ml.so.378.09
root@et:~# ls -l /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.378.09 
-rwxr-xr-x 1 root root 1181216 Feb  2 11:01 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.378.09
```

This file is important to manage temperature, fans, utilization etc.

**Comment by jsteube** [comment]
I'll however add a check for this and output some warning message

**Comment by jsteube** [comment]
I've added a new check to hashcat on startup to disable hardware monitoring in case NVML was not found even if XNVCTRL was found, because it depend on it. That's what happend in your case and lead to the segfault. 

I've pushed the fix to GitHub with commit: https://github.com/hashcat/hashcat/commit/0aca372ce8e8674dbdda1cc7ce3a6b684b7d118e
There's also a binary beta on: https://hashcat.net/beta/

It would be nice if you can test the fixes.

Additional I recommend to push libnvidia-ml.so to Kali because this library is really useful. After that, you'll find the following informations in your status screen:

```
HWMon.Dev.#1.....: Temp: 42c Fan: 33% Util: 95% Core:1189Mhz Mem:2700Mhz Lanes:16
```

**Comment by rhertzog** [comment]
@jsteube libnvidia-ml.so is available in the libnvidia-ml1 package but i'm not sure how to best get it installed... nvidia-opencl-icd has no functional dependency on that library so it doesn't look like the correct place. hashcat can work with multiple GPU so it's not the proper place either.

Maybe we should create binary packages hashcat-nvidia, hashcat-intel, hashcat-amd that would have the correct dependency on each OpenCL module + additional requirements for hardware monitoring ?

**Comment by jsteube** [comment]
You're right, the hardware monitor library has no dependency to the OpenCL library.

However, from my understanding the libnvidia-ml.so library shouldn't be a separate package. It is an official part of the nvidia-driver installer that you can download from their site. I think it should get installed to the user system whenever the user installs the nvidia driver package. This also solves the problems caused by mixing different versions of the library and the driver.

If you really don't want to do that, the suggested packages hashcat-nvidia, hashcat-intel and hashcat-amd are actually a nice idea. Make sure those package can be installed in parallel, that is because hashcat also supports mixed GPU types (different vendors) and mixed device types (GPU and CPU) to run in parallel. I'd think of them as a kind of additional packages to a hashcat base package.

**Comment by rhertzog** [comment]
@jsteube So the bug reporter already had libnvidia-ml1 installed... the issue is somewhere else. He provided this backtrace:
```
hashcat (v3.30) starting in benchmark mode...

* Device https://bugs.kali.org/view.php?id=1: Old CUDA compute capability 3.0
detected, OpenCL performance is reduced.
             For ideal hashcat performance on NVIDIA GPU you need CUDA compute
capability 5.0 or higher (Maxwell)

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b62484 in hm_NVML_nvmlDeviceGetPowerManagementLimit (
    limit=0x7fffffffdfdc, device=0x0, hashcat_ctx=0x555555759010)
    at src/hwmon.c:1012
1012    src/hwmon.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7b62484 in hm_NVML_nvmlDeviceGetPowerManagementLimit (
    limit=0x7fffffffdfdc, device=0x0, hashcat_ctx=0x555555759010)
    at src/hwmon.c:1012
#1  hwmon_ctx_init(hashcat_ctx=hashcat_ctx@entry=0x555555759010)
    at src/hwmon.c:3894
#2  0x00007ffff7b5b504 in hashcat_session_init(hashcat_ctx=0x555555759010,
    install_folder=0x5555555565c6 "/usr/bin",
    shared_folder=0x5555555565b3 "/usr/share/hashcat", argc=4,
    argv=0x7fffffffe2a8, comptime=1484845219) at src/hashcat.c:1025
#3  0x0000555555555203 in main (argc=4, argv=0x7fffffffe2a8) at src/main.c:975
(gdb)
```

**Comment by jsteube** [comment]
Maybe the library is not in the search path? So that hashcat will not
find it on Kali Systems, whatever the package is installed or not?

**Comment by rhertzog** [comment]
That seems wrong in general:
```
$ apt-file show libnvidia-ml1
libnvidia-ml1: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so
libnvidia-ml1: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
libnvidia-ml1: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.304.131
$ cat /etc/ld.so.conf.d/x86_64-linux-gnu.conf 
# Multiarch support
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
```

**Comment by jsteube** [comment]
Do you mean that it's from version 304.x which is damn old? You really
need to update it.

**Comment by rhertzog** [comment]
No, I wanted to show the precise location of the library. Actually the version in Kali (and Debian Testing) is version 375.39-1 but it's in the same location which is in the usual library search path. This was just a bad copy-paste because I picked the output that referred to an older version of Debian.

**Comment by jsteube** [comment]
Can you please try to find out (using strace) if hashcat is finding and
loading the library successfully? From my perspective it still looks
like it wasn't found that's why the error occurs. Btw you should update
to the latest v3.40 version which detects this kind of error and does
not segfault and just disables the not working hardware management.
