### ISSUE TITLE
CL_OUT_OF_RESOURCES

### ISSUE THREAD

**Issue by kenkoonwong** [hashcat/hashcat#1116]
Win10 64bit
RAM: 32G
Mobo:  ASUS Z170-P LGA
CPU: Intel core i7-6700
GPU: 4x GTX 1080
Driver: 378.49
Hashcat 3.30

When I ran hashcat64 -m 2500 test.hccap -a 3 ?u?l?l?l?d?d?d?s -w 3, after a few minutes these came up and stops hashcat. i've tried on both hashcat 3.30 and 3.20. 

Time.Started.....: Sun Feb 19 18:45:46 2017 (1 sec)
Time.Estimated...: Mon Feb 20 09:51:08 2017 (15 hours, 5 mins)
Input.Mask.......: ?u?l?l?l?d?d?d?s [8]
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#3.....:   430.3 kH/s (93.89ms)
Speed.Dev.#4.....:   402.2 kH/s (100.53ms)
Speed.Dev.#5.....:   395.1 kH/s (50.80ms)
Speed.Dev.#6.....:   438.0 kH/s (92.30ms)
Speed.Dev.#*.....:  1665.7 kH/s
Recovered........: 0/6 (0.00%) Digests, 0/6 (0.00%) Salts
Progress.........: 0/90481248000 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/580008000 (0.00%)
Candidates.#3....: Sari198! -> Swuk720!
Candidates.#4....: Skfg820! -> Smld498!
Candidates.#5....: Ssws498! -> Sprn101!
Candidates.#6....: Sysn101! -> Srxy680!
HWMon.Dev.#3.....: Temp: 50c Fan: 33% Util: 99% Core:1809Mhz Mem:4513Mhz Lanes:16 *Throttled*
HWMon.Dev.#4.....: Temp: 48c Fan: 32% Util:100% Core:1974Mhz Mem:4513Mhz Lanes:1 *Throttled*
HWMon.Dev.#5.....: Temp: 51c Fan: 33% Util:100% Core:1949Mhz Mem:4513Mhz Lanes:1 *Throttled*
HWMon.Dev.#6.....: Temp: 48c Fan: 33% Util:100% Core:1809Mhz Mem:4513Mhz Lanes:4 *Throttled*

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit =>
clWaitForEvents(): CL_OUT_OF_RESOURCES

clGetEventProfilingInfo(): CL_OUT_OF_RESOURCES

clGetEventProfilingInfo(): CL_OUT_OF_RESOURCES

clWaitForEvents(): CL_OUT_OF_RESOURCES 

How can I fix this? Thanks

**Comment by epixoip** [comment]
See if https://hashcat.net/wiki/doku.php?id=timeout_patch resolves this for you, and please report back to let us know if it did or did not work.

When using CUDA we used to see error 702 (CUDA_ERROR_LAUNCH_TIMEOUT). Based on a few other people's reports, it appears Nvidia's OpenCL just returns -5 (CL_OUT_OF_RESOURCES ) for the same condition. Probably because OpenCL doesn't define any sort of timeout error code like CUDA does. I think -2 (CL_DEVICE_NOT_AVAILABLE) may have been a more appropriate equivalent, but I don't work at Nvidia so my opinion doesn't count ;)

**Comment by jsteube** [comment]
I've seen the CL_OUT_OF_RESOURCES only in combination with Win10, but never with Windows version lower than 10. If there's a problem with CUDA_ERROR_LAUNCH_TIMEOUT, then it's probably a combination of Windows 10 + CUDA_ERROR_LAUNCH_TIMEOUT. Also note that from the status screen:

```
Speed.Dev.#3.....: 430.3 kH/s (93.89ms)
Speed.Dev.#4.....: 402.2 kH/s (100.53ms)
Speed.Dev.#5.....: 395.1 kH/s (50.80ms)
Speed.Dev.#6.....: 438.0 kH/s (92.30ms)
```

We can clearly see the kernel timeout is less than 2 seconds.

**Comment by kenkoonwong** [comment]
exipoip, thanks! The patch worked! Completed the process without error. I'll monitor if I get that error message again on the other modes. 

jsteube, you're right, for some reason it felt like a few minutes...

**Comment by jsteube** [comment]
Thanks for clarify! I've re-added the check for timeout patch

**Comment by Dmo68** [comment]
I need to put this timeout patch on my windows 10 machine as well because I am also getting the CL_OUT_OF_RESOURCES error. I have read the instructions on https://hashcat.net/wiki/doku.php?id=timeout_patch but I am a noob when it comes to editing the registry. I have looked everywhere for a more detailed instruction on how to install this patch. Would someone be so kind as to give me a step by step guide on how to add this file to the registry to fix this issue?

**Comment by roycewilliams** [comment]
GitHub isn't the support path for hashcat - the forums are. Also, please don't cross-post to GitHub and the forums.
