### ISSUE TITLE
Invalid hccapx version

### ISSUE THREAD

**Issue by cclements** [hashcat/hashcat#1129]
I captured a WPA handshake then converted with the latest git rev of hashcat-utils as follows:

```
./cap2hccapx.bin ./handshake_some-net.cap some-net.hccapx
Networks detected: 1

[*] BSSID=00:18:xx:xx:xx:xx ESSID=Some Net (Length: 9)
 --> STA=40:b8:xx:xx:xx:xx, Message Pair=4, Replay Counter=1
 --> STA=f8:cf:xx:xx:xx:xx, Message Pair=0, Replay Counter=1
 --> STA=40:b8:xx:xx:xx:xx, Message Pair=4, Replay Counter=1
 --> STA=f8:cf:xx:xx:xx:xx, Message Pair=0, Replay Counter=1
 --> STA=f8:cf:xx:x:xx:xx, Message Pair=2, Replay Counter=1

Written 5 WPA Handshakes to: some-net.hccapx
```

When trying to crack it, hashcat complains the hccapx version is wrong:

```
hashcat64.exe -m2500 some-net.hccapx ../wl/* -w3
hashcat (v3.30-319-g5ec763fa+) starting...

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: TITAN X (Pascal), 2047/12288 MB allocatable, 28MCU


Hashfile 'some-net.hccapx': Invalid hccapx version
Hashfile 'some-net.hccapx': Invalid hccapx version
Hashfile 'some-net.hccapx': Invalid hccapx version
Hashfile 'some-net.hccapx': Invalid hccapx version
No hashes loaded

Started: Thu Feb 23 08:05:09 2017
Stopped: Thu Feb 23 08:05:09 2017
```

When I try the _current_ git rev of hashcat against an _old_ hccapx file I converted with the hashcat-utils from 3 days ago it works as expected, however, converting the _old_ handshake with the _current_ git rev of hashcat-utils results in the "invalid version" message from hashcat.  Not sure if the issue is with hashcat-utils or hashcat itself.

**Comment by philsmd** [comment]
From your output I can see that you are using an older revision (5ec763fa) and not the current one of hashcat (just to have the full picture the version update changes were made later: see 9b08d4af0fd92691779f3d624f2e071cdee914ca), use:

```
make clean
git pull
make
```

to update to the newest version.

BTW: you need to use the newest version of both hashcat and hashcat-utils. Since you use a dev version (the git version), it should be clear that many changes could be made each and every day without any announcement (since it's still a beta version).

**Comment by cclements** [comment]
Sorry about that, I had indeed updated the hashcat version but when I uploaded it to my windows box I had forgotten I had the old bin paused in a background window.  File locking prevented the new version from being written.  After fixing this, everything works again.
