### ISSUE TITLE
Hashcat incorrectly reports cracked passwords in some cases

### ISSUE THREAD

**Issue by ekuznetsov139** [hashcat/hashcat#1137]
This seems to be happening mainly/only if I pass multiple hashes in the same file and I use masks.

Example. Take the attached file. Create a text file containing a single word "smoothbanana". Execute the following command:

hashcat64 -m 2500 -a 6 NETGEAR68.hccapx testwords.txt ?d?d?d

With hashcat 3.30, it reports:

9c8bc4b9ee80ca14bab1614a14373a40:NETGEAR68:smoothbanana394
a14ef084e5c07b0d5b4121c490bbdbc5:NETGEAR68:smoothbanana123

Here 'smoothbanana394' is the correct passkey for both hashes, and 'smoothbanana123' is nonsense. By varying the number of characters in the mask, you can also induce hashcat to report smoothbanana312 or smoothbanana391.

[NETGEAR68.zip](https://github.com/hashcat/hashcat/files/802622/NETGEAR68.zip)

**Comment by jsteube** [comment]
hashcat tells me:

```
Hashfile 'NETGEAR68.hccapx': Invalid hccapx version
```

Maybe you're using the old hccapx version 3. Can you please use latest versions and resend the hccapx

**Comment by jsteube** [comment]
In the meanwhile I've patched hashcat to load the hccapx as so that I was able to reproduce it. The bug should be gone with this commit:  https://github.com/hashcat/hashcat/commit/d2e95d5e1b7e15f3d06407aaca2a7bf251b7012a

However you need to recreate the hccapx with latest cap2hccapx or from online site. Thanks for reporting
