### ISSUE TITLE
Is user-defined hash function available in hashcat?

### ISSUE THREAD

**Issue by alaneuler** [hashcat/hashcat#1148]
I need to crack md5 hashed passwords, but due to the incorrect md5 hash function implementation, every byte hash result's leading 0 is ignored, so the md5 hash result is not 32 characters length. So maybe I need a user-defined hash function to crack this kind of passwords hash?

**Comment by magnumripper** [comment]
You mean missing zeros in the hex representation? I think you'd be better off using a perl script (or something) that brute forces all possible full hashes from what you've got. That "backwards" way will run near full speed as opposed to a cracker that does it "forwards". At least unless you've got a really huge set of them.

**Comment by jsteube** [comment]
@alaneuler see @magnumripper comment, that's the way to go.

**Comment by alaneuler** [comment]
@magnumripper You mean with hashes whose length is less than 32 characters, I insert 0 into all possible positions to produce the 32 characters long hashes and then using hashcat to crack them?

**Comment by magnumripper** [comment]
Something like that, yes. If your hash is 31 characters, you'll end up with 31 versions of it. If your hash is only like 25 characters, there will be lots of alternatives but it will still not slow Hashcat down much.

I bet @philsmd could write a script for it in five minutes if you could persuade him (it would take me longer because I tend to code first and think later and this is somewhat tricky). 

But again, if you have lots and lots of them, it could be worthwhile creating a format. Is this a one-off? Where did you see it?

**Comment by alaneuler** [comment]
I don't have much of them, it's a one-off, and I think your solution is enough for me. I think I can code myself :). Thank you very much!
