### ISSUE TITLE
Keyspace BUG

### ISSUE THREAD

**Issue by s77rt** [hashcat/hashcat#1153]
hashcat64.exe -a 3 -1 efghijklmnop ?1?1?1 --keyspace
You need to specify a mask if you specify a custom-charset

**Comment by Chick3nman** [comment]
To add some more details and confirm this issue, using --keyspace with a custom character set, such as in the command shown above, will cause hashcat to not recognize that a mask has been set for some reason, whereas using a mask that doesn't include a custom character set works just fine. Custom character sets work in attacks, it's only when trying to use --keyspace that they fail, giving the error shown on the second line above. The same command as above does work in 3.30, so i believe the intended behavior is for it to work in 3.40 as well.

**Comment by philsmd** [comment]
Note: for now (until next release if you really do not want to use upcomming beta versions or git versions), you could just work around this incorrect sanity check with the use of a mask file:
```
$ cat a.hcmask 
efghijklmnop,?1?1?1
$ hashcat --keyspace -a 3 a.hcmask
144
```

Note: it is not allowed to use .hcmask file with multiple lines in it whenever you use --keyspace. Therefore, this is just one possible dirty hack to trick hashcat to generate the keyspace value. You shouldn't get used to this mechanism, because devs might also decide to disable reading .hcmask completely whenever the --keyspace argument was used. So just use this dirty hack if you really need to and can't wait for the next release (or use git version/beta).

**Comment by s77rt** [comment]
looks im going to use the beta version for the first time... (could not wait for the new release)
https://hashc.co.uk all depends on it

for now i would kindly ask you to check this issue: #1155
