### ISSUE TITLE
Hash 7000 (FortiGate/FortiOS) - Issue with base64ish characters

### ISSUE THREAD

**Issue by ss23** [hashcat/hashcat#1160]
When using hashcat legacy, a hash which contained a trailing = would be accepted as a valid type 7000 hash.
I don't have the ability to generate new test hashes at the moment, so I've censored one I have:
`AK1jmUe[...]EqAo2DiOM=` would be successfully recovered as `AK1jmUe[...]EqAo2DiOMA`.
That is, with hashcat legacy, it would accept and attempt to crack a hash of the first form (which is how these hashes are represented in the FortiGate/FortiOS configuration file), and successfully crack it, though it would write that the hash it ran on ended with an A, rather than a =.

With the reimplemented version however, this is no longer the case. Instead, a hash of the first form (the form coming from the FortiGate/FortiOS configuration file) will recieve `line length exception`.

It's worth noting there are other characters in the hashes that can be base64ish (such as `+` or `/`), and I'm unsure whether these are handled correclty by the new implementation also.

Unfortunately I have no knowledge of the internals of the hash, so I've been unable to debug or PR this directly.

**Comment by philsmd** [comment]
Are you sure about the "Line-length exception" error?

That specific error would mean that the length of the line is not correct (it shouldn't matter if there is a = or an A at the end).

Please be more specific about the total length of the hashes, it should be 3 (signature) + 44 (hash + padding) = 47

You should only get a "Line-length exception" whenever the length is not 47. Can you please verify that?

After we clarify that, we can double-check if the padding is correct (with "=" or not)...
A (or preferably several) real-word example would be great, otherwise I can't really tell what is going on.

Thx

**Comment by ss23** [comment]
I got the error slightly wrong, I have included some more output that might help debug it. Unfortunately the only hashes I have are from a client job, so I can't provide a real world example. Perhaps if anyone out there has a FortiOS device they can pull a hash from, that could be used.

```
root@zx-keyscore:/opt/crack# /opt/hashcat-legacy/hashcat-cli64.bin --hash-type 7000 ss23-fortinet-hashes.txt -a 0 /opt/wordlists/
Initializing hashcat v2.00 with 4 threads and 32mb segment-size...

Added hashes from file ss23-fortinet-hashes.txt: 1 (1 salts)
Activating quick-digest mode for single-hash with salt

[s]tatus [p]ause [r]esume [b]ypass [q]uit =>
```
vs
```
root@zx-keyscore:/opt/crack# /root/hashcat/hashcat --hash-type 7000 ss23-fortinet-hashes.txt -a 0 /opt/wordlists/ --force
hashcat (v3.30-396-gd57b493) starting...

ADL_Overdrive6_TargetTemperatureData_Get(): -8

OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: Tonga, 3813/4005 MB allocatable, 32MCU
* Device #2: Tonga, 3818/4045 MB allocatable, 32MCU
* Device #3: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz, skipped

Hashfile 'ss23-fortinet-hashes.txt' on line 1 (AK1jmUeq[...]o2DiOM=): Hash-length exception
Parsing Hashes: 0/1 (0.00%)...No hashes loaded
```

As you can see, this is using the exact same hash between both versions of hashcat, but the new implementation gives an error.

I can confirm the hash length in both cases is 47 characters.

**Comment by philsmd** [comment]
ah, see ?

this is a completely different error (at least when we look at what hashcat internally sees/reports)
Hash-length exception is different from Line-length exception

Now the problem makes (just a little bit) more sense ;)
we need to investigate...

Thx

**Comment by philsmd** [comment]
Well, I found some examples within the john the ripper code and it seems that you found an interesting bug that I can confirm with these examples: https://github.com/magnumripper/JohnTheRipper/blob/9737dea214b5e52e87fd5775acadc7839d0fcdee/src/FGT_fmt_plug.c#L78-L80

Since -m 7000 = Fortigate (FortiOS) was ported from hashcat-legacy (and you also wrote/confirmed above that there is some inconsistency between input/output of hashes with hashcat-legacy)... we unfortunately also propagated that parsing/encoding/decoding bug to hashcat (see https://github.com/hashcat/hashcat-legacy/blob/master/src/engine.c#L2193).

I have no clue, why this faulty code exists in hashcat-legacy, but I don't think it is worth patching hashcat-legacy... hashcat-legacy is kinda completely replaced by hashcat and we do not really change it a lot anymore.

Thank you and please test

**Comment by ss23** [comment]
Works for me! Happy to have this closed once merged 👍
