### ISSUE TITLE
WPA / WPA2 Output hash:mac_ap:mac_sta:essid

### ISSUE THREAD

**Issue by s77rt** [hashcat/hashcat#1167]
Hi
Since the forum is a bit slow in some helps, specially on hashcat internal system, github looks a better place for such questions
new outfile format for wpa/wpa2 is hash:mac_ap:mac_sta:essid

example:
eb78f2dde751d67f6c00b9923e387e56:b4eeb4fe338b:48e9f19d7397:HOTFiber-1255

question is:
How the hash is being generated?
IOW
How this hash: "eb78f2dde751d67f6c00b9923e387e56" is being generated?

**Comment by philsmd** [comment]
No, this is the wrong place to ask question like this.

This is not a bug/issue at all (nor a feature request or anything related).

The answer was already given here: https://hashcat.net/forum/thread-6355-post-33892.html#pid33892
 . If you really want to know how it is generated, you should check the code (and take your time to understand it)... otherwise, you shouldn't bother at all about this checksum. There is no reason, why you should be that eager to force us to tell you bit-by-bit what this code does, do the reading yourself. There is absolutely no reason why you need to mess around with this checksums etc.

**Comment by s77rt** [comment]
@philsmd no one forced you to do anything.
i have a reason, to identify each wpa handshake as an uniq hash, since mac_ap:mac_sta:essid can be the same for two different handshake, while the hash not

example:
 16450dbe240e410657e933042e78cf3f:b4eeb4fe338b:48e9f19d7397:HOTFiber-1255
 eb78f2dde751d67f6c00b9923e387e56:b4eeb4fe338b:48e9f19d7397:HOTFiber-1255

**Comment by philsmd** [comment]
Again, this is not a hashcat issue... if you really want to implement some (external) wrapping code, then you should spend the time understanding how the checksum is generated.
Otherwise, you could just use --show / --left / --remove options.

**Comment by s77rt** [comment]
looking at the code,,
what are: salt->salt_buf & wpa->pke

not found on hccapx detailed structure
https://hashcat.net/wiki/hccapx

**Comment by jsteube** [comment]
As @philsmd already mentioned, this is kind of irrelevant for users. It's only part of the potfile because it's required to mark the right handshakes as cracked when hashcat is starting up or in case the user uses --show or --left. However from a user perspective it shouldn't be important. The hash bases on MD5, but it's no a true MD5 because for our usecase it's good enough as it is now. If you really need to copy the procedure, simply copy the code out of interface.c and save yourself alot of headache.
