### ISSUE TITLE
Option to test hashes without cracking

### ISSUE THREAD

**Issue by roo7break** [hashcat/hashcat#1185]
It would be really beneficial to have an option to test commands (e.g. --test) and/or hashes instead of waiting for exception to be raised.

This way if we are trying to automate cracking using scripts, we can ascertain whether the information is in the right format before trying to start a new session.

**Comment by roycewilliams** [comment]
More broadly, the deep symptom you're describing seems to be that it sometimes takes a long time to find out that syntax or inputs are obviously wrong.

You're definitely right that simple checks -- for the existence of files and directories, sanity/format of masks, etc. -- need to happen earlier in some cases. Moving them prior to expensive phases like checking for duplicates, sorting hashes, etc. would be a big win. The need for this becomes more obvious as the number of hashes goes up.

Things that should happen up front or sooner (some of which may already be there, just listing them for completeness):

* Checking for existence and permissions of all required files and directories (both the ones specified on the command line, and the default/assumed ones)

* Whether or not the combinations of command line options and flags are compatible and sane

* Whether or not the hashes in the file are the expected length and composition (I would like to have the default behavior be that as soon as a single hash is seen as obviously incorrect, the entire run aborts instead of trying to continue to load them all, and to have this check happen quickly up front instead of after all hashes are loaded, deduped, sorted, etc.)

It would also be useful for an early rough guess for resources on the target platform. If each hash format hash a relatively well known memory requirement (or at least a rough upper bound), we can probably make a pretty good guess as to if the job will fit on the current platform. Even a rough check of size of hashes file and rule count against available OpenCL memory would go a long way to stopping a nonsensical command line very early.

**Comment by jsteube** [comment]
> It would be really beneficial to have an option to test commands (e.g. --test) and/or hashes instead of waiting for exception to be raised.

Hashcat is not starting up in case there's fundamental errors.

>> Checking for existence and permissions of all required files and directories (both the ones specified on the command line, and the default/assumed ones)

Maybe you missed it, but that already happend with hashcat v3.40: https://github.com/hashcat/hashcat/blob/master/docs/changes.txt#L115

>> Whether or not the combinations of command line options and flags are compatible and sane

Already done on startup

>> Whether or not the hashes in the file are the expected length and composition (I would like to have the default behavior be that as soon as a single hash is seen as obviously incorrect, the entire run aborts instead of trying to continue to load them all, and to have this check happen quickly up front instead of after all hashes are loaded, deduped, sorted, etc.)

Already done on startup

>> It would also be useful for an early rough guess for resources on the target platform.

Already done on startup

----

TBH issues like this make me really angry.

**Comment by jsteube** [comment]
Feel free to provide some example where hashcat can do something better and reopen the issue

**Comment by roycewilliams** [comment]
@jsteube , my apologies for the potentially contentious feedback earlier. I recognize that hashcat has made huge advances in making sanity checks much earlier in a run than in the past. I know that a lot of work has gone into it, and it has helped me to learn hashcat because it is now more forgiving of my errors. :)

That being said, it's clear that the original poster has at least one use case where they are experiencing feedback later in the process than expected. I, too, would like to hear more from them about the exact syntax used, to address any issue.

I myself encountered an issue recently where I thought that hashcat could have aborted much sooner. Unfortunately, I did not record it at the time. :( So I have tried to rediscover it today. In my testing, I discovered a few other cases where sanity checks for naive or unusual input may still be needed. 

I also suspect that any remaining delayed-feedback failure modes are probably now rare for experienced users. But they are more likely to be triggered by unusual or naive use cases. It is common for new users to try "creative" things that are more likely to result in typos or nonsensical combinations. I think that it is a good idea to be supportive of new and creative uses of hashcat, and I believe that a good way to support that is to provide extra sanity checking for syntax and inputs ... where time permits. :)

**Please be gentle**, as I do not mean to pile these on as an insult. I just wanted to capture the effort so that others could work from the list if needed. 

1. When an invalid attack mode (such as "-a bogus" or "-a 9") is specified, all hashes are loaded and the attack run begins, assuming stdin input. Solution: check for invalid attack modes early.

2. Specifying a directory as rules input ("-r /var/tmp/dir") is accepted. Hashcat pauses for a very long time at "Generated bitmap tables". (It appears that hashcat may be trying to parse the directory as a ruleset? This could have weird side effects we should avoid). Reading rules from a directory was a recent feature request, so naive users may try this. Solution: check if -r input is directory and reject.

3. An empty rules file ("-r /var/tmp/emptyfile") is not detected until after the expensive activities of loading all hashes, etc is completed. (This one may seem iffy, but this could happen if, for example, a script tried to combine rules files automatically but experienced an error, resulting in a zero-byte rules file). I think this may have been the one I encountered. Solution: Detect and reject empty rules files early.

I also found some incidental ones that are not delayed-feedback issues, but may also need attention at some point:

4. An empty session name ("--session=") is accepted, resulting in a functional run, but using run files with an empty filename prefix, and just the bare file/dir names '.pid', '.outfiles', '.log', etc. Solution: explicitly reject empty session names.

5. An empty potfile path ("--potfile-path=") is accepted. This results in an immediate error, but the error is "No such file or directory". Solution: explicitly reject empty potfile paths 

6. An empty restore-file path ("--restore-file-path=") is accepted. I am not sure if this is supposed to be interpreted the same as "--restore-disable" or not, but should probably return an error.

(And really, any other cmdline options that are expecting a value should reject an empty one, which might be common when using scripts or environment variables)

All tests above were against v3.40-49-g20057d8.

If you prefer, I can create a new issue for the items that I found. 

"Why the heck would anyone do that?" is a reasonable response to many of these. :) However, note also that, beyond naive users, but not yet at the level of using the full API, there are also people who want to do simple scripting around hashcat work. Scripting errors can also cause unusual failure modes, like empty variables, files that are supposed to be directories and vice versa, etc. In other words, while naive users might do silly things on purpose, experienced users might do unexpected things as side effects of upstream processes like scripting, so weird corner cases are IMO worth pursuing.

Even if the items that I found are not a high priority for the core team, if other people can submit PRs for them, it might be worth tracking.
