### ISSUE TITLE
Help me please!

### ISSUE THREAD

**Issue by Alexelroki** [hashcat/hashcat#1193]
I'm Spanish but I'm going to speak in English because I think that everybody here speak English...
My problem is the next:
![captura](https://cloud.githubusercontent.com/assets/26529439/24085282/47b8094e-0cf9-11e7-90f9-a24adf51699e.PNG)
Please, help me.

**Comment by roycewilliams** [comment]
Problems with operating hashcat should probably be posted on the hashcat forum instead.

https://hashcat.net/forum/

Your problem is shown in the error:
"Intel's OpenCL runtime (GPU only) is currently broken"

This may or may not be workaround for you:
"You can use --force to override this but do not post error reports if you do so"

As the error says, this is a problem that Intel must fix in their GPU OpenCL driver. It's possible that if there is a version of Intel's GPU OpenCL driver that is newer than your version, that might work.

**Comment by Alexelroki** [comment]
Okay @roycewilliams, thanks for your quickly answer, I will post on that page.
