### ISSUE TITLE
wpa feature request (expand value of message_pair field to indicate status of replycount)

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#1199]
Right now the message_pair field doesn't contain informations about the use of the replycount.
For further going analyses of hccapx files it is necessary to know if the replycount was disregarded or not. The aim is to use a free bit of the message_pair field to indicate that case:

Please use bit 8 as follows:
bit 8 set to 1   if replycount was disregarded
bit 8 cleared   if correct replycount was used

Best regards
ZerBea

**Comment by philsmd** [comment]
To clarify things a little bit here: as far as I understood, this request is about a general change of the hccapx structure/format for this particular case:
1. an external (3th party) tool could not (solely, or not at all!) rely on the replay counter because sometimes focusing only on the replay counter could fail (consider the case where M1 from the AP was captured ... after that a new M1 - the one that is needed! - was not captured, furthermore M2 - the response - was captured later on, in this case we could falsely ignore these sequence of good packets, even if replay counters do not match, but nonce-bruteforce would correct it)
2. the external tool should be able to mark these messages such that the hccapx format knows if the replay counter was considered (and some filtering was done based on the replay counters of the messages from the AP and STA) or if it was ignored (and for instance only timestamps and the message order were considered for filtering)
3. hashcat should, for the time being, just ignore the highest bit of the message_pair (bit 8), which could be used to indicate exactly this fact (replay counter ignored or not ignored)
4. this additional bit could be used both for analysis/statistics, but also  (in the future) in some cases to trigger some further logic (e.g. related to nonce-bruteforce)

Correct?

**Comment by ZerBea** [comment]
Correct.
We are able to do weak point analysis using hccapx files. It's important to know, whether replaycount was disregarded or not, since hashcat had a build in anonce-corr.
Well, it's not a big change in hashcat, but should be laid down in hccapx structure/format...
Best regards
ZerBea
