### ISSUE TITLE
support building without ADL (and without CUDA)

### ISSUE THREAD

**Issue by rhertzog** [hashcat/hashcat#120]
I would like make a proper Debian package of oclHashcat for Kali Linux, unfortunately it's not currently possible because it's not possible to build oclHashcat without ADL and ADL's license makes it impossible to ship that SDK even in the non-free section of Kali (you need a special authorization to ship it as part of an operating system).

I wanted to build the package with only OpenCL support but actually building the OCL version fails because it cannot find adl_sdk.h... the codebase seems to entangle the header files of the various SDK.

Ideally we can build each version independently (./configure --with-opencl or --with-adl or --with-cuda if you added autoconf support). But at the very least we should have makefile targets to build each version.

**Comment by jsteube** [comment]
Hey, first for thinking of building a proper package for Kali. We really need this!

My comments on this so far:

1) Why do you want to ship the SDK at all? You don't need to ship the SDK. All you need is the ADL library itself (the .so files) and those are part of the Catalyst driver package. That's why it's enough for endusers to simply install Catalyst and oclHashcat will work. Users really need this feature to avoid burning their hardware.

2) With oclHashcat v2.10 there's no more CUDA at all. NVidia devices will use OpenCL runtime the same way as AMD devices. You don't need to worry about CUDA anymore! This also enabled us to use OpenCL CPU drivers. See here for details: https://github.com/hashcat/oclHashcat/issues/4 and https://github.com/hashcat/oclHashcat/issues/3

3) There's no ./configure in oclHashcat because we do not use autotools. There are people working on it but I think it will take some time. Anyway even with autotools we'd need to change the code so that it accepts an build without hardware-management. But in regards to 1) I don't think we'd need such a solution.

4) oclHashcat v2.10 had lots of changes to make it more easy for maintainer to integrate it into a packaging system. Basically you simply set the PREFIX in Makefile as you'd do it with ./configure and the files were installed on there after running make install. Files created for sessions or kernel cache are stored in home directory. See here for details: https://github.com/hashcat/oclHashcat/issues/20

**Comment by jsteube** [comment]
Just to make this complete: Both you as the maintainer and the package endusers do _not_ need any of those SDK:
- CUDA SDK 
- AMD APP SDK

Those actually create more problems than they do good. All you both need is the NVidia ForceWare driver or the AMD Catalyst driver. They include all the libraries oclHashcat need to run.

Only you as the maintainer who builds a native binary needs the following additional SDK:
- ADL SDK
- GDK

**Comment by rhertzog** [comment]
Yes, I'm speaking specifically of ADL SDK, the one that can be downloaded here: http://developer.amd.com/tools-and-sdks/graphics-development/display-library-adl-sdk/ and that forces you to accept http://developer.amd.com/amd-license-agreement/ where it says that “9.  Additional Licenses.  DISTRIBUTION OR USE OF THE SOFTWARE WITH AN OPERATING SYSTEM MAY REQUIRE ADDITIONAL LICENSES FROM THE OPERATING SYSTEM VENDOR." and also that you don't have the right to electronically transfer the software except for purposes allowed by the license (which amounts to backup purpose only as far I can see).

A debian source package can "build-depend" on other packages to make anything needed available at build time. Thus if the ADL SDK is needed, it needs to be packaged, but this is not possible due to its license. :-| (And obviously I want a proper package that builds native binaries from source)

FTR, I don't know much about usage of all those GPU SDK, but I discovered that Debian has OpenCL and Installable Client Driver (ICD) for AMD/Nvidia and more:
https://packages.debian.org/sid/amd-opencl-icd
https://packages.debian.org/sid/nividia-opencl-icd

And I was thus hoping that it would be possible to build oclHashcat relying only on OpenCL only and thus hide the hardware-specific code behind OpenCL. That's possibly what you explained in point 2... if yes, then it's great. But then why is ADL SDK still needed? Is it because OpenCL does not provide enough features to manage the hardware (you say "avoid burning their hardware") ?

**Comment by epixoip** [comment]
ADL SDK is needed to enable hardware monitoring and fan control for AMD GPUs. Without this you will not be able to see GPU temp or fan speed.

If you cannot simply build with ADL SDK without distributing ADL SDK, then my suggestion is to not distribute a source package, or to not build from source. Simply download the binary release from hashcat.net as you've done with other releases in the past.

**Comment by jsteube** [comment]
Well I don't know enough about package maintainance. All I can say is that you need the ADL SDK only for building the binary package. Using something like a build-depend package sounds good but in this case you need to avoid it. Again, you do not distribute the SDK you just use it for building. Therefore the license doesn't apply.

Don't confuse the vendors ICD with the vendors OpenCL runtimes: Check out this post for a much more detailed explanation: http://wiki.tiker.net/OpenCLHowTo

The ICD's from NV and AMD should not be used. Ideally there's also a OSS ICD from Khronos Group. For example I'm using Ubuntu, such a package exist on there.

You will find out that for all the different OpenCL compatible devices they usually need a vendor driver. Intel has one for the GPU and CPU, AMD has one for their GPU and CPU and NV has  one for their GPU. There also exists other vendors that provide runtimes for FPGA, for example. 

The User has to pick the right one for his hardware. For example if he installs the NVidia ForceWare because he has a NVidia GPU, the driver also ships an OpenCL runtime library. Also it will put a configuration for the OpenCL ICD folder in order to "register" it's own OpenCL runtime library. 

When oclHashcat starts up, it checks which drivers are registered at the ICD and loads all the available runtimes.

No magic here :)

**Comment by magnumripper** [comment]
You already use dlopen() so I suppose you actually just need some ADL and NVML headers to be able to build. Redistributing [parts of] them ought to fall under fair use.

**Comment by jsteube** [comment]
@rhertzog What's the status? Do you need anything?

**Comment by rhertzog** [comment]
I will give a try at bundling only the ADL SDK headers in my source package. That said if @magnumripper is correct that this falls under "fair use", then you might want to consider doing this direcly. Provide the header in your git repository (and release) so that users do not have to download the ADL SDK at all.

That said it would still be nice if oclHashcat was buildable without those headers since they are effectively a non-free dependency which will prevent the inclusion of oclHashcat in Debian main. But if we can build without it, it could be included and it would still provide value to users of non-AMD GPU... if we get to that point, maybe the hardware management layer that requires the non-free parts can then be externalized to a plugin that can be separately built (and provided in Debian contrib or non-free).

**Comment by magnumripper** [comment]
I just had a look at how it was done in JtR (two years ago, couldn't remember). For NV, we don't seem to have any whole file from their SDK, just a bunch of defines and declarations in our own header and that's it. Possibly copied from nvapi.h from their SDK but I really can't remember. I might have nicked it from https://github.com/gat3way/hashkill.

For AMD it looks like we simply provide straight copies of adl_structures.h, adl_sdk.h and adl_defines.h from whatever ADL SDK was released at the time. One could probably just pick the need-to-know from those files like we did for NV - but OTOH why bother.

**Comment by jsteube** [comment]
About the non-free thing. oclHashcat does not depend on catalyst by default. It's only required if you want to use AMD GPU. The same is true for Forceware + Nvidia.

Anyway, with latest oclHashcat in theory you could run it with only pocl, which I'm not sure if it is completely free or not but I'd think so.

**Comment by rhertzog** [comment]
@magnumripper I built it successfully embedding only the header files (3 for ADL, 1 for Nvidia).

@jsteube I understand but when you build a package for a distribution, you want it usable for all users, whatever their hardware. And you still want to keep the package in main if possible (instead of non-free). So the code that requires the non-free header files ought to be compilable separately from the main code (in a non-free package), building a plugin that the main code can dlopen() to handle hardware management. Or something similar.

**Comment by jsteube** [comment]
@rhertzog What exactly do we need to change to make you happy?

**Comment by matrix** [comment]
@rhertzog @jsteube I found a way for do that (needed also for osx support).
I'll show you shortly.

**Comment by rhertzog** [comment]
@jsteube For the short term: include the 4 header files for ADL/NV directly in your git repository and update the bulid machinery to find them here (instead of /opt/something).

In the long term, enhance the project so that the parts requiring those headers can be compiled separately as a plugin that can then be loaded by oclhashcat. That way oclhashcat can be in Debian main, and non-free can have the plugin which need those files to be built.

**Comment by jsteube** [comment]
@rhertzog It should be possible now to compile oclHashcat without ADL/NVML/NVAPI completely. Do you think we can close this issue now or do we need to do additional changes?

**Comment by rhertzog** [comment]
@jsteube It's up to you to make that call. It's certainly nice to have achieved this but given that hardware monitoring is an important feature it would be even better if it could be enabled on a plain oclhashcat binary compiled without it just by intsalling a plugin that the main binary would then pick up automatically. And we should be able to build that plugin in a standalone way.

**Comment by magnumripper** [comment]
I can't see any point of a plugin since you already use dlopen. The AMD/NV libs themselves should **be** the plugins!

To make that happen you'd just add the four needed headers (or select parts of them) to the tree and drop those SDKs from the build deps. Then you're set. If user doesn't have any non-free stuff, dlopen wont find them so they simply wont be used (even for AMD/NV, a failing dlopen should be a soft failure and behave just like --gpu-temp-disable after possibly emitting a warning). If it does find them, they will be used. Simple as that.

**Comment by rhertzog** [comment]
@magnumripper In general, I would agree with you and I would not object to this. But my suggestion is specifically to address the requirements of Debian. In Debian main, all files from the source package must be under a DFSG-compatible free license and the header files required for building hardware monitoring code for AMD/NV would thus be stripped from the source package. And it would thus not be possible to compile that feature in oclhaschat. Even if the user installs the required libs afterwards, it would not work. In that scenario, we should provide a second copy of oclhashcat in non-free that would replace/divert the one provided in main...

To avoid that duplication I was thus suggesting that the hardware monitoring code could be compiled separately and be used at run-time by the oclhashcat binary provided in the main package.

**Comment by magnumripper** [comment]
If I understand you correctly, you can't distribute JtR Jumbo at all because we currently do provide the AMD headers in our source tree, and have done so for two years.

If I were to create an independent header file with an MIT license (for use by both projects) that has all glue we need for NV and AMD, would that solve this problem? If not, I give up.

**Comment by rhertzog** [comment]
On Mon, 25 Jan 2016, magnum wrote:

> If I understand you correctly, you can't distribute JtR Jumbo at all
> because we currently do provide the AMD headers in our source tree, and
> have done so for two years.

FYI JtR Jumbo is not in Debian, only in Kali.

> If I were to create an independent header file with an MIT license (for
> use by both projects) that has all glue we need for NV and AMD, would
> that solve this problem? If not, I give up.

Yes, this would be enough I believe.

## Cheers,

Raphaël Hertzog ◈ Debian Developer

Support Debian LTS: http://www.freexian.com/services/debian-lts.html
Learn to master Debian: http://debian-handbook.info/get/

**Comment by jsteube** [comment]
@magnumripper sounds like a plan :+1:

**Comment by magnumripper** [comment]
BTW I abandoned the idea of creating a single file shared between JtR and oclHashcat. I did try that idea first, but adding it to ext_ADL.h and ext_nvml.h ended up much cleaner IMHO.
