### ISSUE TITLE
Truncate longer hash format in status output

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#1203]
Truncating the displayed hash in the status output to a set length limit would avoid output spam, as shown in the image below, when running single long hash formats.

http://i.imgur.com/QV36gbU.png

**Comment by roycewilliams** [comment]
Rather than truncating, a compression notation (...) that leaves both beginning and end of the target hash might be better, as in:

$7z$0$19$0$salt$8$f6196259a7326e3f0000000000000000$185065650$112$98$f3b...421cf2

**Comment by Chick3nman** [comment]
I like that idea better @roycewilliams  👍

**Comment by philsmd** [comment]
Don't forget to suggest what should be an acceptable length in your opinion. Please discuss it here...

**Comment by roycewilliams** [comment]
Fair question!

I suggest using the current maximum screen width for ordinary output (the HWMon lines), which appears to be 80, as a starting point (well, actually 81, if the number of lanes is 16!). My example above was intended to be aligned with that.

That being said, some native consoles (such as some used on FreeBSD) actually force an extra linewrap to appear if 80 characters are used, so 79 characters may be a better universal choice.

I also personally like the idea of showing only the last 6 or 8 characters (or so), so that the maximum amount of non-digest material (before the last $) is shown. Most hash formats tend to prepend non-digest material, rather than appending it, so I think that would generally work.

Should the compression itself be a user-configurable option? Or should we simply compress all hashes above a certain size (and if so, at what threshold? And should that threshold be user-configurable?) I don't want to bog down in too many options, but people may have strong and differing opinions that would be satisfied by making the compression and the length configurable.

**Comment by Chick3nman** [comment]
I dont think it should be a configurable option, thats a bit too much. Simply compressing near the middle of the hash using an ellipsis to keep it within 1 terminal line would be fine in my opinion.

**Comment by roycewilliams** [comment]
That's fair.

**Comment by jsteube** [comment]
I've pushed this with https://github.com/hashcat/hashcat/commit/6d66ff96c16992d32aa7fedc51e9b0cdf7ed19ae

I've also remove 2x "." from the status labels, otherwise it wouldn't make much sense to compress the hash to length 79 and the HWmon line is still at 81.

I've written a special function to do the compress in case we want to use it on a different place, too.

Please close the issue if fixed

**Comment by roycewilliams** [comment]
Great call with tightening up the width overall - much appreciated!

**Comment by Chick3nman** [comment]
Looks good, thanks!
