### ISSUE TITLE
Make -o /dev/null great again

### ISSUE THREAD

**Issue by Hydraze** [hashcat/hashcat#1206]
After recent modifications, we can't use -o /dev/null anymore.
While this is not a critical issue, I sometimes use --potfile-disable and -o /dev/null when doing presentations, just to show cracking speed and amount of password cracked in a given time.

On IRC atom proposed to create a --outfile-disable flag but I think it could be interesting to allow /dev/null as an output file to avoid creating yet another command line argument.

**Comment by Chick3nman** [comment]
I personally feel that the status should be on stderr so that pipes can be used to handle cracked hashes and other output on stdout. This would remove the need to add a new flag just for /dev/null and would open things up a bit more for people to pipe cracks into other applications to handle them before going to a file.

**Comment by jsteube** [comment]
Sounds like a complete misuse of hashcat. If you want to see only cracked hashes, use an outfile. If you need it as a stream, run tail -f on it. About the issue itself, I'll add an exception for special devices like /dev/null for outfiles.

**Comment by jsteube** [comment]
Changed with commit: https://github.com/hashcat/hashcat/commit/c3e118f5ea1a67b6cf28db278ef0d86362d101da

Please close the issue if fixed. Thanks for reporting!

**Comment by Hydraze** [comment]
It works, thanks.
