### ISSUE TITLE
Support for additional MD5 Format for hash

### ISSUE THREAD

**Issue by xpwn3rx** [hashcat/hashcat#1243]
This is a fork of 3910 essentially. I need support for MD5(MD5($salt)MD5($pass)). I would add myself, but am not familiar with C only C#/Java/VB.Net.

**Comment by philsmd** [comment]
This looks more like -m 3710 than like 3910 (since the salt in your case should be prepended), furthermore as always we need more details like mentioned here: https://hashcat.net/faq#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this

It would be interesting which software/cms etc uses this algorithm.
Furthermore, this reminds me of this recent forum thread: https://hashcat.net/forum/thread-6558.html, where the algorithm turned out to not use just MD5(x) but a mix of raw MD5 and hex version of MD5 (e.g. only the final output was in hex).

Therefore it is very important to get the algorithm details correct from the beginning, including max pass/salt length and hex/raw formats etc.


Also note: MD5($salt) is a very bad algorithm design, since this can be precomputed

**Comment by jsteube** [comment]
Problem was already fixed + no response from OP, therefore closed
