### ISSUE TITLE
Office 2013 is not compatible with some machines, usually AMD GPU

### ISSUE THREAD

**Issue by deadash** [hashcat/hashcat#1267]
like this:
```
hashcat -m 9600 -a 3 $office$*2013*100000*256*16*ab8a7e729bd26f0ab2e7820facd5f67c*797f712f0a478e53cf3670e4ade8f320*573f3351733e2e280fa0eba836726b041efa1c7cbcd6d8579982d6a70c1b103f -1 1 ?1
```
some machine run out is  Exhausted.

**Comment by jsteube** [comment]
Exhausted is not an error

**Comment by deadash** [comment]
but the 1 is the file of password

**Comment by jsteube** [comment]
I know, but it's not a hashcat error, I've tested it. It cracked fine on my systems. Please fix your driver setup.

**Comment by deadash** [comment]
I've tested the software on 2 different computers, it worked on one PC but failed on the other (which is amd). I'll perform the drive test later.Perhaps the self-test should be added, in this situation, it will present run-time failures like` john the ripper` other than exhausted. I've also ran the other ones like office2007, office2010,etc. they all worked normally.

**Comment by jsteube** [comment]
Just added self-test functionality

**Comment by deadash** [comment]
I noticed there is a self-test functionality in the newest version, which is really exciting. I'm gonna do more tests on my computer to find where the problem is.

**Comment by maykelbembibre** [comment]
I confirm that the same hash of office 2013 gets cracked on my machine with Nvidia graphics card but finishes as exhausted in my other machine with AMD graphics card. It's not a drivers issue in the second machine because on it I have tested a lot of other algorithms and all of them have cracked successfully. So, in a nutshell:
- In Nvidia all algorithms I've tested do crack the hash.
- In AMD all algorithms I've tested do crack the hash except for office 2013.

It seems like there is a sort of problem when we combine specifically the algorithm for office 2013 and AMD hardware environments.

**Comment by jsteube** [comment]
There's special code used in Office 2013 that differs from other algorithms but it's the kernel compiler who's responsible for creating the right byte code for the GPU out of it. This compiler is part of the drivers (one of the reasons why the GPU drivers are so huge these days). IOW: Just because all other algorithms worked but office 2013 doesn't mean it's not a driver issue. It is a driver issue!
