### ISSUE TITLE
Version numbers should not go backwards, please...

### ISSUE THREAD

**Issue by rhertzog** [hashcat/hashcat#1275]
Hello,

I am among the Debian/Kali packagers of hashcat and the last two release (3.5.0 and 3.6.0) have version numbers that are smaller than the former releases (3.40) and this makes it impossible to respect your versioning scheme in the Debian/Kali package since upgrades should always have a higher version number. In Kali we manually worked around this by using 3.50 instead of 3.5.0 but you should get this straight on your side really.

I suggest to retag the last two releases as 3.50 and 3.60 and to continue with 4.0.0 if you want to switch to version numbers with 3 parts. Or 3.61.0 if you don't want to bump the first digit.

Thank you!

**Comment by roycewilliams** [comment]
Totally understood. This has been debated quite a bit on IRC, and @jsteube has no plans to revert this. 

The workaround in Kali that you're describing -- arbitrarily picking a different version number that never existed upstream -- is unusual and not recommended, as it can make things much worse.

Fortunately, for Debian/Ubuntu variants, there is a well-known way to handle this:

https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version

**epoch**

_This is a single (generally small) unsigned integer. It may be omitted, in which case zero is assumed. If it is omitted then the upstream_version may not contain any colons._

_It is provided to allow mistakes in the version numbers of older versions of a package, and also a package's previous version numbering schemes, to be left behind._

**Comment by rhertzog** [comment]
I know of this but using epoch is just ugly... epoch makes sense when you switch from a date-based versioning scheme back to a traditional version number. But otherwise it's really just up to upstream to bump the version numbers appropriately. We are not short on numbers and going with 4.x to reset the versioning scheme is certainly fine.

**Comment by roycewilliams** [comment]
As I said, @jsteube has made it very clear that this isn't going to change. And I do get exactly what you're saying, and I even personally agree a bit. But two release cycles have happened since, and they're not going to be reverted.

**Comment by rhertzog** [comment]
History is history, I don't want to rewrite it but I'll wait @jsteube answer here for now before deciding to put an epoch. The epoch is completely non-revertable once used and changes the version number displayed in quite a few places. Instead of 3.6.0, users will see 1:3.6.0 and will wonder what this mean.

**Comment by ZerBea** [comment]
Seems to be working on other distro's:
https://www.archlinux.org/packages/community/x86_64/hashcat/

Cheers
ZerBea

**Comment by jsteube** [comment]
I've accidentially sent my response to @rhertzog directly, so here it is:

The reason why hashcat changed this version number is simply because it was wrong before. When I meant 3.40 I've actually meant 3.4.0. I simply didn't know something like "Semantic Versioning" existed at that time. IOW, this was a bug and I've fixed it.

From my perspective the problem you have is the following: Your package management system interprets something into the version numbering, in this case that"40" is a number. But when I released 3.40 it wasn't meant as such, your system just expected it to be so. Basically the same that happens if you want to sort a textfile using "sort" of numbers but not use the "-n" switch. The conclusion, in my perspective, is that you're now asking me to fix an error that you (not you in person, but the system) made in the past.

I'm willing to help you to solve the problem, but only as long it's not on the cost of confusing hashcat users. I've did that change to normalize the versioning with a standard that I think is accepted by a large community. Herein is the problem. If I change it, for example to v4.0.0, I'm afraid hashcat users would lose confidence in it. Such a change would be a violation of the "Semantic Versioning" standard because there's no major change in the code.

**Comment by rhertzog** [comment]
Blah, it's not my fault if you meant 3.4.0 and you used 3.40. 40 is a number and the error is not in the system... I understand 4.0.0 would be a violation of the semantic versioning but going backwards is also a violation of the semantic versioning. In that case you could just continue with 3.61.0, 3.62.0, 3.63.0... (I suggest this and not 3.41.0, 3.42.0, 3.43.0 because I used 3.50 in Kali and 3.60 in Debian to work around the lower version number).

**Comment by roycewilliams** [comment]
And that is why deciding to use arbitrary version numbers in the packages -- that match no existing upstream versioning _and don't even match each other_ -- was ill-advised.

The most robust thing to have done would have been to make a one-time correction, just as @jsteube described. The best way to do this would have been with **epoch**.

And at this point, even with the multiple unrelated version numbers in play, using **epoch** is still the best way to fix the situation and move on.

But _please_ don't continue to change the downstream version numbers out of sync with the true version number. If you think that using **epoch** confuses users ... arbitrary, made-up version numbers will surely confuse _everyone_ even more. The hashcat project will start getting bug reports for version numbers that have never existed and never will. It will be a nightmare.

The best thing, both for hashcat and the downstreams, is to bump everything to 1:3.6.0 ASAP, and move forward.
