### ISSUE TITLE
Support for md5hmac(left, salt, 16) XOR sha1hmac(right, salt, 16) needed

### ISSUE THREAD

**Issue by SandraK82** [hashcat/hashcat#1283]
Hi, 
we encountered a system with interesting challenge response:

1. a Salt is given as 28 bytes
1. a 16 byte Password is split into a left and right half
1. two hashes (md5hmac(left, salt, 16) and sha1hmac(right, salt, 16) ) a generated and combined via XOR into the result

We know through man in the middle attack the salt and result and verificated the generation with one known password.

**Comment by DoZ10** [comment]
I believe this is actually a really bad design.

1) Using two independant parts combined with XOR enables collisions. 
2) This algorithm is not secure. It is vulnerable to a clever attack by pre-computing the right side which may be empty (or padded) for passwords below 9 chars. 

Which system uses this ?

**Comment by SandraK82** [comment]
It is used in a closed medical appliance, an insulin delivery pump. The pump uses different hard coded passwords to authenticate different application layers to access the pump functions. 
We need to get one of the passwords as we want to be able to use the pump in a so called closed loop system. 
One layer we can access as the configuration software uses this (known) password to program different settings on the pump.

**Comment by DoZ10** [comment]
Do you have a hint on the password's length you are looking for ? Or is it really fixed to 16 bytes ?

Also, can you provide a test samples ?

**Comment by SandraK82** [comment]
the password is 16 bytes, 8 bytes per side, the resulting hash is 16 bytes, the salt is 28 bytes

```
salt = "service pwd" + "56D59E656ABDC651294AB2AFBBF21E0E".decode('hex')
challenge_response = "07932f496a777a880b927b85b5b267a9".decode('hex')

(r1, r2) = evenHalveString("u+5Fhz6Gw4j1Kkas")
m1 = md5Khmac(r1, salt, 16)
s1 = sha1Khmac(r2, salt, 16)

orig_result=stringXOR(m1, s1)

assert(orig_result == challenge_response)
```
for the functions please look at: https://github.com/jamorham/SightProxy/blob/master/lib/cryptograph.py#L75L79

**Comment by DoZ10** [comment]
To be honest, I don't believe that implementing that algorithm will solve your problem.

If the password is known to be 16 bytes and is not using common dictionary terms, you stil have to search in the whole key space which is about 26**16 for only lowercase characters... which is kinda huge.

The way I see the problem, is that you could abuse from the collision problem of the XORing operation instead. You'll get a lot more probabilities of getting a successful result. The rationale behind this is the following:

We are looking for challenge C for a password in two parts P1 & P2. The result is thus C = f(P1) XOR g(P2) where f & g are hmacs functions. If we use small numbers to represent this, we know that 7 = 5 XOR 2 = 2 XOR 5. So there exists such collision if we inverse the results. But also, 7 = 3 XOR 4 = 4 XOR 3 and so on... It is a better bet to find a collision instead of a unique pair.

The attack could be simple: Pre-compute one side with 8 bytes password and XOR the result with the hash you are looking for. Store all resulting hashes with the password part used. Then compute the other side with new guesses and match the output against the hash stored at previous step. When you get a hit, you get a collision (or the ral password if really really lucky).

Of course finding a collision will be useless if the password is reused along with another algorithm for further processing.... But if used only for authentication, than this could be a great solution.

**Comment by savek-cc** [comment]
Looking at the known pw, it seems to be 16 chars from [a-z][A-Z][0-9] and probably a couple of [,.-+?/()%&...] - so we have 26+26+10+10= 72 possibilities per char.
With 8 chars, this leaves us with 72^8 or ~2^50 *16 byte storage space for the pre-computed side (slightly >5 PiB).

**Comment by savek-cc** [comment]
Using a-z, A-Z, 0-9, as well as the following symbols: !"$%&/()=<>+*#',;.:-_
We would have 83 possibilities per char --> 16 EiB. While this is a whole lot more doable than a brute-force of a 16 char pw, it's still ambitious.

**Comment by DoZ10** [comment]
I agree.

If the password was less than 16 chars this could've been a trivial attack just like fo LM hashes. But for 16 byte passwords it gets more tricky.

Now understand that the attack I presented IS ambitious but has better potential than a pure key space search.

In the end, the question is "shall we implement such kernel ?". I don't belive so. But I am ready to help if other (and better) options are available. 

Perhaps core hashcat members can reject comments here.

**Comment by jsteube** [comment]
Is the password always of length 16? I mean exactly 16? What if it password is length 15, does it need to be padded and if yes, which byte is used for padding?

**Comment by SandraK82** [comment]
It seems to be always 16bytes

Von meinem iPhone gesendet

**Comment by jsteube** [comment]
I agree with @DoZ10 this is not really an algorithm that should be added to hashcat. Except your usecase  no one could make use of it. 

However I find the topic important, given the fact that it's used in a medical application. My question therefore would be, is a "collision" enough to exploit whatever type of issue you found or is it required to be the correct key?

**Comment by TebbeUbben** [comment]
Yes, a collision would be a enough. It's just used to generate a password hash based on a given salt.

**Comment by jsteube** [comment]
@SandraK82 The magic "service pwd" is only 11 byte, including the 16 byte salt this makes 27. But your descriptions says 28 byte.

**Comment by TebbeUbben** [comment]
You should take a look at this: https://github.com/jamorham/SightProxy/blob/master/lib/cryptograph.py
This would be the method call for a service password we already know: `multiHashXOR("u+5Fhz6Gw4j1Kkas", "service pwd" + "56D59E656ABDC651294AB2AFBBF21E0E".decode('hex'), 16)`

**Comment by jsteube** [comment]
OK and what is the result? Because 07932f496a777a880b927b85b5b267a9 doesn't match.

**Comment by TebbeUbben** [comment]
The result is hex encoded: `07932f496a777a880b927b85b5b267a9`

**Comment by TebbeUbben** [comment]
Why does this not match?

**Comment by jsteube** [comment]
hmac md5 of '736572766963652070776456d59e656abdc651294ab2afbbf21e0e' (in hex) with key 'u+5Fhz6G' = bec6cc8cafb4a5bd2750b8ccce274e63
hmac sha1 of '736572766963652070776456d59e656abdc651294ab2afbbf21e0e' (in hex) with key 'w4j1Kkas' = 9e816ba5db708fd311a6830d9ffaf231

bec6cc8cafb4a5bd2750b8ccce274e63 ^ 9e816ba5db708fd311a6830d9ffaf231 = 2047A72974C42A6E36F63BC151DDBC52

**Comment by DoZ10** [comment]
Looking at the Python code....

```
def getHmac(secret, data, hash):
    return hmac.new(secret, data, hash).digest()


def Khmac(secret, seed, bytes, hash):
    nu_seed = seed
    output = ''
    while len(output) < bytes:
        nu_seed = getHmac(secret, nu_seed, hash)
        output += getHmac(secret, nu_seed + seed, hash)
    return output[:bytes]
```

I've never implemented HMACs myself, but it looks odd to perform the computation twice. Seems like your problem may come from there @jsteube

**Comment by jsteube** [comment]
Indeed, it's double hmac! It worked now:

b6c4fae33b7d5c2dcf843d4da0ce474b ^
b157d5aa510a26a5c41646c8157c20e2 =
07932f496a777a880b927b85b5b267a9

**Comment by jamorham** [comment]
As the key gets split in half and then the resulting hashes are xor'd.. is it possible to treat one side of the password as a block of work and then iterate the other half of the password and compare with the xor of the challenge and the hash result from the "block" so that only, for example, the md5 component needs to be calculated rapidly while the sha1 component is only calculated once per "block" ?

**Comment by savek-cc** [comment]
As described in https://github.com/hashcat/hashcat/issues/1283#issuecomment-310754000 ?

**Comment by DoZ10** [comment]
@jamorham Yes if you are looking for a collision., because pre-computing the whole keyspace for just 8 bytes (one half) still requires a huge amount of space. So finding the exact pair will still remain a problem.

**Comment by jsteube** [comment]
The reason why I was asking if a collision is "ok" was the following: What we can do is to precompute let's say a "set" of precomputed hashes (the SHA1 ones), but we're kind of limited in size here. I guess 10-50 million hashes max (means 10-50 million input candidates), depending on the GPU memory. This set can be used in multihash cracking mode as the salt is always the same. Now we can run the full 96^8 ascii charset against this list. On my 4*GTX1080 I expect this to run ~16 days. However, there's no guarantee it will crack at least one. But if not we can continue with another set that will run 16 days again, and so on...

**Comment by TebbeUbben** [comment]
Maybe we all can take different sets? (I have a GTX 1060, so I must take a smaller set, if this is possible.)

**Comment by jamorham** [comment]
@savek-cc @DoZ10 I don't think what I'm describing is a collision, I thought it was just a re-arrangement of the components. I'm not suggesting any pre-computation except that for each "block" of the iterations for half the key the other half of the key would be calculated. So that you only have to calculate one of the hmacs in a loop.

**Comment by jamorham** [comment]
@jsteube A collision would be just fine if it can produce the challenge response for any challenge using this algorithm. If it passes that test that is all the "key" is needed for. But the second part of the challenge/salt will be different each time. I don't understand enough of what is discussed above to understand the distinction or how much the key-space gets reduced by looking for collisions.

**Comment by savek-cc** [comment]
Well - yes - basically that is just an ordering of the "passwords" to take a fixed value for the upper 8 bytes and then iterate through the full lower 8 bytes. It's the same as proposed by @jsteube though - only that he would test against 10-50 mil "upper bytes" with one loop through all lower halfes.

**Comment by jamorham** [comment]
@savek-cc that sounds about 10-50 million times faster than what I was suggesting.

**Comment by DoZ10** [comment]
If you guys really want this password.. I believe what @jsteub is proposing will be your best bet.

**Comment by jsteube** [comment]
Here's a patch that enables -m 50 to do the cracking:

```
diff --git a/OpenCL/m00050_a3.cl b/OpenCL/m00050_a3.cl
index b5120e89..45af4de0 100644
--- a/OpenCL/m00050_a3.cl
+++ b/OpenCL/m00050_a3.cl
@@ -296,6 +296,30 @@ void m00050m (u32 w0[4], u32 w1[4], u32 w2[4], u32 w3[4], const u32 pw_len, __gl
 
     hmac_md5_run (w0_t, w1_t, w2_t, w3_t, ipad, opad, digest);
 
+    w0_t[0] = digest[0];
+    w0_t[1] = digest[1];
+    w0_t[2] = digest[2];
+    w0_t[3] = digest[3];
+    w1_t[0] = salt_buf0[0];
+    w1_t[1] = salt_buf0[1];
+    w1_t[2] = salt_buf0[2];
+    w1_t[3] = salt_buf0[3];
+    w2_t[0] = salt_buf1[0];
+    w2_t[1] = salt_buf1[1];
+    w2_t[2] = salt_buf1[2];
+    w2_t[3] = salt_buf1[3];
+    w3_t[0] = salt_buf2[0];
+    w3_t[1] = salt_buf2[1];
+    w3_t[2] = (64 + 16 + salt_len) * 8;
+    w3_t[3] = 0;
+
+    hmac_md5_run (w0_t, w1_t, w2_t, w3_t, ipad, opad, digest);
+
+    digest[0] ^= swap32 (0x07932f49);
+    digest[1] ^= swap32 (0x6a777a88);
+    digest[2] ^= swap32 (0x0b927b85);
+    digest[3] ^= swap32 (0xb5b267a9);
+
     COMPARE_M_SIMD (digest[0], digest[3], digest[2], digest[1]);
   }
 }
@@ -413,6 +437,30 @@ void m00050s (u32 w0[4], u32 w1[4], u32 w2[4], u32 w3[4], const u32 pw_len, __gl
 
     hmac_md5_run (w0_t, w1_t, w2_t, w3_t, ipad, opad, digest);
 
+    w0_t[0] = digest[0];
+    w0_t[1] = digest[1];
+    w0_t[2] = digest[2];
+    w0_t[3] = digest[3];
+    w1_t[0] = salt_buf0[0];
+    w1_t[1] = salt_buf0[1];
+    w1_t[2] = salt_buf0[2];
+    w1_t[3] = salt_buf0[3];
+    w2_t[0] = salt_buf1[0];
+    w2_t[1] = salt_buf1[1];
+    w2_t[2] = salt_buf1[2];
+    w2_t[3] = salt_buf1[3];
+    w3_t[0] = salt_buf2[0];
+    w3_t[1] = salt_buf2[1];
+    w3_t[2] = (64 + 16 + salt_len) * 8;
+    w3_t[3] = 0;
+
+    hmac_md5_run (w0_t, w1_t, w2_t, w3_t, ipad, opad, digest);
+
+    digest[0] ^= swap32 (0x07932f49);
+    digest[1] ^= swap32 (0x6a777a88);
+    digest[2] ^= swap32 (0x0b927b85);
+    digest[3] ^= swap32 (0xb5b267a9);
+
     COMPARE_S_SIMD (digest[0], digest[3], digest[2], digest[1]);
   }
 }
```

And here's a small perl program to precompute the SHA1 blocks:

```
#!/usr/bin/perl

use strict;
use warnings;
use Digest::MD5  qw (md5);
use Digest::SHA  qw (sha1);
use Digest::HMAC qw (hmac);

my $seed = "service pwd";
my $salt = "56d59e656abdc651294ab2afbbf21e0e";

while (my $line = <>)
{
  $line =~ s/\n$//;
  $line =~ s/\r$//;

  my $final_salt = $seed . pack ("H*", $salt);

#  my $hash_buf1 = hmac ($final_salt, $line, \&md5, 64);
#  my $hash_buf2 = hmac ($hash_buf1 . $final_salt, $line, \&md5, 64);

  my $hash_buf1 = hmac ($final_salt, $line, \&sha1, 64);
  my $hash_buf2 = hmac ($hash_buf1 . $final_salt, $line, \&sha1, 64);

  printf ("%s:%s\n", unpack ("H*", substr ($hash_buf2, 0, 16)), unpack ("H*", $final_salt));
}

# md5:  b6c4fae33b7d5c2dcf843d4da0ce474b
# sha1: b157d5aa510a26a5c41646c8157c20e2
```

Note that I've inlined the final hash (the one we want to compare) into both kernels (single and multi hash) by simply XOR the result of the double MD5 HMAC with it, because it doesn't matter which way we use it... since it's XOR! This way we can use hashcats fast bitmaps and binary tree searching on device.

The perl program just takes every input on stdin and creates the hash out of it. You can use maskprocessor to create a full BF-stylish attack if you want to do that and pipe it to the perl program. The list that comes out is the hashlist to feed hashcat with.

Example:

```
root@et:~/hashcat# echo 'w4j1Kkas' | perl dict2hash.pl 
b157d5aa510a26a5c41646c8157c20e2:736572766963652070776456d59e656abdc651294ab2afbbf21e0e
root@et:~/hashcat# 
```

```
root@et:~/hashcat# ./hashcat -m 50 hash.txt --hex-salt -w 3 -a 3 'u+5Fhz6G' --quiet
b157d5aa510a26a5c41646c8157c20e2:736572766963652070776456d59e656abdc651294ab2afbbf21e0e:u+5Fhz6G
root@et:~/hashcat# 
```

It's important to use -a 3 and --hex-salt here.

**Comment by jamorham** [comment]
@jsteube this is really great, thank you

**Comment by TebbeUbben** [comment]
I get this error when I try to run the patch:
```
Initialized device kernels and memory...* Device #1: ATTENTION! OpenCL kernel self-test failed.

Your device driver installation is probably broken.
```

I already followed this guide: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_may_have_the_wrong_driver_installed_what_should_i_do
