### ISSUE TITLE
Request for basic DES-ECB cracking

### ISSUE THREAD

**Issue by mattames** [hashcat/hashcat#129]
Hi Guys,

Can you add a basic DES-ECB cracker? Since Hashcat contains several algorithms (-m 1500 and 3000) that use DES-ECB as a core component, I figure most of the work is done already. This mode would simply take a known 64 bit DES input and output plaintext/ciphertext pair and then brute force the key used.

This would be greatly advantageous to myself as part of some other work I am doing on another open source project, and it would enable some cool comparisons between GPU and FPGA solutions in terms of keys per second/cost/complexity/power consumption.

**Comment by jsteube** [comment]
For me this sounds like a bad idea to compare FPGA/CPU with GPU using DES since DES is so extremely FPGA/CPU friendly. A comparison based on MD5 makes much more sense since this algorithms is friendly for both platforms.

Anyway I think such an algorithm can make sense for known-plaintext based attacks since so many crypto schemes still base on raw DES but it should be mode-independant. You can anyway simply reverse the ECB from it before putting it to oclHashcat.

**Comment by mattames** [comment]
Yes, once the plaintext/ciphertext pair is extracted (easy to do) they can then be fed into oclHashcat. FPGA implementations are hard to come by, require experience with FPGAs, expensive software tools to be able to create the bitstreams on the larger devices ($5000 for one vendor), and can be time consuming to create an image and troubleshoot it.

By comparison, oclHashcat on GPU is fast, off the shelf and if you collaborate with a few friends with GPUs they can 'lend' you their spare cycles and it would be feasible to split the keyspace up into slices for a zero-cost solution using the GPUs that people already own...

**Comment by STUCK12** [comment]
Seconded. Is there any public software that can actually support 64-bit DES (CPU or GPU based)?

**Comment by mattames** [comment]
Hi Guys,

Is there any chance someone might be able to implement this one? 

Cheers,
Matt

**Comment by roycewilliams** [comment]
https://github.com/hashcat/hashcat/commit/71a8459d851d246945343ea59effa1d46b965bf8
