### ISSUE TITLE
Error in Hmac patch

### ISSUE THREAD

**Issue by TebbeUbben** [hashcat/hashcat#1293]
As I don't know if you have been notified about my answer in the other issue because it's close, I create a new one.

I downloaded and installed the patch you provided here: https://github.com/hashcat/hashcat/issues/1283

But when I try to run it, I get this error:
```
Initialized device kernels and memory...* Device #1: ATTENTION! OpenCL kernel self-test failed.

Your device driver installation is probably broken.
```

I already followed this guide: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_may_have_the_wrong_driver_installed_what_should_i_do
The benchmark runs without any errors.

**Comment by jsteube** [comment]
In the patch I've hacked the kernel and this results in a final digest which does not match the expected one. That's good it does that, because it tells us the self-test is working. If it cracks with my example data provided you can assume it's fine.

**Comment by TebbeUbben** [comment]
But how can I run the patch without pressing R all the time?

**Comment by jsteube** [comment]
Try --self-test-disable

**Comment by TebbeUbben** [comment]
My CPU RAM is completely full and the only message Hashcat displays is "Sorting hashes..."

Is that normal? (I'm using about 13 Millionen hashes)

**Comment by jsteube** [comment]
It will take time. Cracking so many salted hashes is very unusual (unliked unsalted hashes), because it's expected to be all different salts. If that would be the case, no one would do it. So it's a special behavior caused by a special use case.

**Comment by Freudma16310** [comment]
* Device #1: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz, skipped
* Device #2: Iris Pro, 384/1536 MB allocatable, 40MCU
* Device #3: AMD Radeon R9 M370X Compute Engine, 512/2048 MB allocatable, 10MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD-LOOP

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

Error: out of memory.

* Device #2: Kernel /usr/local/share/hashcat/OpenCL/m09600-pure.cl build failed - proceeding without this device.

Host memory required for this attack: 547 MB

* Device #3: ATTENTION! OpenCL kernel self-test failed.

Your device driver installation is probably broken.
See also: https://hashcat.net/faq/wrongdriver

Aborting session due to kernel self-test failure.

You can use --self-test-disable to override this, but do not report related errors.

Started: Sat Oct 12 11:10:46 2019
Stopped: Sat Oct 12 11:13:39 2019

**Comment by Freudma16310** [comment]
How to use --self-test-disable?

**Comment by Rdgeno** [comment]
Hashcat Forums said not to use that it will run like a bastard but wont find the password. I ran a test they where right.

**Comment by Rdgeno** [comment]
If your using windows that's the only way I know that works go to custom command and enter --self-test-disable.
