### ISSUE TITLE
[Feature Request] $RAR3$*1 Support

### ISSUE THREAD

**Issue by astandarduser** [hashcat/hashcat#1334]
Just tried this type of hash today only to find out it doesn't work :( Is there any plan on implementing support for this?

**Comment by roycewilliams** [comment]
Huh - this was news to me, didn't realize there was a difference (or why hashcat's -m 12500 is listed as "RAR3-hp" - to distinguish from what I would expect would be called "RAR3-p"):

http://blog.zorinaq.com/brute-forcing-rar-archives-encrypted-with-the-hp-option/
https://stackoverflow.com/questions/44504313/rar3-hashing-algorithm
http://openwall.info/wiki/john/sample-non-hashes#RAR

This thread suggests that support is planned, "but don't ask when": :)

https://hashcat.net/forum/thread-5334-post-28950.html#pid28950

**Comment by magnumripper** [comment]
#68 

In order to check such RAR3 archives you need to implement loads and loads of deflating code on CPU side (it simply wont work on GPU), with very clever early-rejection stuff to keep speed up.

**Comment by TsmSwagLorD** [comment]
Has there been any progress on this?

**Comment by martclau** [comment]
Hi hashcat team, any chance of supporting RAR3 type 1 files? From rar2john.c:

_For type = 1 for files encrypted with "rar -p ..." option:

archive_name:$RAR3$*type*hex(salt)*hex(crc)*PACK_SIZE*UNP_SIZE*0*archive_name*offset-for-ciphertext*method:type::file_name
 
or:

archive_name:$RAR3$*type*hex(salt)*hex(crc)*PACK_SIZE*UNP_SIZE*1*hex(full encrypted file)*method:type::file_name_

**Comment by jsteube** [comment]
Maybe. For 7zip we had some special hooks added to do the checking. Maybe @philsmd can help here?

**Comment by magnumripper** [comment]
In JtR we use ClamAV unrar code (simply because it's C as opposed to C++) for decompression/CRC and before even calling that, we have our own early-rejection code, required for performance. Also, the ClamAV code had more semi-early rejection added (bail immediately on error instead of chugging along) and was modified for streaming CRC instead of unpacking the potentially huge compressed buffer to an even larger uncompressed buffer. You'd probably be best off nicking the code from Jumbo and put it in those hooks. I could do it for hashcat except I don't have any spare time at all right now so @philsmd is probably your best bet (I could be of help in case of questions though).

**Comment by martclau** [comment]
Any feedback re this? NB: currently using an alternative but would really prefer to use hashcat.

**Comment by mblackshore** [comment]
@philsmd are you up for the task?

**Comment by magnumripper** [comment]
It's a fairly heavy task

**Comment by martclau** [comment]
NB: I would assume that type 1 is the most commonly used format when encrypting RAR files.

**Comment by magnumripper** [comment]
Yeah, by far.

**Comment by mblackshore** [comment]
Have anyone worked with sha-1 collisions? I'm asking due to $RAR3$*1 uses sha-1 , yes?
and could the method be used here?
I'm refering to this:
https://github.com/corkami/collisions

**Comment by BarrowHill** [comment]
dear hashcat team, please add $RAR3$*1 Support.

**Comment by philsmd** [comment]
I think the non-compressed version of `$RAR3$*1*` could possibly be supported quite easily.

These archives are generated by this command (old rar 3 archives, not the newer RAR5):
```
rar -p -m0 a file.rar file.txt
```

The hash format would look like this:
```
$RAR3$*1*salt*crc*pack_size*unpack_size*1*data*30
```

please note that there is a `*30` at the end.

The algorithm for cracking these archives is similar to the -m 12500 = RAR-hp one, but we need to perform a CRC32 checksum of the decrypted data (Attention, in case of the method **30**, there is **no decompression** involved, no unrar code needed), here is my POC:
```
#!/usr/bin/env perl

# Author: philsmd
# Date: June 2020
# License: public domain, credits go to philsmd and hashcat

# This algorithm only works for old RAR3 files generated with:
# rar -p -m0 a file.rar file.txt

# hash format:
# $RAR3$*1*salt*crc*pack_size*unpack_size*1*data*30
# i.e. method 30 at the end is important (not compressed, no deflate)

use strict;
use warnings;

use Digest::SHA;
use Digest::CRC qw (crc32);
use Crypt::CBC;
use Encode;

#
# Constants
#

my $ITERATIONS = 0x40000;

my $SHA1C00 = 0x5a827999;
my $SHA1C01 = 0x6ed9eba1;
my $SHA1C02 = 0x8f1bbcdc;
my $SHA1C03 = 0xca62c1d6;

my $SHA1M_A = 0x67452301;
my $SHA1M_B = 0xefcdab89;
my $SHA1M_C = 0x98badcfe;
my $SHA1M_D = 0x10325476;
my $SHA1M_E = 0xc3d2e1f0;


#
# Examples
#

# Example 1:

# $RAR3$*1*e54a73729887cb53*49b0a846*16*14*1*34620bcca8176642a210b1051901921e*30:hashcat

my $pass  = "hashcat";
my $salt  = pack ("H*", "e54a73729887cb53");
my $crc32 = unpack ("L<", pack ("H*", "49b0a846"));

my $pack_size   = 16;
my $unpack_size = 14;

my $data = pack ("H*", "34620bcca8176642a210b1051901921e");


# Example 2:

# $RAR3$*1*c47c5bef0bbd1e98*965f1453*48*47*1*c5e987f81d316d9dcfdb6a1b27105ce63fca2c594da5aa2f6fdf2f65f50f0d66314f8a09da875ae19d6c15636b65c815*30:test

# my $pass  = "test";
# my $salt  = pack ("H*", "c47c5bef0bbd1e98");
# my $crc32 = unpack ("L<", pack ("H*", "965f1453"));

# my $pack_size   = 48;
# my $unpack_size = 47;

# my $data = pack ("H*", "c5e987f81d316d9dcfdb6a1b27105ce63fca2c594da5aa2f6fdf2f65f50f0d66314f8a09da875ae19d6c15636b65c815");


#
# Helper functions
#

sub rotl32
{
  my $x = shift;
  my $n = shift;

  return (($x << $n) | ($x >> (32 - $n))) & 0xffffffff;
}

sub blk
{
  my $b = shift;
  my $i = shift;

  $$b[$i & 15] = rotl32 ($$b[($i + 13) & 15] ^
                         $$b[($i +  8) & 15] ^
                         $$b[($i +  2) & 15] ^
                         $$b[($i +  0) & 15], 1);

  return $$b[$i & 15];
}

sub R0
{
  my ($b, $v, $w, $x, $y, $z, $i) = @_;

  $$b[$i] = unpack ("L<", pack ("L>", $$b[$i])); # blk0 or just swap_byte32 ()

  $z += (($w & ($x ^ $y)) ^ $y) + $$b[$i] + $SHA1C00 + rotl32 ($v, 5);

  $z &= 0xffffffff;

  $w = rotl32 ($w, 30);

  return ($z, $w);
}

sub R1
{
  my ($b, $v, $w, $x, $y, $z, $i) = @_;

  $z += (($w & ($x ^ $y)) ^ $y) + blk ($b, $i) + $SHA1C00 + rotl32 ($v, 5);

  $z &= 0xffffffff;

  $w = rotl32 ($w, 30);

  return ($z, $w);
}

sub R2
{
  my ($b, $v, $w, $x, $y, $z, $i) = @_;

  $z += ($w ^ $x ^ $y) + blk ($b, $i) + $SHA1C01 + rotl32 ($v, 5);

  $z &= 0xffffffff;

  $w = rotl32 ($w, 30);

  return ($z, $w);
}

sub R3
{
  my ($b, $v, $w, $x, $y, $z, $i) = @_;

  $z += ((($w | $x) & $y) | ($w & $x)) + blk ($b, $i) + $SHA1C02 + rotl32 ($v, 5);

  $z &= 0xffffffff;

  $w = rotl32 ($w, 30);

  return ($z, $w);
}

sub R4
{
  my ($b, $v, $w, $x, $y, $z, $i) = @_;

  $z += ($w ^ $x ^ $y) + blk ($b, $i) + $SHA1C03 + rotl32 ($v, 5);

  $z &= 0xffffffff;

  $w = rotl32 ($w, 30);

  return ($z, $w);
}

sub sha1_transform
{
  my ($state, $buffer) = @_;

  my @block = unpack ("L<*", $$buffer);

  my $a = $$state[0];
  my $b = $$state[1];
  my $c = $$state[2];
  my $d = $$state[3];
  my $e = $$state[4];

  ($e, $b) = R0 (\@block, $a, $b, $c, $d, $e,  0);
  ($d, $a) = R0 (\@block, $e, $a, $b, $c, $d,  1);
  ($c, $e) = R0 (\@block, $d, $e, $a, $b, $c,  2);
  ($b, $d) = R0 (\@block, $c, $d, $e, $a, $b,  3);

  ($a, $c) = R0 (\@block, $b, $c, $d, $e, $a,  4);
  ($e, $b) = R0 (\@block, $a, $b, $c, $d, $e,  5);
  ($d, $a) = R0 (\@block, $e, $a, $b, $c, $d,  6);
  ($c, $e) = R0 (\@block, $d, $e, $a, $b, $c,  7);

  ($b, $d) = R0 (\@block, $c, $d, $e, $a, $b,  8);
  ($a, $c) = R0 (\@block, $b, $c, $d, $e, $a,  9);
  ($e, $b) = R0 (\@block, $a, $b, $c, $d, $e, 10);
  ($d, $a) = R0 (\@block, $e, $a, $b, $c, $d, 11);

  ($c, $e) = R0 (\@block, $d, $e, $a, $b, $c, 12);
  ($b, $d) = R0 (\@block, $c, $d, $e, $a, $b, 13);
  ($a, $c) = R0 (\@block, $b, $c, $d, $e, $a, 14);
  ($e, $b) = R0 (\@block, $a, $b, $c, $d, $e, 15);

  ($d, $a) = R1 (\@block, $e, $a, $b, $c, $d, 16);
  ($c, $e) = R1 (\@block, $d, $e, $a, $b, $c, 17);
  ($b, $d) = R1 (\@block, $c, $d, $e, $a, $b, 18);
  ($a, $c) = R1 (\@block, $b, $c, $d, $e, $a, 19);

  ($e, $b) = R2 (\@block, $a, $b, $c, $d, $e, 20);
  ($d, $a) = R2 (\@block, $e, $a, $b, $c, $d, 21);
  ($c, $e) = R2 (\@block, $d, $e, $a, $b, $c, 22);
  ($b, $d) = R2 (\@block, $c, $d, $e, $a, $b, 23);

  ($a, $c) = R2 (\@block, $b, $c, $d, $e, $a, 24);
  ($e, $b) = R2 (\@block, $a, $b, $c, $d, $e, 25);
  ($d, $a) = R2 (\@block, $e, $a, $b, $c, $d, 26);
  ($c, $e) = R2 (\@block, $d, $e, $a, $b, $c, 27);

  ($b, $d) = R2 (\@block, $c, $d, $e, $a, $b, 28);
  ($a, $c) = R2 (\@block, $b, $c, $d, $e, $a, 29);
  ($e, $b) = R2 (\@block, $a, $b, $c, $d, $e, 30);
  ($d, $a) = R2 (\@block, $e, $a, $b, $c, $d, 31);

  ($c, $e) = R2 (\@block, $d, $e, $a, $b, $c, 32);
  ($b, $d) = R2 (\@block, $c, $d, $e, $a, $b, 33);
  ($a, $c) = R2 (\@block, $b, $c, $d, $e, $a, 34);
  ($e, $b) = R2 (\@block, $a, $b, $c, $d, $e, 35);

  ($d, $a) = R2 (\@block, $e, $a, $b, $c, $d, 36);
  ($c, $e) = R2 (\@block, $d, $e, $a, $b, $c, 37);
  ($b, $d) = R2 (\@block, $c, $d, $e, $a, $b, 38);
  ($a, $c) = R2 (\@block, $b, $c, $d, $e, $a, 39);

  ($e, $b) = R3 (\@block, $a, $b, $c, $d, $e, 40);
  ($d, $a) = R3 (\@block, $e, $a, $b, $c, $d, 41);
  ($c, $e) = R3 (\@block, $d, $e, $a, $b, $c, 42);
  ($b, $d) = R3 (\@block, $c, $d, $e, $a, $b, 43);

  ($a, $c) = R3 (\@block, $b, $c, $d, $e, $a, 44);
  ($e, $b) = R3 (\@block, $a, $b, $c, $d, $e, 45);
  ($d, $a) = R3 (\@block, $e, $a, $b, $c, $d, 46);
  ($c, $e) = R3 (\@block, $d, $e, $a, $b, $c, 47);

  ($b, $d) = R3 (\@block, $c, $d, $e, $a, $b, 48);
  ($a, $c) = R3 (\@block, $b, $c, $d, $e, $a, 49);
  ($e, $b) = R3 (\@block, $a, $b, $c, $d, $e, 50);
  ($d, $a) = R3 (\@block, $e, $a, $b, $c, $d, 51);

  ($c, $e) = R3 (\@block, $d, $e, $a, $b, $c, 52);
  ($b, $d) = R3 (\@block, $c, $d, $e, $a, $b, 53);
  ($a, $c) = R3 (\@block, $b, $c, $d, $e, $a, 54);
  ($e, $b) = R3 (\@block, $a, $b, $c, $d, $e, 55);

  ($d, $a) = R3 (\@block, $e, $a, $b, $c, $d, 56);
  ($c, $e) = R3 (\@block, $d, $e, $a, $b, $c, 57);
  ($b, $d) = R3 (\@block, $c, $d, $e, $a, $b, 58);
  ($a, $c) = R3 (\@block, $b, $c, $d, $e, $a, 59);

  ($e, $b) = R4 (\@block, $a, $b, $c, $d, $e, 60);
  ($d, $a) = R4 (\@block, $e, $a, $b, $c, $d, 61);
  ($c, $e) = R4 (\@block, $d, $e, $a, $b, $c, 62);
  ($b, $d) = R4 (\@block, $c, $d, $e, $a, $b, 63);

  ($a, $c) = R4 (\@block, $b, $c, $d, $e, $a, 64);
  ($e, $b) = R4 (\@block, $a, $b, $c, $d, $e, 65);
  ($d, $a) = R4 (\@block, $e, $a, $b, $c, $d, 66);
  ($c, $e) = R4 (\@block, $d, $e, $a, $b, $c, 67);

  ($b, $d) = R4 (\@block, $c, $d, $e, $a, $b, 68);
  ($a, $c) = R4 (\@block, $b, $c, $d, $e, $a, 69);
  ($e, $b) = R4 (\@block, $a, $b, $c, $d, $e, 70);
  ($d, $a) = R4 (\@block, $e, $a, $b, $c, $d, 71);

  ($c, $e) = R4 (\@block, $d, $e, $a, $b, $c, 72);
  ($b, $d) = R4 (\@block, $c, $d, $e, $a, $b, 73);
  ($a, $c) = R4 (\@block, $b, $c, $d, $e, $a, 74);
  ($e, $b) = R4 (\@block, $a, $b, $c, $d, $e, 75);

  ($d, $a) = R4 (\@block, $e, $a, $b, $c, $d, 76);
  ($c, $e) = R4 (\@block, $d, $e, $a, $b, $c, 77);
  ($b, $d) = R4 (\@block, $c, $d, $e, $a, $b, 78);
  ($a, $c) = R4 (\@block, $b, $c, $d, $e, $a, 79);

  $$state[0] = ($$state[0] + $a) & 0xffffffff;
  $$state[1] = ($$state[1] + $b) & 0xffffffff;
  $$state[2] = ($$state[2] + $c) & 0xffffffff;
  $$state[3] = ($$state[3] + $d) & 0xffffffff;
  $$state[4] = ($$state[4] + $e) & 0xffffffff;

  $$buffer = pack ("L<*", @block);
}

sub sha1_getstate
{
  my $ctx = shift;

  my $info = $ctx->getstate;

  # state:

  my $idx = index ($info, "H:");

  my $state = substr ($info, $idx + 2, 44);

  $state =~ s/://g;

  my @state_arr = unpack ("L>*", pack ("H*", $state));

  # block:

  $idx = index ($info, "block:");

  my $block = substr ($info, $idx + 6, 191);

  $block =~ s/://g;

  $block = pack ("H*", $block);


  return (\@state_arr, $block);
}

sub sha1_update_rar29
{
  my $ctx   = shift;
  my $data  = shift;
  my $len   = shift;
  my $count = shift;

  my $ctx_orig = $ctx->clone;

  $ctx->add ($$data);


  # two early exits from this function, if (strange data) manipulation is not needed:

  my $j = $count & 63;

  return if (($j + $len) <= 63);


  my $i = 64 - $j;

  return if (($i + 63) >= $len);


  # proceed with updating $data:

  my ($state, $block) = sha1_getstate ($ctx_orig);


  substr ($block, $j, $i) = substr ($$data, 0, $i);

  sha1_transform ($state, \$block);


  while (($i + 63) < $len)
  {
    my $workspace = substr ($$data, $i, 64);

    sha1_transform ($state, \$workspace);

    substr ($$data, $i, 64) = $workspace;

    $i += 64;
  }
}

sub rar3_p
{
  my $pass = shift;
  my $salt = shift;

  # convert to utf16le:

  my $buf = encode ("UTF-16LE", $pass);

  # add the salt to the password buffer:

  $buf .= $salt;

  my $len = length ($buf);

  my $count = 0;

  my $ctx = Digest::SHA->new ('SHA1');

  my $iv = "";

  # main loop:

  for (my $i = 0; $i < $ITERATIONS; $i++)
  {
    sha1_update_rar29 ($ctx, \$buf, $len, $count);

    $count += $len;

    my $pos = substr (pack ("L<", $i), 0, 3);

    $ctx->add ($pos);

    $count += 3;

    if (($i & 0x3fff) == 0)
    {
      my $dgst = $ctx->clone->digest;

      $iv .= substr ($dgst, 19, 1);
    }
  }

  my $key = $ctx->digest;

  $key = pack ("L<*", unpack ("L>4", $key)); # byte swap the first 4 * 4 = 16 bytes

  return ($key, $iv);
}

#
# Start
#

# main hash generation function:

my ($key, $iv) = rar3_p ($pass, $salt);


# AES-128 decrypt:

my $aes = Crypt::CBC->new (
  -cipher      => "Crypt::Rijndael",
  -key         => $key,
  -iv          => $iv,
  -keysize     => 16,
  -literal_key => 1,
  -header      => 'none',
  -padding     => 'standard'
);

my $data_encrypted = substr ($data, 0, $pack_size);
my $data_decrypted = $aes->decrypt ($data_encrypted);


# CRC32 checksum of the decrypted data:

my $data_crc = substr ($data_decrypted, 0, $unpack_size);

my $crc32_computed = crc32 ($data_crc);


# verify:

if ($crc32_computed eq $crc32)
{
  print "Password found '$pass'\n";
}
```

I think even the crc32 checksum should be done on GPU... we just need to decide how much data can/should be allowed for this type of hashes... We probably need a data buffer limit under or around 320 KB or so (similar to 7-zip/pkzip etc).

The problem could be that this type of hashes are not that common, because normally you use compression ("deflate") when it comes to compressed archives like RAR files.
Anyway, it would probably make much more sense to split this **method 30** algorithm that could be computed 100% on GPU from the one that probably needs a hook (method 33 ?).

What's your opinion about this ? Does somebody even have such a non-compressed (method 30) hash that needs to be cracked ? How common is this ?

**Comment by magnumripper** [comment]
I'm of the opinion you should add the full proper support instead. It's not THAT hard, especially if you nick the JtR code. But I realize, somehow, that it's up to you (@philsmd ) or won't happen. I'll be happy to help out.

**Comment by magnumripper** [comment]
BTW how's the support in hc for early rejection, *after* being submitted to a hook?

**Comment by philsmd** [comment]
we just use some structs (that can be defined for each and every hash type/module differently) to communicate between cpu hook code and the OpenCL/CUDA kernels. e.g. https://github.com/hashcat/hashcat/blob/a20cd998f1bb63938d99a490ba73cf7f382cd2e8/OpenCL/m11600-pure.cl#L347
in this case the hook_success tells the kernel that the CPU hook code was successful (of course you could name it however you like and also have multiple variables within that struct etc).

**Comment by mblackshore** [comment]
oh, finally some movement!
#hope

**Comment by magnumripper** [comment]
@mblackshore you could just attack it with JtR (jumbo) in the meantime. It's quirky and not 2020's style good stuff in many ways - but it does support just about any size and any type of rar.

**Comment by mblackshore** [comment]
The Open CL omplementation is 4x faster than CPU on JtR. So I have up after 2 weeks active breaking.

**Comment by magnumripper** [comment]
4x?! That must be a toy GPU

**Comment by mblackshore** [comment]
alright, it might been a bit faster but I have memories of hashcat being faster with the cuda implementation.

**Comment by philsmd** [comment]
I have a little update for you here:
I managed to implement this hash type `Rar3-p` in hashcat with a hook as an experiment with the latest code from rarlab (`unrar`) in my local test. It works perfectly fine and is quite fast.

I decided to use the latest `unrar` code because the other codes seem quite old and out-dated (unrar doesn't even support this ANSI C code anymore, since ages and neither does `libclamunrar`, I guess they also fixed a lot of - security - bugs during these years etc so for me it's the only valid option to use the latest code).

I didn't implement any early skip etc yet, but it's still very fast (well, the hook performance of course depends a little bit on your CPU etc.... but anyway, the decompression code is quite negligible compared to the 262144 iterations of SHA1 on the GPU.
These are the current hash types I added as an experiment (code not released yet, the -m hash type number might change of course):
```
  23300 | RAR3-p (Uncompressed)                             | Archives
  23400 | RAR3-p (Compressed)                               | Archives
```

I added 2 because for the uncompressed version, we of course do not need any `hook` at all, because no unrar code is involved (only CRC32 on the GPU, as mentioned above, method 30).

I'm not sure when the code will be finished / published. There is still the question about the license (what files do we need to include in src and release version, I guess the binary version also needs to have some LICENSE files etc) and if everything is working also on other operating systems (I used the C++ code from unrar as a slightly modified library, so need to see if it's possible to compile and use this library on all operating systems that hashcat supports).

BTW: @magnumripper just to let you know that JTR still produces false negatives with RAR3-p and RAR3-hp whenever the password is longer than 28 characters, see sha1_process_rar29 () and https://github.com/hashcat/hashcat/issues/2390 . I would suggest reading that github issue and the fix https://github.com/hashcat/hashcat/pull/2419 . Thx

PS: please do not ask when it's ready and if you can have an early copy etc for it. It will be ready when it's ready and tested... no earlier. There is no testing version etc available for now. Be patient (it could also happen that it will never be merged, if we discover some major problems... so don't be too optimistic here, it's just a test)

**Comment by mblackshore** [comment]
Thanks philsmd, I'm very excited to see this happen!

**Comment by philsmd** [comment]
I think it should be enough to copy the `license.txt` of the `unrar` source code to something like `docs/license/unrar/LICENSE` and mention the 3rd party license in both the `--help` output and in our `docs/license.txt` file (mention within that file that there are more 3rd party licenses under the `docs/license/` directory for the libraries that hashcat uses).

I think this `docs/license/` directory then needs to be available also in the **release** versions of hashcat (even though there is no source code there). The license (and most of other licenses too actually) requires that the terms and credits are mentioned in every project that uses that library and binary form of it too.

I think this is a good strategy and we could make this our standard also for other libraries we could use in the future

**Comment by mblackshore** [comment]
Sounds fantastic!

**Comment by HasseM** [comment]
-never mind-
