### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by dandv** [hashcat/hashcat#1344]
Starting a new issue to store doc typos while the wiki isn't editable by GitHub contributors.

https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#what_is_a_potfile should explain what a "pot" file stands for ("plain output", presumably)? Then,

> However we strongly recommend to no disable it.

should be

> However we strongly recommend leaving it enabled.

Also,

> The .pot file is stored in hashcat's profile folder with the name “hashcat.pot”.

Should be

> The potfile is stored in hashcat's profile folder with the name “hashcat.potfile”.

**Comment by philsmd** [comment]
Thank you very much.

I've updated the FAQ page (https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#what_is_a_potfile) according to your suggestions.

I know that it could be easier if the wiki is somehow editable... but at the end it's not a big problem because even if it would be editable the amount of change request is not that high and therefore reporting it here or on the hashcat forum worked so far. I'm not against an editable wiki. I just think it is not currently possible with the mediawiki system that is in use (and if it was editable we would probably need to fight spam or malicious change requests etc).

If you think it was correctly fixed, please do not forget to close the issue.

Thank you very much
