### ISSUE TITLE
Hashcat hangs in more 14600

### ISSUE THREAD

**Issue by joeyhub** [hashcat/hashcat#1346]
This comes up:

     [s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit =>s

It does nothing though, the only thing that works is ctrl+c. It does seem to be doing something as I can here fans spinning. It is totally ignoring stdin though.

**Comment by philsmd** [comment]
We need much more details to understand this problem.

For instance, what operating system do you use? What type of prompt/shell do you use? cmd.exe?
What version of hashcat do you use?
Which GPUs do you have? Which driver do you have installed? How did you install the driver? Did you install the drivers cleanly, downloads from amd.com/nvidia.com?
etc, etc

**Comment by joeyhub** [comment]
It's the latest from the website (3.6.0). Using putty to connect to Ubuntu 16 (latest LTS). The good news is that it's running and you can work around with --status to at least get some output about how long it will take, progress, etc.

I don't see hashcat using any special library for input, it's just stdin and standard fd handling procedures. However the code does look quite complex as input processing goes.

I would guess that something is either screwing with stdin or denying the mutex to the terminal thread.

I have AMD and Intel both using the latest opencl drivers. In theory none of those should be touching stdin and are most likely touching the mutex. On the other hand you should be able to wget the AMD drivers without having to set a referrer and Intel should provide deb packages for their drivers but don't, both should be providing a repo and AMD should be providing support for ubuntu 17. Essentially all bets are off when it comes to expecting that those drivers might not do things like touch stdin.

**Comment by jsteube** [comment]
Please post all files/commandline/etc we need to reproduce locally

**Comment by joeyhub** [comment]
./hashcat64.bin -m14600 -a3 /dev/luksdev ?d?d?d?d?d?d?d

I can't give you the file but you can easily dd zero to something like a 100MB file, cryptsetup luksFormat on it. You don't need to mount it and mkfs as normal since it's not testing cracking, the problem should present as it is exhausting.

**Comment by philsmd** [comment]
Does it behave similar to the problem reported here: https://hashcat.net/forum/thread-6202-post-35411.html#pid35411 ? Does the problem only happen if the intel opencl driver is installed?
Does it also happen if you do not use putty (or do not remotely connect to the computer)?

**Comment by joeyhub** [comment]
ii  intel-opencl                                  0r5.0-63504                                  amd64
     ii  libopencl1-amdgpu-pro:amd64                   17.30-465504

It very well could be that, which would mean most likely the driver is doing something around the context or stdin. I'll see if I can reproduce it after my current test has run.

It happens without putty as well.

**Comment by joeyhub** [comment]
It's definitely the intel drivers doing it.

**Comment by philsmd** [comment]
If I'm not totally mistaken, there was some guy on the hashcat's IRC channel #hashcat that recently said that by deleting 1 of the files shipped by the intel package, he was able to still use the Intel OpenCL and AMD/Nvidia OpenCL devices without the problem with the non-interacting hashcat process.

Unfortunately, I can't remember what file it was and how difficult it was to get it working.

The problem is that this seems to have nothing to do with hashcat and we can't do anything to fix it. It's a problem of the Intel driver.
Maybe you can try to troubleshoot it and come up with a howto tutorial on how to fix it (even with working Intel CPUs)?

I'm not sure what is going on with the driver and why it makes the hashcat process non-interactive.
I can't think that it is hashcat's fault since it works flawlessly with all other setups.

I'm not sure if it makes sense to keep this issue open... but a howto/tutorial on forum etc would be nice if we can find out how to fix it (while keeping the Intel OpenCL driver working and Intel CPUs useable).
It's not even clear if it only happens with Intel + AMD or if it is a general problem with Intel driver (but I also have the Intel OpenCL drivers installed on some systems and never experienced any problems with it, so there must be some combination of installed drivers that trigger this problem).

**Comment by roycewilliams** [comment]
That IRC ref:

2017-05-28 09:25:48    [redacted] after copying Intel OpenCL runtime (SRB4.1_linux64.zip) to / the status/pause/etc middle attack controls dont function. but after removing even only the files that got put in /etc/ everything goes to normal (without the drivers ofcourse)

**Comment by philsmd** [comment]
Thanks @roycewilliams for the relevant log line...
Unfortuately, that sounds worse than I remembered: I thought it was working with both Intel/AMD after the user removed some files (but from the quote above it seems that the Intel driver wasn't working anymore i.e. "without the driver ofcourse")... Therefore, this "fix" is actually not better than removing the Intel OpenCL driver completely.
I'm pretty sure there must be some culprit and some (hashcat-external) fix. Again, I don't think that this is hashcat's fault or that hashcat can do anything about it.

**Comment by jsteube** [comment]
I think the same, we would need to reproduce this locally. We have some testfiles for luks here: https://hashcat.net/misc/example_hashes/hashcat_luks_testfiles.7z

You can try with those files locally?

**Comment by jsteube** [comment]
No response from OP, closing
