### ISSUE TITLE
Add Guess Mask Length to Machine Readable Output

### ISSUE THREAD

**Issue by jmmcatee** [hashcat/hashcat#1374]
When parsing the machine readable output for a mask attack with incremental mode enabled, the estimated time to completion is only accurate for the current mask length. Would it be possible to include in the machine readable output the current mask length when this is the case? I am willing to take a shot at adding this to the current output code, but wanted to know if there is a overall reason this would be undesirable or outside the scope of the existing machine readable output feature.

Thanks

**Comment by jsteube** [comment]
In theory that should be no problem. However I think it's the wrong approach. Using anything related to machine readable in combination with queued attack inputs doesn't fit together. Better run hashcat a several times but using only single attacks. Then you know the current mask. Another alternative would be to use the hashcat API, that gives you full control on everything. There's however no documentation on, but using main.c as reference in the perfect example because hashcat commandline frontend is basically just calling hashcat API functions.
