### ISSUE TITLE
crash: Segmentation fault when running oclHashcat

### ISSUE THREAD

**Issue by roo7break** [hashcat/hashcat#139]
Hi,

I got oclHashcat 2.01 on Xubuntu alongside John the ripper. To run both I installed amd-catalyst-14.9 and AMD-APP-SDKv3.0. However, it seems oclHashcat now crashes everytime i try and run it. It crashes if I run benchmark or using any of the example files.

GDB output is below:

Reading symbols from oclHashcat64.bin...(no debugging symbols found)...done.
(gdb) run --benchmark
Starting program: /home/crackuser/cracker/oclHashcat-2.01/oclHashcat64.bin --benchmark
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
oclHashcat v2.01 starting in benchmark-mode...

Program received signal SIGSEGV, Segmentation fault.
0x00007fffd08bce5c in ?? ()
   from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so

Can you help?

Thanks

**Comment by jsteube** [comment]
Thanks for that GDB dump. From there it looks like the crash is somewhere in the libamdocl12cl64.so which is part of the AMD catalyst drivers. The library is used the query fanspeed, and temperature from the device. Since it's not oclHashcat that crashes, we can't do anything to avoid it. But you can. From my experience this segfault is caused because you need to have X Authority and/or disable X11 ACLs with "xhost +". This can be a bit tricky if you run it over ssh.

You can also disable Hardware Monitoring --gpu-temp-disable.

**Comment by philsmd** [comment]
@roo7break could you please provide the results of the --gpu-temp-disable test ? Does the crash also happen when ssh is not involved ? We need more information for this issue

**Comment by jsteube** [comment]
Issue closes; OP not responding

**Comment by Aspect9** [comment]
Im getting "/usr/bin/menuexec: line 11:  4459 Segmentation fault      sudo $*" when i run oclhashcat - wassup wid that brothers? sisters?
