### ISSUE TITLE
feature request: --benchmark-all

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1411]
For some testing purposes, it would be convenient to have a way to run all benchmarks (including the slow ones), perhaps with a flag like `--benchmark-all`.

**Comment by jsteube** [comment]
Problem is there are algorithms that are "dangerous" because they are very resource intensive. While not being a problem with systems with a modern GPU, with older ones they can stop the entire process. This is while the benchmark mode currently is "limited. Anyway I like the idea of having to "sets" of benchmarks and we can reduce the current (default) one to a more limited selection.

**Comment by jsteube** [comment]
So the complicated question here is, which mode is important enough to be in the default selection?

We need to discuss this with a larger audience, so let's use the forum for that:

https://hashcat.net/forum/thread-6970.html

**Comment by jsteube** [comment]
Added with https://github.com/hashcat/hashcat/commit/1184ae1cddb3a1e801649b3f3ebda0b006c8de61
