### ISSUE TITLE
feature request: remote wordlist

### ISSUE THREAD

**Issue by dylib** [hashcat/hashcat#1416]
I'm just thinking a bit outside the box (literally) and wondered if it might be possible to reference a remote wordlist with `hashcat`. The thinking here is that I have limited drive space to store the wordlist on the machine running `hashcat` so remotely accessing it might be an idea. I presume that I could map a network drive to the wordlist, although I'm thinking something more along the lines of https perhaps.

It's possible this is a stupid idea or just not possible to do effectively with how hashcat references the wordlist, so I'm open to any suggestions too. Thanks!

**Comment by Chick3nman** [comment]
You can already reference a wordlist on a different/networked drive. As long as hashcat has a clear path to the wordlist, it will work. Protocols like HTTP are likely not going to be supported and the speed of read/access would be terrible anyways.

**Comment by mhasbini** [comment]
Adding to @Chick3nman comment: You can also pipe the wordlist to hashcat. (e.g. `wget http://example.com/list.txt | hashcat ...`).

**Comment by jsteube** [comment]
Wordlists have to be local for ideal performance and to precalculate the ETA. It needs to know how many words are in the wordlist to do this, so it needs to have full access. The trick with wget seems nice, but needs a correction:

`wget -qO- http://example.com/list.txt | hashcat ...`

Otherwise it writes to file
