### ISSUE TITLE
4.0.0 decimates -m 14800 speed

### ISSUE THREAD

**Issue by GrepItAll** [hashcat/hashcat#1418]
After installing 4.0.0, I have found that the speed for -m 14800 (iTunes >=10) has been drastically reduced. I have gone from around 165 h/s per 1080 Ti to approx 27 h/s per 1080 Ti. I cannot use the optimized OpenCL kernel with -O as this has not been implemented for 14800. For reference, I am using a workload profile of 3.

For now I am going to be sticking with 3.6.0, unless someone can suggest a workaround or fix that makes 4.0.0 competitive.

Thank you :)

**Comment by jsteube** [comment]
Probably the --scrypt-tmto setting. Try values 1 to 8. Also note that's a thread difference between -w 3 and -w 4, so also try them. The kernel code itself wasn't changed (from 3.6) so it's somewhere in the default settings.

**Comment by GrepItAll** [comment]
Ah ok, looks like 1d04de3 changed the number of kernel loops from 1000 to 250. I will test 4.0.0 with the --scrypt-tmto flag and different workload profiles.

**Comment by GrepItAll** [comment]
Ok, so using a workload of 4 instead of 3 brings hashcat back up to comparable levels of performance, although it averages out at about 5% slower than under 3.6.0 - I know that this isn't much, but it's such a slow algorithm anyway that that 5% is quite noticeable in the long term.

I experimented with the --scrypt-tmto setting in both 3.6.0 and 4.0.0 and it did not appear to make a difference to either of them. Does -m 14800 actually make use of this flag? I was under the impression that 14800 uses PBKDF2, not scrypt.

**Comment by jsteube** [comment]
You're right, it's just PBKDF2. Forget what I said about the --scrypt-tmto. For PBKDF2 there's a change that enabled it to crack of passwords > length 32. However the -O is not required here, because PBKDF2 (the slow iteration part) is unchanged. That's why such a kernel is not implemented. There should be no performance loss, thus the confusion.

**Comment by GrepItAll** [comment]
Ok, so I should just use -w 4 then under 4.0.0? If so, I guess this issue can be closed.

**Comment by jsteube** [comment]
Yes, I'll close the issue. My recommendation is that you play around with the parameter -u, -n, --opencl-vector-width (try values 1,2,4,8) but always also set -w 4, because this let's the GPU access the high numbers of threads (but also large blocks of workload that lead to slower updates of restore checkpoints). It's a game of trade-off.
