### ISSUE TITLE
NEED HELP

### ISSUE THREAD

**Issue by wermaxta** [hashcat/hashcat#1422]
Hi my OS is Windows 8.1 my video is AMD 7990 my video drivers version is 17.7.1 and
when i start hashcat 4.0 to crack -m 2500 with option -O i got this message
hashcat-4.0.0/OpenCL/m02500-optimized.cl: optimized OpenCL kernel not found, falling back to pure OpenCL kernel

Thank you

**Comment by philsmd** [comment]
This is not an error, but just a notice/hint. It means, whenever you are trying to use optimized kernels (with the -O option) and the kernel itself only comes with one variant (instead of both: optimized and also a specialized kernel supporting lengths > 31 or > 55), it will display this hint/warning. It's not an error message.

You could just look at the OpenCL/ folder if there are many files starting with OpenCL/m02500* it means that there are 2 variants of the kernel (and therefore using -O and not using -O makes a difference).

BTW: <sarcasm>this seems to be a high quality issue: very appropriate, easy to find and clever title and an issue description that already speaks for itselfs and includes already the answer to the question</sarcasm> I'm just kidding, ;)
But, jokes apart, maybe ("noob") questions like this shouldn't be posted on github since devs could use the time they spent to answer such question with more challenging and important things, like solving really important issues/bugs and/or implementing new hash types or features.
don't get me wrong... it's not only you that asks some very basic things like this on github... and it's totally fine to better ask to be sure. I can see your point of view too!!!
...it's also a little bit annoying that for instance I can't close this issue right now. The current permission system only allows you (the original poster, OP), or the owner (atom, jsteube) to close this issue.
So we either need to wait that you close it or ask a further person to spent some time here, just to close the issue. I stop my rant here ;)
Have a nice day.
