### ISSUE TITLE
Kernel Self-Test of iTunes Backup Failed

### ISSUE THREAD

**Issue by http403** [hashcat/hashcat#1429]
I forgot my iPhone backup password, so I go hashcat hoping I can get the password back. I'm using a RX 480 and a GTX 960 but problems surface. In benchmark with 14800 hash mode(iTunes backup >= 10.0), the kernel self-test failed and 0 hashrate in 960. Both cards preform good in other hashes (only pass -b to the program, to IPMI2 RAKP HMAC-SHA1) so I assume the driver is working properly and have problems in the kernel. Can some one investigate this issue?

**Comment by philsmd** [comment]
Can you please tell us which version of hashcat you use? It should be at least 4.0

**Comment by GrepItAll** [comment]
Just for reference: #1418 
Not saying that these are necessarily related, but just be aware that -m 14800 is very slow at the best of times and may not be working as it should be in 4.0.0 anyway

**Comment by jsteube** [comment]
It's normal to have "0" here, because hashcat does not display floating point values only pure integers. So the speed is eventually somewhere between 0 and 1. If you run a true cracking task you should see the progress value increasing after some time. If it does, everything is fine. 

Also note that using -b in combination with such a slow hash is bad because it utilizes -a 3 to do the benchmark. Using -a 3 in combination with -m 14800 is a really bad idea, therefore you should not use it. If you really need to use -a 3 for a real-life cracking task, you can use a pipe as a much better alternative like : 

```
hashcat -a 3 --stdout ?a?a?a | hashcat -m 14800 --status --status-timer 1 hash.txt
```

**Comment by http403** [comment]
Since the hard disk of my machine is damaged and all data lost(including all backups), I will close this issue for now.
