### ISSUE TITLE
4.0.1 Salt-length exception 

### ISSUE THREAD

**Issue by mabrowning** [hashcat/hashcat#1435]
Looks like version 4.0's salt length increase still has a few issues

I have a hash file like (mode 1710: sha512($pass.$salt) )
`username:D8103CC4309F9F5E73BA331495521ED523446B299270E5154D0A7632AC18F92FA373A6758793D6CCFD606908B0C892F57E975CD8218FD459181E2E9C56F53586:ZQqkGKNcvLbnk/jGKRYOWyy6+Cm2g9XXER8xJJwg7uLCeVpZW1UaGHY5LzhYAEtewx/Cf57fDMJzw2VXr4Z4Ew==` 

Cracking works with
`$ hashcat -a 0 -m 1710 --username hashes wordlist` (and it does work! I actually spent quite a few hours trying to unsuccessfully increase salt length back in v3.3)

However, hashcat --show does not:

```
$ hashcat --show -m 1710 --username hashes
Hashfile 'hashes' on line 1 
(username:D8103CC4309F9F5E73BA331495521ED523446B299270E5154D0A7632AC18F92FA373
A6758793D6CCFD606908B0C892F57E975CD8218FD459181E2E9C56F53586:ZQqkGKNcvLbnk/jG
KRYOWyy6+Cm2g9XXER8xJJwg7uLCeVpZW1UaGHY5LzhYAEtewx/Cf57fDMJzw2VXr4Z4Ew==): 
Salt-length exception
No hashes loaded.
```

Seems like `--show` has a different opinion on the maximum salt length.

**Comment by philsmd** [comment]
Hey
thanks for the report.

I've suggested a fix here: https://github.com/hashcat/hashcat/pull/1436

BTW: always make sure that whenever you report a problem with example hashes, that the passwords are also mentioned (especially in this case where one would need to have the hash:pass combination within the file hashcat.potfile) . I'm clever/experienced enough to work around this problem, by either generating a similar hash for which I know the password and/or just writting a wrong hash:pass combination into the hashcat.potfile (this works, because hashcat doesn't validate that the "crack" is correct, since it assumes that whatever is in the hashcat.potfile is always correct. It would be a waste of resources to crack/validate the hashes in the potfile again and again).
Furthermore, we are not willing (or always able in a short amount of time) to crack the user's/reporter's hashes. In short, do not forget to post the password too in the future. Otherwise we might even need to assume that you do not know the password and just report a problem such that others crack hashes for you (this happened a lot in the past, I'm not saying that this is the case here, but other people are trying to trick people like this)

Thank you very much

Best
