### ISSUE TITLE
Segmentation fault 24 hours into job

### ISSUE THREAD

**Issue by GrepItAll** [hashcat/hashcat#1441]
Hi,

I know that there are reports of Segfaults from time to time on here and the first response is typically to remake hashcat with debugging enabled, which I plan to do.

However, as the segfault I encountered occurred 24 hours into a job, I'm not sure as to how reproducible or not the error may be.

This line was in my syslog: `Nov 13 14:18:29 rig1 kernel: [251460.373547] hashcat[30977]: segfault at 1bacfd010 ip 000000000046d671 sp 00007f02153fb420 error 4 in hashcat[400000+a0000]`

Is this in itself of any use, or do I need to attempt to get a full trace of the error?

Thanks in advance :)

**Comment by philsmd** [comment]
Unfortunately, the output you posted doesn't really help to troubleshoot this. We need to know what happened and where exactly it crashed, only having the stack pointer (sp), instruction pointer (ip) etc doesn't help much to see what happened.

The problem is that it could also be very independent from hashcat itself, i.e. it could be an ASIC hang a crash within the driver code (all external from hashcat) etc
Yes, a full run build with make DEBUG=1, maybe even with backtrack (but this would require running it with gdb), would help to see what happened here.

**Comment by GrepItAll** [comment]
Yeah, I didn't think it would shed much light on it, I was just being optimistic!

I'll see if I can find time to run those tests properly (it occurred on a 'production' system)

**Comment by jsteube** [comment]
Please reopen if more informations are available
