### ISSUE TITLE
hex-encoded passwords are encoded twice when using --show

### ISSUE THREAD

**Issue by wdormann** [hashcat/hashcat#1447]
Some passwords are shown to be encoded in HEX.   For example, the password 'a:b', when cracked with hashcat (md5) shows:

```
hashcat64 -m 0 colontest.txt -a 3 ?l?a?l
<snip>
d8160c9b3dc20d4e931aeb4f45262155:$HEX[613a62]

Session..........: hashcat
Status...........: Cracked
Hash.Type........: MD5
Hash.Target......: d8160c9b3dc20d4e931aeb4f45262155
Time.Started.....: Tue Nov 14 14:21:51 2017 (0 secs)
Time.Estimated...: Tue Nov 14 14:21:51 2017 (0 secs)
Guess.Mask.......: ?l?a?l [3]
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:  5401.5 kH/s (0.02ms)
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 12350/64220 (19.23%)
Rejected.........: 0/12350 (0.00%)
Restore.Point....: 0/2470 (0.00%)
Candidates.#1....: aar -> a z
HWMon.Dev.#1.....: Util: 16% Core:1649MHz Mem: 945MHz Bus:16

Started: Tue Nov 14 14:21:48 2017
Stopped: Tue Nov 14 14:21:52 2017
```

However if I use the --show command, it **double** hex encodes the password:
```
hashcat64 -m 0 colontest.txt --show
d8160c9b3dc20d4e931aeb4f45262155:$HEX[244845585b3631336136325d]
```
The above hex string decodes to "$HEX[613a62]"
which obviously is the correct password of 'a:b'

If an already-cracked password is already encoded as $HEX[], the --show command shouldn't re-encode that entire hex string as another hex string.

**Comment by philsmd** [comment]
Hey

Thanks for the report

I can confirm and reproduce this. It doesn't seem that the actual content (the hexadecimal characters within $HEX[]) has something to do with it. It happens all the time when $HEX[] is used within the potfile.

This problem might have to do with this recent patch https://github.com/hashcat/hashcat/commit/a4616e6c6d2b69aa4e4c39f6bccc339eea9a8655

The above patch fixed the situation that whenever the *actual plain* was using "$HEX[" and ending with "]" we had to hexify it.
Well, for --show it is different because we do not apply this logic again (e.g. we do not need to hex $HEX[] passwords, because the potfile already has the correct version). We do not need to modify it at all when using --show.

I think a special case must be added when using --show or (this needs to be tested) skip need_hexify () completely whenever the user used --show (because in theory the potfile handling/writing already hexified it, if needed).

Thanks again.
