### ISSUE TITLE
7zip CRC length too short

### ISSUE THREAD

**Issue by malcolmputer** [hashcat/hashcat#1450]
7zip hashes created with 7z2hashcat can have CRC lengths greater than 5.  In the wild, I have seen a hash length of 6 in use.  Please see the attached hash with password "01234567899876543210".

philsmd from the hashcat forums was nice enough to write the attached patch to fix the issue.

[patch.txt](https://github.com/hashcat/hashcat/files/1475360/patch.txt)
[hash.txt](https://github.com/hashcat/hashcat/files/1475361/hash.txt)

**Comment by philsmd** [comment]
Hey,
Thank you very much for the report.

This patch is of course acceptable and seems to solve the problem reported on the hashcat forum: https://hashcat.net/forum/thread-7013.html

I found a problem that could lead to random crashes when applying this patch. But this patch itself isn't responsible for the random crashes.
I've investigated it a little bit and it seems that we need to increase the following buffers to allow cracking longer hashes:
1) https://github.com/hashcat/hashcat/blob/c8819e6e8b2f1d82fb4dd22a98002886912fd0db/include/types.h#L1931 (because copied here: https://github.com/hashcat/hashcat/blob/c8819e6e8b2f1d82fb4dd22a98002886912fd0db/src/event.c#L50)
2) https://github.com/hashcat/hashcat/blob/c8819e6e8b2f1d82fb4dd22a98002886912fd0db/src/hashes.c#L1556 (because copied here: https://github.com/hashcat/hashcat/blob/c8819e6e8b2f1d82fb4dd22a98002886912fd0db/src/outfile.c#L433)
3) and finally the temp buffer for the out_buf: https://github.com/hashcat/hashcat/blob/c8819e6e8b2f1d82fb4dd22a98002886912fd0db/src/hashes.c#L1562

HCBUFSIZ_LARGE is currently "only" 20480 bytes large (see https://github.com/hashcat/hashcat/blob/c8819e6e8b2f1d82fb4dd22a98002886912fd0db/include/common.h#L107) while for -m 11600 we need a hash buffer that is more than 655056 bytes large (see https://github.com/hashcat/hashcat/blob/c8819e6e8b2f1d82fb4dd22a98002886912fd0db/include/interface.h#L1211)

HCBUFSIZ_TINY is of course even less than HCBUFSIZ_LARGE, therefore we might need to change char old_buf[MAX_OLD_EVENTS][HCBUFSIZ_TINY]; to use HCBUFSIZ_LARGE and increase HCBUFSIZ_LARGE?

It would make sense to fix this reason for possible crashes first and afterwards apply this patch.
Thx
