### ISSUE TITLE
Problems with -m 15700

### ISSUE THREAD

**Issue by lcsondes** [hashcat/hashcat#1461]
Platform: Win10 x64
Hardware: Tahiti, 2816/3072 MB allocatable, 28MCU
Version: v4.0.1

This works perfectly:
`hashcat64 -m 99999 -a 3 hello`

However this doesn't:
`hashcat64 -m 15700 -a 3 myhash.txt`

One of two things happen: I either get a black screen and my driver resets (even with `-w 1`), or I get this output:
```
...[snip usual stuff]...
Increasing total device memory allocatable for --scrypt-tmto 1.
Initialized device kernels and memory...
```

and then nothing happens, my CPU and GPU are both idle for minutes.

**Comment by philsmd** [comment]
The problem here is that scrypt is one of the GPU unfriendliest algorithm currenlty supported by hashcat.
It could make sense to run -m 15700 with a very fast CPU with OpenCL support. The problem mainly is memory usage with very high cost factors (yes, this has also to do with tmto).
Even on a 1080ti (one of the best GPUs on the market) this hashing algorithm is kinda difficult to run. This doesn't depend much on hashcat, but on the algorithm itself. It is designed to be GPU unfriendly and those high cost factors make it even worse.

**Comment by lcsondes** [comment]
Using CPU causes `* Device #1: ATTENTION! OpenCL kernel self-test failed.` even though I'm on 16.1.1.

**Comment by jsteube** [comment]
Invalid self-test message, fixed with https://github.com/hashcat/hashcat/commit/829ea605c514c457948a84487e7dbb51e18f5c36
