### ISSUE TITLE
clGetDeviceIDs(): CL_DEVICE_NOT_FOUND

### ISSUE THREAD

**Issue by 8L4NK** [hashcat/hashcat#1473]
hashcat -m 2500 -a 3 --nvidia-spin-damp=50 --force /root/Documents/hashcat_john_test/hcc.hccap  ?l
hashcat (v4.0.1-71-gf21137a1) starting...

clGetDeviceIDs(): CL_DEVICE_NOT_FOUND

clGetDeviceIDs(): CL_DEVICE_NOT_FOUND

nvmlDeviceGetFanSpeed(): Not Supported

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 1070, 2028/8113 MB allocatable, 16MCU

OpenCL Platform #2: The pocl project
====================================
* Device #2: pthread-Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, skipped.

OpenCL Platform #3: Mesa, skipped or no OpenCL compatible devices found.

/root/Documents/hashcat_john_test/hcc.hccap: Old hccap format detected! You need to update: https://hashcat.net/q/hccapx

Started: Thu Dec 14 18:57:27 2017
Stopped: Thu Dec 14 18:57:27 2017

what is wrong and how can it be fixed??

**Comment by philsmd** [comment]
1. uninstall mesa
2. uninstall pocl (if both mesa and pocl were already pre-installed and you use Kali linux, make sure that you switch to a different operating system that makes it easier to work with OpenCL/hashcat, like ubuntu)  
3. make sure that the correct driver is installed from nvidia.com (as recommended on https://hashcat.net/hashcat)
4. use hccapx for -m 2500 = WPA/WPA2 , the hccap file format is superseded since ages
5. do not report user problems here. use the FAQ (https://hashcat.net/faq/ ) the wiki (https://hashcat.net/wiki/) and the forum search (https://hashcat.net/forum/) instead
6. close this issue since it doesn't report a bug/problem or requests a new feature/algorithm

Issues here are meant for development and bugs, not for problems where the user didn't install the drivers as recommended (https://hashcat.net/faq#i_may_have_the_wrong_driver_installed_what_should_i_do)
