### ISSUE TITLE
Hashcat for android

### ISSUE THREAD

**Issue by Squattydent** [hashcat/hashcat#1474]
hello, is there for hashcat development in android ??

**Comment by philsmd** [comment]
Sorry, what do you want to do with android? cracking on a android device?
I don't think that is a good idea if we think about the battery, the temperature issues, OpenCL support etc

**Comment by jsteube** [comment]
Sounds like a bad idea indeed. It's much more clever to capture the handshake with the mobile device and then copy it to a remote site for cracking.

**Comment by k8ieone** [comment]
I actually think, that would be a pretty good idea...If you have a big number of phones lying around doing nothing...
For cluster computing there are things like hashtopussy.

**Comment by neheb** [comment]
Lol

**Comment by roycewilliams** [comment]
For GPU-driven cracking like hashcat's ... for the effort of setting up 20 used and semi-outdated phones, you could probably get the same computational equivalent by picking up two GPUs.

**Comment by dizcza** [comment]
Although I use my phone as @jsteube mentioned - capture handshake and send to a cracking server, - sometimes such a pipeline is not convenient and I'd like to check _really_ small password candidates beforehand. Once I missed for hashcat in android when I was sort of underground or in other countries where for some reason you can't use 3G (for example, it's not cheap for your network provider). Doing WPA/WPA2 handshake password guessing, aircrack-ng is an alternative. But in this case, you'd have to support both versions - hashcat and aircrack-ng - which is not what you want simply because hashcat is a more advanced engine.
Another alternative is to run hashcat in a docker container in Android. Has anyone tried this?

**Comment by megapro17** [comment]
Can this reopened now? It will be very useful in emergency situations. Gpu's now more powerful than it was. Adreno is pretty fast. Iphones gpu probably even faster, but there is a garbage os.

**Comment by Darkar25** [comment]
> Sounds like a bad idea indeed. It's much more clever to capture the handshake with the mobile device and then copy it to a remote site for cracking.

that`s the point...remote server requires internet access...and when you are in the area without open networks and captured the hadshake you basically cannot do anything with it

**Comment by neheb** [comment]
I tested on my Pixel 3a. OpenCL not available. What phones even support it?

**Comment by buffermet** [comment]
Good news, hashcat can now be run on CPU on native Android.

Google has recently incorporated a Linux development environment which is a virtual Debian environment, and it allows you to install hashcat using APT:

```sh
sudo apt update
sudo apt upgrade
sudo apt install hashcat
```

In order to get this Terminal app for the VM, you must enable it in developer options.

OpenCL is not supported so GPU cannot be instrumented natively yet.

Read more about Android 15's new Debian VM environment: https://www.androidpolice.com/android-15-linux-terminal-app/

It's still buggy. If it says "Unrecoverable error", just ignore it, you don't have to keep reinstalling Debian! Just quit the app and reopen it until it boots the VM. This error is only caused by a connection timeout (the terminal uses a localhost connection).

![Image](https://github.com/user-attachments/assets/ffbb8ac2-4c21-4a94-b0d8-04820d3c8ba2)
![Image](https://github.com/user-attachments/assets/bc1b3a5c-3e89-4a51-853d-14e59e723593)

**Comment by albaluz35** [comment]
@buffermet i see some kind of support being cooked in, have you luck with GPU functionlity?

I did the following procedure in one slot qith linux nethunter pro and the OpenCL Rusticl freedreno inside my nspawn container shows in hashcat the GPU but when I run any cracking or benchmark I get the error **clEnqueueNDRangeKernel(): CL_INVALID_WORK_ITEM_SIZE**  as stated in these issues:
* https://github.com/hashcat/hashcat/issues/4550  
* https://gitlab.freedesktop.org/mesa/mesa/-/issues?show=eyJpaWQiOiIxNDE0MyIsImZ1bGxfcGF0aCI6Im1lc2EvbWVzYSIsImlkIjoxNDIyMTB9

# PROCEDURE:

sudo apt install -y debootstrap systemd-container
mkdir -p ~/rusticl-opencl-runtime
cd ~/rusticl-opencl-runtime

# choose an output path
ROOTFS=~/rusticl-opencl-runtime/rusticl-rootfs

# create the rootfs (arm64)
sudo debootstrap --arch=arm64 trixie "$ROOTFS" http://deb.debian.org/debian

/////////////////////////////////////////////////////
#  PREPARE RUSTICL (Mesa OpenCL runtime)
/////////////////////////////////////////////////////
# Freedreno uses DRM device nodes under /dev/dri.

cat > ~/rusticl-opencl-runtime/run_rusticl_container.sh <<'EOF'
#!/bin/bash
set -e
ROOTFS="$HOME/rusticl-opencl-runtime/rusticl-rootfs"
# Prefer /dev/dri for Mesa/Freedreno, fallback to /dev/kgsl-3d0 if needed
DEVICE="/dev/dri"
[ -e /dev/kgsl-3d0 ] && DEVICE="/dev/kgsl-3d0"
echo "Starting minimal container with $DEVICE bound..."
sudo systemd-nspawn -D "$ROOTFS" \
  --bind=$DEVICE \
  --private-users=no \
  --bind-ro=/sys/class/drm \
  --bind-ro=/sys/devices \
  --bind-ro=/lib/modules/$(uname -r) \
  --bind-ro=/lib/firmware/qcom \
  --property=DeviceAllow='/dev/dri/renderD128 rwm' \
  --property=DeviceAllow='/dev/dri/card0 rwm' \
  --capability=all \
  /bin/bash --login
EOF
chmod u+x ~/rusticl-opencl-runtime/run_rusticl_container.sh

-----------------------------------------
# Enter the container
# You will be dropped into a root shell inside the debootstrap Debian environment. 
# Everything you do now is isolated (except for the bound device nodes).

~/rusticl-opencl-runtime/run_rusticl_container.sh

root@rusticl-rootfs:/#
ls -l /dev/dri
total 0
drwxr-xr-x  2 root root         80 Oct 16 16:27 by-path
crw-rw----+ 1 root video  226,   0 Oct 16 16:33 card0
crw-rw----+ 1 root render 226, 128 Oct 16 16:33 renderD128
root@rusticl-rootfs:/# getent group render
render:x:992:
ls -l /lib/firmware/qcom/a63*
ls -l /lib/firmware/qcom/sdm845
test -r /dev/dri/renderD128 && echo "Can read renderD128" || echo "Cannot read"
test -w /dev/dri/renderD128 && echo "Can write renderD128" || echo "Cannot write"

apt update
apt install -t trixie-backports \
  hashcat clinfo binutils \
  mesa-libgallium \
  mesa-opencl-icd \
  libgl1-mesa-dri \
  libgbm1 \
  libegl-mesa0 \
  mesa-vulkan-drivers \
  libdrm-common \
  libdrm-freedreno1 \
  libdrm2 \
  mesa-utils

ldconfig
export RUSTICL_ENABLE=freedreno
