### ISSUE TITLE
-a 1 option doesn't work correctly

### ISSUE THREAD

**Issue by mohemiv** [hashcat/hashcat#1492]
For example, hashfile:
```
php -r 'echo md5(str_repeat('1', 52));' > hashfile.txt
```

dictionary:
```
11111111111111111111111111 (26 characters)
111111111111111111111111111111111 (33 characters)
```

**The fisrst problem:**
```
hashcat -m 0 ./hashfile.txt -a 1 ./dictionary.txt ./dictionary.txt

125b8576304ab4e519d45ed6aa84fb8e:1111111111111111111111111111111111111111111111111111 (52 characters)
```
But 26 + 33 = 59, 59 != 52

**The second problem:**
```
hashcat -m 0 ./hashfile.txt -a 1 ./dictionary.txt ./dictionary.txt --optimized-kernel-enable
125b8576304ab4e519d45ed6aa84fb8e:1111111111111111111111111111111
```
The output was reduced to 31 character, and it isn't 52 characters.

**Comment by philsmd** [comment]
The first "problem" is probably just a misunderstanding: if you combine 2 dicts with -a 1 and both use the same file path, then each and every line/password from the first dictionary will be combined with each and every line from the second dictionary and since the files are the same the words will also be combined with themselves.
Therefore the full combinations basically are:
11111111111111111111111111 (26 characters) + 11111111111111111111111111 (26 characters)
111111111111111111111111111111111 (33 characters) + 11111111111111111111111111 (26 characters)
11111111111111111111111111 (26 characters) + 111111111111111111111111111111111 (33 characters)
111111111111111111111111111111111 (33 characters) + 111111111111111111111111111111111 (33 characters)

and therefore: 26+26=52, 33+26=59, 26+33=59, 33+33=66 

Therefore your statement about "But 26 + 33 = 59, 59 != 52" is not valid, since whenever hashcat makes all combinations of all passwords also the combination 26+26 = 52 will be tested.
Therefore problem 1 is not a problem but just a misunderstanding.

To avoid that hashcat combines each and every word you could just create 2 distinct dictionary files (say dictionary_1.txt and dictionary_2.txt and combine those two dictionaries with -a 1).

The second problem is a little bit more difficult to understand and "fix" and I agree that it shouldn't be in the output like it currently is. The plain does not match the hash. I *think* that the GPU cracks it anyways and the host code won't output hashes with -O that are larger than 31 characters... therefore it probably will be truncated... This seems to be a bug and should be investigated. thx

**Comment by mohemiv** [comment]
Thanks @philsmd,

The first one is really my misunderstanding. The 31-character password confused me, and I thought it was wrong too.

**Comment by jsteube** [comment]
Problem should be resolved. Thanks for reporting.
