### ISSUE TITLE
Current speed for AES decryption and ways to speed it up

### ISSUE THREAD

**Issue by emcee59** [hashcat/hashcat#1495]
As some of you might already know I've spent some time [bothering people in the forums](https://hashcat.net/forum/thread-6671-post-38872.html#pid38872) about implementing an Electrum wallet cracker. I ended up biting the bullet myself and went for it. I've uploaded a proof of concept in the forums.

However my speed is limited to around 100 M/s using a 1080. The bottleneck is the AES decryption algorithm, where I need to set the key, decrypt one round and repeat. Setting the key becomes one of the biggest bottlenecks, followed by the decryption round. Around 90% of the GPU time is spent doing the AES decryption.

The AES decryption hashcat uses seems to be based on a few papers describing inverting the key and using look up tables instead of performing standard AES row shifts operations, etc. Hashcat also seems to be using two "standard" implementations: when no GPU is detected, the 10kb worth of look up tables are stored in a static variable. 

When GPUs are detected, the look up tables are loaded so that multiple local workers of the same work group (same multiprocessor to use cuda language) are only partially loaded, so that the decryption work can be shared between them. As in of the 128 local workers, every single one of them will operate on different parts of the decryption, bit-split, with the result merged at the end. 

I don't understand how that makes anything faster, but since that I don't know how to share the AES decryption load in the local workers after running the previous required sha256 operations for every single worker independently (using global memory would be too slow), I simply initialise all of the AES look up matrix the same for every local worker.

Sorry for the wall of text. I wrote even more details in the forum.

If anyone is willed to help, I would like to pay them.

You can download the proof of concept from the forum, but here is the kernel code to get you an idea:

https://pastebin.com/keuCRGkV

Thank you.

**Comment by jsteube** [comment]
From what I see there's like two different version for Electrum wallets. That's kind of confusing since you're talking only about a specific one in particular. If you want that algorithm added cleanly into hashcat, please provide all the data we need in full and everything described here: 

https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this

There more you stick to the data requested on there, the higher the chances to motivate me to add it.

While looking at the JtR Code, I found that one example hash:

```
{"$electrum$1*d64ac297de09893a03bc540b346d5e97*0af493539c512e3ded466b4879b8a47b", "openwall123"},
```

The above example, does this match the algorithm that you're talking about?

There's also many different Electrum versions listed. But when it comes to the wallet, it seems there's one for wallets and "encrypted" wallets. So from hashcat perspective, we should distinguish between wallet and encrypted wallets?

There's no need to pay. If I want to add it, I'll do it for free.

**Comment by jsteube** [comment]
I'd estimate performance to be around 250MH/s on a single GTX1080

**Comment by emcee59** [comment]
I would love to see 250 MH/s on a 1080! Do you have any idea why I only get half that? If you can help me optimise my standalone program (it's in the linked forums thread), I would be more than happy to spend whatever time is needed to use it as a basis for a hashcat merge.

> While looking at the JtR Code, I found that one example hash:

I believe so, 99%. Electrum 1.x wallets should be checked by decrypting with sha256(sha256(pass)) and making sure the whole half seed is base16, I __believe__ something very similar applies to versions between 2 and 2.8 (salt type 2, where they have the "starts with xprv check"), while they are using full wallet encryption for 2.8+.

The various extract scripts you see around are just taking the iv + first 16 bytes of the encrypted seed, leaving the remaining 32 bytes "private".

I can open another issue for the addition request if you want to, of course. But since that I'm working on this almost fulltime maybe helping me optimise my terrible opencl code has the most return on time invested? ;)

Thank you!

**Comment by jsteube** [comment]
I've pushed the changes to hashcat with commit: https://github.com/hashcat/hashcat/commit/553668bb9f6311fb86991e4642cd8e0451e3ea52

You should be able to test with latest github master or binary beta from https://hashcat.net/beta/

If you really want to contribute, the salt-type 2 and 3 are not yet implemented. You can add a new branch for them in the kernels after the AES decryption part.

I'll close the issue because it should be working now.
