### ISSUE TITLE
@Apple -m 2501 AMD Radeon R9 M395 88060.7 kH/s !!!

### ISSUE THREAD

**Issue by diegodieguex** [hashcat/hashcat#1513]
I think something is wrong in benchmark mode

hashcat -m 2501 -b
hashcat (v4.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, skipped.
* Device #2: AMD Radeon R9 M395 Compute Engine, 512/2048 MB allocatable, 28MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 2501 - WPA/WPA2 PMK (Iterations: 1)

Speed.Dev.#2.....: 88060.7 kH/s (0.08ms) @ Accel:512 Loops:1 Thr:64 Vec:1

Started: Wed Feb  7 15:03:44 2018
Stopped: Wed Feb  7 15:03:48 2018

**Comment by philsmd** [comment]
Can you please describe the problem that you are experiencing ? What do you think is wrong?

You are using -m 2501 (1 iteration)... if you want to use the non-PMK version with 4k iterations you need to use -m 2500 instead.

**Comment by diegodieguex** [comment]
well I think than -m 2501 displayed a huge speed while -m 2500 is getting slower

hashcat -m 2500 -b
hashcat (v4.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, skipped.
* Device #2: AMD Radeon R9 M395 Compute Engine, 512/2048 MB allocatable, 28MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 2500 - WPA/WPA2 (Iterations: 4096)

Speed.Dev.#2.....:    29942 H/s (117.53ms) @ Accel:128 Loops:64 Thr:64 Vec:1

**Comment by diegodieguex** [comment]
I hope to make captures with hcxtools and generate the possibles PMK. you think it's feasible compiling it in Apple systems ?

**Comment by philsmd** [comment]
That speed difference (between PMK and non-PMK, i.e. 2501 vs 2500), as said, is perfectly what we would expect. The ratio/factor is exactly the 4096 iterations i.e. the 2501 does not have the heavy _loop kernel function of 4k iterations.
Again, the speed (especially of 2500) is not what a R9 395 would normally achieve with a good driver... but that discussion is already taking place here: https://github.com/hashcat/hashcat/issues/1290
I would suggest that we should close this issue, because it seems to be just a misunderstanding about the PMK-variant i.e. the fact that 2501 should be a factor of 4096 faster than 2500.
Thx
