### ISSUE TITLE
mask attack slow

### ISSUE THREAD

**Issue by c67871f2** [hashcat/hashcat#1522]
when i run this command:./hashcat64 -m 0 -a 3 8743b52063cd84097a65d1633f5c74f5 hash?a?a?a?a?a?a?a?a -O --status
![default](https://user-images.githubusercontent.com/8402161/36170894-ba587686-113b-11e8-8a24-55002e501b92.PNG)

**Comment by philsmd** [comment]
salted hashes, like md5 ($salt.$pass) should be cracked with the correct hash type.
Hashcat supports:
-m 20 = md5 ($salt.$pass)
The hash must be specified like this:
hash:salt
e.g. 8743b52063cd84097a65d1633f5c74f5:hash
(since the characters "hash" form the salt in your case)

see https://hashcat.net/wiki/doku.php?id=example_hashes

The command to run would be 

./hashcat64 -m 20 -a 3 -w 3 -O --status 8743b52063cd84097a65d1633f5c74f5:hash  ?a?a?a?a?a?a?a?a

also do not forget to -w 3 or -w 4 if you want to achieve maximum speed.

Please do not forget to close the issue if the problem was fixed with these instructions. Try to use the hashcat's forum search function and use the forum for questions like this. Github is used for development purposes and to fix real bugs and implement new features.

Thx

**Comment by fuck-shithub** [comment]
Wow. My exact issue is literally this. When I just have "?a?a?a?a?a?a" as mask it goes around 5000 MH/s NTLM, but when I put a word within the mask like "test?a?a?a?a?a?a" it becomes 28000 kH/s.
Why is it so slow when I just put a word there? I want it to crack it like that. I'd expect it to be faster as it's still brute forcing only those 6 characters after the word "test", but no, it's running at 28000 kH/s now.
What a shame this issue was closed, and a completely different """"solution"""" was given.

**Comment by philsmd** [comment]
hey @GrimReaperFloof ,

first of all, it's a documented and well-known problem/compromise, see:https://github.com/hashcat/hashcat/blob/e194fec2291e487d01c313934932ba782eed1367/docs/performance.txt#L6-L7

furthermore, in the hashcat forum and over github issues we explained a couple of times that using the attack modes (-a 6) or salted hash types should work as a "workaround" in most cases. The reason for this "problem" was also explained dozens of times already... hashcat (on -a 3) very quickly loops within the OpenCL (or "CUDA") kernel over the first couple of bytes (first characters in the password)... if they are kind of static/hard-coded that's very bad for performance ! This was a design decision and other attack modes and salted hashes of course do it differently (prepending the bytes very quickly).
