### ISSUE TITLE
Please add support for building with the system lzma-sdk

### ISSUE THREAD

**Issue by yarda** [hashcat/hashcat#1528]
We are trying to package the hashcat to Fedora [1]. We cannot build it with the bundled lzma-sdk. I will provide PR adding support for building with the system lzma-sdk.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1540347

**Comment by jsteube** [comment]
I was trying to find a way to make this more generic so that it will work on other distributions than fedora but failed. For example, on Ubuntu, there's no package which provides Lzma2Dec.h header. I think the better way of handling this would be to use "Lzma2Dec.h" in the ext_lzma.h file as include, and then use a full path to the lzma sdk in the Makefile using -I. Can you rewrite your patch that way?

**Comment by yarda** [comment]
I also added LZMA_SDK_INCLUDE variable which can specify full path to the SDK. Maybe we could use just one variable for it. Unfortunately the LZMA-SDK is not yet standardized across distros and the upstream LZMA-SDK release has still room for improvement.
