### ISSUE TITLE
Sessions resume : restart from the beginning  ?!

### ISSUE THREAD

**Issue by adrastee** [hashcat/hashcat#1537]
Hello,
First, I run:
`hashcat64 --session sessionmd5 -m 0 -a 3 -o result hash ?a?a?a?a?a?a?a?a?a?a?a?a?a`
I hit 'c' for checkpoint ater 10 hours, and wait for the end.
Then I run:
`hashcat64 --restore --session sessionmd5`
I am expecting that `Time.Started` is already 10 hours, but I have `0min, 1 sec`
Does it really starts from the beginning ?
Thanks.

**Comment by philsmd** [comment]
Only the progress (and restore point value, dict position, mask position etc) will be larger if you restore a session.
The time started value will always indicate the time when this specific process started, it will not continue growing across runs. It's just the current value not the total amount of time.
btw. it is easy to calculate the total time because it should always be linear. so for instance if  you know that 10% are done in 5 hours you also know that 100% are done in 50 hours.
This is just how it was designed and it's not really a problem/bug in my opinion.

**Comment by jsteube** [comment]
That's how it is expected to work.
