### ISSUE TITLE
Unoptimized OpenCL Kernel with Mask Attack

### ISSUE THREAD

**Issue by binary1985** [hashcat/hashcat#1552]
Could you configure hashcat to use the optimized OpenCL Kernels when performing a mask attack which is < 32 length? For instance ?a?a?a?a?a?a?a?a runs nearly twice as fast with the optimized kernel and it wouldn't ever be bigger than 8.

**Comment by jsteube** [comment]
The problem is that there's switches that can have influence on a mask/iterate it. That is for example when you use -i or if you use mask files instead of a mask. However, if both cases are false, we can auto-activate the switch. But then how do we disable that behavior if the user (for whatever reason) wants that?

**Comment by jsteube** [comment]
After some thinking with @philsmd we found a major problem when it comes to automatic optimized kernel selection:

If the mask is small enough which would allow the use of optimized kernel, we can't say for sure if the salt length is. For example, we can not crack a salt of length 200 in optimized kernel mode, only in pure kernel. However the mask length has no influence here. One can say ok so you check on start the salt length as well, but what if it's a hashfile with multiple salts. And what if some of them are short enough for optimized kernels and others are not. Note that we can not switch between kernels as soon as hashcat has been initialized.

This complicates everything and it's even more complicated to explain it to the users because it requires some deep knowledge about hashcats architecture and optimization techniques being used.
