### ISSUE TITLE
how can i crack md5(md5($ password).$salt) with Six bit salt

### ISSUE THREAD

**Issue by 687766616e** [hashcat/hashcat#1575]
I want to crack discuz bbs system admin's password hash

but...
it used md5(md5($ password).$salt) with Six bit salt
........?

(my English is not good

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by 687766616e** [comment]
like this : 3b437c4e55d4a759117a83ba08912099

**Comment by roycewilliams** [comment]
If the above is a real hash, please delete it and replace it with a hash with a known plaintext (along with the plaintext).

**Comment by 687766616e** [comment]
@roycewilliams but I don't know salt...
if I knew it, how I can crack it? -m 2611?
but....... 6bits salt... no 3bits or 30bits..

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by jsteube** [comment]
You're talking about byte, not bit. I can assume that since vbull (mode 2611) has salts of length 3 byte and 30 byte. However there's no way to do that for 6 byte, the keyspace is simply too big. The only exception would be if you know the Password, in that case you can easily BF a 6 byte salt. However, that would require a different kernel.

**Comment by CrackMd5** [comment]
https://www.cmd5.org This site can crack md5(md5($ password).$salt) with Six salt online.
