### ISSUE TITLE
feature request: --hex-rules

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1580]
I'd like to be able to specify non-ASCII characters in rulesets. 

Much like --hex-charset, --hex-wordlist, etc. this flag would (for simplicity) interpret **all** characters in rules as being specified in hex.

Use cases this would support:

* naive newline/separator/null handling
* unusual, custom, or broken encodings that hashcat is not aware of
* simple simulated multibyte/utf8 handling

**Comment by jsteube** [comment]
Can you please add some examples? There's a lot different interpretations possible.

**Comment by roycewilliams** [comment]
I'm open to suggestions on the best way to approach it. Naively, I would say make any part of a rule that isn't the rule directive, but rather the rule argument, interpreted as hex.

Maybe something like:

`$!` would instead be `$21`
`$0` would instead be `$30`

You could then do a high-frequency newline append with `$0a`, for example.

One problem, of course, is that it would be very nice to be able to do multibyte substitutions, but the rules syntax today assume that replacement rules are only one byte for their arguments (`so0`, etc.). Ideally, a rule syntax that allows delimiting of the two arguments (like `/o/0`, `/oo/00`, etc.) would be very valuable for use with hex rules.

**Comment by jsteube** [comment]
OK, so my basic understanding was the same

```
$! would instead be $21
$0 would instead be $30
```

My problem was, it's also possible that the function itself could be written in hex, we would end up in:

```
$! would instead be 2421
$0 would instead be 2430
```

And what about rules that use an offset, like insert rule:

```
i0! would instead be i021
i10 would instead be i130
```

So basically --hex-rules would only change the rules that use a character. It's not touching the function name nor the offset. That would be ok.

When it comes to multibyte characters, this is very different than hex rules. There's a special ticket for that. We should not mix up things here.

In the end of all, what do we get from it. The only advantage I can see is that it becomes possible to add 0x0a easily. But it was possible all the time (it's just a bit more tricky to do). What I mean is that if you add for example the character 0x01 after the function $ then hashcat will append 0x01.

We should also note that supporting such a syntax will also change the way people will write rules. If people start writing rules with --hex-rules syntax they become incompatible with JtR rules for example.

Also I can see problems with parsing. Mixed up rules for example, because many user simply cat * > new.rule sometimes. A rule like this:

```
$3c
```
Would be valid in both syntaxes. In the current one it means "append a 3, then capitalize" but it will be also valid for the --hex-rule in which it would mean "append <".

**Comment by roycewilliams** [comment]
Yes, only using hex in the characters seems best.

I do not intend to mix this up with multibyte, but I do think that we should keep multibyte in mind for the future for this. I will add my comment about multibyte to that other issue.

To avoid mixed up rules, we could simply not allow them. We could say that if `--hex-rules` is used, all rules will be interpreted as hex, and that if `--hex-rules` is *not* used, then *no* rules will be interpreted as hex. I can see how that would be a little bit inconvenient - it would mean that if you wanted to mix, you would have to convert all rules to hex rules. But I am not sure of a better way to resolve this.

**Comment by jsteube** [comment]
What I tried to explain is that there are users that simply "throw everything at it" mentality. So what they do is that they create one large ruleset out of all rules they have. They don't care what the rules do in detail. If we start having hex rules in default rules/ folder then they will end up in a mixed ruleset build out of hex rules and non hex rules. The problem is, as I described above, that some rules will be parsed as "valid" in both cases, but their meaning is a different one, depending if you use --hex-rules or not.

However, what I don't really see is why do we need this. I don't see any case where you can not use the engine as it is today.

**Comment by roycewilliams** [comment]
Ah, I see. What I didn't realize is that single-byte printable ASCII can be handled natively by hashcat rule processing!

I still see value in preparing to handle non-printable single-byte (linefeeds, control characters, etc.). Since rules syntax will need to be updated to handle multibyte, I recommend that the future update to rules syntax also have a way to specify hex, perhaps using 0x notation or similar. And IMO, that work could be done independently of the multibyte work (or at least in parallel).

**Comment by magnumripper** [comment]
Please note that JtR has supported `\xNN` notation for many years. Eg. you can append a tab using `$\x09`. I suggest implementing that (if anything) for compatibility.

https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/doc/RULES

**Comment by jsteube** [comment]
All right, if that makes us even more compatible that's an ideal change.

**Comment by jsteube** [comment]
OK, should work now, see commit: https://github.com/hashcat/hashcat/commit/b88c956d9754a56a99f45ebfa95767b65f8bf4eb

**Comment by roycewilliams** [comment]
Wow, that's fantastic! I should have searched for other implementations that could be compatible. Thanks very much! This won't get a high number of additional passwords - but the ones that it does get will be interesting!

**Comment by roycewilliams** [comment]
... and it works like a charm! 

(Hmm - note the extra newline in the output; should passwords with non-printable ASCII be automatically HEX-ified?)

```
$ echo "passwordwithtrailingnewline" | md5sum
c35dd5862611090e628ebab5a25f21d9  -

$ echo 'c35dd5862611090e628ebab5a25f21d9' >target.hash

$ cat target.hash
c35dd5862611090e628ebab5a25f21d9

$ echo "$\x0a" > test.rule

$ cat test.rule
$\x0a

$ echo "passwordwithtrailingnewline" > test.dict

$ cat test.dict
passwordwithtrailingnewline

$ hashcat --quiet -a 0 -m 0 -r test.rule target.hash test.dict
c35dd5862611090e628ebab5a25f21d9:passwordwithtrailingnewline


$ tail -2 ~/.hashcat/hashcat.potfile 
c35dd5862611090e628ebab5a25f21d9:passwordwithtrailingnewline

$
```
