### ISSUE TITLE
Issue when loading pot file

### ISSUE THREAD

**Issue by marioskourtesis** [hashcat/hashcat#1593]
Cracked passwords containing colon character (Ie: Password:2018) are not loaded from the Pot file when using the --outfile-autohex-disable flag.  If there are successfully cracked again, they will be added for the second time in the Pot file.

**Comment by jsteube** [comment]
Right, this goes back to the problem that the format system of hashes and salts are flawed in the first place. The only way to solve this is to make sure to not have the colon character as part of the password, which is why we will autohex it. So this is a bug, but not a bug in hashcat and therefore there's no way to solve it.
