### ISSUE TITLE
Improvement of build description for windows

### ISSUE THREAD

**Issue by BotPass** [hashcat/hashcat#1615]
To insert debug code I need to build hashcat for windows, using ubuntu 16.04 with mingw-w64 for it. But I get errors and it took me some time to realise that iconv is missing _and_ there is no package thus it has to be build. Yes, you can find "the instruction" in the source code but I do not look into the Makefile in such cases, maybe this is a fault.

Nevertheless here is a suggestion to improve the build description in Build.md to make it easier for other people in the future. Oh, and a fixed typo in Makefile (or I don't get it). I hope the syntax is correct (don't use git) and there are not to much language errors in it (no native English speaker).
Yes, this was done with the source code for version 4.1.0 but Build.md did not change till this version and the typo is still in Makefile.

As I told, this is only a suggestion not more.

[moreDetailedWindowsBuild.diff.txt](https://github.com/hashcat/hashcat/files/2181790/moreDetailedWindowsBuild.diff.txt)

**Comment by philsmd** [comment]
that sounds interesting/good. Do you think you are able to send a pull request (PR) that can be reviewed by the devs ? you already have written the diff, therefore it should be easy to create/send a PR from it.

I think the OpenCL headers download is not needed because we suggest that the submodules are initialized with git directly (git submodule update --init). This guarantees that you always use the correct/compatible/tested version of the headers.

Thanks for your contribution

**Comment by jsteube** [comment]
No response from OP for too long
