### ISSUE TITLE
Looks like hashcat execution steps changed, need proper execution steps

### ISSUE THREAD

**Issue by rkothako** [hashcat/hashcat#1639]
I was unable to run specific mode with the latest hashcat.

I followed below steps to run specific mode like 11300.

git clone https://github.com/hashcat/hashcat.git
cd hashcat
git submodule update --init
make 
sudo make install
./hashcat -m 11300
I am unable to run, whats the reason? How to run this specific mode.

**Comment by philsmd** [comment]
I think questions like this should be first **searched** in the forum and if really no answer was provided it should be **asked** in the **hashcat forum** over here: https://hashcat.net/forum/

The github issues are more addressed at fixing problems, requesting new feature etc, not really user questions like this.

It's not even clear what you are trying to do in detail and what problem you are experiencing. My guess is that you want to crack a bitcoin wallet.dat file and that you want to run this with hashcat but get some error message. What error message did you get? What do you mean by "unable to run"? You should be more specific here.

For -m 11300 = Bitcoin/Litecoin wallet.dat you first need to convert the wallet.dat file with something like bitcoin2john.py to a "hash" that can be run with hashcat. The hash formats are mentioned here: https://hashcat.net/wiki/example_hashes (if bitcoin2john.py outputs the filenames too, you need to adapt the output hash to the format that hashcat expects, without the file names and colon).

You normally either run "sudo make install" or run hashcat with "./hashcat [args]". Not both.
That means, you either install it, or run it within the current folder. Not both.

Furthermore, your hashcat command misses the attack type (mask attack, combinator, straight etc) , the hash file and the mask/dict etc.

a correct command would be something like this:
```
hashcat -m 11300 -a 0 hash.txt dict.txt
```
where the output of bitcoin2john.py (adapted to the hash format mentioned on the wiki) is stored within the file hash.txt and the dict.txt file contains your password candidates (one per line).

These are all very basic points in how to use hashcat, that are not really difficult to find in the wiki/faq/forum etc and furthermore, as said, not very suitable for this kind of issues on github. Maybe you have some other problems, but you need to mention the details. It's not easy to guess what your problem with using hashcat is when you just say "I am unable to run".

Please do not forget to close the issue if the problem was fixed or whenever you plan to ask the question on the hashcat forum with more details etc.
Thx
