### ISSUE TITLE
Feature Request: Specify minimum length of candidate words

### ISSUE THREAD

**Issue by nyxgeek** [hashcat/hashcat#1642]
While cracking slow hashes like NetNTLMv2 it would be useful to specify minimum password candidate lengths. If a password is known to be at least 12 characters, a lot of time is wasted on candidate words that will not match.

**Comment by jsteube** [comment]
That's only possible before applying rules (or any other form of amplifier).

You can use something like this:

```
./hashcat --stdout example.dict -j '>B'
007ambiorix
007matthias
01Neunauge10
03chevrolet
03coffeeman
03liverpool
03montessori
03salvatore
...
```

**Comment by nyxgeek** [comment]
With John the Ripper you can use the 'external' filters to throw out candidate words that don't meet criteria before hashing takes place, but after the rules are applied. I'm hoping something similar can be implemented.

**Comment by magnumripper** [comment]
JtR can do that only because it's so slow/ineffective for this use case: It does all rules processing on CPU side and then has to transfer all resulting candidates, which is a bottleneck (for fast hashes like this).

Hashcat applies rules on GPU-side. This fact makes it more or less impossible to implement what you want. The upside is that it's WAY faster so the end result may still be a whole lot faster than JtR.

**Comment by jsteube** [comment]
Yeah there's no useful way to do this on GPU since you have to spawn the thread anyway and then it has to wait for the others to complete, we can not request "next" in this case. For slow hashes you can use the method I've shown and pipe to hashcat.
