### ISSUE TITLE
name of the files present _a0, _a1, _a3

### ISSUE THREAD

**Issue by komyaka** [hashcat/hashcat#1648]
/hashcat/OpenCL/ in the name of the files present _a0, _a1, _a3. What is this designation for and what does it affect?

**Comment by philsmd** [comment]
The github issue tracker is meant to report problems/bug with hashcat and report feature request.

User questions (that were btw already answered elsewhere a couple of times) are more suitable for the hashcat forum (https://hashcat.net/forum). Many answers to user questions can also be found in the wiki and faq of hashcat.net

Hashcat uses so called attack modes (see --attack-mode or short -a) to try to crack a hash in a very particular way. e.g. by using a word list attack, a combinator attack (2 wordlists), or a brute-force/mask attack (no dict involved).
This attack modes sometimes (for fast hashes) need dedicated kernel source code, because of the way they can be optimized. _a0 stands for -a 0 (dict), _a1 stands for -a 1 (combinator, -a 1 dict1.txt dict2.txt) and -a 3 stands for mask attack (improved "brute-force", -a 3 ?u?a?a?a?a?d?d?d for instance).

Please close this issue and consider asking user questions (not related to bugs or feature requests) on the forum only if AFTER using the forum's search function (or googling for it) didn't return any results.
Thanks
