### ISSUE TITLE
Token Length Exception

### ISSUE THREAD

**Issue by iceypotato** [hashcat/hashcat#1697]
While trying to crack a macosx password from El Capitan, I keep getting this token length exception error.

I enter this command
`./hashcat -m 7100 ~/Desktop/hash -a 3`

Any ideas? Oh and I am new to this.

**Comment by Banaanhangwagen** [comment]
This is not a development issue.
Please look here https://hashcat.net/forum/thread-7792.html

**Comment by iceypotato** [comment]
I looked at the article, but I don't know to convert it to 64 bytes

**Comment by Xanadrel** [comment]
In the forum post Karamba said to **cut**, not **convert**, so if your hash is:

`$ml$38167$4fb7de70c60407a7542932b1fe8f8bd366bad000066e9607687ef1503fe094a5$0feb2bb941c7e8b71d58e1e882270058892b92e97f80c89e1ab4e0b9405078b925ea08957f3c9741cd1723a11a049c3a3f99f8173fdeb3c8dfd5bd6717537372d66e4098c60b6f653489d8233c7c8b2239acc71a8f347b26d5262bb7bf3755baed57e564d67f976a11589002ff2a591befc9a7d183523cac2bdb2e84ed75a6e6`

you would just take the first 64 bytes (128 chars in hex ascii) of the entropy:

`$ml$38167$4fb7de70c60407a7542932b1fe8f8bd366bad000066e9607687ef1503fe094a5$0feb2bb941c7e8b71d58e1e882270058892b92e97f80c89e1ab4e0b9405078b925ea08957f3c9741cd1723a11a049c3a3f99f8173fdeb3c8dfd5bd6717537372`

**Comment by philsmd** [comment]
If you search for "OSX v10.8+ (PBKDF2-SHA512)" here: https://hashcat.net/wiki/doku.php?id=example_hashes
you will see an example hash.

The length of the last field is 128 hex characters (or 64 bytes in binary).
The last field is:
```
752351df64dd2ce9dc9c64a72ad91de6581a15c19176266b44d98919dfa81f0f96cbcb20a1ffb400718c20382030f637892f776627d34e021bad4f81b7de8222
```
note this can be seen by just searching for the last "$" character within the line.

This last field should not be longer than 128 characters (like the example above). If it is longer, you can just remove everything after the 128th character and try running hashcat with this new hash (where the last field was cut to 128 hex characters or 64 binary bytes).

Please close the issue if the problem was fixed. Thx
