### ISSUE TITLE
amd driver for kali linux for hashcat

### ISSUE THREAD

**Issue by Nandkishor1986** [hashcat/hashcat#1698]
Radeon HD 7500M/7600M Series pls tell me how to configure for hash cat 
it showing only intel device 1
but amd is not...............pls..........help me

**Comment by philsmd** [comment]
this is a quite old card (2012 ?). does the latest AMD driver even support it and is OpenCL officially supported with this GPU? You might want to try this: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_may_have_the_wrong_driver_installed_what_should_i_do

but the best (and probably only working) solution would be to buy a more modern GPU like the Nvidia 1080 ti or if you want a new AMD GPU.

Please close this issue if you think this "problem" is solved because hashcat can't do anything here and only a hardware upgrade can fix it.

**Comment by jsteube** [comment]
Not a hashcat problem anyway
