### ISSUE TITLE
Why so aggressive about BOMs?

### ISSUE THREAD

**Issue by j-mattsson** [hashcat/hashcat#1704]
What's the rationale behind ending the hashcat session when a BOM is encountered in a wordlist?

Seems to me like hashcat is overreacting. Having collected many smaller wordlists over the years it's not unusual for some of them to start with a  BOM.

I would personally prefer if this change was reverted, at most we could print a warning to the console to inform the user about the BOM.

**Comment by jsteube** [comment]
hashcat is reading wordlists bytewise, therefore it misinterprets the first bytes which ar part of the BOM header as part of the first password. 

Additionally, new users try out hashcat just to see if it works and then they place a correct test password in the first line of the wordlist. If they do that including a BOM, then hashcat will not find the expected password and new users are disappointed.

Anyway wordlists should not include BOM because the functionality is ignore anyway.
