### ISSUE TITLE
Stuck on "Initializing device kernels and memory..." when trying to crack WPA2

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#1714]
**GPU:** RX 580
**OS:** Windows 10 1809
**Drivers**: Adrenalin 18.9.3
**Hashcat Version:** 4.2.1

```
D:\Programs\Hashcat> .\hashcat64.exe -m 2500 WPA-01.hccapx rockyou.txt
hashcat (v4.2.1) starting...

OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: Ellesmere, 3264/4096 MB allocatable, 36MCU

Hashes: 5 digests; 3 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Salt
* Slow-Hash-SIMD-LOOP

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Watchdog: Temperature abort trigger set to 90c

Initializing device kernels and memory...
D:\Programs\Hashcat>
```

However, non-WPA2 works, such as SHA1

**Comment by ghost** [comment]
Hashcat 3.6.0 works with WPA2.

**Comment by philsmd** [comment]
it's probably a driver issue. Did you try to reinstall the driver for instance by following this guide https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_may_have_the_wrong_driver_installed_what_should_i_do

Furthermore, did you try with different driver versions? Does it really depend only on the hashcat version or is that just a coincident (because the OpenCL kernel code changed for WPA between hashcat versions 3.6.0 and 4.2.1).

You say it is stuck... How long did you wait? Do you see any new files created within the kernels\ folder while it is initializing ?

Did you try to downloading a fresh version of hashcat (within a new folder) and try again ? Did you try using the beta version of hashcat from https://hashcat.net/beta/ ?

**Comment by ghost** [comment]
It says "15.12 or later"... and I have 18.9.3

**Comment by ghost** [comment]
Also, yes, the beta works for some reason...

**Comment by snake-4** [comment]
Can confirm, same problem happens with RX580 8GB and 18.10.1. And beta only works when --self-test-disable is present.

**Comment by snake-4** [comment]
And also it is not stuck on that text, program just quits after that text is displayed if you look closely to the console log.

**Comment by jsteube** [comment]
I can reproduce this problem with 18.10.1 and latest hashcat. However, it's not a hashcat problem. 

The same hashcat version on the same system runs fine on:

- Linux AMD rocm driver 1.9.211
- Linux AMD legacy driver 18.30-641594

If you think it's a problem related to Windows, that's not the case.

The same hashcat version runs fine on:

- Windows Intel driver 6.4.0.25
- Windows NVidia driver 416.34

The reason why hashcat 3.6 works is because it is missing some features especially in WPA kernel. For example cracking WPA2 + SHA256. 

Also all other kernels work fine using Windows + AMD 18.10.1.

**Comment by jsteube** [comment]
Please retry with hashcat 5.0.0 and reopen if not fixed.

**Comment by snake-4** [comment]
Seems like problem is fixed but only works if --self-test-disable present.

> *Device #1: ATTENTION! OpenCL kernel self-test failed.

> Your device driver installation is probably broken.
> See also: https://hashcat.net/faq/wrongdriver

> Aborting session due to kernel self-test failure.

> You can use --self-test-disable to override this, but do not report related errors.
