### ISSUE TITLE
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

### ISSUE THREAD

**Issue by qiufengqq** [hashcat/hashcat#1715]
hashcat (v4.1.0) starting...

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 1080, 2028/8113 MB allocatable, 20MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD-LOOP

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Watchdog: Temperature abort trigger set to 90c

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<kernel>:12:1: error: unknown type name 'DECLSPEC'
DECLSPEC void generate_pw (u32 pw_buf[64], __global const cs_t *root_css_buf, __global const cs_t *markov_css_buf, const u32 pw_l_len, const u32 pw_r_len, const u32 mask80, const u32 bits14, const u32 bits15, u64 val)
^
<kernel>:12:10: error: expected identifier or '('
DECLSPEC void generate_pw (u32 pw_buf[64], __global const cs_t *root_css_buf, __global const cs_t *markov_css_buf, const u32 pw_l_len, const u32 pw_r_len, const u32 mask80, const u32 bits14, const u32 bits15, u64 val)
         ^
<kernel>:55:3: warning: implicit declaration of function 'generate_pw' is invalid in C99
  generate_pw (pw_buf, root_css_buf, markov_css_buf, pw_l_len, pw_r_len, mask80, bits14, bits15, off + gid);
  ^

* Device #1: Kernel /usr/local/share/hashcat/OpenCL/markov_le.cl build failed - proceeding without this device.

**Comment by qiufengqq** [comment]
the hashcat version is 4.1.x or later ,will find the error above,  version old than 4.0.x is run well.

**Comment by philsmd** [comment]
It seems you are compiling hashcat yourself by using "make install", is that right?

Are you sure that you always used the "make uninstall" before you installed the new version ?

What happens if you just use the normal "make" and try running hashcat like this
```
./hashcat -b
```
i.e. run it locally from the current working directory (cwd)

Furhermore, please make sure that /usr/local/share/hashcat/OpenCL/inc_vendor.cl exists and contains the DECLSPEC declarations e.g.
```
#define DECLSPEC inline
```
etc

I would say it makes sense to also try the latest beta and release versions and if all of them work I would assume it has something to do with your way that you've installed hashcat (or is this a package provided by a repo that misses some files ? did you manually compile it or not ?)

**Comment by jsteube** [comment]
It's pretty clear. There was an older version of hashcat installed, either by using "make install" or from a package. You can not mix old kernel and new hashcat binary.

Make sure to use "make uninstall" and then run "make install" again.
