### ISSUE TITLE
Luks wrong passwort Cracked

### ISSUE THREAD

**Issue by marku89** [hashcat/hashcat#1729]
I have found my Old flash drive an not know the Password anymore, so guessing some parts and want to Crack this. But i get false positive cracks from hashcat. 

```
# cryptsetup luksDump flash.pcmcia.image 
LUKS header information for flash.pcmcia.image

Version:        1
Cipher name:    aes
Cipher mode:    cbc-essiv:sha256
Hash spec:      sha1
Payload offset: 4096
MK bits:        256
MK digest:      4d a6 f5 28 d3 6a 33 de 3c 9e ab 70 56 fe df 03 0a be 86 55 
MK salt:        32 06 6f 2b d1 48 bc 1e 72 99 b0 43 80 7e 9d 32 
                93 fa 46 d3 e0 e1 95 73 57 88 4b 9c c0 c8 25 3d 
MK iterations:  27250
UUID:           eeaa26d9-e9a5-4d8b-8b3a-3624b4c656f4

Key Slot 0: ENABLED
        Iterations:             109010
        Salt:                   a0 dd 9a a5 43 5c 0e bc ba a6 f4 84 f1 b9 f0 6e 
                                34 66 57 ac c4 4f e9 63 3f 84 03 41 96 85 94 e0 
        Key material offset:    8
        AF stripes:             4000
Key Slot 1: DISABLED
Key Slot 2: DISABLED
Key Slot 3: DISABLED
Key Slot 4: DISABLED
Key Slot 5: DISABLED
Key Slot 6: DISABLED
Key Slot 7: DISABLE
```

So i dd the header with:
`dd if=flash.pcmcia.image of=luksheader bs=512 count=4097`

And start hashcat with the example wordlist
```
./hashcat -m 14600 -a 0 luksheader example.dict 
hashcat (v4.2.1-128-g48cf3f72) starting...

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 750 Ti, 500/2002 MB allocatable, 5MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Slow-Hash-SIMD-LOOP

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Watchdog: Temperature abort trigger set to 90c

Dictionary cache hit:
* Filename..: example.dict
* Passwords.: 128416
* Bytes.....: 1069601
* Keyspace..: 128416

luksheader:0308swat                              
                                                 
Session..........: hashcat
Status...........: Cracked
Hash.Type........: LUKS
Hash.Target......: luksheader
Time.Started.....: Thu Oct 25 06:42:50 2018 (4 secs)
Time.Estimated...: Thu Oct 25 06:42:54 2018 (0 secs)
Guess.Base.......: File (example.dict)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:     2184 H/s (2.44ms) @ Accel:2 Loops:64 Thr:1024 Vec:1
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 10240/128416 (7.97%)
Rejected.........: 0/10240 (0.00%)
Restore.Point....: 0/128416 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:108992-109009
Candidates.#1....: 0 -> 1cg9wP
Hardware.Mon.#1..: Temp: 46c Fan: 32% Util:100% Core:1215MHz Mem:2750MHz Bus:16

Started: Thu Oct 25 06:42:41 2018
Stopped: Thu Oct 25 06:42:55 2018
```
But the provided passwort wont work to unlock  
if i re-run hashcat , the next guess is luksheader:03051989, but also wrong

i tested the example luksdump an this works fine and crack the password 

```
# file luks_tests/hashcat_sha1_aes_cbc-essiv_256.luks
luks_tests/hashcat_sha1_aes_cbc-essiv_256.luks: LUKS encrypted file, ver 1 [aes, cbc-essiv:sha256, sha1] UUID: 722e199c-1f73-42f4-affa-513e99bef203
# file luksheader 
luksheader: LUKS encrypted file, ver 1 [aes, cbc-essiv:sha256, sha1] UUID: eeaa26d9-e9a5-4d8b-8b3a-3624b4c656f4
```

**Comment by philsmd** [comment]
Do you know what the original file system type was ?

--keep-guessing might help, but you shouldn't get too many "cracks"

Hashcat detects a correct crack on luks by checking the entropy of the decrypted bytes. You shouldn't get too many incorrect results, because if the "key" was not correct the data should be gibberish and therefore the entropy threshold shouldn't be reached.
see https://hashcat.net/forum/thread-6225.html

I wouldn't exclude other reasons, driver problems etc... but without more details (e.g. troubleshooting the entropy value etc), we probably can't say for sure.

I would recommend to start testing with --keep-guessing and see how many results per minute/hour you get.
Thx

**Comment by marku89** [comment]
Im not completely sure what is was , but could be non default filesystem. In this time i often used sparc filesystems and experiment a lot. It is a image of a 8MB PCMCIA slot card and dd the whole device. 


With --keep-guessing its around 1 guess per second , but non of this keys are good. Is there a switch to use the old key check and not guess the filesystem on the device , i know this is very rare and 99% of the luks partitions are ext2-4 systems. 

I provide the luksheader for detailed troubleshooting.
[luksheader.zip](https://github.com/hashcat/hashcat/files/2515222/luksheader.zip)

**Comment by philsmd** [comment]
I think you should create an almost identical disk and format it with the same file system etc and use a known password and test hashcat with this sample instead.
(do not forget to use this test disk before making the dd backup, because if you do not "use" it e.g. by formatting it, it can't be cracked, because it has random data) 

note: hashcat doesn't guess any file system, it just uses an entropy check and only if the decrypted data has very low entropy, it's kind of guaranteed that the key was correct (because decrypting with the wrong key would result in "very random" data with a very high entropy).

there is no such thing as the "old key check", hashcat always used the data entropy check for the luks algorithm

**Comment by philsmd** [comment]
btw I did some troubleshooting and my conclusion is that your data part seems to be not valid/encrypted.

while the test from the wiki seems to have random data (and the cracking works):
```
dd if=luks_tests/hashcat_sha1_aes_cbc-essiv_256.luks bs=1 count=64 skip=$((4096 * 512)) 2>/dev/null | xxd -g 1
00000000: 8a c9 38 96 49 2a 73 6b f9 2f 19 a7 b3 bc 5e 00  ..8.I*sk./....^.
00000010: 2b 7a 35 37 ca b0 bb 23 46 20 3a 5e 76 d1 6f 1a  +z57...#F :^v.o.
00000020: 53 f0 9c 98 aa 5c 86 b9 b2 38 2a 43 18 41 53 0f  S....\...8*C.AS.
00000030: 45 67 64 4f 61 ad 16 95 71 f0 d1 5e dc c9 b1 3c  EgdOa...q..^...<
```

this is the data part of your luks file:
```
dd if=luksheader.flash.image bs=1 count=64 skip=$((4096 * 512)) 2>/dev/null | xxd -g 1
00000000: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
00000010: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
00000020: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
00000030: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
```
of course this is not random/valid data (and therefore low entropy)

the data offset comes from
```
cryptsetup luksDump luksheader.flash.image
...
Payload offset: 4096
...
```

I'm pretty sure there is something wrong with your data part. I guess that a test with a properly formatted data/disk won't show all those 0xffffffff

**Comment by magnumripper** [comment]
@philsmd this gave me the idea you could possibly check entropy at loading stage, detecting this, right? At that time we're not even running hot code so it could be a really proper entropy test. Actually it should possibly be shared code because this could be used in other formats as well at loading (most any data blobs that ~are not compressed but~ should be encrypted and/or compressed) for ensuring input data quality.

**Comment by marku89** [comment]
Thanks for your reply , now im sure there is no formation on it. I just read about this case , but nobody shown how i look like. 

So i start testing this with many headers and cases, they never look like 0xffffffff. 

@magnumripper I also like your idea of warning, that your crypto block is suspicious. I mean this could happen if you had data corruption and blocks are not able to read , we all know old flash drives :)
