### ISSUE TITLE
Driver temperature threshold met warning still occur with --gpu-temp-disable switch

### ISSUE THREAD

**Issue by mastercracker1** [hashcat/hashcat#1757]
Like the title says even if I have the --gpu-temp-disable switch on my attack, I get the constant "Driver temperature threshold met warning...".  That was not happening on the 4.2 version and it was the desired state.

EDIT:  I forgot to mention a couple of key things.  It's running under Windows 7 64 bit with Nvidia cards.  I am also using the -S switch which was not in the previous version.

**Comment by jsteube** [comment]
Are you sure that this is really a bug? The "Driver temperature threshold met warning..." message was always displayed (also in 4.2) even if --gpu-temp-disable was specified. That's a wanted behaviour.

Maybe the use of -S causes the GPU to create more heat (because of an eventual higher GPU utilization). In that case everything works as expected. Please verify.

**Comment by mastercracker1** [comment]
Not in my case.  Version 4.2.1 does not display any information about the GPU temps when --gpu-temp-disable is activated:
![image](https://user-images.githubusercontent.com/28833108/47976313-d7c0b800-e07f-11e8-9948-5067ea717ada.png)
Here's what I get with 5.0.0:
![image](https://user-images.githubusercontent.com/28833108/47976536-ec518000-e080-11e8-98ff-fb76dff9a109.png)
The definition of --gpu-temp-disable in the help is "Disable temperature and fanspeed reads and triggers".

**Comment by mastercracker1** [comment]
I did not include it but when the temperature of the GPU #3 goes above  80°C, it starts adding yellow lines with the Driver temperature threshold met... message (in v5.0.0 only).  The information from the status display quickly become out of sight and you see only lines of the warning message.  I have MSI afterburner running in the background that keeps charge in throttling the card when it goes above 80°C.  Without it, it would go way above 80°C.  That's constant for both hashcat version so it's not an effect of a higher utilization of the card.

**Comment by philsmd** [comment]
This "new behaviour" was introduced with this PR https://github.com/hashcat/hashcat/pull/1673 .

I think we should first think about what is the correct behaviour and afterwards try to handle it accordingly.
First, we have 2 options:
--gpu-temp-disable
--gpu-temp-abort

As far as I know, before we merged the PR mentioned above all fan and temp stuff was disabled with --gpu-temp-disable (also warnings/errors) etc.
The above PR changes this behaviour slightly and also allows fan/temp reads even if --gpu-temp-disable was specified.
According to the description for --gpu-temp-disable ("Disable temperature and fanspeed reads and triggers") the old behaviour could be seen as more accurate/correct.
Also note that we have no option for fan, therefore it's always either fan & speed... or none (this would be also a little bit difficult to change because we only have 1 line for them in the status screen).

The question now is: should --gpu-temp-disable only affect the monitoring of the temp and if needed aborting hashcat.... or should it affect everything (as it did before the PR, i.e. also reading/displaying the fan speed and temperature)?

It's quite easy to come up with a fix, but I think the fix that @mastercracker1 wants is to basically revert the above mentioned PR (with maybe some further changes).

I think that we should make hashcat behave according to the --gpu-temp-disable description (or if we decide otherwise we need to change this description too). What do you think ?

It would be great if @RAN1 could also join the discussion to see if we can come up with a solution we all are happy with.

**Comment by mastercracker1** [comment]
I am definitely not against seeing the GPU temps all the time.  It's just the continuous stream of lines saying "Driver temperature threshold met..." that is annoying.  There I can think of 2 options but I don't know if they are implementable.  1) Instead of having the "Driver temperature..." message.  Change the color of the line showing the temperature (or the temperature value only) to a different color (yellow or red). 2) When the temperature is reached, push the whole status display and the warning line.   I think the first option would be the best or I am open to other suggestions.  Worst case scenario revert to old behavior.

**Comment by jsteube** [comment]
I tend to agree with @philsmd to revert the changes (not really a git revert but restore the behavior as it was before the PR), but do an additional change. 

Instead of calling the parameter --gpu-temp-disable and --gpu-temp-abort we should rename them to --hwmon-disable and --hwmon-temp-abort. Note that even if there's no temperature reading for CPU today it doesn't mean we will never have it in the future.

It would be nice to have @RAN1 to comment in detail the reason for the changes. But as we want to release a bug-fix release soon we should not wait too long in case @RAN1 does not respond and just to the changes as discussed.

**Comment by jsteube** [comment]
Since there was no response I did the modifications here: https://github.com/hashcat/hashcat/commit/2aff01b20ee3d56defea58fc573dd3340b435293

New beta is up on https://hashcat.net/beta/

Thanks for reporting!

**Comment by RAN1** [comment]
Hi all, sorry about the late reply.

The main reason for the PR was just that the behavior didn't match the flag name. I forgot about the help description, and I didn't notice that the throttle warnings would be set off when temperature abort isn't set.

The only other reason was a cosmetic issue with hwmon-less systems, where the hwmon and temp abort flags would prevent the hwmon-not-detected message from displaying. However it's no longer a problem so it doesn't have any significance here.

The most recent commit is probably the best way to handle it anyways, again sorry for not seeing this earlier.
