### ISSUE TITLE
some sha1 hash can't be cracked by hashcat

### ISSUE THREAD

**Issue by zdavid9** [hashcat/hashcat#1769]
songcodondetienuongruouasdqwez
sha1 hash
ca9b29bf69a2416bb90b6867fa1f6a16f326558c
can't be cracked by hashcat.

**Comment by roycewilliams** [comment]
Unable to reproduce.

```
$ cat sha1.hash
ca9b29bf69a2416bb90b6867fa1f6a16f326558c

$ cat sha1.list
songcodondetienuongruouasdqwez

$ hashcat --quiet -m 100 -a 0 sha1.hash sha1.list
ca9b29bf69a2416bb90b6867fa1f6a16f326558c:songcodondetienuongruouasdqwez

```

**Comment by jsteube** [comment]
I can not reproduce this as well. Tested systems:

Windows 7 - AMD
Windows 10 - Intel
Linux native driver
Linux rocm driver

This is probably just a driver installation issue, therefore please reopen if you are sure you did everything described here: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_may_have_the_wrong_driver_installed_what_should_i_do

But give more details in order to reproduce this locally.
