### ISSUE TITLE
how to save session ?

### ISSUE THREAD

**Issue by Phoenix1112** [hashcat/hashcat#1784]
hello ... thank you for this project

but i can't do save sesson and restore..

md5.txt =  my hash file

rockyou.txt = my wordlist

deneme1 = my session name

i am using kali linux and My hashcat versin is v4.2.1

i am usng this command :

hashcat -m 0 -a 3 -D 1 --session deneme1 md5.txt rockyou.txt --force

i am stoping attack.

i am restore now

hashcat --session deneme1 --restore
   
Restore file '/home/cyberthereaper/.hashcat/sessions/deneme1.restore': No such file or directory

how can i save session ??? please help me

**Comment by philsmd** [comment]
This must have to do with your setup and how you installed hashcat.
Since you use The-Distribution-Which-Does-Not-Handle-OpenCL-Well (Kali), you might have installed hashcat system-wide with packages etc.

hashcat itself recommends using the binaries from https://hashcat.net/hashcat/ and use the tool directly within the extracted download folder, for instance:
```
./hashcat --help
```

an accepted/recommended alternative for more advanced users would be to use the git repository https://github.com/hashcat/hashcat (clone the repo, make (see BUILD.md), ./hashcat --help) and this also allows to use "make install" to install hashcat.

If you do this (make install) the folder ${HOME}/.hashcat/ and subfolders will be created automatically.

My guess is that on your system there is a problem (or conflict) with the installed hashcat version and/or the folder /home/cyberthereaper/.hashcat/ does not exist.

It's difficult/impossible for us to track all kali issues here, if the downloaded version (run it locally with ./hashcat, not just "hashcat") and/or the "make install" version (be aware that you might first need to uninstall all the hashcat packages etc, otherwise there could be further conflicts) works, it's not a hashcat problem.

Please test and do not forget to close the issue if the problem was fixed with these instructions.
Thank you

---

update: do not forget the most important rule **DO NOT EVER** report a problem and use --force ;)
this --force flag tells us that your setup is broken and there is something you need to fix (e.g. install correct/proprietary drivers etc) before reporting (other?) problems

**Comment by Phoenix1112** [comment]
today I downloaded the hashcat program from github..

I installed hashcat program with make install

hashcat program is currently in my downloads folder

i did use this command

./hashcat -m 0 -a 3 -D 1 --session deneme1 /home/cyberthereaper/zzzzz/md5.txt /home/cyberthereaper/zzzzz/rockyou.txt --force   

(brute force does not start if I do not write the --force command)

brute force process started and i stopped the program later

wanted to continue again but again I got a similar error

![ekran goruntusu 2018-11-17 16 58 45](https://user-images.githubusercontent.com/42475284/48661874-1bf18680-ea8a-11e8-8fe1-e4aebb6a0c5c.png)

I looked into the hashcat folder, but hashcat was created a file called deneme1.log

should I press a special key when stopping the brute force attack? c or q  ? Maybe that's why the session command doesn't work..

**Comment by philsmd** [comment]
omg your command is completely wrong.

you are using a mask attack (-a 3 ) with a dictionary file (rockyou.txt)

try this:
```
./hashcat -m 0 -a 0 -D 1 --session deneme1 /home/cyberthereaper/zzzzz/md5.txt /home/cyberthereaper/zzzzz/rockyou.txt
```

**Comment by Phoenix1112** [comment]
thank you so much... it is worked now....but I'm shocked now ....only 5 seconds the attack is over.. this is ver nice...this is very good.. this is very beautiful :) 

rockyou.txt is have 14344385 pass... hashcat is king...
