### ISSUE TITLE
--keep-guessing doesn't continue in some circumstances

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1794]
Example:

```
$ cat descollide.list 
cqjmide
ifpqgio

$ cat descollide.hash 
hiH9IOyyrrl4k

$ hashcat --quiet --potfile-path=/dev/null -a 0 -m 1500 --keep-guessing descollide.hash descollide.list
hiH9IOyyrrl4k:cqjmide
$

$ hashcat --quiet --potfile-path=/dev/null -a 3 -m 1500 --keep-guessing descollide.hash cqjmid?a ifpqgi?a
hiH9IOyyrrl4k:cqjmide
$
```

**Comment by philsmd** [comment]
wait?
this has nothing to do with --keep-guessing.

If you want to test several masks with hashcat, you need to use the hashcat mask file feature (https://hashcat.net/wiki/doku.php?id=mask_attack#hashcat_mask_files).

Hashcat never allowed to specify a list of masks directly on the command line like you just tried with the command above. something like this is **not** allowed:
```
-a 3 hash.txt ?u ?d ?u?u ?d?d ?u?u?u ?d?d?d ?u?u?u?u ?d?d?d?d
```

hashcat only expects and accepts one single mask. Indeed, it should give an error otherwise. I guess it's because it's sometimes tricky to catch if there is some additional (not used) parameters in the command line (but it could be fixed indeed).

--keep-guessing on the other hand does not care about if there are multiple masks or multiple dicts etc, it only does **NOT** mark the digests as "done" and therefore the GPU keeps working on this particular hash.

**Comment by roycewilliams** [comment]
Huh, I had no idea that multiple masks weren't allowed - just never tried it before! So that explains why my second example doesn't work, but I don't understand yet why my first example doesn't work.

**Comment by philsmd** [comment]
it should have something to do with the limitations mentioned here:
https://github.com/hashcat/hashcat/blob/38e97bd89ada27dd07c74046889b102b34686781/docs/limits.txt#L25-L41

note: the limits.txt file says that all distinct passwords are guaranteed to be reported at least once, but I guess it's not always possible if the same kernel function call (should) find 2 correct hits (with a tiny keyspace like in your case). maybe @jsteube can confirm this

**Comment by jsteube** [comment]
That's correct since we usually dont have the a collision with up-to-date modes. It's also the correct answer to the questoin, therefore closing.

**Comment by roycewilliams** [comment]
That's unfortunate for my (admittedly unusual) use case - I was deliberately searching for collisions. 

But isn't that what --keep-guessing is for - finding collisions? Otherwise, why need --keep-guessing at all?

This would also mean that limits.txt would need to be updated, because it's not only "the same password twice for the same hash", but also "two different passwords for the same hash".
