### ISSUE TITLE
What is going on ?

### ISSUE THREAD

**Issue by Franchium** [hashcat/hashcat#1817]
what is that ? how to fix it ?

![screenshot from 2018-12-11 16-18-08](https://user-images.githubusercontent.com/41231953/49790306-710a7a80-fd60-11e8-8cbc-60133e6c867d.png)

**Comment by philsmd** [comment]
Did you install the drivers ? the recommended drivers are mentioned under https://hashcat.net/hashcat

Which hardware do you have? Which drivers have you installed?

You need to give more details about your setup.

Does clinfo work, if not even clinfo lists all your CL_DEVICE_TYPE_GPU and/or CL_DEVICE_TYPE_CPU , hashcat also won't work (because the drivers are not correctly installed). Therefore we recommend testing with clinfo first (such that we are sure it's not hashcat's fault).

BTW: this type of questions are not really suitable for this type of bug/problem tracker (github issues). We recommend searching for the error on https://hashcat.net/forum/

please do not forget to close the issue if installing the driver fixed the problem (also see https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_may_have_the_wrong_driver_installed_what_should_i_do).

Thx
