### ISSUE TITLE
brute force sha256 of a sha256

### ISSUE THREAD

**Issue by NadirRed** [hashcat/hashcat#1831]
Hello,
i have a sha256 hash of a sha256 hash
im hashcat newbie, and im trying to know how to use hashcat for this task

this is what i got so far :
./hashcat64.exe -m 1400 -a 3 --increment-min 64 --increment-max 64 hash.txt -o cracked.txt

now im trying to set charset to [a-z]+[0-9]

the value of hash.txt is : 
`6941a2b50a1d1e25af682d434b1065a4222c76a27960eb1501f383be88797e87`

**Comment by philsmd** [comment]
it's way too huge keyspace:
[a-f0-9] (note you said a-z which is wrong !) is 16 different characters
sha256 has length 64 in hexadecimal.
Therefore your keyspace is:
16^64 = 115792089237316195423570985008687907853269984665640564039457584007913129639936

do you even realize how large this is ? (hint: try to think about the amount of all atoms on the word, it's just incredible huge), therefore infeasible

to answer your question see https://hashcat.net/wiki/doku.php?id=mask_attack : 
-a 3 hash.txt ?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h?h

would be the correct mask, but it's of course not accepted because it's an insane large mask that leads to insane large values of keyspace etc... (=> 64 bit variables can't hold such large values)

As you can see from https://hashcat.net/wiki/example_hashes sha256(sha256($pass)) is currently not supported, but might be possible to implement. Do you know if sha256(sha256($pass)) is the correct algorithm used in your case ?

BTW: the github issues are not suitable for questions like this, please try finding a solution on wiki/forum/faq instead. If there is currently no answer to a question you have by looking at wiki/forum/faq, you might consider opening a new thread on the hashcat forum instead https://hashcat.net/forum/
github is for issues/bugs/feature report only, not for general non-technical discussion/help requests.

Please do not forget to close this github issue as soon as possible (only the author of this github issue and owner of this repository have the right to close github issues).

**Comment by magnumripper** [comment]
> hint: try to think about the amount of all atoms on the word

Oh, but there's only one Atom! 😄
