### ISSUE TITLE
Proposal: Improve message regarding pure and optimized kernels

### ISSUE THREAD

**Issue by s3inlc** [hashcat/hashcat#1866]
When running a pure kernel, the following message is normally shown:
```
ATTENTION! Pure (unoptimized) OpenCL kernels selected.
This enables cracking passwords and salts > length 32 but for the price of drastically reduced performance.
If you want to switch to optimized OpenCL kernels, append -O to your commandline.
```
The given length limit of 32 characters is only true in certain cases, a lot of the kernels support a different maximum length in optimized mode. It might be better to just mention that with the optimized kernels there is a limit in length and that this should be checked on the kernel. As it's normally printed anyway, e.g.
```
Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 55
Minimim salt length supported by kernel: 0
Maximum salt length supported by kernel: 51
```
this could be simply referred to, that people can check there what the according limit of an optimized kernel is.

**Comment by roycewilliams** [comment]
To simplify and to conserve screen real estate, I suggest:

`Lengths supported by kernel: passwords: 0  - 55; salts: 0 - 51`

**Comment by s3inlc** [comment]
Oh, I was not referring to improving the way how this message is displayed. My point mostly was to improve the (in most cases) wrong statement about 32 being the limit of optimized kernels.

But your idea is quite nice as well, reducing the number of lines printed, makes a better overview.

**Comment by jsteube** [comment]
I just wanted to implement this but now I had some new thoughts. If we replace the fixed value 32 with a value which is the correct one for the current attack the user selected, then it's also possible the user gets a wrong impression. 

For example, in md5crypt we are limited to Password length 15 in optimized mode. If we display the value 15 instead of the 32 in the warning message, the user (especially the new ones) maybe do not realize the 15 is valid only for the current attack, but generally for using -O.

The only way out I currently see is to not name any limits. For example, calling it like this:

```
ATTENTION! Pure (unoptimized) OpenCL kernels selected.
This enables cracking passwords and salts of shorter lengths but for the price of drastically reduced performance.
If you want to switch to optimized OpenCL kernels, append -O to your commandline.
```

I'm not perfectly happy with this. Maybe there's a better way to explain? What do you think @s3inlc @roycewilliams ?

**Comment by roycewilliams** [comment]
Maybe we could combine the output somehow, like always saying both:
```
Kernel type in use: [pure|optimized]
Pure kernels (no -O) allow longer lengths but are usually slower.
    Pure lengths supported for this hashtype: passwords: 0 - X; salts: 0 - Y
Optimized kernels (-O) are often faster, but only work with shorter lengths.
    Optimized lengths supported for this hashtype: passwords: 0 - Z; salts: 0 - Q
```

**Comment by jsteube** [comment]
This looks even more complicated and overwhelming to new users. I'll use the generalized message type.

**Comment by roycewilliams** [comment]
That's fair, understood. Though I would also argue that it's the level of information that matches the actual complexity. Most users will ignore it. The ones who do not will be the ones who need to know it. :)

**Comment by jsteube** [comment]
https://github.com/hashcat/hashcat/commit/4653447dfad1427d9c809529e49c9d0d72a656e9
