### ISSUE TITLE
Generate vanity hashes - Matches hashes against patterns

### ISSUE THREAD

**Issue by GuthL** [hashcat/hashcat#1874]
Hi,
I'm trying to generate hashes with matches against patterns and could not find a way to do it with hashcat nor simply logging the hashes.
Would it be easy to implement?

Thanks

**Comment by s3inlc** [comment]
What kind of vanity hashes are you trying to generate?
I have some modifications which allow finding special sha1 hashes: https://github.com/s3inlc/hashcat/tree/full-minmax

Maybe this can help to see what you need to change to generate what you need.

**Comment by GuthL** [comment]
Thanks a lot!
I'm trying to get the most 0 in a Keccak256. It does not matter how they are positioned.
How can I play with your version?

**Comment by s3inlc** [comment]
Take a look at the changes which were required on the m00100_a3-optimized kernel, basically you can do nearly the same for the keccak kernel, just adjusted for the kind of vanity hashes you want.

**Comment by 0age** [comment]
Hey, jumping in here - asked @GuthL to lend his expertise and he knew the right place to look for answers :)

Basically, the challenge can be broken up into three steps that would all be executed in parallel:
* Construct a payload that is exactly 85 bytes long, with a 41-byte static "header", a 12-byte variable search-space "body", and a 32-byte static "footer", that will serve as the input to keccak256 *(this seems to be supported out-of-the-box via an appropriate mask)*
* Take a keccak256 hash of that payload *(e.g. using hash mode 17800)*
* Drop the first 12 bytes from the resultant hash to get the 20-byte address, then count the number of zero bytes in that address; if there are five or more, write the input to stdout or a file *(this step is the generally problematic one)*

Looking at the kernel you referenced ([this is the one](https://github.com/s3inlc/hashcat/blob/full-minmax/OpenCL/m00100_a3-optimized.cl), correct?), are you referring to `COMPARE_S_SIMD` in `m00100s`? Where might I find more information about how to configure the pattern to match against?

Thank you for taking a look at this!

**Comment by 0age** [comment]
One more quick followup question: I can successfully run `./hashcat -m 11111 -b` after building your forked branch, as well as very specific searches like `./hashcat -m 11111 -a 3 f000111122223333444455556666777788889999`, but attempts to utilize a mask / filter command all seem to fail. What would a proper command actually look like? Thanks!

**Comment by 0age** [comment]
Correct me if I'm wrong here, but it seems as though the hash you use to match against is basically disregarded for this particular mode. I think I've figured out how to apply a mask, but have run into a more fundamental issue: There's no "Pure OpenCL kernel" available (and appears as though the same is true for 17800 / keccak256) and **the optimized kernel has a maximum password length that is too short** (55 < 85).

However, it does look like the optimized 17800 kernel also makes a salt available, up to length 51, but 17800 doesn't seem to support salts - if the salt could be applied directly to the password in raw-hashing mode, that could be used as one work-around. Otherwise, how feasible would it be for me to try and extend the supported password length in the optimized kernel?

Here's the command I'm running on your branch:

```
./hashcat -a 3 -w 3 -m 11111 --outfile-format=4 -o out.txt --hex-charset \
  0000000011111111222222223333333344444444 \
  'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccc?b?b?b?b?b?bdddd' # still needs 30 more bytes!
```

Thanks again and let me know if there's a more appropriate forum for this line of inquiry.

**Comment by jsteube** [comment]
Looks like all information required has been given. Please feel free to reopen if needed.
