### ISSUE TITLE
Request: match truncated output

### ISSUE THREAD

**Issue by jcjc29** [hashcat/hashcat#1899]
Hello

I'm trying to find sha-1 hashes that match the truncated hash I provide, and ideally I want to let the first or last n bytes match.
For example with the hex `48922d7f5f` (5 bytes), any hash like these would match:
```
48922d7f5f······························
······························48922d7f5f
```

Is there a way to do this with hashcat already (even with just one case), and if not, could something be implemented that allows this behaviour?

Thanks.

**Comment by philsmd** [comment]
It's not supported currently, but there are already other example hash types like -m 5100 = Half MD5 that do basically the same (just in this case for MD5).

Of course it wouldn't be impossible to implement, but the problem is that we need of course to have good performance in mind (and that's the difficult part and kind of impossible without implementing a dedicated OpenCL kernel for each and every substring of a hash). Also see https://github.com/hashcat/hashcat/issues/116 (that means that this issue is actually a **duplicate** of the older issue).
