### ISSUE TITLE
Hashcat (Linux) cpu wpa cracking slow compared to aircrack-ng

### ISSUE THREAD

**Issue by gitxmax** [hashcat/hashcat#1900]
Running latest Manjaro with the opencl built from https://aur.archlinux.org/packages/compute-runtime-bin

Cpu Intel 8400 with 8gb 2666 ram and ssd drive
Weird thing (perhaps) hashcat is only maxing out 1 core out of 6, the others are at idle.
I get 7450 keys/sec

Running aircrack-ng, all 6 cores are maxed out and the rate is 20.000 keys per second.

**Comment by philsmd** [comment]
does aircrack-ng even use OpenCL ?

I suspect that this is a driver/setup problem and your comparison is flawed because one software is using the intel OpenCL driver (hashcat), while the other one (aircrack-ng) is not using this package at all.

btw, we had all kind of strange issues like this and at the end it turned out that the users did something strange (like using hashcat within a very restricted vm with limited resources) or configured the system incorrectly (by for instance not using the official drivers from the vendor etc).

I would also say that problems like these are better suited for the hashcat forum @ https://hashcat.net/forum/ and since these are probably not really software bugs (in hashcat) or feature requests, you might find more/better solutions and help on the forum instead of on the dev issue tracker.

**Comment by jsteube** [comment]
Make sure to install the correct OpenCL runtime (Intel OpenCL runtime from their site!). Probably you have the wrong one (or two, and using the wrong one).

**Comment by gitxmax** [comment]
Thanks.
This is not a VM machine.
Can only run with the --force, otherwise, I get:

`hashcat -b --opencl-device-types 1,2
hashcat (v5.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

* Device #1: Intel's OpenCL runtime (GPU only) is currently broken.
             We are waiting for updated OpenCL drivers from Intel.
             You can use --force to override, but do not report related errors.
No devices found/left.
`

With --force, the output is 👍 
`hashcat -b --opencl-device-types 1,2 --force
hashcat (v5.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: Intel(R) Gen9 HD Graphics NEO, 3129/6258 MB allocatable, 23MCU

Benchmark relevant options:
===========================
* --force
* --opencl-device-types=1,2
* --optimized-kernel-enable

Hashmode: 0 - MD5

Speed.#1.........:   492.7 MH/s (95.95ms) @ Accel:128 Loops:64 Thr:256 Vec:4

Hashmode: 100 - SHA1

Speed.#1.........:   132.6 MH/s (89.38ms) @ Accel:64 Loops:32 Thr:256 Vec:4

Hashmode: 1400 - SHA2-256
`

**Comment by gitxmax** [comment]
Well, I'm not fully convinced, it's not a hashcat bug..
Been playing with it for a while and finally, managed to get both cpu and HD 630 gpu running.
The only way it works is running:
`hashcat -b --opencl-device-types 1,2 --force

Total wpa cracking speed is over 25000 keys per second, which seems very good, for having no dedicated gpu...
`

hashcat (v5.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: Intel(R) Gen9 HD Graphics NEO, 3129/6258 MB allocatable, 23MCU

OpenCL Platform #2: Intel(R) Corporation
========================================
* Device #2: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz, 1955/7822 MB allocatable, 6MCU

Benchmark relevant options:
===========================
* --force
* --opencl-device-types=1,2
* --optimized-kernel-enable

Hashmode: 0 - MD5

Speed.#1.........:   499.8 MH/s (95.42ms) @ Accel:128 Loops:64 Thr:256 Vec:4
Speed.#2.........:   559.9 MH/s (10.84ms) @ Accel:1024 Loops:1024 Thr:1 Vec:8
Speed.#*.........:  1059.7 MH/s

Hashmode: 100 - SHA1

Speed.#1.........:   134.8 MH/s (88.72ms) @ Accel:64 Loops:32 Thr:256 Vec:4
Speed.#2.........:   402.6 MH/s (3.80ms) @ Accel:1024 Loops:256 Thr:1 Vec:8
Speed.#*.........:   537.5 MH/s

Hashmode: 1400 - SHA2-256

Speed.#1.........: 63598.7 kH/s (94.11ms) @ Accel:64 Loops:16 Thr:256 Vec:4
Speed.#2.........:   178.6 MH/s (34.86ms) @ Accel:1024 Loops:1024 Thr:1 Vec:8
Speed.#*.........:   242.2 MH/s

Hashmode: 1700 - SHA2-512

Speed.#1.........: 12402.7 kH/s (60.45ms) @ Accel:16 Loops:8 Thr:256 Vec:1
Speed.#2.........: 51414.2 kH/s (60.60ms) @ Accel:1024 Loops:512 Thr:1 Vec:4
Speed.#*.........: 63816.9 kH/s

Hashmode: 2500 - WPA-EAPOL-PBKDF2 (Iterations: 4096)

Speed.#1.........:     7313 H/s (96.76ms) @ Accel:64 Loops:8 Thr:256 Vec:1
Speed.#2.........:    18175 H/s (81.91ms) @ Accel:1024 Loops:1024 Thr:1 Vec:8
Speed.#*.........:    25488 H/s

Hashmode: 1000 - NTLM

Speed.#1.........:   820.4 MH/s (57.58ms) @ Accel:128 Loops:64 Thr:256 Vec:4
Speed.#2.........:   971.5 MH/s (6.19ms) @ Accel:1024 Loops:1024 Thr:1 Vec:8
Speed.#*.........:  1791.9 MH/s

**Comment by philsmd** [comment]
sorry, but I didn't really understand what you did or what/why it is working now?

Didn't you say that the speed was bad (compared to aircrack-ng) and that you see that only 1 CPU core was used ? What happened if this is no problem anymore ?

I also noticed from your screenshots above that one is mentioning the "i5-8400" and the other is not (even if you used -D 1,2 in both of them). So there is maybe a little bit confusion and misunderstanding going on here that we need to clarify first.

**Comment by gitxmax** [comment]
My point is, to get the set up working, the way it is now, I had to use the extra options "--opencl-device-types 1,2 --force", which are hardly documented anywhere. Before I found those, I spent a lot of time thinking it was the drivers problem.
Feel free to close the issue now, as  I'm happy with the end result now.

**Comment by philsmd** [comment]
oh, now I understand what is working and what wasn't working before. Thanks for clarifying and confirming.

Let me explain the 2 options briefly.
--opencl-device-types as explained within the --help output is needed to whitelist your CPU OpenCL device. The default for hashcat is that "only" GPUs are enabled/whitelisted by default (except if the system only has CPUs).
With the opencl-device-types 1 you enable the CPU device type and the value 2 means GPUs (see --help output under "OpenCL Device Types"), the option --opencl-device-types 1,2 of course enables both CPUs and GPUs.

--force in this particular case is only needed because your GPU is a Intel GPU for which we know the driver has several bugs and speed problems. That is  why by default (without the --force command line switch) you get the error "Intel's OpenCL runtime (GPU only) is currently broken." (as you can see it says that only GPUs are affected and therefore (as far as we know) the Intel OpenCL Runtime for CPU devices (Intel Core and Intel Xeon) is working perfectly fine.
This means that users without Intel GPUs won't need to set --force and the ones that only have Intel GPUs are guaranteed to see the error message that warns them from using this device/driver.
This also means that most of the hashcat users fortunately won't need to use the --force option i.e. if they do not have Intel GPUs (these GPUs for the time being are also not recommended, because they both are, among others, slower compared than both Nvidia and AMD GPUs).

I hope that explains a little bit what is going on. I assume you already figured out most of what I just wrote, but it's always good to document it here just in case somebody else reads it and doesn't understand what is going on.

If you have any suggestion how to improve this (or the documentation forum/wiki/faq) it is of course very welcome. Unfortunately, in your case you had to use both options (and install the OpenCL runtime for your Intel Core correctly) but I don't see much we can do to improve the user experience here (the --force hint was in the output and the device that wasn't whitelisted yet, had the "skipped" warning in the output to notify the user that --opencl-device-types must be used to whitelist it).

Thanks for your explaination and feedback

BTW: only the original poster in this github issue (author, you @gitxmax ) and the project owner (@jsteube) can close issues... so please don't forget to close it if we agree that we can't improve/do anything here

**Comment by jsteube** [comment]
Thanks for clarify
