### ISSUE TITLE
8x Tesla V100s on Google Cloud Platform: nvmlDeviceGetFanSpeed(): Not Supported

### ISSUE THREAD

**Issue by taliseen** [hashcat/hashcat#1909]
Any ideas on why this fails on GCP with 8 Tesla V100s?

![image](https://user-images.githubusercontent.com/25210355/52796999-26440200-3032-11e9-9d95-734d69bd042e.png)

**Comment by taliseen** [comment]
Also doesnt work in 5.0.1 with hwmon disabled:  
![image](https://user-images.githubusercontent.com/25210355/52797339-e893a900-3032-11e9-9784-b6fdb218f5ac.png)

**Comment by philsmd** [comment]
"Killed" as far as I know has most of the time to do with exhausting all RAM (memory) of the system and therefore the process is killed by the system.

With 8 times 4 GB you should have *at least* 32 GB available host memory, because the driver (not hashcat) will pre-allocate this.

Try testing with only one card, e.g. by adding --opencl-devices 1 (or short -d 1, lowercase "d").

This sounds like a question more suitable for the hashcat forum: https://hashcat.net/forum , because the community over there will know what you have to do (or just use the forum search function). The github issues are meant for development (bug reports/new features etc) and therefore not the correct place for user questions like this.

Thanks

BTW: do not forget to close the issue if fixed

**Comment by jsteube** [comment]
@taliseen Can you please run the test which @philsmd was suggesting?

**Comment by 16010** [comment]
@taliseen Hi! Have you found a solution yet or did you create a thread in the hashcat forum? Please let me know, Thank you very much

**Comment by jsteube** [comment]
Closing thread because there's no response from OP. The problem is believed to be fixed using latest GitHub master or beta binary from https://hashcat.net/beta/

If you find the problem is not fixed feel free to reopen
