### ISSUE TITLE
i cant build binary

### ISSUE THREAD

**Issue by TheYkk** [hashcat/hashcat#1910]
process_begin: CreateProcess(NULL, x86_64-w64-mingw32-gcc -W -Wall -Wextra -Wno- unused-variable -Wno-unused-function -O2 -pipe -std=gnu99 -Iinclude/ -IOpenCL/ - Ideps/LZMA-SDK/C -Ideps/OpenCL-Headers -fPIC -I/ -I/opt/win-iconv-64/include/ -m 64 -DWITH_HWMON -c -o obj/affinity.WIN.64.o src/affinity.c, ...) failed.         make (e=2): The system cannot find the file specified.                           make: *** [src/Makefile:655: obj/affinity.WIN.64.o] Error 2
--

**Comment by philsmd** [comment]
What are you trying to do ? Where are you trying to build it ?
Do you use a windows system ?

The usual way we compile the binary is (by following the BUILD.md instruction of course) using an ubuntu LTS system with mingw cross-compilers installed (of course make/gcc and other tools - e.g. built-essential on ubuntu - need to be installed too).

Without any more information it's very difficult for us to understand what you are trying to do and how you are compiling it (and therefore difficult to understand why it fails for you)?
Please give more details what you are doing and what this CreateProcess()/process_begin  etc has to do with hashcat compilation etc !

Thx

BTW: I think this some kind of android stuff. Android is not officially supported by hashcat and therefore you shouldn't really report errors (and especially not reporting errors without mentioning that you are compiling for Android. This is very confusing for devs if they do not know what is going on and what you are trying to do). If you are trying to get hashcat working on Android you would probably need to make a lot of changes/patches... and even then it would probably just be extremely slow because the OpenCL support on mobile devices is just bad as far as I know (let alone the problem with heating/temperature and power consumption etc)

**Comment by TheYkk** [comment]
i use windows platform (win 10) , and install msys for make command

**Comment by philsmd** [comment]
did you try with cygwin instead ?

I think you would need several packages also for cygwin (like gcc, make, libiconv-devel etc) but it should work

The devs usually cross-compile the binary for windows under linux by using the x86_64-w64-mingw32-gcc cross-compiler and the win-iconv dependency.

I'm pretty sure that several users managed to compile hashcat directly under windows. If the BUILD.md is not up to date and if it does not mention all the instruction steps, we should probably improve it.
For instance, I see that there is no mention of win-iconv within BUILD.md (needed for cross-compilation on a Linux host system) at all. That's not good.
If you can, please help to improve it.

That said, it should work with both mingw/cygwin/msys, because we tested this in the past (I personally didn't test it lately unfortunately).

**Comment by TheYkk** [comment]
i install cygwin and same problem

**Comment by jsteube** [comment]
I just build hashcat (current master) on msys2. No problems.

**Comment by jsteube** [comment]
I even tried using cygwin and hash-mode-plugin branch. It works without any problems. Please try harder.

**Comment by TheYkk** [comment]
i cant build 
![image](https://user-images.githubusercontent.com/21688838/52875147-a9fe0b80-3164-11e9-9bdc-a1d59aeab28b.png)
![image](https://user-images.githubusercontent.com/21688838/52875180-c306bc80-3164-11e9-86e9-f029a17d9a93.png)


i have cygwin and msys2

**Comment by philsmd** [comment]
maybe this helps: https://stackoverflow.com/questions/33674973/makefile-error-make-e-2-the-system-cannot-find-the-file-specified,  https://stackoverflow.com/questions/3848357/createprocess-no-such-file-or-directory etc

you are either missing some packages / libs or didn't setup mingw correctly.
I would suggest trying the solutions suggested for the CreateProcess errors on stackoverflow.

probably gcc is not installed or not working (try to compile a hello world program for instance)
