### ISSUE TITLE
Support for Android adb backup encryption passphrases

### ISSUE THREAD

**Issue by joshtriplett** [hashcat/hashcat#1931]
The Android `adb backup` mechanism supports providing a passphrase to encrypt the backup. The format is documented, and there are tools to extract adb backups. I'd love to have support for testing candidate passphrases against an adb backup.

(At backup time, Android only prompts for the passphrase once, not twice, and hence I find myself using hashcat to attempt to figure out just how I typoed my passphrase at backup time.)

**Comment by philsmd** [comment]
It seems also the current version still uses PBKDF2 (see https://github.com/aosp-mirror/platform_frameworks_base/blob/c1e55147c91f9be219f2dd824d3ab6f9b39d5c3b/services/backup/java/com/android/server/backup/BackupPasswordManager.java#L135-L136), older explanation https://nelenkov.blogspot.com/2012/06/unpacking-android-backups.html and https://forum.xda-developers.com/showthread.php?t=1730309

We would at least need some examples to confirm and a way to "extract" the data.

I really thought that Android did move to SCRYPT completely/everywhere.
Does somebody know if this is true ? I mean the BackupPasswordManager.java is kind of very clear that it's "just" PBKDF2 with 10000 rounds (see https://github.com/aosp-mirror/platform_frameworks_base/blob/e80b45506501815061b079dcb10bf87443bd385d/services/backup/java/com/android/server/backup/utils/PasswordUtils.java#L37) and AES encryption

I guess PBKDF2 is used because it's easier to combine with the AES encryption, but afaik the  on-device full disk encryption (FDE) is also done with scrypt, isn't it ?

Note: this is the non-github link: https://android.googlesource.com/platform/frameworks/base.git/+/refs/heads/master/services/backup/java/com/android/server/backup/BackupPasswordManager.java
on googlesource.com

**Comment by philsmd** [comment]
update: just checked if john the ripper (jtr) supports it already. and it seems it was recently added (summer 2018) in jtr:
1. extractor: https://raw.githubusercontent.com/magnumripper/JohnTheRipper/27f51880a4daf1372a115a49c2e04b9fb2406209/run/androidbackup2john.py
2. key derivation and pass check: https://github.com/magnumripper/JohnTheRipper/blob/27f51880a4daf1372a115a49c2e04b9fb2406209/src/androidbackup_fmt_plug.c#L195-L203

Thank you very much for the help/suggestion

**Comment by jsteube** [comment]
Added with commit https://github.com/hashcat/hashcat/commit/29fedf2c41bb54a982a270bf7bf754bee6496245

You can build from source or use the beta from here: https://hashcat.net/beta/

**Comment by joshtriplett** [comment]
Awesome, thank you! I managed to figure out the issue and figure out the passphrase another way (https://issuetracker.google.com/issues/125696135), but I'm glad that this support exists now.

As far as I can tell, it looks like this requires manually extracting some data from the Android backup file and feeding it in as a specially formatted hash? Is there some documentation of the hashcat expected input format?

**Comment by jsteube** [comment]
You can use the androidbackup2john.py from here https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/run/androidbackup2john.py

**Comment by joshtriplett** [comment]
Thanks!
