### ISSUE TITLE
Password in list, but hashcat can't find it? [Electrum litecoin wallet]

### ISSUE THREAD

**Issue by Metatronovich** [hashcat/hashcat#1942]
Hi all,
I am trying to brute force one of my old electrum litecoin wallets but before I started - i wanted to check if I having the right password on a list will even work.

These are the steps i used:

- Downloaded the correct correlated version of the wallet, created a new wallet with 123abc as a password.
- downloaded the newest Jumbo package john the ripper program to use electrum2john.py 
- converted my wallet file into a hash which gave me "$electrum$2*XXXXXXXXXX*XXXXXXXXX") -> into hash.txt
- I've put 10 lines of passwords with one of them being the right one (123abc), called the file known.txt
- I've used hashcat64.exe -m 16600 -a 0 hash.txt known.txt

The program seems to be running, but nothing is found.

anyone have any idea why is this happening? I understood $electrum$2 does work from not long ago.

Thanks in advance!

**Comment by jsteube** [comment]
Hi There. thanks for creating that issue. Please follow there following steps:

1. Retry with the latest version either by compiling yourself from Github master or by using the binary beta from https://hashcat.net/beta/
2. If the problem still exists, please retry the same test with the JtR
3. If the problem still exists, please provide all the files we need to reproduce locally

**Comment by Metatronovich** [comment]
Hi and thank you for your reply.
Using the beta version did work and I manage to 'crack' the test wallet.

Any things i need to notice when\if using the beta version as oppose to the latest release?

**Comment by philsmd** [comment]
Thanks for confirming.

I think it makes sense because we have this patch from 2018/12/06 https://github.com/hashcat/hashcat/pull/1805 and latest hashcat version v5.1.0 was released 2018/12/02 (therefore about 4 days earlier than the fix).

In general the betas are kind of "experimental", but due to very hard work by the devs they are actually quite stable and reliable (most of the time). You can use it the same way you use the release version and after a new release version will be available, you should/could update to that one (it will be listed here https://hashcat.net/hashcat a version > 5.1.0 in the future).

For the time being, you should be able to use the beta without any major problems/disadvantages :)
(you can read the always-changing changelog here https://raw.githubusercontent.com/hashcat/hashcat/master/docs/changes.txt if you are interested what is new and what was changed between the versions, including beta versions).

@jsteube I think we can close this issue :)
