### ISSUE TITLE
Word file passphrase matches & rules do not for WPA-EAPOL-PBKDF2

### ISSUE THREAD

**Issue by clintonm9** [hashcat/hashcat#1993]
I am trying to match a WPA2 passphrase where I know the password. The password is `360Office`.

If I run the following I get a successful crack and pot file:
`hashcat -m 2500 packet-Network.hccapx -a 3 360Office --potfile-disable -o t`

If I run the following with the `word` file having one entry of `360Office` it works:
`hashcat -m 2500 packet-Network.hccapx word --potfile-disable -o t`

Using a rule to have the same passphrase generated is not working. The rule file has one line of  `^0 ^6 ^3` and the word file has one entry of Office. I run the following:
`hashcat -m 2500 packet-Network.hccapx word -r simple.rule  --potfile-disable -o t`
This will not create the pot file and says `Exhausted`.

Generating a list of passphrases used will return 360Office:
`hashcat --stdout  word -r simple.rule | grep 360Office`

So why would the rule not be matching when generating the create passphrase?

**Comment by jsteube** [comment]
It's exactly is supposed to be. If the input word (in this case length 6) is less than 8 it gets rejected before it is processed because the minimum password length for WPA is 8. So this is more like a processual question because after the rule applied the word becomes longer than 8 and should not get rejected. However one way or another, hashcat has to choose one which is the default strategy. However, if you want to change that behavior just use -S and it should work.
