### ISSUE TITLE
hash line reading: fgetl () should return error code

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#2054]
While testing/investigating some .zip hashes (pkzip) when implementing this fix https://github.com/hashcat/hashcat/pull/2053 I've found out that fgetl () is doing some nasty stuff behind the scenes that I wasn't aware of and it seems that this could be quite dangerous and with side-effects:

this check here:

https://github.com/hashcat/hashcat/blob/581839d40283f001f6779c4e25f0fc528e661240/src/filehandling.c#L55

is able to corrupt our input data and manipulate the input (e.g. a hash) in a way that it isn't received correctly.

We should definitely try to avoid this and either show a direct error message or return an error code that the caller must check.

Thanks

**Comment by jsteube** [comment]
Commit https://github.com/hashcat/hashcat/commit/97c9e86d155df741fc50bc61453d63888427ef86 should handle this as good as possible. It will print a warning message to the user. Since the function does not have the hashcat_ctx object it's unable to use hashcats internal error message system. Note that the fgetl() function was changed so that the user can add the buffer size to the call and make it more flexible.
