### ISSUE TITLE
Outdated NVIDIA CUDA Toolkit version '10020' detected

### ISSUE THREAD

**Issue by sbtc1** [hashcat/hashcat#2058]
Upgrading from Hashcat 4.2.1 to current Git repo, gives incompitibility with Cuda toolkit.

```
hashcat (v4.2.1) starting...

OpenCL Info:

Platform ID #1
  Vendor  : NVIDIA Corporation
  Name    : NVIDIA CUDA
  Version : OpenCL 1.2 CUDA 10.2.120

  Device ID #1
    Type           : GPU
    Vendor ID      : 32
    Vendor         : NVIDIA Corporation
    Name           : GeForce GTX 1080 Ti
    Version        : OpenCL 1.2 CUDA
    Processor(s)   : 28
    Clock          : 1683
    Memory         : 2794/11178 MB allocatable
    OpenCL Version : OpenCL C 1.2
    Driver Version : 430.26
```

with new git clone hashcat fails:

```
hashcat (v5.1.0-1138-g581839d4) starting...

Outdated NVIDIA CUDA Toolkit version '10020' detected!

See hashcat.net for officially supported NVIDIA CUDA Toolkit versions.
```

I got this error with Cuda 10.0.0 as well, so I upgraded to the latest one, but as you can see this still fails.

**Comment by philsmd** [comment]
my guess is that nvrtc.dll, nvrtc64_*.dll nvrtc64_*_0.dll are outdate because 10020 seems to be okay (the error message is a little bit missleading becaue it checks both libraries and only mentions one):

https://github.com/hashcat/hashcat/blob/581839d40283f001f6779c4e25f0fc528e661240/src/backend.c#L5046-L5054

you should follow this https://hashcat.net/faq/wrongdriver and make sure that nvrtc.dll, nvrtc64_*.dll nvrtc64_*_0.dll are gone and after the driver installation they should be up-to-date again.

**Comment by sbtc1** [comment]
@philsmd Thank you for your reply. I fogot to mention I'm running this on Ubuntu 18.4. 
I'm reading that nvrtc should be part of the Cuda toolkit, so I'm not really sure how it can be a different version? (Note I already unisntalled and reinstalled the Nvisia drivers via apt). I'll try to follow this 'wrong driver' section though and see if that helps.

**Comment by philsmd** [comment]
the operating system actually doesn't change much here besides the file extension (.so for linux).

https://docs.nvidia.com/cuda/nvrtc/ : according to this you have a lib64/libnvrtc.so.Major.Minor that is too old. Would be intesting what exact version you have.

Maybe you also have some other of those cuda libs (libnvrtc.so*) available, installed and reachable by the system that you can't remember.

With a clean installation it should work because we tested this. but you should also be able to "fix" your system without reinstallation but you need to find out which libs are loaded and why they are old.

**Comment by sbtc1** [comment]
Great, that was indeed the issue!  Thank you fir the swift repsonse.

I did a find for this file and found:
```
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libnvrtc.so.10.0.130
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libnvrtc.so.10.0
/usr/lib/x86_64-linux-gnu/libnvrtc.so.9.1.85
/usr/lib/x86_64-linux-gnu/libnvrtc.so.9.1
```
After rmoving the latter 3, the error is gone and I get the expected output. There is however one new warning about missing cuda tookit now that I assume is related:

```
hashcat (v5.1.0-1138-g581839d4) starting...

* Device #1: CUDA SDK Toolkit installation NOT detected.
            CUDA SDK Toolkit installation required for proper device support and utilization
             Falling back to OpenCL Runtime

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: NVIDIA Corporation
  Name....: NVIDIA CUDA
  Version.: OpenCL 1.2 CUDA 10.2.120

  Backend Device ID #1
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: GeForce GTX 1080 Ti
    Version........: OpenCL 1.2 CUDA
    Processor(s)...: 28
    Clock..........: 1683
    Memory.........: 2794/11178 MB allocatable
    OpenCL.Version.: OpenCL C 1.2
    Driver.Version.: 430.26
```

does this impact performance?

**Comment by philsmd** [comment]
well, the support for CUDA toolkit was (re)added quite recently (last couple of weeks) and the speed difference is often very small, but there are some hash algorithms that are faster and some that have still some unfixed "speed problems". That's why you should have both OpenCL and CUDA installed to benchmark it yourself with newest versions.

I would suggest using "apt-file search" instead and remove the packages and install latest CUDA version from https://developer.nvidia.com/cuda-downloads instead. I think 10.1 is currently the only one that is quite recent and supported and your version was very old (and by deleting the single files you might have broken the CUDA support completely).

**Comment by sbtc1** [comment]
ok thanks a lot for your quick answers! I'll try to read into this and get the cuda toolkit correctly installed.

**Comment by sbtc1** [comment]
for one's reference, got Hashcat to use CUDA by 
- removing CUDA fully
sudo apt-get remove --auto-remove nvidia-cuda-toolkit
sudo apt-get purge nvidia-cuda-toolkit or sudo apt-get purge --auto-remove nvidia-cuda-toolkit
sudo apt-get autoremove
- reinstalling from network, https://developer.nvidia.com/cuda-downloads

After reboot, Hashcat now recognizes the correct CUDA version. Speed is about the same as OpenCL for the 16600 hash algo. 

Thanks again at @philsmd for the quick help and the entire team for this great product. Speed of the v5 is almost double from the v4 for this algo!
