### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Allesanddro** [hashcat/hashcat#2166]
hello there it seems i cant compile hashcat via cygwin on my system i got this error 
obj/combined.NATIVE.a(hashcat.NATIVE.o):hashcat.c:(.text+0x3f2): Warnung: undefinierter Verweis auf »set_cpu_affinity«
obj/combined.NATIVE.a(hashcat.NATIVE.o):hashcat.c:(.text+0x3f2): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `set_cpu_affinity'
collect2: Fehler: ld gab 1 als Ende-Status zurück

Warnung: undefinierter Verweis auf = Warning undefined reference to

**Comment by philsmd** [comment]
what hardware (CPU etc) do you have ?

It seems that  "relocation truncated to fit: R_X86_64_PC32" is some compiler error that happens only in some special cases like compiling with wrong architecture (32/64 bit) and/or if compiler has problems with some optimizations (registers) etc. just google it

For sure this is not a very common problem, because this was never reported beforehand here.

Does this also happen with the mysys2 compilation steps: https://github.com/hashcat/hashcat/blob/master/BUILD_MSYS2.md ?

**Comment by Allesanddro** [comment]
Ryzen 2700x 

> Does this also happen with the mysys2 compilation steps: https://github.com/hashcat/hashcat/blob/master/BUILD_MSYS2.md ?

ill test this later on

**Comment by Allesanddro** [comment]
mysys worked flawlessly so ye ill do some research and try to fix it somehow

`Update`
Well i don't know but seems like working now didn't changed anything just recloned the repo so i have no clue what was the issue 

![](https://i.sandrotracker.biz/98dacdf72c5072cac960a764cacad9ef.png)
