### ISSUE TITLE
MAC runs for 1 minute and then exits. How did this happen

### ISSUE THREAD

**Issue by dragon-D** [hashcat/hashcat#2167]
This is my running record and it says it took 30 minutes to run and then it's over after 1 minute, right?
![image](https://user-images.githubusercontent.com/5046296/63136868-93971680-c006-11e9-9d26-d2dfddbdae70.png)

**Comment by Allesanddro** [comment]
what issue do u have there? anymore details would be helpful

**Comment by dragon-D** [comment]
@Allesanddro What makes a program stop running? The hashcat calculation ran for 31 minutes, but ended up running for only one minute, with the normal password in the text but not found

**Comment by philsmd** [comment]
I have no clue what you mean by "only one minute", the output of hashcat clearly says that the estimated time would be 31 minute, but your operating system/driver killed hashcat after 1 second (1 sec).

I would suggest trying with a different device -D 1 (your CPU) for instance etc. We actually have several open issues regarding -m 2500 = WPA not working on some Apple devices (see https://github.com/hashcat/hashcat/issues?q=is%3Aissue+is%3Aopen+WPA). This is defintely some bad macOS driver and maybe also temperature/cooling problem with these systems, because other systems (linux/windows) with similar AMD (or Nvidia, Intel) hardware have no problems at all.

You should at least give more details about which (other) hash types crash and if other OpenCL devices on the same system (-D 1 for instance) work etc. Thx

**Comment by dragon-D** [comment]
@philsmd  Thank you. I tried to run it on a dedicated GPU device and found no problem
