### ISSUE TITLE
about hashcat office 2007 docx crack

### ISSUE THREAD

**Issue by stwin1996** [hashcat/hashcat#2180]
Hello,I have a puzzling question about office 2007 docx .

I use "./hashcat -a 3 -m 9400 hashdoc_9400.dat ?b?b" 

Try to crack the following: 
$office$*2007*20*128*16*2dceb26afdcb534c2b230ff06b926a03*85f945f1437f83d8387f4765025bdf63*1897b1129386eb97b535a9a531b3c917f5aa9d3e

$office$*2007*20*128*16*fada9d83684562d05646078d610ad61f*830922c75602ff50a3d2c73f2ec1765a*448f9b27dd0fa3f8bce3dc9423c2b0240557e911
but failed 

the corrent  answer is 0x7889
I can't get the right results.

Who can help me see where the problem is?
Thanks!!!

**Comment by philsmd** [comment]
can you share the document ? Does it open with that password ?

I guess this is a problem with utf16 encoding. So it's probably a known limitation :(

note: Hashcat's OpenCL/CUDA kernel code does not respect all the conversion rules from bytes to utf16le, to make the kernel code faster. Internally -m 9400 uses utf16 (unicode) within the algo

**Comment by stwin1996** [comment]
Thank you for your answer.
You mean is that if it weren't for utf16 encoding, it would not be cracked successfully.

**Comment by stwin1996** [comment]
> can you share the document ? Does it open with that password ?
> 
> I guess this is a problem with utf16 encoding. So it's probably a known limitation :(
> 
> note: Hashcat's OpenCL/CUDA kernel code does not respect all the conversion rules from bytes to utf16le, to make the kernel code faster. Internally -m 9400 uses utf16 (unicode) within the algo

Thank you for your answer.
You mean is that if it weren't for utf16 encoding, it would not be cracked successfully.

**Comment by stwin1996** [comment]
> can you share the document ? Does it open with that password ?
> 
> I guess this is a problem with utf16 encoding. So it's probably a known limitation :(
> 
> note: Hashcat's OpenCL/CUDA kernel code does not respect all the conversion rules from bytes to utf16le, to make the kernel code faster. Internally -m 9400 uses utf16 (unicode) within the algo

I tried to modify the m09400-pure.cl file by replacing sha1_update_global_utf16le_swap with sha1_update_global_swap, it doesn't work either. 
Doing so does not block utf-16 encodong?

**Comment by philsmd** [comment]
utf16 encoding is of course **strictly required** by the algorithm design.

what I was saying is that hashcat does cheat a little bit and replace every second byte by a NUL byte \x00 and therefore it doesn't always work especially if the input is not ASCII but instead if in the input are already some multi-byte characters.

It's a problem similar to this one https://github.com/hashcat/hashcat/issues/2121

If you remove the utf16 encoding from the kernel itself, you would need to do the (correct, better, but much slower) utf16 encoding externally, before the kernel execution.

you could use --encoding-to utf16le (see hashcat --help) for encoding to utf16 externally and replace the utf16 encoding from all related kernels for that specific hash type (without --encoding-to it of course won't work, except if the bytes are already utf8 to utf16 encoded etc **AND** the kernel was modified accordingly).

You would also need to make sure that you remove all cached kernels from the "kernel" folder etc. So this modifications shouldn't be done in general by any non-advanced users, because it's kind of risky (you could risk to modify the kernel in such a way that it doesn't work at all anymore and if you forget to externally encode the bytes it won't work anymore, even for the most simple ASCII passwords etc).

I would say that this is kind of a known limitation (performance-related design decision), even if I would like that we implement this suggestion (https://github.com/hashcat/hashcat/issues/2121), which is kind of a duplicate. Should we close this issue?
