### ISSUE TITLE
Hashcat NetHunter error

### ISSUE THREAD

**Issue by cr4sh-me2** [hashcat/hashcat#2191]
Hi, I have a issue on my NetHunter
while try hashcat -I or use wifite2 i see:

Cannot find an OpenCL ICD loader library.

You are probably missing the native OpenCL runtime or driver for your platform.

* AMD GPUs on Linux require this runtime and/or driver:
  "RadeonOpenCompute (ROCm)" Software Platform (1.6.180 or later)
* Intel CPUs require this runtime and/or driver:
  "OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)
* Intel GPUs on Linux require this runtime and/or driver:
  "OpenCL 2.0 GPU Driver Package for Linux" (2.0 or later)
* NVIDIA GPUs require this runtime and/or driver:
  "NVIDIA Driver" (367.x or later)

What I can do???

**Comment by winxp5421** [comment]
Welp, hmm. How to answer this in a nice way.

You actually posted the solution to your own problem.
The error output is directly informing you what you are missing. 

The actual error "Cannot find an OpenCL ICD loader library"

The Solution: 

You are probably missing the native OpenCL runtime or driver for your platform.

Hashcat's prerequisites : (what you should be searching for to remedy the situation)
 
AMD GPUs on Linux require this runtime and/or driver:
"RadeonOpenCompute (ROCm)" Software Platform (1.6.180 or later)
Intel CPUs require this runtime and/or driver:
"OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)
Intel GPUs on Linux require this runtime and/or driver:
"OpenCL 2.0 GPU Driver Package for Linux" (2.0 or later)
NVIDIA GPUs require this runtime and/or driver:
"NVIDIA Driver" (367.x or later)


Everybody gets one :)

**Comment by cr4sh-me2** [comment]
Sure,but did I mention it's an android?
Is driver for arm64 processor?

**Comment by winxp5421** [comment]
My Previous statement is still 100% valid. 
You have dependencies that are not being met.
Meet those dependencies. 

Why on this good green earth you are trying to crack WPA2 networks on an android device the universe may never know. I highly suggest you offload cracking work to a more reasonable platform.
Even if you had a perfectly working OpenCL environment the performance would be disappointing at best. Capture with nethunter > push captures to a more suitable piece of hardware.

**Comment by winxp5421** [comment]
Maybe that was a little harsh. 

What you are trying to do on the platform that you are trying to do it on is. 
In my opinion unreasonable. 
Is it possible? sure its technically possible, but it is not normal. 
So much so that you will likely have to pave your own path to make it happen.

You need an OpenCL environment in order for hashcat to work.
So you will have to find how to install an OpenCL environment on your particular device. 

So even if you got an OpenCL environment running on the device I would still caution you.
I would highly recommend not using a portable device for cracking workloads. 
It's likely the device manufacturer was not planning on the device to be used at 100% CPU usage for hours on end. 
Damage will likely occur to the unit!
On top of that, the performance will likely be rather disappointing at best.

Best of luck on your adventure but you will likely not find help here.

**Comment by jsteube** [comment]
Not a hashcat issue
