### ISSUE TITLE
Why can't my amd GPU crack this hash and NVIDIA GPU is ok

### ISSUE THREAD

**Issue by gs135269** [hashcat/hashcat#2204]
hash：
12.zip:$pkzip2$1*1*3*1*1412*7800*ea14f88e*0*2a*8*6*ea14*4665*12.zip*$/pkzip2$:::::12.zip

Why can't my amd GPU crack this hash and NVIDIA GPU is ok

amd gpu：
OpenCL API (OpenCL 2.1 AMD-APP (2906.10)) - Platform #1 [Advanced Micro Devices, Inc.]
======================================================================================
* Device #1: Ellesmere, 4048/8192 MB allocatable, 36MCU
./OpenCL/m17200_a0-optimized.cl: Optimized kernel requested but not needed - falling back to pure kernel
Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Not-Iterated
* Single-Hash
* Single-Salt

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

Initializing backend runtime for device #1...
It’s over

**Comment by rdgeno12** [comment]
My first guess would be Hashcat isnt set up right, actually more correctly you computer. I have an AMD GPU and on Hashcat it shows three devices.  Device 1Gpu
Device 2 is the CPU and on board graphics card. Go into bios then advanced then turn on the other integrated video. When you turn Hashcat back on you'll have all three, they will be listed as two devices. I dont think that matters though. This shouldn't matter either but what model GPU is it ? I had problems getting mine to work but you seem to have got that. From what I understand it shouldn't matter what GPU your using. Your giving both the same information and using the same tools to get the answer so there really shouldn't  be a difference other than speed. Make sure your entering the command the same as the other too. I Google searched why would one computer get the correct answer and another computer get the wrong answer, and there was only one article I found that was even close and that one might be a programming problem there wasn't an answer. Googled why would Nvidia GPU get the right answer and AMD GPU doesn't get an answer, I got nothing, so I'm guessing it has to be the command line if neither suggestion helps heres AMD tech support, TECH.SUPPORT@amd.com they helped me a lot. They take a while to answer, I dont know where you are but I'm in the eastern time zone in the United States for some reason their responses usually came at 1:00 am or after. Be very specific and request that the question actually gets forwarded to the tech guys that the answer isnt in a script that's what I had to do and I finally got an actual tech guy and we solved the problem instead of canned answers. 
Sent from Yahoo Mail on Android 
 
  On Sun, Oct 20, 2019 at 8:04 AM, gs135269<notifications@github.com> wrote:   
hash：
12.zip:$pkzip2$113114127800ea14f88e02a86ea14466512.zip$/pkzip2$:::::12.zip

Why can't my amd GPU crack this hash and NVIDIA GPU is ok

amd gpu：
OpenCL API (OpenCL 2.1 AMD-APP (2906.10)) - Platform #1 [Advanced Micro Devices, Inc.]
   
   - Device #1: Ellesmere, 4048/8192 MB allocatable, 36MCU   
./OpenCL/m17200_a0-optimized.cl: Optimized kernel requested but not needed - falling back to pure kernel   
Hashes: 1 digests; 1 unique digests, 1 unique salts   
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates   
Rules: 1

Applicable optimizers:
   
   - Not-Iterated
   - Single-Hash
   - Single-Salt

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

Initializing backend runtime for device #1...
It’s over

**Comment by roycewilliams** [comment]
@rdgeno12, I know you're trying to help, but please don't answer questions like these on GitHub. 

The hashcat GitHub is for development - true bug reports, feature requests, etc. - and not for support. Support questions and their answers should be handled on [the hashcat forums](https://hashcat.net/forum/) instead.
