### ISSUE TITLE
Hashcat not decrypting blockchain v2,3 wallet

### ISSUE THREAD

**Issue by eastsida** [hashcat/hashcat#2208]
Hi, i have an issue with hashcat somehow it's not decrypting one wallet. Previously it was working well, decrypting v1 and 2,3 wallets. But this one not working. I used hashcat gui from hashkiller and i thought maybe text file contains some symbols or something. Today i tried decrypt straight in command line without gui still the same problem  - no result. I have my own sotfware decryptor and it's working with this hash and somehow hashcat not.
Results on screeshot (left-hashcat, right - my decryptor)
https://i.imgur.com/EtZfCLx.png
Maybe I am doing something wrong I dont understand.

**Comment by philsmd** [comment]
wow, what a nice bug you found !

https://github.com/hashcat/hashcat/blob/04b403ff16dd00f7d2ca46b122d551f5b054d678/OpenCL/m12700-pure.cl#L409

the test should be
```
if ((pt[i + 0] == '"') && (pt[i + 1] == 'a') && (pt[i + 2] == 'd') && (pt[i + 3] == 'd') && (pt[i + 4] == 'r') && (pt[i + 5] == 'e'))
```

"e" in address instead of "addra"


This is a quite rare case that you find problems like this. Maybe you should play the lottery with this luck. hehe

THanks for reporting
