### ISSUE TITLE
Support for sha1($salt.sha1($pass.$salt))

### ISSUE THREAD

**Issue by ANK1036Official** [hashcat/hashcat#2212]
Would you guys be willing to add support for sha1($salt.sha1($pass.$salt)) in the next update?

**Comment by Chick3nman** [comment]
Where is this algorithm being used? Do you have an example hash with a known password?

**Comment by ANK1036Official** [comment]
It was used by Armor games to encrypt users information. I can send a random line of it I guess.

Format: `id	uid	username	email	password	website	biography	aim	msn	yahoo	avatar	birthday	sex	location	xbox	wii	ps3	steam	favoritegame	created_on	updated_on	passwordReset	referralUser_id	level	newsletter	chat	active	points_lastmonth	points_current	points	comment_notify	validation	ip_address	comments	merit_notify	country_id	sync_time	sync	xr_idxr_uid	xr_username	blessed	role	profile_customizations`

`1000011	ac3138545e4bf7cf568375bc3805e9bb	USERNAME_REMOVED	EMAIL_REMOVED	7c2aed16c03c6cb800e6af80b542760451e22bc8						423	0000-00-00						1287965683	1374163478		0	0	0	1	1	0	0	135	Y	NULL	IP_REMOVED	N	Y	NULL	0	0	0		NULL	0	user	NULL
`

8'180'609 hashes total (Excluded: static salt used), 10,604,307 without exclusion of uniques.

Static salt used: 

> Everyone always wants new things. Everybody likes new inventions, new technology. People will never be replaced by machines. In the end, life and business are about human connections. And computers are about trying to murder you in a lake.

**Comment by ANK1036Official** [comment]
Talked about here: https://forum.hashkiller.co.uk/topic-view.aspx?t=28895&p=0

**Comment by trounce1** [comment]
@ANK1036Official is this still of interest to you? i can have a look at implementing

**Comment by ANK1036Official** [comment]
Yes, sorry for the late reply. It'd be useful to my research. I've been unable to replicate results for myself.

**Comment by trounce1** [comment]
@ANK1036Official does the static salt contain the fullstop at the end?, ill make a POC kernel today for a0 mode

**Comment by trounce1** [comment]
@ANK1036Official. i cant seem to find much information about the format. i need to know if it is hexlified at any point. do you have any example hashes with known password so i can implement the test script?

**Comment by trounce1** [comment]
can you send me a link to your hashDB? i have found confirmed passwords here https://raidforums.com/Thread-ArmorGames-Database-Leaked-Download but there is a cost

**Comment by trounce1** [comment]
@ANK1036Official here is my example POC of what i believe the format to be
```python3
from binascii import hexlify
from hashlib import sha1

password = b'hashcat12345'
salt = b'Everyone always wants new things. Everybody likes new inventions, new technology. People will never be replaced by machines. In the end, life and business are about human connections. And computers are about trying to murder you in a lake.'

r1 = sha1(password + salt).digest()

r2 = sha1(salt + hexlify(r1)).digest()

print("password : ", password)
print("salt     : ", salt)
print("r1       : ", hexlify(r1))
print("r2       : ", hexlify(r2))
```

OUTPUT:
```
password :  b'hashcat12345'
salt     :  b'Everyone always wants new things. Everybody likes new inventions, new technology. People will never be replaced by machines. In the end, life and business are about human connections. And computers are about trying to murder you in a lake.'
r1       :  b'605f8c38bf811ea1402279b771e295f05d92087d'
r2       :  b'b94941699d41b0198e38907a46eb574a107f588a'
```

it can be run here https://onlinegdb.com/Syp9af1DD

I have uploaded a kernel in my fork that should work in mode 0 and mode 3 for now. try this https://github.com/trounce1/hashcat/tree/24300

the mode is 24300

it can be simply run by ./hashcat -m 24300 -a 0 HASHFILE WORDLIST
it can be simply run by ./hashcat -m 24300 -a 3 HASHFILE MASK

you just need to put the sha1 hash in the hash file

works for my example hashes

8a92751a048412a8b8642162a21b33e577069381:hashcat123
b94941699d41b0198e38907a46eb574a107f588a:hashcat12345

**Comment by ANK1036Official** [comment]
Oh nice, I really appreciate the work. Sorry I wasn't here to send you the DB but you seem to have found a good source.

**Comment by philsmd** [comment]
Nice. Very good progress here.

I must admit that I didn't try the code of @trounce1 yet (neither the hashcat fork, nor the python script), but I've just independently verified the details of the algorithm.

For the future, it would be great if you @ANK1036Official at least describe the hash algorithm in more detail and provide several `hash:password` pairs such that dev do not waste their time to troubleshoot or research this.

If you really want us to implement something, at least answer this questions over here: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this . Thx

So the hash pairs I just checked with a very simple perl one-liner are as follows:
```
7c2aed16c03c6cb800e6af80b542760451e22bc8:bull$h1t
7a2ac7978911a1991b84b733444abcb531454f60:qwerty123
```
This is the hash from above with password `bull$h1t` that I just cracked with the perl code and the other one is from the forum linked above.

This means/confirms that the algorithm is indead:
```
sha1_hex ($salt . sha1_hex ($pass . $salt))
```

that means that also the inner sha1 hash is converted to hexadecimal first . This is a very important algorithm detail, because it could also be used in binary instead.

Note: in hashcat we just use something like `sha1` or `sha256` within the algorithm names for `sha1_hex` (the hex converted version), but use `sha1_bin` or `sha256_bin` for the raw/binary version.

----

so what we can do now with this issue ?

I would suggest to implement a very flexible / generic hash type that is very similar to all other fast hash types that hashcat supports (using pure and optimized kernels, with a0, a1, a3 attack types for both variants).

Of course you would need to use the pure kernel for this specific hash type, application. This is due to the long salt length. hashcat can use up to 256 bytes of salts in the pure kernels and this would fit, fortunately.

My suggestion is to make this a general format and use the following input for the `Armor game` cracking:
```
7c2aed16c03c6cb800e6af80b542760451e22bc8:Everyone always wants new things. Everybody likes new inventions, new technology. People will never be replaced by machines. In the end, life and business are about human connections. And computers are about trying to murder you in a lake.
7a2ac7978911a1991b84b733444abcb531454f60:Everyone always wants new things. Everybody likes new inventions, new technology. People will never be replaced by machines. In the end, life and business are about human connections. And computers are about trying to murder you in a lake.
```

i.e. hash:salt as with many other salted hashes.

hmm, I just had a quick glance at the forked hashcat code now and this seems strange: https://github.com/trounce1/hashcat/commit/567c6861d21c5b7f2c03a8aad66e7d9f2963422e#diff-df5b67dc5e5474c88361067f0e1c3ad4R64 (why such a long buffer ? 239 * 4 bytes (because of u32) is almost 1 KB for just under 256 byte salt. Furthermore, I highly would suggest to not hard-code the salt but make it more generic/flexible.

Thanks for your contribution here @trounce1 . Do you plan adding a more generic hash type to `hashcat` that is just `sha1 ($salt.sha1 ($pass.$salt))`, which would be able to crack this type of hashes ? That would be great. Thx

**Comment by trounce1** [comment]
@philsmd, I can make it generic no problem. I will implement it within the next 7 days.

**Comment by trounce1** [comment]
im on it right now

**Comment by jsteube** [comment]
Support was added with v6.2.0
