### ISSUE TITLE
Support curve25519

### ISSUE THREAD

**Issue by NStal** [hashcat/hashcat#2223]
Curve25519 is used in many POC cryptos, such as Burst/BHD , to generate plotter id. 

Could we have a batch generation feature to allow creating random curve25519 privatekey/pubkeys?

**Comment by philsmd** [comment]
are you sure you are writing in the wrong repository ?

hashcat is an (advanced) **password** recovery tool, but you are talking about some elliptic curve stuff. how is this related ? does it even have something to do with passwords?

Maybe the forum is a better place to ask for such questions, too. it's very confusing what the goal is here

**Comment by NStal** [comment]
Consider it to be part of the password generation process, like other hash function used in other brute force method. Take dictionary input hash as password transformed to privkey and output pubkey as hash result.

**Comment by NStal** [comment]
Let me explain it in more detail.

Some PoCC folks develop a PoC coin burst, which pretty much like bitcoin stuff but using curve25519 to secure their coins. Later competitors like BHD no longer use curve25519 to secure they coin, but still use the same hashing algo provided to "mine" the coin. It's hard to crack random generated curve25519 privkey. But we no longer use the curve25519 to sign the transaction, we only use the last 8byte of pubkey-hash as mining evidence. There is also another coin called LAVA, using the exact same method but secp256k1 as the elliptic curve. If we can manage to generate an 80-bytes-collission in 2 privkey space, it enables multi mining 2 different coin(LAVA and BHD) using the same device, which increase the revenue of cource. There are lots of fast enough secp256k1 pubkey generation tool out there, so I didn't ask this one here.

I know it may not be proper to ask such a feature here. But I thought hashcat could be a great a tool for high-performance hash collision detection. Maybe the name `hashcat` is misleading me hhhhh.

**Comment by philsmd** [comment]
My little knowledge about this stuff tells me that you are kind of missing some crucial information here: there is probably a key derivation function (KDF like PBKDF2 maybe) that generates some "scalar" value that needs to be used together with the elliptic curve.
so first hash to generate a key and than do some elliptic curve operation (like ECC scalar point multiplication).

The heavy part there of course would be the hashing (if the paramters are chosen wisely, high host factor/iterations) and not the ECC point multiplication.

but this issue is way too general and has no technical explanation what the algorithm used is (starting from a user-generated password like "password123").

I also think your idea about "we can manage to generate an 80-bytes-collission in 2 privkey space" is very infeasible and not suited for hashcat. If anything you could come up with the same public/private key after the key derivation from a easy non-random user-generated password and the ECC operation.

**Comment by NStal** [comment]
Sorry, it's a typo, we actually need a collision in 8byte.

The full algorithm is something like:
```
privekey <= random()
pubkey <= curve25519(privkey).pubkey
pid <= last8Bytes(pubkey)
```

We need a collision in pid.

But I agree that this kind of task may not be suited for hashcat. 

Thank you anyway!
