### ISSUE TITLE
Nvidia driver problem?!

### ISSUE THREAD

**Issue by hellresistor** [hashcat/hashcat#2224]
Hello Guys!
I have a laptop with a nvidia RTX 2080 8GB with windows 10 x64

I am using hashcat to recover my LUKS partition password. And only get 500~600H/s . I think isn't the better value.

My command
`hashcat64.exe -m 14600 -a 3 -D 2 --session=domatosession -w 3 C:\Users\User\LUKS\kingston.001 C:\Users\User\hashcat-5.1.0\masks\rockyou-1-60.hcmask
`

I have found some problem finding the driver version for my GPU and hashcat. Anyone have the right driver link? " NVIDIA GPUs require "NVIDIA Driver" (367.x or later)"

I am stuck here on this FAQ: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_may_have_the_wrong_driver_installed_what_should_i_do

PS: I dont have any OpenCL.dll files into system folders (Step5).

Appreciate some help,

Thank you all!

**Comment by jsteube** [comment]
I think 500-600 H/s is a valid number for a modern LUKS system. Note that LUKS measures the iterations it takes so that the process is busy for 2 seconds. The faster the CPU which creates the original LUKS image, the slower your GPU cracking rates. You can find out the iteration count by using cryptsetup luksDump /dev/sdXX. Since this is not a hashcat bug please continue the discussion on hashcat forum.
