### ISSUE TITLE
macOS Catalina: Radeon RX580 - OpenCL kernel self-test failed.

### ISSUE THREAD

**Issue by unruly-tr** [hashcat/hashcat#2240]
I git cloned the repo and built it on MacOS. I received warnings during the build:

```sh
warning: unknown warning option '-Wno-cast-function-type'; did you mean '-Wno-bad-function-cast'? [-Wunknown-warning-option]
1 warning generated.
```

However, the build completed. The build HashCat version is v5.1.0-1485-g9a2c4e34.

I am able to run the example0.sh without issue using the Intel  integrated GPU. However some test fail on the Radeon RX580 (8GB). For example:

```sh
Hashmode: 1700 - SHA2-512

* Device #3: ATTENTION! OpenCL kernel self-test failed.

Your device driver installation is probably broken.
See also: https://hashcat.net/faq/wrongdriver
```

Does anyone have any idea how to fix this.

**Comment by unruly-tr** [comment]
I'm going to reinstall macOS Catalina on the weekend.

I'll let you know if this fixes it.

**Comment by Hamid-Najafi** [comment]
Catalina uses Metal and hash cat doesnt support!

**Comment by jsteube** [comment]
@Goldenstarc Looks like OpenCL still works, otherwise it would have been stopped at a much sooner time in the benchmark. 
@unruly-tr Drivers on macOS always have been sub optimal, but this is not a hashcat issue.

**Comment by fabulouspanda** [comment]
@jsteube I've encountered this issue as well on macOS 10.14 Mojave using hash mode 11300 and benchmark reports issues with 1700, 2500 (that one gets cl build program failure), 1800, 7100 and 11300

The common factor in most of those seems to be SHA-512. If this isn't something that can be fixed in code is the solution just using 
--self-test-disable
? 

It does seem to be working when I add that flag (progress increases)

I should add that I'm using the same Radeon RX580 which in my case is NOT flashed with Mac firmware and this could potentially be the source of the issue?
