### ISSUE TITLE
Bitcoin hash not working

### ISSUE THREAD

**Issue by fabulouspanda** [hashcat/hashcat#2250]
I've got hash cat working with other wallet hashes, but with this one

$bitcoin$64$41e9fd363951c001696feecf65c6a2e4f64fd8e7ac1308084fec464ce69b3536$16$1935646860f57812$175970$2$00$2$00

using -a 3 -m 11300

I get the token length exception on version 5.1.0 and line length exception on version 3.6.0

What's wrong with this particular hash?

**Comment by philsmd** [comment]
please use/test the git version or beta from https://hashcat.net/beta

works for me

please don't forget to close the issue if fixed. thanks

**Comment by fabulouspanda** [comment]
I can't test the beta version since I'm running macOS but if I compile the git version I get the same error

```
 hashcat -a 3 -m 11300 ./hash.txt
hashcat (v5.1.0) starting...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz, skipped.
* Device #2: AMD Radeon RX 580 Compute Engine, 2048/8192 MB allocatable, 36MCU

Hashfile './hash.txt' on line 1 ($bitco...935646860f57812$175970$2$00$2$00): Token length exception
No hashes loaded.

Started: Mon Dec 16 14:23:25 2019
Stopped: Mon Dec 16 14:23:25 2019
```

**Comment by philsmd** [comment]
you are **NOT** using the git version. 

`hashcat (v5.1.0) starting...`

this means that you are using the release version...

if you would use the correct/git version, it would say something like this:
```
hashcat (v5.1.0-1512-g784eeb25) starting...
```

depending on the git version you use, the "-1512-..." part might change slightly, but it would definitely be different from just "v5.1.0" which is the release version.

Again, I think this problem was already fixed a while ago and your testing is not correct (you are not testing the latest git code aka PEBCAK).

Please try again and close the issue if the problem is resolved. Thank you so much for reporting and testing (but you need to test correctly aka make clean, git pull, make etc, otherwise the testing is flawed).

btw: you also would need to run "./hashcat" instead of just "hashcat" in case of testing a freshly compiled binary within the current folder ("./" is important to indicate which binary you want to test, i.e. the one within the PATH versus the one in the cwd).

**Comment by fabulouspanda** [comment]
Sorry, you spotted what I did there – I forgot the homebrew version is installed system wide whereas I was making but not installing all the other versions and then running hashcat not ./hashcat. Tested from git and it runs although now I have a separate issue to open about the OpenCL driver! Thank you for your help.

**Comment by Ramazik** [comment]
**I try beta version. Hash from Bitcoin now work fine. But i have new error.
Please help**

Hashcat ver: hashcat-5.1.0+1712.7z
Windows 10 x64 v1911, GeForce 1080, Driver v440.97
--------------------------------

D:\Wallet_Hashcat\hashcat>hashcat.exe -a3 -m 11300 D:\Wallet_Hashcat\hashcat\MyBitcoinHash.txt ?a?a?a?a?a?a?a?a?a
hashcat (v5.1.0-1712-gb627536c) starting...

* Device #1: CUDA SDK Toolkit installation NOT detected.
             CUDA SDK Toolkit installation required for proper device support and utilization
             Falling back to OpenCL Runtime

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
OpenCL API (OpenCL 1.2 CUDA 10.2.87) - Platform #1 [NVIDIA Corporation]

============================================================
* Device #1: GeForce GTX 1080, 6720/8192 MB (2048 MB allocatable), 20MCU

OpenCL API (OpenCL 1.2 ) - Platform #2 [Intel(R) Corporation]

=============================================================
* Device #2: Intel(R) HD Graphics 4600, 1565/1629 MB (407 MB allocatable), 20MCU
* Device #3: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD-LOOP
* Uses-64-Bit

Watchdog: Temperature abort trigger set to 90c

**clBuildProgram(): CL_BUILD_PROGRAM_FAILURE**

fcl build 1 succeeded.
fcl build 2 succeeded.
Error: out of memory.

* **Device #2: Kernel ./OpenCL/m11300-pure.cl build failed.**

Started: Tue Mar 03 01:31:17 2020
Stopped: Tue Mar 03 01:33:43 2020

**Comment by Ramazik** [comment]
Sorry. I solved this issue with command line parameter: -d 1
