### ISSUE TITLE
HashCat crashes in a Azure Virtual Machine

### ISSUE THREAD

**Issue by tndata** [hashcat/hashcat#2251]
I am using an Azure Virtual Machine for demonstration purposes of HashCat and I am not able to get any of the later versions of HashCat to work

if I run it from command line, I get (as administrator)
`C:\Temp\hashcat-5.1.0+1512\hashcat-5.1.0>hashcat -I
hashcat (v5.1.0-1512-g784eeb25) starting...

C:\Temp\hashcat-5.1.0+1512\hashcat-5.1.0>`

And the Windows event log records the following issue:

`Faulting application name: hashcat.exe, version: 0.0.0.0, time stamp: 0x5df76f16
Faulting module name: KERNELBASE.dll, version: 10.0.17763.404, time stamp: 0x2528b630
Exception code: 0xe06d7363
Fault offset: 0x0000000000039129
Faulting process id: 0x2334
Faulting application start time: 0x01d5b463826a5b9e
Faulting application path: C:\Temp\hashcat-5.1.0+1512\hashcat-5.1.0\hashcat.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: 3a0d3321-7e03-4637-8864-b0f213e2593c
Faulting package full name: 
Faulting package-relative application ID: `

The Azure machine is a Standard D2s v3 (2 vcpus, 8 GiB memory) with Windows 10 installed and no special other software installed, except Docker for Windows and some other common applications.
No GPU (Hyper-V Video)

Have also tried with version v5.1.0 and version 3.6 without any luck.

Version 2.0 works fine though.

**Comment by Chick3nman** [comment]
You appear to be attempting to run Hashcat on a very under spec'ed instance, especially considering it's lack of GPU so I hope you don't expect it to be very performant. Further, hashcat in a virtual machine at all can be problematic due to the way hardware devices are passed through to the VM/Runtimes. That said, it should still work.

You state that no other special software is installed. Did you install the required OpenCL runtime for the CPU in your box? I would assume it's going to be an Intel Xeon processor in that system so the "Intel® Xeon® Processor or Intel® Core™ Processor Runtime" available from the Intel developer zone website. Without that runtime, hashcat will not be able to use your CPU. Your statement that hashcat 2.0(which is native and not OpenCL) works but the later versions(which are OpenCL) do not pretty clearly confirms that you lack the required runtime.

I don't feel like this qualifies as a github issue, i would really prefer to handle this on the hashcat forums instead if there needs to be further troubleshooting since there's no clear bug identified here yet, no error messages from hashcat, and the poorly configured/absent runtime is almost surely the issue.

**Comment by jsteube** [comment]
Please continue on hashcat forum

**Comment by 7MinSec** [comment]
Hi, not trying to reopen an old issue but I have to know... @tndata did you ever find a fix to this?  Having the exact same config/issue and have installed the latest OpenCl from Intel.
