### ISSUE TITLE
ubuntu bionic needs libiconv: v5.1.0

### ISSUE THREAD

**Issue by akhepcat** [hashcat/hashcat#2254]
In order to successfully build v5.1.0,  ubuntu 18.04  (and beyond, assuming)  need to add libiconv to the linkage.

```
diff --git a/src/Makefile b/src/Makefile
index a922a236..cc17d8ad 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -247,6 +247,7 @@ LFLAGS_NATIVE           += -lpthread
 LFLAGS_NATIVE           += -ldl
 LFLAGS_NATIVE           += -lrt
 LFLAGS_NATIVE           += -lm
+LFLAGS_NATIVE           += -liconv
 endif # Linux

 ifeq ($(UNAME),FreeBSD)
```

allows me to compile correctly

**Comment by philsmd** [comment]
I'm pretty sure (almost 100% confident) it works without this change.
Many online resource also state the same "iconv support is already included in libc":
see https://askubuntu.com/questions/898826/why-is-there-no-libiconv-package-in-ubuntu/898835#898835

also see here: https://packages.ubuntu.com/bionic/amd64/libc6-dev/filelist (iconv.h directly incorporated into libc, also on bionic)...

In fact, there is no such "libiconv-dev" or similar in ubuntu (test with "apt search" or see here: https://packages.ubuntu.com/search?suite=bionic&searchon=names&keywords=iconv)... because already libc has support for iconv (in libc/libc-dev, the standard libc iconv library).

if you install build-essential etc the iconv support should be already available (libc-dev etc, see https://packages.ubuntu.com/bionic/build-essential).

for me this works out-of-the box with all modern ubuntu versions (including disco, bionic and xenial etc)

there is no libiconv.so (or similar) on my system... maybe you are trying to (incorrectly) use an alternative iconv implementation (not the standard libc one, but the external gnu libiconv)

**Comment by akhepcat** [comment]
Without adding it, i get the following:

`
obj/combined.NATIVE.a(wordlist.NATIVE.o): In function `get_next_word':
wordlist.c:(.text+0x3f0): undefined reference to `libiconv'
obj/combined.NATIVE.a(wordlist.NATIVE.o): In function `count_words':
wordlist.c:(.text+0xad8): undefined reference to `libiconv'
obj/combined.NATIVE.a(wordlist.NATIVE.o): In function `wl_data_init':
wordlist.c:(.text+0xf3e): undefined reference to `libiconv_open'
obj/combined.NATIVE.a(wordlist.NATIVE.o): In function `wl_data_destroy':
wordlist.c:(.text+0xfb5): undefined reference to `libiconv_close'
obj/combined.NATIVE.a(backend.NATIVE.o): In function `run_cracker':
backend.c:(.text+0x93b2): undefined reference to `libiconv'
backend.c:(.text+0x97e2): undefined reference to `libiconv'
backend.c:(.text+0x9857): undefined reference to `libiconv_open'
obj/combined.NATIVE.a(dispatch.NATIVE.o): In function `calc_stdin':
dispatch.c:(.text+0x503): undefined reference to `libiconv'
dispatch.c:(.text+0x6e8): undefined reference to `libiconv_open'
dispatch.c:(.text+0x716): undefined reference to `libiconv_close'
collect2: error: ld returned 1 exit status
src/Makefile:511: recipe for target 'hashcat' failed
make: *** [hashcat] Error 1
make: *** Waiting for unfinished jobs....
`

**Comment by akhepcat** [comment]
Ahhh... I see what happened.

Yessss, the system iconv.h  got replaced by the GNU package version, and that caused all sorts of fun problems.

I've restored the distribution copy, and things are back to working
