### ISSUE TITLE
[Feature Request] Timestamps for cracked hashes

### ISSUE THREAD

**Issue by mubix** [hashcat/hashcat#2255]
It would be nice to know exactly when or how long from start a password was cracked for statistics purposes and oddly enough report outs people are very interested in how much better one password is than another. I know that a simple timestamp doesn't correctly convey if one password is better than another, but it's something I have been asked for multiple times.

**Comment by mubix** [comment]
For example:
```
Session..........: hashcat
Status...........: Running
Hash.Name........: SHA1
Hash.Target......: hashes.txt
Time.Started.....: Thu Dec 19 23:51:57 2019 (17 secs)
Time.Estimated...: Tue Dec 31 21:26:13 2019 (11 days, 21 hours)
Guess.Mask.......: ?1?1?1?1?1?1?1?1 [8]
Guess.Charset....: -1 ?u?l?d?s, -2 Undefined, -3 Undefined, -4 Undefined
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:  6453.1 MH/s (12.97ms) @ Accel:8 Loops:256 Thr:1024 Vec:1
Recovered........: 0/15 (0.00%) Digests
Progress.........: 111400714240/6634204312890625 (0.00%)
Rejected.........: 0/111400714240 (0.00%)
Restore.Point....: 0/7737809375 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:339968-340224 Iteration:0-256
Candidates.#1....: Y_7erane -> 8=55y...
Hardware.Mon.#1..: Temp: 54c Util: 99% Core:1245MHz Mem:5000MHz Bus:8

[12-19-2019 23:52:21] b1a056b1b8fb0eddaaf88a1e4321ba9027eb3e96:BlEctone
```
or
```
Session..........: hashcat
Status...........: Running
Hash.Name........: SHA1
Hash.Target......: hashes.txt
Time.Started.....: Thu Dec 19 23:51:57 2019 (17 secs)
Time.Estimated...: Tue Dec 31 21:26:13 2019 (11 days, 21 hours)
Guess.Mask.......: ?1?1?1?1?1?1?1?1 [8]
Guess.Charset....: -1 ?u?l?d?s, -2 Undefined, -3 Undefined, -4 Undefined
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:  6453.1 MH/s (12.97ms) @ Accel:8 Loops:256 Thr:1024 Vec:1
Recovered........: 0/15 (0.00%) Digests
Progress.........: 111400714240/6634204312890625 (0.00%)
Rejected.........: 0/111400714240 (0.00%)
Restore.Point....: 0/7737809375 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:339968-340224 Iteration:0-256
Candidates.#1....: Y_7erane -> 8=55y...
Hardware.Mon.#1..: Temp: 54c Util: 99% Core:1245MHz Mem:5000MHz Bus:8

[31s] b1a056b1b8fb0eddaaf88a1e4321ba9027eb3e96:BlEctone
```

**Comment by Chick3nman** [comment]
There are a few issues i can see that this would cause, as well as some things that may make it very confusing to use.

To start, when you run an attack with say, several masks, dictionaries, etc. The status lines "time started" and "time estimated" are given for only the current dictionary/mask being processed and therefore could not be used to produce "Real" times for the output. A Mask that runs for 5 hrs, followed by one that ran for 5 minutes and found the hash, would produce a hash with a 5 minute time, which is clearly incorrect.

To solve the above issue we have 2 options for output, absolute time and relative time. With absolute being the date/time stamp, and relative being the "time since hashcat initialized". There is a time tracked outside of the time.start/time.estimated and it's displayed when hashcat throws its goodbye output. As its currently handled in hashcat, its track as the time since hashcat's process starts to the time it ends. It does NOT indicate the time running in the attack itself, so long processes like potfile comparisons, dictionary cache building, etc. would cause that time to be incorrectly inflated. We could live with that inflation as a sort of "real world attack time" as it would be indicative of a "normal user" spinning up hashcat. But it would not be accurate enough to compare to other users, only the same setup back to back.

If we wanted to be the most accurate and the most correct with this sort of timing, we would need to create and track a "time spent actually computing since hashcat init" value. This could be done, though it would require significantly more work than just copying the timers we already have into the output. I believe this would be the best way to handle this backend wise, though it's not without further problems. Inaccuracy between runs due to multi compute device async would be something to consider.

Also, if we were to implement such a timer, we would also need to implement a way to turn it on/off as well as give it an output format. We currently have the following outfile formats:

```
- [ Outfile Formats ] -

  # | Format
 ===+========
  1 | hash[:salt]
  2 | plain
  3 | hash[:salt]:plain
  4 | hex_plain
  5 | hash[:salt]:hex_plain
  6 | plain:hex_plain
  7 | hash[:salt]:plain:hex_plain
  8 | crackpos
  9 | hash[:salt]:crack_pos
 10 | plain:crack_pos
 11 | hash[:salt]:plain:crack_pos
 12 | hex_plain:crack_pos
 13 | hash[:salt]:hex_plain:crack_pos
 14 | plain:hex_plain:crack_pos
 15 | hash[:salt]:plain:hex_plain:crack_pos
```

Should we implement a timer as a possible output field, we would need to agree on how to add it to the above formats. If we mixed it in, similar to crack_pos, we would end up with a very large number of possible permutations. I would not suggest this as an option, which leaves us with limited other choices.

The next best way to do it would probably to add an entirely new flag, `--output-timer` or similar, that follows its own formatting and is layered on top of the other output format modifiers. Could possibly go with `--output-timer=#` and set the number values to `1 absolute time, 2 relative time, 3 etc` to solve the issue of there being multiple different ways to track the timing. If this were the case, I would also propose a standard format, similar to the one displayed in the OP, where the time is always in the same place in the output. This would make it easier to handle when dealing with output files after a run. There would be special considerations and changes to be made, however, for all of the non-human status display options as well, including `machine-readable` and `status-json`, since all of the different status options are used/parsed by at least a few wrappers and other external tools.

It wouldn't be the smallest task to add a new tracking system as well as output system, since quite a few things would need alterations and consideration, but it may be doable. With that said, what value does the timing actually bring? Does this actually produce useful analytics? I could think of a few very small cases where it could be used to measure the properties of very specific attacks or something, but overall I don't think the metric would be very useful because it couldn't be meaningfully compared with any other setup/attack.

**Comment by jsteube** [comment]
Adding another option for this sounds overkill. The flags in the output format is a simple bitmask. 

We could write it also this way and easily add the timestamp:

```
0x01 = hash[:salt]
0x02 = plain
0x04 = hex_plain
0x08 = crackpos
0x10 = timestamp
```

Doesn't look to bad I think.

**Comment by roycewilliams** [comment]
@jsteube, I believe you meant to say 0x16 for the timestamp?

**Comment by jsteube** [comment]
Why, it's correct.

**Comment by roycewilliams** [comment]
Yeah, I'm an idiot - disregard. :D

**Comment by mubix** [comment]
Ya, personally I think just the current time stamp of date and time the hash was cracked would allow me to do the math myself over things that hashcat wouldn't be able to know, like you said, multiple runs or different attacks.

**Comment by philsmd** [comment]
we could probably just write something like this in the help (to make it more user-friendly):
```
 1 = hash[:salt]
 2 = plain
 4 = hex_plain
 8 = crack_pos
16 = timestamp

Note: you can combine the above formats into a new one, for instance --outfile-format 19 which is 16+2+1 will show you the timestamp, hash and plain
```

we could also discuss if the order is important too, but I think that's too much (flexibility) and doesn't make sense very often to arbitrarily re-arrange the fields.

Another thing that comes to my mind is if we need both localtime (date + time) and also unix time... or only one of them... for the latter, which one would make more sense (unix time is probably easier, but not very user-friendly) ?

**Comment by Chick3nman** [comment]
Ordering for output options is something we need to decide on because there are wrappers and tools that may be expecting the current outfile format options, which have a consistent ordering. A bitmask style approach would be interesting, though i agree that it may not be the most user friendly. What about just a selection for each field? 

```
 1 = hash[:salt]
 2 = plain
 3 = hex_plain
 4 = crack_pos
 5 = timestamp

--outfile-format=1,2,4,5 for hash[:salt]:plain:crack_pos:timestamp
```
That may be a little easier for users to understand and use, though it's maybe a little ugly.

As for what time style to use, If we are just going to throw the "current time" when the hash gets cracked, i would assume UNIX would be the best since it will remain understandable even if the user is cracking on a remote host with a different time zone or something of that sort. Sure, its not the most user friendly, but i think that may be something they have to live with. Unix -> Local time isn't that hard to convert in my opinion. Hashcat produces the startup/shutdown times for the user on the goodbye screen, would we need to convert those to UNIX time and write them to the output file for the user to be able to determine the time it took to crack each hash? Just producing a time with a hash doesnt tell us much if we dont know when hashcat started.

The other option we have for what time to use is relative time, `[32 seconds]`, from the start of the attack. As i said above, this means we'd need to track the time from the start of hashcat, not just the start of the most recent dictionary/mask/etc., and with the startup times differing for some people, it may be a little harder to use relative time than it would be to just throw the current time.

**Comment by jsteube** [comment]
How about this?

```
1 = hash[:salt]
2 = plain
3 = hex_plain
4 = crack_pos
5 = timestamp (absolute)
6 = timestamp (relative)
```
Absolute is the unix time and relative the time (in seconds) since hashcat startup. This will include the startup time.

**Comment by philsmd** [comment]
yeah, these suggestions sound very good.

Does this mean that --outfile-format=1,2,4,5 is identical to --outfile-format=5,2,1,4 and always
hash[:salt]:plain:crack_pos:timestamp
will be shown?

the only problem with this is that it is a non-backwards-compatible change, while the bitmask approach could be made backwards-compatible . I'm not saying that it's the most important thing in the world... but maybe there exist some (user) scripts using --outfile-format that would break (but of course could be updated)

I also like to mention this other issue: https://github.com/hashcat/hashcat/issues/1664 which I just found and which seems to also mention some --outfile-format changes (but not really a duplicate because it's not addressing timestamps etc).

**Comment by Chick3nman** [comment]
The format could be made either static, where the two example commands are identical, or dynamic, so that the order you select is the order used in the output. That's up to use to decide before we implement it.

Backwards compatibility is something to consider, sure, however if this is something that is going into the 6.0.0 release, i think it would be reasonable to break backwards compatibility since the release is already such a large overhaul of the code base. I would be far more concerned with breaking backwards compatibility if we were only going from say 6.0.0 to 6.1.0 or something of that sort.

#1664 is actually pretty relevant since we would essentially be implementing a numbered version of what @roycewilliams was suggesting. If we chose to use the command order to dynamically set the output order/format, we would essentially cover the first part of what he brought up, and then any additional options to be added could be added later one. Clearing this issue and setting up the base work for future outfile fields all at once would be a pretty good change. Timer first, overhaul how the outfile system works, and then add the rest of his suggestions as we see fit or as they are requested.

**Comment by philsmd** [comment]
Good news for this issue: we recently added support for timestamps (unix time and seconds since start) and also changed the --outfile-format as discussed above with this commit https://github.com/hashcat/hashcat/pull/2292

Would be great if we get some feedback @mubix . Thx

**Comment by Alihaiderg** [comment]
Whttsup hacking training please

**Comment by Alihaiderg** [comment]
Whttsup hacking tool in mobail phone

**Comment by Alihaiderg** [comment]
#2292
