### ISSUE TITLE
[Request] AES Crypt archive cracking 

### ISSUE THREAD

**Issue by Complexoctopus** [hashcat/hashcat#2267]
https://www.aescrypt.com/aes_file_format.html

Thanks!

https://hashcat.net/forum/thread-8874-post-47115.html#pid47115

**Comment by philsmd** [comment]
Hey,

are you able to provide any more details on what this is and how the algorithm and restrictions work etc?

Are there any minimum and maximum password lengths limitations, is the salt length always the same ?

How popular is this software and are there any variations ? I see file format version 2 etc... so maybe there are some alternatives !?

Are there any other crackers that are already able to recover the password of these files ?

What information do we need from the file and are there already some known hash formats ?

Does for instance jtr support this and there is already an extraction tool for the "hashes" ?

If not, we would first have to define a good hash format with all the important information and at the same time develop a "hash extractor" !?

There are many open questions and these are very crucial things we would need to know, otherwise we can't really start implementing it.

also see https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this for what we normally also require for a valid feature request

Thank you very much
