### ISSUE TITLE
[Feature Request] Add MIC or PMKID to 22000 output ?

### ISSUE THREAD

**Issue by mem50** [hashcat/hashcat#2290]
Current result for mode 22000 is:

> macAP:macSTA:ESSID:password

When I capture several handshakes (WPA 02) and recover them via hashcat they have all the same macAP/macSTA/ESSID and I can't know which WPA 02 line has matched (useful for me to play with capture tools and options)

Would it be possible to add to the output something to differentiate them? For example the MIC (or PMKID for WPA*01) ?

Thanks.

**Comment by ZerBea** [comment]
This feature request makes sense. For example hcxpcapngtool and hcxhashtool offer several options to convert (hcxpcapngtool) and filter hashes (hcxhastool) as well as bash tools.

Knowing which option is the best, by evaluating the hashes, would be a nice feature. Adding the PMKIDand the MIC to hashcat's outfile format would be helpful to choose the best option(s):
PMKID and/or MIC : MAC_AP : MAC_STA : ESSID (in ASCII) : PSK (in ASCII)

The potfile format should be untouched, because it contain the static output of the PBKDF2 calculation:
PMK * ESSID(SALT) * PSK
That keep this file small. Adding dynamic values (like PMKID or MIC), would inflate the potfile unnecessarily.

The hashline (22000) should be untouched, too, especially the ESSID field:
https://hashcat.net/forum/thread-8891-post-47257.html#pid47257
https://hashcat.net/forum/thread-6661-post-47256.html#pid47256

**Comment by ZerBea** [comment]
BTW:
We can do this by an additional option on hashcat's --outfile-format 
because adding dynamic values like PMKID and/or MIC can lead to big files, especially if hcxpcapngtool --all is used to convert the hashes.

**Comment by mem50** [comment]
Good idea to add it through a --outfile-format option.

Concerning the ESSID, I would advise to stick to 22000 line, where ESSID is in **hex**.

Output could be : PMKID-or-MIC : MAC_AP : MAC_STA : ESSID **(in HEX)** : PSK (in ASCII)

**Comment by jsteube** [comment]
We're in the middle of a outfile-format reorganization therefore I don't want to change this right now. However, I've add the PMKID/MIC as a first column to the cracked output as suggested.

Note the output of ESSID is in ASCII as long as it is a valid utf8 string and does not contain the separator character. Basically the same way how it works with passwords.

Here's the commit: https://github.com/hashcat/hashcat/commit/7797488a12c657df97c8195388eabba3b36aa28a

**Comment by ZerBea** [comment]
Great, thanks!

**Comment by mem50** [comment]
Will test. Thanks!

**Comment by ZerBea** [comment]
First feet back:
Output is working like expected. Now we are able to correlate output hash with hash line (by running simple bash tools or pearl/python, ...). Doing this we can play with options (hcxtools) to identify the best options/values for future hashcat tasks, to reduce size of the hash file and to convert only the best hashes. That will speed up hashcat on next task, too.
Great work again, Atom.

Cheers
Mike

**Comment by ZerBea** [comment]
BTW:
A simple cut -c 32- will remove the PMKID/MIC. Removing this dynamic hash values will reduce the output file size if we don't need them (keep data base/archive smal).

**Comment by mem50** [comment]
> Now we are able to correlate output hash with hash line
> Doing this we can play with options (hcxtools) to identify the best options/values 

Exactly =)
