### ISSUE TITLE
Compiling from Linux for Windows

### ISSUE THREAD

**Issue by DrDinosaur** [hashcat/hashcat#2300]
```
## To compile win-iconv with mingw clone from here: https://github.com/win-iconv/win-iconv
##
## Then patch the makefile with the patches from tools/win-iconv-64.diff and run make install
##
```

I'm trying to patch the Makefile with that diff

```
❯ patch src/Makefile tools/win-iconv-64.diff
patching file src/Makefile
Hunk #1 FAILED at 6.
Hunk #2 FAILED at 19.
2 out of 2 hunks FAILED -- saving rejects to file src/Makefile.rej
```

Am I doing something wrong? In any case, I think there could be more documentation for this process considering how it's not just a straightforward "make." For example, one step is to first run this: `sudo apt-get install mingw-w64`

Thanks

**Comment by philsmd** [comment]
There is a Makefile in /opt/win-iconv-64/Makefile and you need to change/fix that with the tools/win-iconv-64.diff patch file from the hashcat source code folder.

to do so you can just copy the win-iconv-64.diff file to /opt/win-iconv-64 and run
```
patch < win-iconv-64.diff
```

The problem here is that this is a very special case when/if users **really need** to do this... this is something that normally only hashcat main developers need to do and also only if they build the release version... in all other cases you would just compile the binaries directly with the target system (i.e. with the cygwin/msys instruction for windows and just run "make" for *nix - including macOS - systems).

I also think that this is more or less just a user question that perfectly would fix in the developers section of the hashcat forum, but disqualifies as an issue or feature request for github.

That said, I already said that users might think about creating a new documentation file like:
1. BUILD.md
2. BUILD_CYGWIN.md
3. BUILD_MSYS2.md

but for linux to windows cross-compiling.  The problem here is that it should have a big warning about avoiding to do cross-compiling, but use the native compilation whenever possible.... again, this use case should be very rare (only for distributing binaries, release versions).

also see https://github.com/hashcat/hashcat/issues/2253

I think we should close this issue and maybe consider adding a cross-compilation tutorial in the future (while still warning the user that cross-compiling is discouraged because the native compilation should be preferred, because it's easier with just "make")

**Comment by DrDinosaur** [comment]
I got it compiled now, thanks
