### ISSUE TITLE
Generated bitmap tables...Insufficient memory available Segmentation fault

### ISSUE THREAD

**Issue by Celtic936** [hashcat/hashcat#2304]
OS:  Ubuntu 18.04

HW: 
- Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
-  Memory Size: 64 GB
- 2 *   GeForce RTX 2080 Ti (2*12G mem)

sw src: 5.1 and 2020.02.05 git
 ./hashcat   --backend-ignore-opencl  -m 30 -a 3 -o x hash.txt /tables/weakpass_2_wifi       

weakpass_2_wifi:  27G 

 wc -l hash.txt 
604 hash.txt
Download from : https://weakpass.com/download

command: ( "./hashcat" : from git, "hashcat" : 5.1 )
./hashcat   --backend-ignore-opencl  -m 30 -a 3 -o x hash.txt /tables/weakpass_2_wifi 
hashcat (v5.1.0-1655-gdbfd8d94) starting...

CUDA API (CUDA 10.2)
====================
* Device #1: GeForce RTX 2080 Ti, 9321/11018 MB, 68MCU
* Device #2: GeForce RTX 2080 Ti, 9323/11019 MB, 68MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256
Minimim salt length supported by kernel: 0
Maximum salt length supported by kernel: 256

Generated bitmap tables...
Generated bitmap tables...Insufficient memory available Segmentation fault

hashcat    -m 30 -a 3 -o x hash.txt /tables/weakpass_2_wifi 
hashcat (v5.1.0) starting...

* Device #3: Not a native Intel OpenCL runtime. Expect massive speed loss.
             You can use --force to override, but do not report related errors.
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce RTX 2080 Ti, 2754/11018 MB allocatable, 68MCU
* Device #2: GeForce RTX 2080 Ti, 2754/11019 MB allocatable, 68MCU

OpenCL Platform #2: The pocl project
====================================
* Device #3: pthread-Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz, skipped.

Generated bitmap tables...Insufficient memory available
Segmentation fault

We have 64 GB memory - why "Insufficient memory available" when load a 27 GB file ?

**Comment by philsmd** [comment]
if you read the --help output, you will see very quickly that -a 3 is not a dictionary attack.

```
- [ Attack Modes ] -

  # | Mode
 ===+======
  0 | Straight
...
  3 | Brute-force
```

for word list attacks you need to use -a 0 (not -a 3)

-a 3 is a mask attack (or in special cases a so-called "brute-force").

This is just an user error, not a problem with hashcat.

You are basically trying to run a huge dictionary as a huge set of hashcat masks (hcmask file) and this will require a lot of memory. It is not something you should/can do.. use -a 0 (the correct attack mode) instead.

Please consider using the forum (searching first, and if really nothing is found you can create a new thread) for user questions like this. This helps to keep the github issue (bugs and feature requests only) clean.

BTW (off-topic): you should probably install the Intel OpenCL Runtime from the intel download page instead of using pocl... the intel driver is better and faster (and actually works in most cases ;) )

**Comment by Celtic936** [comment]
Oh, thanks !
I pass it on to my colleague (I didn't look at using it badly either)
