### ISSUE TITLE
Feature Request: adding the new mysql pw hash format

### ISSUE THREAD

**Issue by Viss** [hashcat/hashcat#2305]
The info for the new hash format is here: https://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/

I found it on an engagement and ended up kicking a chair around a room because the hash format is so new it's not in any cracking tools yet :D

**Comment by jsteube** [comment]
Shouldn't be too complicated. Could you please provide a few valid example hashes:password pairs?

**Comment by roycewilliams** [comment]
Some interesting corruption^Wbinary / control characters in the hashes on my version:

```
$ mysql --version
mysql  Ver 8.0.19 for Linux on x86_64 (MySQL Community Server - GPL)

$ cat create-users.sql 
CREATE USER 'password'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'password';
CREATE USER 'hashcat'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'hashcat';
CREATE USER 'facewithtearsofjoy'@'localhost' IDENTIFIED WITH caching_sha2_password BY '😂';

$ cat show-hashes.sql 
use mysql;
SELECT User, plugin, authentication_string 
FROM user
WHERE User IN ('password', 'hashcat', 'facewithtearsofjoy');

$ mysql -p -u root <show-hashes.sql >mysql8-hashes.txt

$ cat mysql8-hashes.txt
User	plugin	authentication_string
facewithtearsofjoy	caching_sha2_password	$A$005$AVeU(;r
                                                               x''.LZ\nYfXyOqM4z0H6kqNB8EI3qbAtZ4PxMBaie5KbUHDWOPgD
hashcat	caching_sha2_password	$A$005$J+TyoSZUBKFLpiLcdkMJDtslD/yOmwbfJy9MXkxqSkF5gnaWxOUrw4Xd8
password	caching_sha2_password	$A$005$E-lL`yUN#xT}P3U02zGfdIsppFL1sO8o0.WUA8ccu85YoD44Aq0bTE0GFCo4

$ cat mysql8-hashes.txt | xxd
00000000: 5573 6572 0970 6c75 6769 6e09 6175 7468  User.plugin.auth
00000010: 656e 7469 6361 7469 6f6e 5f73 7472 696e  entication_strin
00000020: 670a 6661 6365 7769 7468 7465 6172 736f  g.facewithtearso
00000030: 666a 6f79 0963 6163 6869 6e67 5f73 6861  fjoy.caching_sha
00000040: 325f 7061 7373 776f 7264 0924 4124 3030  2_password.$A$00
00000050: 3524 4118 5665 5528 3b72 0b06 0578 271a  5$A.VeU(;r...x'.
00000060: 272e 4c5a 5c6e 5966 5879 4f71 4d34 7a30  '.LZ\nYfXyOqM4z0
00000070: 4836 6b71 4e42 3845 4933 7162 4174 5a34  H6kqNB8EI3qbAtZ4
00000080: 5078 4d42 6169 6535 4b62 5548 4457 4f50  PxMBaie5KbUHDWOP
00000090: 6744 0a68 6173 6863 6174 0963 6163 6869  gD.hashcat.cachi
000000a0: 6e67 5f73 6861 325f 7061 7373 776f 7264  ng_sha2_password
000000b0: 0924 4124 3030 3524 4a2b 5479 6f05 5350  .$A$005$J+Tyo.SP
000000c0: 085a 1c17 1855 424b 464c 7069 4c63 646b  .Z...UBKFLpiLcdk
000000d0: 4d4a 4474 736c 442f 794f 6d77 6266 4a79  MJDtslD/yOmwbfJy
000000e0: 394d 586b 7871 536b 4635 676e 6157 784f  9MXkxqSkF5gnaWxO
000000f0: 5572 7734 5864 380a 7061 7373 776f 7264  Urw4Xd8.password
00000100: 0963 6163 6869 6e67 5f73 6861 325f 7061  .caching_sha2_pa
00000110: 7373 776f 7264 0924 4124 3030 3524 452d  ssword.$A$005$E-
00000120: 0e6c 4c60 7955 1a4e 2378 547d 0250 3355  .lL`yU.N#xT}.P3U
00000130: 3032 7a47 6664 4973 7070 464c 3173 4f38  02zGfdIsppFL1sO8
00000140: 6f30 2e57 5541 3863 6375 3835 596f 4434  o0.WUA8ccu85YoD4
00000150: 3441 7130 6254 4530 4746 436f 340a       4Aq0bTE0GFCo4.
```
Is it possible that this hash format is mostly ASCII, but with some non-ASCII components? Or is it just a bug?

Ref: https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html

**Comment by Viss** [comment]
heh, Royce beat me to it. 
The hashes I have are from a live engagement and I don't have the cleartext passwords. My next step would have been to do exactly what Royce has already done!

**Comment by roycewilliams** [comment]
For the record, I think this is either a bug, or misinformed. Hashes should either be binary, a hex representation of it, or in human-readable $type$salt$hash format. I can think of no good reason to push a "mostly-ASCII-with-a-little-binary" mashup of data into the $type$salt$hash format. If this isn't a bug and/or the MySQL team doesn't want to address this, a de-facto alternative $type$salt$hash format will emerge anyway for portability reasons, and will be similar to the hash formats produced by a hypothetical oracle82john or equivalent tool in the future.

**Comment by philsmd** [comment]
The algo/format seems exactly what we already know as sha256crypt, with 5000 rounds of (default) iterations and a salt length of (default) 20 bytes (the binary data you see, in addition to the tabs and new lines in your output which you also could see as binary or control characters).

an example from your above output is:
```
password:$A$005$452d0e6c4c6079551a4e2378547d025033553032$zGfdIsppFL1sO8o0.WUA8ccu85YoD44Aq0bTE0GFCo4:password
```

The format I used here is $user:$hash:$pass and the $hash ($A$...GFCo4) above uses the 20 bytes of salt in hexadecimal (that was of course just my quick choice to convert it... we definitely need to come up with a better hash format like maybe
```
$mysql$version*salt*digest
```
or similar.

The problem was I could **NOT** really test this idea with any cracker or common programming or scripting language (php, perl, python, nodejs, ...) because most of these "libraries" limit the sha256crypt salt to a maximum length of 16 bytes.

Fortunately, I quickly found out that JTR pass_gen.pl tool uses a manual shacrypt function and therefore I just tested it with this slightly modified version (and it works !!!):
```
#!/usr/bin/env perl

#
# This is modified pass_gen.pl from https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/run/pass_gen.pl

# Copyright: https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/doc/pass_gen.Manifest
# public domain
# written by Jim Fougeron

#
# updated for new MySQL hashes by philsmd
# modified date: February 2020
# license: public domain
#

use warnings;
use strict;

use Digest::SHA qw (sha256);

my @i64 = ('.', '/', '0'..'9', 'A'..'Z', 'a'..'z');

sub to64
{
  my $v = shift;
  my $n = shift;

  my $str;

  while (--$n >= 0)
  {
    $str .= $i64[$v & 0x3F];

    $v >>= 6;
  }

  return $str;
}

sub sha_crypts
{
  my ($func, $bits, $key, $salt, $loops) = @_;

  my $bytes = $bits / 8;

  my $b = $func->($key . $salt . $key);

  # Add for any character in the key one byte of the alternate sum.

  my $tmp = $key . $salt;

  for (my $i = length ($key); $i > 0; $i -= $bytes)
  {
    if ($i > $bytes)
    {
      $tmp .= $b;
    }
    else
    {
      $tmp .= substr ($b, 0, $i);
    }
  }

  # Take the binary representation of the length of the key and for every 1 add the alternate sum, for every 0 the key.

  for (my $i = length ($key); $i > 0; $i >>= 1)
  {
    if (($i & 1) != 0)
    {
      $tmp .= $b;
    }
    else
    {
      $tmp .= $key;
    }
  }

  my $a = $func->($tmp);

  # NOTE, this will be the 'initial' $c value in the inner loop.

  # For every character in the password add the entire password.  produces DP

  $tmp = "";

  for (my $i = 0; $i < length ($key); $i++)
  {
    $tmp .= $key;
  }

  my $dp = $func->($tmp);

  # Create byte sequence P

  my $p = "";

  for (my $i = length ($key); $i > 0; $i -= $bytes)
  {
    if ($i > $bytes)
    {
      $p .= $dp;
    }
    else
    {
      $p .= substr ($dp, 0, $i);
    }
  }

  # produce ds

  $tmp = "";

  my $til = 16 + ord (substr ($a, 0, 1));

  for (my $i = 0; $i < $til; $i++)
  {
    $tmp .= $salt;
  }

  my $ds = $func->($tmp);

  # Create byte sequence S

  my $s = "";

  for (my $i = length ($salt); $i > 0; $i -= $bytes)
  {
    if ($i > $bytes)
    {
      $s .= $ds;
    }
    else
    {
      $s .= substr ($ds, 0, $i);
    }
  }

  my $c = $a; # Ok, we saved this, which will 'seed' our crypt value here in the loop.

  # now we do 5000 iterations of SHA2 (256 or 512)

  for (my $i = 0; $i < $loops; $i++)
  {
    if ($i & 1) { $tmp  = $p; }
    else        { $tmp  = $c; }

    if ($i % 3) { $tmp .= $s; }
    if ($i % 7) { $tmp .= $p; }

    if ($i & 1) { $tmp .= $c; }
    else        { $tmp .= $p; }

    $c = $func->($tmp);
  }

  my $inc1; my $inc2; my $mod; my $end;

  if ($bits == 256) { $inc1 = 10; $inc2 = 21; $mod = 30; $end =  0; }
  else              { $inc1 = 21; $inc2 = 22; $mod = 63; $end = 21; }

  my $i = 0;
  $tmp = "";

  do
  {
    $tmp .= to64 ((ord (substr ($c, $i, 1)) << 16) | (ord (substr ($c, ($i + $inc1) % $mod, 1)) << 8) | ord (substr ($c, ($i + $inc1 * 2) % $mod, 1)), 4);
    $i = ($i + $inc2) % $mod;
  } while ($i != $end);

  if ($bits == 256) { $tmp .= to64 ((ord (substr ($c, 31, 1)) << 8) | ord (substr ($c, 30, 1)), 3); }
  else              { $tmp .= to64  (ord (substr ($c, 63, 1)), 2); }

  return $tmp;
}

sub sha256crypt
{
  my $pass = shift;
  my $salt = shift;
  my $iter = shift;

  my $bin = sha_crypts (\&sha256, 256, $pass, $salt, $iter);

  # TODO: fix (or create new) hash format:

  return "\$5\$" . unpack ("H*", $salt) . "\$$bin";
}

#
# what is particular about this format?
# the (default) 20 byte salt ! most sha256crypt implementions are limited to 16 bytes salt
#

my $ITER = 5000;
my $pass = "password";
my $salt = pack ("H*", "452d0e6c4c6079551a4e2378547d025033553032");

print sha256crypt ($pass, $salt, $ITER) . "\n";
```
note: again, the hash format (output) needs to be adapted for sure (something like $mysql$version*....)

conclusion: it is just sha256crypt with a strange salt length and a strange output/format (but maybe that is part of the obfuscation and not-really-supported-by-common-crackers because non-standard salt etc, lol).

some code references:
https://github.com/mysql/mysql-server/blob/4869291f7ee258e136ef03f5a50135fe7329ffb9/include/crypt_genhash_impl.h#L33
https://akkadia.org/drepper/SHA-crypt.txt
https://github.com/mysql/mysql-server/blob/4869291f7ee258e136ef03f5a50135fe7329ffb9/mysys/crypt_genhash_impl.cc#L242
https://github.com/mysql/mysql-server/blob/ea7d2e2d16ac03afdd9cb72a972a95981107bf51/sql/auth/sha2_password.cc#L667
https://github.com/mysql/mysql-server/blob/ea7d2e2d16ac03afdd9cb72a972a95981107bf51/sql/auth/sha2_password.cc#L407-L426
https://github.com/mysql/mysql-server/blob/ea7d2e2d16ac03afdd9cb72a972a95981107bf51/sql/auth/sha2_password.cc#L269-L276
https://github.com/mysql/mysql-server/blob/8e797a5d6eb3a87f16498edcb7261a75897babae/sql/auth/i_sha2_password.h#L55
(this is why we have 005 * 1000 = 5000)

Thanks for the example and credits to jtr for pass_gen.pl that made this "idea" that it is/could be sha256crypt very easy to test (since most other libraries do NOT support long salts).

**Comment by roycewilliams** [comment]
As a quick workaround, @philsmd suggested using one of the native SQL functions HEX() or TO_BASE64() to convert prior to export:

```
$ cat show-hashes2.sql
use mysql;
SELECT User, plugin, TO_BASE64(authentication_string), HEX(authentication_string)
FROM user
WHERE User IN ('password', 'hashcat', 'facewithtearsofjoy');

$ mysql -p -u root <show-hashes2.sql >mysql8-hashes2.txt

$ cat mysql8-hashes2.txt
User	plugin	TO_BASE64(authentication_string)	HEX(authentication_string)
facewithtearsofjoy	caching_sha2_password	JEEkMDA1JEEYVmVVKDtyCwYFeCcaJy5MWgpZZlh5T3FNNHowSDZrcU5COEVJM3FiQXRaNFB4TUJh\naWU1S2JVSERXT1BnRA==	244124303035244118566555283B720B060578271A272E4C5A0A596658794F714D347A3048366B714E4238454933716241745A3450784D42616965354B62554844574F506744
hashcat	caching_sha2_password	JEEkMDA1JEorVHlvBVNQCFocFxhVQktGTHBpTGNka01KRHRzbEQveU9td2JmSnk5TVhreHFTa0Y1\nZ25hV3hPVXJ3NFhkOA==	244124303035244A2B54796F055350085A1C171855424B464C70694C63646B4D4A4474736C442F794F6D7762664A79394D586B7871536B4635676E6157784F55727734586438
password	caching_sha2_password	JEEkMDA1JEUtDmxMYHlVGk4jeFR9AlAzVTAyekdmZElzcHBGTDFzTzhvMC5XVUE4Y2N1ODVZb0Q0\nNEFxMGJURTBHRkNvNA==	24412430303524452D0E6C4C6079551A4E2378547D0250335530327A47666449737070464C31734F386F302E575541386363753835596F443434417130625445304746436F34
```
But this is just treating the symptom. 

Tentatively, it appears that only the salt is being mis-converted. Fixing just the salt, and leaving the rest of the human-readable hash intact, might be possible with creative use of the SQL SUBSTR() function. If Oracle doesn't see this as a bug, that would be the most portable and human-readable workaround.

**Comment by philsmd** [comment]
I'm not too sure if the mysql team would be willing and interested to change the format. Remember, that this is a almost 3 year old format (https://github.com/mysql/mysql-server/commit/110fdc26a7cdaebfaa6a0507666f38d402dfd2bb , that makes me wonder why nobody already requested it yet, maybe it's just not the default on many systems)

The SQL query could be something like this:
```
SELECT CONCAT_WS('$',SUBSTR(authentication_string,1,6),LOWER(HEX(SUBSTR(authentication_string,8,20))),SUBSTR(authentication_string,28,43)) AS hash FROM user WHERE user = 'user';
```

but I'm still not sure if we should use that $A$... format as a hash for hashcat, or if we should use some kind of
```
$mysql$version*salt*digest
```
format, which would be more aligned and consistent with other hash formats we recently added.

@Viss Could you please give some feedback here, especially for the question if the "user" database is the one you have access to and for which you dumped the "hashes" (and if they also look like $A$ hashes etc)... because afaik there is also the possibility to sniff the network traffic (and the algorithm seems to be of course very different, so which one do you have ?)

**Comment by Viss** [comment]
in this circumstance, it's a hosted mysql instance and the org hosting the db hasnt given me physical permission to enter the datacenter or tap stuff or anything like that. In other circumstances that could perhaps have been an approach, this one forces ssl and makes you fetch a ca cert to talk to it. its fairly hardened. 

that query totally worked - here's the output:

>$A$005$050f1f6c7f0a14380a2d590c774a112c5b65625c$fNc.DxO4pOcqhJQofYKUFZG4JC8IXXbUBwc1kWO3tu1 
>$A$005$5a097c440740186c1118530f2d073967214a7675$pqFVqtugeMvMiZN0Abgrcsg9ygLLMMS9.STJ1R4Z2S4 
>$A$005$3f2e080366060e6b512e03096d137b6a2e470a3b$xB6SzgL866JxLVRVehkriUAys2gw6fDsn81peRD5frC 
>*DAA5F$3241374143414233344641424641304431393445$C15EE1CE177788                     
$A$005$154a6b3420054d31583171407c375d204f307118$ZcyVMr9NoEhcDTm5PZzxpNHWNIX/9JAjibfD77J0jjC 

though in my experience doing ths sort of work, if you find yourself with access between a mysql server and the stuff its serving, you're usually way way past the point where you're trying to crack passwords to move laterally :D

**Comment by philsmd** [comment]
wow great. thanks for the confirmation and update...

I discussed this a little bit with @jsteube a couple of hours ago and we agreed that a good hash format would be a combination of the $mysql$... (with salt and digest) format and the $A$ as a "version" number (because it seems $A$ stands for "sha256" and maybe future version could be updated to $B$ for sha512 etc etc ... just an example).

My suggestion therefore is to use this query:
```
SELECT CONCAT(user,':$mysql',SUBSTR(authentication_string,1,6),'*',LOWER(HEX(SUBSTR(authentication_string,8,20))),'*',SUBSTR(authentication_string,28,43)) AS 'user:hash' FROM user WHERE plugin = 'caching_sha2_password' AND NOT authentication_string LIKE '%INVALIDSALTANDPASSWORD%';
```

and the user:hash output would look like this:
```
username:$mysql$A$005*06437a150142644d74187a6a2f0d7971094f2575*HfzgHSftZ0OjHzspBPf4e3zu02QWhzQ6J8MsuTBI9p.
```

this of course would be used together with --username (or users could just remove the "username:" field)

The format of the hash itself would be:
```
$mysql$A$[ITERATIONS]*[HEX_SALT]*[BASE64_VARIANT_DIGEST]
```

any testers or reasons to use a different format ? does the query work for you guys too ?

**Comment by philsmd** [comment]
it turns out that the format with mixed hex and the (non-standard) base64 variant is also not really that nicely formatted and not consistent (we would prefer to use only hex or only base64).
The problem with everything converted to base64 is that the base64 table that sha256crypt algo uses is non-standard base64 (and the mysql team decided to use the sha256crypt base64 variant and there is no SQL function for an alternative base64 table/encoding).

To avoid making the query top complex and long, I have a new suggestion (yeah, I know at the end it doesn't really matter too much which encoding/format we use, but we should decide before we implement it and it should kinda look consistent and nice):
```
SELECT user, CONCAT('$mysql',LEFT(authentication_string,6),'*',INSERT(HEX(SUBSTR(authentication_string,8)),41,0,'*')) AS hash FROM user WHERE plugin = 'caching_sha2_password' AND authentication_string NOT LIKE '%INVALIDSALTANDPASSWORD%';
```

this query produces results like this:
```
| user | $mysql$A$005*06437A150142644D74187A6A2F0D7971094F2575*48667A67485366745A304F6A487A73704250663465337A7530325157687A51364A384D737554424939702E |
```

i.e. we have the user on the first column and the hash as the second column (this avoids us mentioning that the --username flag is needed). Furthermore, the hash itself is now all in hexadecimal. With INSERT() we insert a * char after the salt (to make it look nicer). The digest (last field) is now actually a hex encoded base64-variant of the raw hash (yeah, this is kind of weird and unnecessary double-encoding, but the hash line now looks much nicer).

The format of the hash now would be:
```
$mysql$A$[COST_FACTOR]*[HEX_SALT]*[HEX_OF_BASE64_VARIANT_DIGEST]
```

BTW, I also removed the LOWER() function (because we have other MySQL formats with uppercase hex chars too, like the old PASSWORD() outputs) and I also used LEFT() instead of the first SUBSTR() to make the query both shorter and better understandable.

It seems now to be quite a good compromise between short SQL query and quite nice looking and easy to parse hash format. What do you think ? Could you test it?
Thx

**Comment by jsteube** [comment]
In case you want to play with the binary beta: https://hashcat.net/beta/

**Comment by jedai47** [comment]
The exemple provided by philsmd ie $A$005$452d0e6c4c6079551a4e2378547d025033553032$zGfdIsppFL1sO8o0.WUA8ccu85YoD44Aq0bTE0GFCo4:password didn't work on the latest and beta version of hashcat, as I've got this error: 
```bash
Hashfile '.\mysqlex.hash' on line 1 ($A$005...sO8o0.WUA8ccu85YoD44Aq0bTE0GFCo4): Separator unmatched
No hashes loaded.
```

**Comment by jedai47** [comment]
Hi I was playsing a ctf and my hash is in this format : 
```bash
$A$005$YU*▒i▒x3
               {K=\r
```
I tried retriving as a hex then add the $mysql at the beginning of the hash it then becomes: 
```bash
$mysql$A$005$YU*151869051878330b037b064b3d0d17
```
I then try to exploit it with hashcat and get the following error : 
```bash
Hashfile '.\test2.hash' on line 1 ($mysql...U*151869051878330b037b064b3d0d17): Separator unmatched
No hashes loaded.
```
Any help ?
