### ISSUE TITLE
CP1251 and NTLM / NetNTLM hashes

### ISSUE THREAD

**Issue by s0i37** [hashcat/hashcat#2311]
Hello.
I am trying to crack cyrillics password of `пароль` (means `password`) with hashcat v5.1.0.
But for both NTLM and NetNTLM hashcat can't crack it:
```
hashcat --force -a 0 -m 5600 hash-netntlm.txt /opt/wordlists/ru/words_ru.cp1251.txt
...
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
```
and
```
hashcat --force -a 0 -m 1000 hash-ntlm.txt /opt/wordlists/ru/words_ru.cp1251.txt
...
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
```
In same time `john` can crack it:
```
john --format=netntlmv2 --wordlist=/opt/wordlists/ru/words_ru.cp1251.txt --encoding=cp1251 hash-netntlm.txt
Loaded 1 password hash (netntlmv2, NTLMv2 C/R [MD4 HMAC-MD5 32/64])
Will run 8 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
пароль           (admin)
1g 0:00:00:00 DONE (2020-02-20 16:57) 50.00g/s 409600p/s 409600c/s 409600C/s необходимых..высказывания
Use the "--show --format=netntlmv2" options to display all of the cracked passwords reliably
Session completed
```
and
```
john --format=nt --wordlist=/opt/wordlists/ru/words_ru.cp1251.txt --encoding=cp1251 hash-ntlm.txt 
Loaded 1 password hash (NT [MD4 256/256 AVX2 8x3])
Warning: no OpenMP support for this hash type, consider --fork=8
Press 'q' or Ctrl-C to abort, almost any other key for status
пароль           (admin)
1g 0:00:00:00 DONE (2020-02-20 16:58) 50.00g/s 278400p/s 278400c/s 278400C/s попытался..клавиатуры
Use the "--show --format=NT" options to display all of the cracked passwords reliably
Session completed
```

It seems another flags don't require for hashcat, for example I can crack cyrillics md5 hash:
```
hashcat --force -a 0 -m 0 hash-md5.txt /opt/wordlists/ru/words_ru.cp1251.txt
...749789e4982b0c563f6729aac100a614
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
```

hash-ntlm.txt:
`admin:1000:aad3b435b51404eeaad3b435b51404ee:507e3ee80df7db7c1fdd8d50ae8db606:::`

hash-netntlm.txt:
`admin::win7-vm:647fb0e4d50e9272:2E0172B385DB8B734A3B4839E0E6FD4F:0101000000000000C0653150DE09D2017795CE17D2649E4E000000000200080053004D004200330001001E00570049004E002D00500052004800340039003200520051004100460056000400140053004D00420033002E006C006F00630061006C0003003400570049004E002D00500052004800340039003200520051004100460056002E0053004D00420033002E006C006F00630061006C000500140053004D00420033002E006C006F00630061006C0007000800C0653150DE09D201060004000200000008003000300000000000000000000000003000003044CCB8DE35BBC5CACD42910AEB4C206F9871E10ED2318FEE3D10AC7BB0C2DC0A0010000000000000000000000000000000000009001A0063006900660073002F00310030002E0030002E0030002E003100000000000000000000000000`

hash-md5.txt:
`749789e4982b0c563f6729aac100a614`

**Comment by jsteube** [comment]
It's a known problem. on NTLM you can workaround by using -m 900 in combination with --encoding-from and --encoding-to options.

##
## Hashing algorithms that internally use UTF-16 characters could in special cases lead to false negatives
##

The UTF-16 conversion implementation used within the kernel code is very elementary and for performance
reasons does not respect all complicated encoding rules required to correctly convert, for instance, ASCII
or UTF-8 to UTF-16LE (or UTF-16BE).

The implementation most likely fails with multi-byte characters, because we basically add a zero byte every
second byte within the kernel conversion code.

Was added to docs/limits.txt with https://github.com/hashcat/hashcat/commit/469e13aa0b80978297ccecaf312df960d8a5e223
