### ISSUE TITLE
The program freezes and the result is not correct

### ISSUE THREAD

**Issue by m9ams9a** [hashcat/hashcat#2314]
Tested the new hashcat beta-5.1.0+1697. It was found that the program hangs when working and does not respond to the status, pause, exit buttons. 
Also, when decrypting the mod 21700 issued a password that does not match the desired one. 
I created the hash for the test myself. 
The password was BEXk2xmpZZpME, and the cat issued that password 4245586b32786d705a5a704d45

**Comment by philsmd** [comment]
What is your hardware/setup and drivers etc ?
What operating system do you use ?

You should try to uninstall the drivers and re-install the newest/latest drivers from the vendor homepage.

You should use something like Driver Fusion or Display Driver Uninstaller (DDU) to get rid of all old libs / drivers, also see https://hashcat.net/faq/wrongdriver

We saw the problem of not being able to hit any key in the past and it had always to do with some strange CPU OpenCL Runtime that was still installed (but actually not even needed in those cases) or wrongly configured/installed drivers/systems. Cleanly uninstalling and installing only the needed drivers step by step (not installing what isn't needed first, e.g. only installing the Nvidia driver with every other OpenCL driver cleanly uninstalled) helped in actually **all** of the cases in the past.

or do you use some remote shell/ssh connection etc ?... these shells also often lead to problems if not configured correctly. Do you use cmd on windows or power shell ?

I don't understand your second problem, what command do you run ? What are the command line parameters ? Do you use --outfile-format ?
It seems that 4245586b32786d705a5a704d45 is just the hexadecimal represenation of BEXk2xmpZZpME because $HEX[4245586b32786d705a5a704d45] is the same as BEXk2xmpZZpME

hex to binary/ascii convert in linux:
```
echo 4245586b32786d705a5a704d45 | xxd -r -p
```

I don't think this is a hashcat problem/bug, it seems that you are doing something wrong within your command line (which you didn't mention).

In general, you should give much, much, much more information when reporting a problem... we can't really guess everything you do/have/tried . Why do you not mention the hardware, operating system and command line in the first place ? It should be the most logical and most important thing to do when reporting some problems, at least in my opinion.

Thank you anyway for the report, hopefully it's just an user/driver "problem".
Thx

**Comment by m9ams9a** [comment]
> What is your hardware/setup and drivers etc ?
> What operating system do you use ?
> 
> You should try to uninstall the drivers and re-install the newest/latest drivers from the vendor homepage.
> 
> You should use something like Driver Fusion or Display Driver Uninstaller (DDU) to get rid of all old libs / drivers, also see https://hashcat.net/faq/wrongdriver
> 
> We saw the problem of not being able to hit any key in the past and it had always to do with some strange CPU OpenCL Runtime that was still installed (but actually not even needed in those cases) or wrongly configured/installed drivers/systems. Cleanly uninstalling and installing only the needed drivers step by step (not installing what isn't needed first, e.g. only installing the Nvidia driver with every other OpenCL driver cleanly uninstalled) helped in actually **all** of the cases in the past.
> 
> or do you use some remote shell/ssh connection etc ?... these shells also often lead to problems if not configured correctly. Do you use cmd on windows or power shell ?
> 
> I don't understand your second problem, what command do you run ? What are the command line parameters ? Do you use --outfile-format ?
> It seems that 4245586b32786d705a5a704d45 is just the hexadecimal represenation of BEXk2xmpZZpME because $HEX[4245586b32786d705a5a704d45] is the same as BEXk2xmpZZpME
> 
> hex to binary/ascii convert in linux:
> 
> ```
> echo 4245586b32786d705a5a704d45 | xxd -r -p
> ```
> 
> I don't think this is a hashcat problem/bug, it seems that you are doing something wrong within your command line (which you didn't mention).
> 
> In general, you should give much, much, much more information when reporting a problem... we can't really guess everything you do/have/tried . Why do you not mention the hardware, operating system and command line in the first place ? It should be the most logical and most important thing to do when reporting some problems, at least in my opinion.
> 
> Thank you anyway for the report, hopefully it's just an user/driver "problem".
> Thx
--What is your hardware/setup and drivers etc ?
Microsoft Windows [Version 10.0.14393] x64
NVIDIA 441.66
GPU NVIDIA GTX 1070

--You should try to uninstall the drivers and re-install the newest/latest drivers from the vendor homepage.
I can delete the drivers. On other versions everything works stably hashcat-3.30+50, hashcat-5.1.0, hashcat-4.2.1


--or do you use some remote shell/ssh connection etc ?... these shells also often lead to problems if not configured correctly. Do you use cmd on windows or power shell ?

Connecting via an RDP connection


--I don't understand your second problem, what command do you run ? What are the command line parameters ? Do you use --outfile-format ?

As for the password, I use the Hashcatgui 1.1 blandyuk interface

Start:
hashcat.exe -a 0 --session=2020-02-21 -m 21700 -w 2 --force --status --status-timer=60 --potfile-disable --remove -p : -O --hwmon-disable -d 1,2,3 -o "C:\temp\test_0-11300.txt" --outfile-format=3 -r "Z:\HashcatGUI_1.1beta0\rules\my.rule" "C:\2elect\test.txt" "Z:\dic\final-wordlist.txt" "Z:\dic\mega.txt" "Z:\dic\passwords2.txt" "Z:\dic\dictionary_big.dic"

**Comment by philsmd** [comment]
yeah, so you are using a 3rd party tool (hashcatgui), which furthermore wasn't updated in a long time and therefore is **not** compatible with the latest hashcat beta/release versions. Of course, this is not a hashcat problem. You would need to contact the author of that tool and ask them to update it (or even simplier just use hashcat without GUI).
It is needless to say that if you look at the output of "hashcat --help" you will see that --outfile-format 3 is using hex encoding and therefore your problem of "wrong password" makes no sense at all (it is the correct password, but you told hashcat with --outfile-format=3 to convert it to hexadecimal).

For the other problem, I again suggest re-installing the drivers cleanly and try to use hashcat directly (without RDP connection/shell).

I think both problems are not really hashcat bugs and therefore I would suggest that you @kreol2012 or @jsteube close this issue (only the author or project owner have the permission). Thx

**Comment by m9ams9a** [comment]
It hangs on this algorithm, on other MD5, sha1 and so on everything is normal

**Comment by jsteube** [comment]
Could you please retry with the latest hashcat beta but without the GUI?

**Comment by jsteube** [comment]
Fixed with #2350
