### ISSUE TITLE
?s missing § 

### ISSUE THREAD

**Issue by H4xl0r** [hashcat/hashcat#2316]
the hashcat ?s bruteforce is missing the sign § ? 
or am i wrong ?

**Comment by philsmd** [comment]
It's simple: it is just no ASCII character (0x00-0x7f)
https://en.wikipedia.org/wiki/ASCII (https://en.wikipedia.org/wiki/ASCII#cite_note-54)
https://theasciicode.com.ar/
https://www.asciitable.com/ (https://www.asciitable.com/index/asciifull.gif)

in UTF-8 for instance it must be represented with 2 bytes 0xc2a7
(https://www.utf8-chartable.de/ search for c2 a7)

This means that for cracking a "normal" utf-8 password with § in it you would need to brute-force 2 bytes (?b?b for instance) :(

The good think is that in hashcat we have dictionary attacks with native encoding (and in addition also --encoding-to and --encoding-from features).

I don't think we can/should add § to ?s because it's not 1-byte character in most common encodings (utf-8 etc), of course this depends on the encoding because also 0xa7 could represent § in some specific encoding schemes (e.g. https://en.wikipedia.org/wiki/ISO/IEC_8859-1 , but this is neither ASCII, nor UTF-8)
