### ISSUE TITLE
Hashcat benchmark works incorrect

### ISSUE THREAD

**Issue by ahvahsky2008** [hashcat/hashcat#2335]
`hashcat64.exe --machine-readable --quiet --progress-only --restore-disable --potfile-disable --session=hashtopolis -p "\t" ..\\..\\hashlists\\15 -a 3 -2 ?l -1 ?a -3 !LlPp?d ?3?3?3?3?3?3?3?3  --hash-type=11300  -o ..\\..\\hashlists\\15.out`

**Hashcat 5 show me this result**
![image](https://user-images.githubusercontent.com/8035828/76910135-3b870200-68be-11ea-8671-07c39601df4b.png)
But Hashcat v5.1.0-1745-g434ad763 show me inccorect result
![image](https://user-images.githubusercontent.com/8035828/76910168-56f20d00-68be-11ea-97fa-f3b2f81b52d5.png)

**Comment by philsmd** [comment]
Note: the same discussion is already taken place over the hashcat forum: https://hashcat.net/forum/thread-9050.html

Hint: it's not a good idea in general to just double post everywhere... it has a counter-intuitive effect... even people that would want to help, see that the discussion is already taken place somewhere else or they cant *decide where* to answer and therefore you get even less answers.  Another disadvantages could be that part of the discussion could be taken place in the forum, another suggestion/answer is given here... nobody will "sync" it (and maybe some even don't know that there are identical questions asked and discussions started in the forum). Patience is a virtue and important... otherwise your outcome could and will be worse than you expect (double posting most of the time could be seen as disrespectful and too aggressive).

In general, you should only file a bug/issue on github, if there is a problem that is confirmed and easy to reproduce.... I don't even see any reason why you would test with such a complicated command line (maybe because of hashtopolis, but there is no mention of it and if you tried to just run "hashcat -m 11300 -b" etc ).

**Comment by philsmd** [comment]
I can't really reproduce this problem. In my tests the numbers seem to be correct.

Could you please try with latest code (git or https://hashcat.net/beta/) and/or release version hashcat-6.0.0 from https://hashcat.net/hashcat/ .

Thx
