### ISSUE TITLE
The graphics card temperature is too high

### ISSUE THREAD

**Issue by jimlius** [hashcat/hashcat#2357]
how to easy use at win10

**Comment by jimlius** [comment]
hashcat64.exe: unknown option -- gpu-accel

**Comment by philsmd** [comment]
please ask these type of questions on forum rather than here. This is a bug/problem issue tracker.
Questions like this are already answered, and if not, will be answered on the forum.

in general, you have to use  `hashcat --help` to see the available command line options.

To fix the problem, you would need to improve cooling or airflow or use reference/founder edition cards (or more space between GPUs etc). Another solution could be to use `-w 1`, but this is hardly a solution, just a workaround that reduces speed.

Please close

**Comment by jimlius** [comment]
OK   thanks

**Comment by jimlius** [comment]
Feel the software design is not very friendly, I'm not a professional use this software
