### ISSUE TITLE
attack in stdin mode && GPU

### ISSUE THREAD

**Issue by s0i37** [hashcat/hashcat#2358]
Hello.
I'm trying to bruteforce with hashcat via pipe:
`combinator dict1.txt dict2.txt | hashcat -m 12345 hash.txt`
But in this mode hashcat doesn't use GPU.
Is it possible to use GPU while passwords generate with other tools like `kwp`, `combinator`, etc?

**Comment by philsmd** [comment]
what do you mean by it doesn't use GPU ? how do you know/see that ?

In general, the stdin mode might be slower because of the left and right part of the pipe need to synchronize and one of them could be the bottleneck (for instance the I/O from the command on the left).

Instead of combinator you could test by using -a 1 which is an in-built combinator attack.

I would also suggest to use some amplifier on the right side (e.g. some rules to accelerate the cracking and therefore improve the hash rate, H/s).

I think these type of questions should be better ask on the forum, because these are neither bug/problem reports, nor feature requests... these are just some very common questions that forum users could/willl answer very in-depth/extensively. Indeed, many answers to these questions can just be looked up by using the forum search function.

Should we close this issue (and maybe discuss this further on the forum, if not already answered) ?

**Comment by s0i37** [comment]
Yes. Thanks.
