### ISSUE TITLE
Documented "disable autotune" options are outdated

### ISSUE THREAD

**Issue by mpalmer** [hashcat/hashcat#2361]
`docs/hashcat-plugin-development-guide.md` recommends the use of the following options for development:

* -n 1 -u 1 -T 1: The combination of these three options with these exact values will disable the auto tune.

However, when I attempt to run hashcat with those options (on `master`), I get the following:

```
The manual use of the -n option (or --kernel-accel) is outdated.

Please consider using the -w option instead.
You can use --force to override this, but do not report related errors.
```

As best I can tell, setting `DEBUG=1` in `src/Makefile` is the correct way of disabling autotune these days.  If that's correct, let me know and I can drop a PR to nuke the out-of-date options from the docs.

**Comment by mpalmer** [comment]
Just realised I was misreading the code, and `-n 1 -u 1` is required to get into the `#if defined(DEBUG)` code path I found earlier.  Would a PR for a "hidden" `-w 0` value to replace `-n 1 -u 1` be acceptable?

**Comment by philsmd** [comment]
"outdated" in this case just means that the users should prefer using -w 1, -w 2, -w 3 or -w 4 instead of manually using the -n or -u parameter, in general. This holds true for almost 100% of the use cases.
Of course if you are a developer and try to mess around with the loop/accel manually, you are in a very exceptional situation.... therefore as mentioned in the error message, you have to use
ATTENTION: dangerous command line parameter for the general user
```
--force
```
ATTENTION: dangerous command line parameter for the general user


The --force parameter is used also for other purposes and of course should **NOT** be used by non-expert or non-advanced users or non-devs, but the same holds for manually tuning with -n / -u... it is discouraged to be used by the general user (they should neither use --force, nor -u, nor -n etc).

**Comment by mpalmer** [comment]
Fair enough.  Should I PR a change to indicate that `--force` is a required option for development work, then, alongside the `-n 1 -u 1` settings? (Turns out [you don't need `-T 1`](https://github.com/hashcat/hashcat/blob/master/src/autotune.c#L121), so I'll change that in the PR, too, unless there are objections)
