### ISSUE TITLE
[Windows] hashcat does not read from stdin

### ISSUE THREAD

**Issue by s77rt** [hashcat/hashcat#2362]
Hi,
First, thank you for all your work :)

Seems that there is a problem with hashcat (windows only)
The thing is i'm trying to send some requests to hashcat (such as "r", "s", "p", ...).
hashcat reads those commands from stdin, so i'm feeding the stdin with "r" for resume and "p" for pause and so on...

This works as expected on linux (and probably macos too), however on windows hashcat seems rather listening for key press events on stdin than reading from stdin ([ref](https://github.com/hashcat/hashcat/blob/f96594ef878b367cfa0ef7098ed24f362757528f/src/terminal.c#L467-L505))

i'm asking you if you can make hashcat read from stdin in windows just as it does in linux.

**Comment by philsmd** [comment]
This is actually a feature that hashcat provides/uses: the windows shell input is forced into a special mode that doesn't echo the typed keystrokes and does allow to just type a key without the need of entering the NEWLINE/enter key.

We had several similar request in the forum etc:
- https://hashcat.net/forum/thread-8995-post-47751.html#pid47751
- https://hashcat.net/forum/thread-4754-post-26779.html#pid26779
- https://hashcat.net/forum/thread-4073-post-23198.html#pid23198
- https://stackoverflow.com/questions/21545897/how-to-control-interactive-console-input-output-from-python-on-windows/21595810#21595810

so I would say this is just a very special handling of windows itself, that you need to enable this strange mode to allow the user to interact with hashcat the way it currently does (no echo of the keys pressed and no enter key needed after typing a character).
On Linux/MAC it is very different (because the operating systems do it differently, much more easier on linux/macOS) and therefore you see this behaviour of not being able to just send "s" etc only on windows ...

I think we can't do much here (if we want to keep the interaction hashcat currently has without echo and no enter keys needed) and therefore if you really need to write a wrapper you also have to use this special mode (see stackoverflow link etc).

On the other hand, in most of the cases there aren't really good arguments to send hashcat keystrokes like you suggest to do (in general, there always might be some exceptions)... therefore maybe it would make sense to rethink if other ways to use hashcat from wrappers (e.g. with -s / -l, yes, even with kill etc) might work and even work better (and these might also be much more flexible/stable ways to interact with hashcat). For instance, just look at how hashtopolis interacts with hashcat or similar projects.

What do you think ? Should we close this issue because we can't do much without losing a very important feature (interacting on the command line with hashcat under windows) ?
Thx

**Comment by s77rt** [comment]
@philsmd thanks for your reply.

to give you a better idea the purpose of my request is that i'm working on a cross-platform app that is made to control hashcat using a gui, (nothing similar to hashtopolis, -s and -l have nothing to do here) called hashcat.launcher (80% is done) [demo](https://i.postimg.cc/W4Tfdmg6/hashcat-launcher.gif)

the buttons (pause, resume, quit) are supposed to write to stdin, and it works as expected for linux, but as for windows i though about sending keys to hashcat using windows api (user32.dll) (similar as stackoverflow link solution) this actually works but only for one hashcat session at a time, if there is two sessions it gets dirty. you see hashcat.launcher is made to control many sessions from one place, so it really not possible to rely on keyboard on this one.

having hashcat interactive is not needed in this case, so i would really appreciate if you can add a flag option that's if it's passed windows will read from stdin just like linux, i understand that if that flag is passed a single char is not enough, i need to pass a newline too which is fine.

or if you have any other solution please let me know

**Comment by jsteube** [comment]
Please do not try to use hashcat executable binaries if you want to control hashcat automatically. 

There's a dedicated hashcat API (hashcat.so on Linux and hashcat.dll on Windows). In fact, the hashcat executable is just a wrapper of this API. Please see `src/main.c` main() function in order on how to use it. There's no specific documentation on the API but you will see from the code it's simple to use.

**Comment by s77rt** [comment]
@jsteube 
actually it's not clear on src/main.c main() on how the api is being used. can you please attach an example? (say create a hashcat session with a given list of args)
(just a confirmation: using api, won't require a new compile does it?, the goal is to use official hashcat binaries (+ /beta ))

also does not this seems a little overkill? since hashcat control ('r', 'p', 's') seems there for a while and stable, so it's easier to rely on that?

**Comment by s77rt** [comment]
I have found a solution using windows api, i'm posting the code(golang) here for future ref :)

```
func PostKey(pid int, key uint8) (uintptr, error) {
	var user32 = syscall.NewLazyDLL("user32.dll")

	EnumWindows := func (enumFunc uintptr, lparam uintptr) {
		user32.NewProc("EnumWindows").Call(uintptr(enumFunc), uintptr(lparam))
	}

	var hwnd uintptr
	cb := syscall.NewCallback(func(h uintptr , prm uintptr) uintptr {
		var itr_pid uint32
		itr_pid = 0x0001
		user32.NewProc("GetWindowThreadProcessId").Call(uintptr(h), uintptr(unsafe.Pointer(&itr_pid)))
		if int(itr_pid) == pid {
			hwnd = h
			user32.NewProc("PostMessageW").Call(h, 0x0100, uintptr(key), 0)
			//return 0 // stop enumeration (commented to make sure all windows created by our process get's the message)
		}
		return 1 // continue enumeration
	})
	EnumWindows(cb, 0)
	if hwnd == 0 {
		return 0, fmt.Errorf("No window with pid %d found", pid)
	}
	return hwnd, nil
}
```
Basically it uses the [PostMessageW](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-postmessagew) to send the keys to a window handler  
A window handler is being determined based on it's parent process id, (so we just find the correct handler with the parent process id that match our process id (of hashcat.exe in this case)  
using some helpers: [EnumWindows](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enumwindows) to get all the available windows and [GetWindowThreadProcessId](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowthreadprocessid) to get the process id for each window
