### ISSUE TITLE
--status-json doesnt escape " in target and produces invalid json

### ISSUE THREAD

**Issue by bgmastermind** [hashcat/hashcat#2369]
example target md5($pass.$salt) a9f52a88089bc71e185a2e027a35417c:E#6dsdn[z/K""&|OvS

**Comment by philsmd** [comment]
@Chick3nman maybe you can help here, since you helped a lot to implement the json feature (or basically you implemented all of the JSON support, as far as  I know) ?

Thanks for the report, it should be easily fixable... but we could use this chance to think if there are any other places that need a fix (not just the hash:salt part), or maybe even add a general function and function call to escape every string that is used within a json key/value/attribute

**Comment by Chick3nman** [comment]
Interesting, good spot. I'll take a look and see if this comes up anywhere else as well. As philsmd said, should be an easy fix.

**Comment by philsmd** [comment]
Any news here @Chick3nman ?

I think we discussed this on #hashcat IRC (freenode) for a little bit and came to the conclusion that even if many values are in the JSON output, only the salts could have very special characters (that need to be escaped in JSON).
Furthermore, we discussed that even if the JSON spec has a lot of characters like TABS or new lines that would need to be "translated" to JSON-compatible format (escaped), in our hashcat salts, we kind of only could find a very limited set of chars like quotes and backwards-slashes etc that really need to be converted. This is good news, because it makes the number of changes probably quite manageable/small.

Thx a lot

**Comment by Chick3nman** [comment]
Been busy, haven't had a chance to sit down and fix this. Last I looked at it I was still searching for a concise way to do this that covers everything and isn't messy with the buffer size or anything.

I will need to inject the character escapes for both `module_ctx->module_hash_encode_status != MODULE_DEFAULT` and when it is default, as those two cases both present a hash that may have characters that need to be escaped. The filename and other return conditionals won't have those characters as they are not part of valid file names as far as I know(feel free to correct me on that).

Here is the relevant section of the code where the escapes need to be added to the hash/salt:
https://github.com/hashcat/hashcat/blob/master/src/status.c#L306
