### ISSUE TITLE
[Feature Request] Windows Password Policy

### ISSUE THREAD

**Issue by haroldLuiz** [hashcat/hashcat#2376]
In many occasions i am able to retrieve the Active Directory Password Policy.
As far as i searched for (maybe it is already implemented somewhere on hashcat or on a third-party tool, but i did not find), there isn't a way to feed hashcat with those rules to filter out attempts from wordlists/mask atacks that do not follow those rules.
Implementing those options would be priceless.

Thanks and sory if i am asking something that already exists.

Update, i tryed developing a third-part tool, but Stdin is too slow, and the wordlist would be gigantic. The only solution appears to be implemeting it on hashcat.

**Comment by philsmd** [comment]
I'm not sure if hashcat could help much here. I think PACK from https://github.com/iphelix/pack with policygen could help a lot and in general a more clever prepared input to hashcat. Filtering is also slow and often kind of impossible to do in a reasonable fast way on GPU (it's heavily parallelized, any branches and conditions are very bad etc).

You could prepare masks with PACK or use pre-computed/prepared/filtered word lists etc etc etc... this would probably be much clever and slower (it also get rid of some I/O if your dicts are already smaller/filtered etc).

I think this is kind of a general discussion and maybe you could try to ask some good strategy on the hashcat forum instead of this github bug tracker (which is better suited for problem fixes and new algorithms or implement already accepted and very detailed new approaches/strategies/attack-modes etc ?). I think asking this on the hashcat forum wouldn't hurt... maybe somebody has already a good strategy to address some of your requirements ?
I think we should close this issue for now, could you close it @haroldLuiz and ask this on the hashcat forum ? Thx
