### ISSUE TITLE
cannot find an OpenCL ICD loader Library

### ISSUE THREAD

**Issue by Goldleman** [hashcat/hashcat#2380]
~# `hashcat -I`
hashcat (v5.1.0) starting...

cannot find an OpenCL ICD loader Library.

You are probably missing the native OpenCL runtime or driver for your platform.

```
* AMD GPUs on Linux require this runtime and/or driver:
   "RadeonOpenCompute (ROCm)" Software Platform (1.6.180 or later)
* Intel CPUs require this runtime and/or driver:
   "OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)
* Intel GPUs on Linux Require this runtime and/or driver:
   "OpenCL 2.0 GPU Driver Package for Linux" (2.0 or later)
*  NVIDIA GPUs require this runtime and/or driver
   "NVIDIA Driver" (367.x or later)
```

**Comment by philsmd** [comment]
I think this hashcat forum question is related https://hashcat.net/forum/thread-9178.html ? Is this you on the forum ?

I think the setup is quite strange here... why would you use linux on macOS ? what software do you use for virualization (vmware, parallels, bootcamp etc ?) ?

I don't think it's a good idea to use this virtualizations, because they come with a lot of problems... at least I would say, that only experience hashcat users could play with them, but not really report problems if the virtualization doesn't work out-of-the-box (it could be just a problem with your configuration / virtualization, not a hashcat issue).

For the remaining part, I already explained in the hashcat forum, that you would need to cleanly install the drivers (https://hashcat.net/faq/wrongdriver) and in some cases also install
```
ocl-icd-libopencl1 opencl-headers clinfo
```
as explained in the forum...


I think this is not really a hashcat source code problem and therefore I think that we should close this and get more information about why and how you do the virtualization etc in the above mentioned forum thread. @Goldleman, please do not forget to close this issue. thx

**Comment by philsmd** [comment]
please be aware that this post was changed and that the original post was stating "**I Am Using Linux on OS X**" .
Screenshot of original post:

![macos](https://user-images.githubusercontent.com/921533/82794021-1be9f800-9e72-11ea-9923-8de2db754387.jpg)

now my comment seems to be out of context, completely unrelated and wrong.

@Goldleman could you please answer the questions above ? Otherwise we need to mark the github issue as **invalid** and close it

**Comment by Goldleman** [comment]
> Acho que esta questão do fórum hashcat está relacionada https://hashcat.net/forum/thread-9178.html ? É você no fórum?
> 
> Eu acho que a configuração é bem estranha aqui ... por que você usaria o linux no macOS? qual software você usa para virualização (vmware, paralelos, bootcamp etc?)?
> 
> Não acho que seja uma boa ideia usar essas virtualizações, porque elas vêm com muitos problemas ... pelo menos eu diria que apenas os usuários com hashcat podem brincar com eles, mas realmente não relatam problemas se a virtualização não funciona de imediato (pode ser apenas um problema com sua configuração / virtualização, não um problema de hashcat).
> 
> Na parte restante, eu já expliquei no fórum hashcat, que você precisaria instalar os drivers corretamente ( https://hashcat.net/faq/wrongdriver ) e, em alguns casos, também instalar
> 
> ```
> ocl-icd-libopencl1 opencl-headers clinfo
> ```
> 
> como explicado no fórum ...
> 
> Eu acho que isso não é realmente um problema de código-fonte hashcat e, portanto, acho que devemos encerrar isso e obter mais informações sobre por que e como você faz a virtualização etc. no tópico do fórum acima mencionado. @ Goldleman , não se esqueça de encerrar esta questão. valeu



> Acho que esta questão do fórum hashcat está relacionada https://hashcat.net/forum/thread-9178.html ? É você no fórum?
> 
> Eu acho que a configuração é bem estranha aqui ... por que você usaria o linux no macOS? qual software você usa para virualização (vmware, paralelos, bootcamp etc?)?
> 
> Não acho que seja uma boa ideia usar essas virtualizações, porque elas vêm com muitos problemas ... pelo menos eu diria que apenas os usuários com hashcat podem brincar com eles, mas realmente não relatam problemas se a virtualização não funciona de imediato (pode ser apenas um problema com sua configuração / virtualização, não um problema de hashcat).
> 
> Na parte restante, eu já expliquei no fórum hashcat, que você precisaria instalar os drivers corretamente ( https://hashcat.net/faq/wrongdriver ) e, em alguns casos, também instalar
> 
> ```
> ocl-icd-libopencl1 opencl-headers clinfo
> ```
> 
> como explicado no fórum ...
> 
> Eu acho que isso não é realmente um problema de código-fonte hashcat e, portanto, acho que devemos encerrar isso e obter mais informações sobre por que e como você faz a virtualização etc. no tópico do fórum acima mencionado. @ Goldleman , não se esqueça de encerrar esta questão. valeu
