### ISSUE TITLE
Hashcat speed dropped to 415 H/S

### ISSUE THREAD

**Issue by syarz** [hashcat/hashcat#2381]
Hi, I'm trying to crack rar5 hash using hashcat 4.0 on windows 10 but the problem is cracking speed is quite slow. It was working fine a few days ago and speed was 300 kh/s but now I can't get the speed more than 415 h/s and it shows estimated time 9 hours for rockyou.txt. which is 133mb in size. I even tried with hashcat 5.0 but the same issue.
"hashcat -m 13000 -a 0 hash.txt -w 3 rock you.txt -o crack.txt"

I'm using Windows 10 Pro x64 
Nvidia 630m 2gb
RAM 8gb

**Comment by philsmd** [comment]
why do you test with hashcat 4.0 ?

it's outdated since ages... please use at least the latest release version or even better... test with the latest beta version from https://hashcat.net/beta/

Normally when we see some mobile GPUs being used e.g. your NVIDIA 630m, the first thing that comes to our minds is that you are using a laptop with very bad cooling/fan and therefore it is throttling ? Did you try with another system that isn't a laptop and that has good airflow / cooling ?


I think there are so many details that you need to provide about your system and when exactly this started happening and what you did to the system etc etc ? I think this is not really a hashcat source code problem and therefore it would be much better to ask questions like this with very detailed information about what you are trying to do and what you have and what happened to your system etc (and always use latest version of hashcat)  ... in the hashcat forum instead.

hashcat github issues are meant to report bugs/problems with the source code and or request new feature or algorithms. it's better to ask user questions like yours in the hashcat forum. THx

BTW: please do not forget to close the issue after you posted the very detailed explanation about your problem on the hashcat forum (https://hashcat.net/forum/) ? thx

**Comment by syarz** [comment]
Thanks for the quick response and thank you for the compliment about my laptop & yes 4.0 is outdated that's why I have downloaded the latest release which is 5.x (that's why I mentioned "I even tried with hashcat 5.0 but the same issue").
I have installed nothing and made no changes to my laptop but it got slow for some unknown reason which I can't figure out why. 

I'm just trying to crack a simple rar5 hash & it was working fine a day ago when this started happening. The cracking speed dropped from  300/400 MH/s to 300/400 H/s and it's not that I have been running hashcat for hours so GPU got heated up and the speed dropped consequentially. I get 400 h/s even if everything is cooled down.

No, I haven't tried any other system as this is the only system I got. I can understand this is not the hashcat bug/issue, I'll make another one and gonna post it on the user forum. Thanks
