### ISSUE TITLE
OPTS_TYPE_PT_HEX and test.sh

### ISSUE THREAD

**Issue by seger672** [hashcat/hashcat#2385]
If a module has the `OPTS_TYPE_PT_HEX` flag set, the candidate will be parsed as hexadecimal, but won't be converted back for output, and test.sh will mark them as "hash:plains not matched in output".

It seems like either the frontend code should be changed to convert the internal password back to the supplied format (in this case HEX[00ff] -> 00ff), or test.sh should changed to something like this:

    if [ "${pass_only}" -eq 1 ]; then
      search1=":${pass}"
      search2=":HEX[${pass}]"
    else
      search1="${hash}:${pass}"
      search2="${hash}:HEX[${pass}]"
    fi

    echo "${output}" | grep -F "${search1}" >/dev/null 2>/dev/null
    r1="${?}"
    echo "${output}" | grep -F "${search2}" >/dev/null 2>/dev/null
    r2="${?}"

    if [ "${r1}" -ne 0 -a "${r2}" -ne 0]; then

        ret=10

    fi

**Comment by philsmd** [comment]
so as far as I understand this is not an "acute" problem, but a theoretical problem with future modules that **could** use OPTS_TYPE_PT_HEX in the future.

For now we do NOT have any module that uses OPTS_TYPE_PT_HEX directly already:
```
grep -r OPTS_TYPE_PT_HEX src/modules/
```

The main reason why we currently do not use OPTS_TYPE_PT_HEX in modules is that we expect from the user to use --hex-wordlist or --hex-charset etc to supply the correct input for instance for old office collider mode hashes or DES/3DES hashes etc...

The problem if you force the input to be hex, is that hashcat has currently no way to disable it.... i.e. there is no --hex-wordlist-disable flag etc... so the dict input always needs to be hex-converted.... and this of course doesn't make much sense for most of the hashes, because hashcat is a [b]password[/b] recovery tool that expects some (most of the time human readable) passwords ( I know there could be exceptions for instance as you can see we have DES keys and collider values etc as exceptions already, but even for those we do NOT restrict the input to be HEX-only, because otherwise the user couldn't choose to perform a non-hex test or supply a non-hex-converted password).

Is there any reason why you would need this ? I am correct in assuming that this is not an issue that is already present (e.g. that current test runs fail with the current hashcat code, master branch), but this could  potentially/theoretically be a problem with future modules, that for some strange reason try to force HEX dictionaries ?

Can you elaborate why HEX need to be forced and we can't just use --hex-charset / --hex-wordlist (or just dictionaries with $HEX[]) ?

btw your diff is probably NOT 100% currect, because you miss the "$" before the "HEX", e.g. it must be $HEX[...]  .

It would also be weird if the user supplies the input with just hex (e.g. 00112233), but the output is $HEX[00112233]... so I think there must be more discussion and more time spend thinking about the input/output format !?

Thank you so much

**Comment by seger672** [comment]
In that case, accepting input as ASCII and telling users to use the $HEX[] notation seems like the best way to do it, thanks.

But why keep the OPTS_TYPE_PT_HEX feature at all? It's not used, and even for DES, users could just use $HEX[00112233] syntax instead.
