### ISSUE TITLE
uses gpu for 1 second and then does not use it 

### ISSUE THREAD

**Issue by mat43211** [hashcat/hashcat#2386]
hashcat64.exe -m 2500 -a3 --opencl-device-type 1,2 --hwmon-disable C:\Users\matthew\Desktop\hashcat-5.1.0\1.hccapx -1 abcedf0123456789 ?1?1?1?1?1?1?1?1?1
this is my command
it runs fine 
but if I look on task manager the gtx 1060 is not being used like for the first second it goes to 100 percent usage and after it is not used at all. there are no errors

**Comment by philsmd** [comment]
what is your other device ? what happens if you only try with -D 2 (default) or only try with -D 1 ?

do you use a laptop ? maybe cooling/throttling problem ?

Does this also happen with other hash types e.g. MD5 etc ? Is the benchmark (-b) speed good / normal ?

as you can see we would need much more information here

could you try the example hash from https://hashcat.net/wiki/example_hashes (hashcat.hccapx) with the following command:
```
hashcat64.exe -m 2500 -a 3 -w 3 hashcat.hccapx ?a?a?a?a?a?a?a?a
```
and see how good the speed is ? then test with only -D 1, then both ? maybe your CPU/GPU combination is just not good enough to work at the same time (we experienced this problem especially if you use OpenCL with NVIDIA GPUs instead of the newly supported CUDA backend with hashcat beta from https://hashcat.net/beta/, you would need to install CUDA SDK for the beta, there is a NVIDIA spinning loop which makes the combo of GPU/CPU kind of useless sometimes, if the driver uses 100% of the CPU already even if not computing hashes on the CPU.... just the driver spinning loop, see --spin-damp parameter)

could you try if the beta from https://hashcat.net/beta/ fixes your "problem" ?

**Comment by philsmd** [comment]
I actually got some input from another hashcat user here that told me that the windows task manager is basically unable to understand the work/usage by most (or almost every) OpenCL program.

That means that the windows task manager, even if it has a GPU tab to show the usage, only reports the usage of well-known programs like media players or video editing software etc... it won't work for most other OpenCL programs.

To test the actual usage you would rather use the built-in hashcat "Util" percentage value (in the status prompt) or some (GPU) tuning software like GPU-Z or afterburner etc... they will most likely get the information correclty and directly from the GPU etc.

The values reported by the task manager are just wrong, because microsoft windows doesn't consider hashcat a software using GPU or some other strange problem like this. :(

please close this issue (only original author or repository owner/admin can close issues here)

**Comment by oam7575** [comment]
Depending on windows version Win 7 / Win 8 / Win 10 the task manager will display GPU usage differently.

In Windows 10 you usually need to change the GPU section the task manager --> Performance tab to display the "Cuda" usage of the GPU.

Running the following command
E:\hashcat\hashcat-6.0.0>hashcat.exe -a 0 -m 3200 --opencl-device-type 1,2 --hwmon-disable ..\hashcat-5.1.0\hp1920s.txt ..\wordlists\rockyou.txt

Shows ~80% Cuda usage ; with ~0% usage for all other GPU functions.

![hashcat_cuda](https://user-images.githubusercontent.com/18411503/85213212-a274f500-b39e-11ea-9b75-0d33416f042b.PNG)

**Comment by philsmd** [comment]
Thanks for the info @oam7575 . This is very appreciated information.

Anyway, I still think there is nothing we can do here and I suggest that @mat43211 is closing this issue as soon as possible, since this is just a windows task manager question we have no influence about (it's a microsoft thing) . Thx
