### ISSUE TITLE
Driver temperature threshold met on GPU #... (Win, v5.1.0)

### ISSUE THREAD

**Issue by ilya7zz** [hashcat/hashcat#2396]
Hello!
Hashcat version 5.1.0
8 gtx 970, afterburner temperature limit of 60 degrees.
OS Win 10 or Win 7, the same. 1 GPU or 4 is the same.
options used: set opt=-m 2500 -w 4 --force
speed per 1 GPU 180-200 kH/s
Nicehash works great 24/7 ... 4 years :)
On screen every second random gpu:
Driver temperature threshold met on GPU # 1.
Driver temperature threshold met on GPU # 1.
Driver temperature threshold met on GPU # 1.
Driver temperature threshold met on GPU # 3.
Driver temperature threshold met on GPU # 4.
Driver temperature threshold met on GPU # 4.
...
--hwmon-disable — only way out?..
Tell me please.

![hashcat-err-temp](https://user-images.githubusercontent.com/53345402/81625187-ca1c8900-9400-11ea-892d-9ea1bd525cfa.png)

**Comment by philsmd** [comment]
why set a such a low limit ?

you can't really compare mining with hash cracking... they are doing very different tasks in a very different way.

It's very strange to set a low limit and ask why the low limit is reached so fast... try to not set it that low or try other ways to reduce temperature (cooling/airflow/undervolting etc).

I don't see any hashcat problem/bug here...

This type of questions are also better suited for the hashcat forum... this is not really a source code bug/problem, but just an user/usage question. Can we continue this discussion on the hashcat forum on https://hashcat.net/forum/ ? Please do not forget to close this issue. Thx

**Comment by ilya7zz** [comment]
Low? I have extensive experience in servicing servers, 60 degrees is ideal :) In this server air conditioning is weak, in winter +10 in summer +30. The voltage of all GPUs is set to minimum. Overclocking tips do not apply to your question.
The question was about another.
"It's very strange to set a low limit and ask why the low limit is reached so fast ..." - I did not ask about the limit! What is the relationship between 60 degrees of the map and an error in the program that does not see the temperature and displays a message every second? The program should warn above 90. The temperature does not exceed 60.
I don’t understand what the problem is.
The forum did not let me in, I wrote here :)

**Comment by philsmd** [comment]
The nvidia driver is reporting throttling problems due to the limit of the temperature (your profile limits) being reached. The driver therefore notifies hashcat that the card is throttling, hashcat will get this info and pass it to the user.

I think that is exactly working as it should be (but I might be wrong, but I don't see why we shouldn't notify the user if the nvidia driver gives us this alarm)... maybe there are other means to keep the temperature low without setting the "throttling limit" so low that it alerts hashcat of a problem.

Isn't there any other way with the profile to set/keep a target temperature without reaching the limits ? I'm not too sure about this, but again... this really is a general discussion that should be asked on the forum. I don't see any obvious hashcat bug here (but I might be wrong)
