### ISSUE TITLE
Does hashcat support snmp v3 password cracking?

### ISSUE THREAD

**Issue by MG-302** [hashcat/hashcat#2401]
There are authentication password and encrypted password in snmp v3. Does hashcat support the decoding of these passwords?

What should I do if I want to develop the hashcat algorithm library? Is there any instructions for source code development?

**Comment by philsmd** [comment]
Hey, yeah it's not supported yet.

John The Ripper (JTR) seems to support it with https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/snmp_fmt_plug.c

Would be nice if you could do some research (or even develop a short python/perl proof of concept, POC, script) to show how the algorithm works internally and how "hashes" are generated or cracked.

It seems also that there are some variants and the JTR format lists these hashing components: HMAC-MD5-96/HMAC-SHA1-96 32 .

What do you use to extract these hashes ? just wireshark ? it also seems the network2john.lua file has some SNMP hash extraction functions. Is this the way how you normally extract these hashes ?
maybe other network dumping/sniffing tools, like metasploit/nmap etc, are also able to recognize/generate/extract these hashes ? Is there any common format (otherwise I would suggest to use the JTR, without file names, as we do most of the time in cases we do not already have the algorithm implemented in hashcat) ?

and yeah, we have a guide for developers to implement new hash types/algorithms: https://github.com/hashcat/hashcat/blob/master/docs/hashcat-plugin-development-guide.md
This guide is also quite new... would be great if you could have a look at it and maybe help as with both improving/double-checking the guide and help implementing the SNMP hash type. That would be fantastic. (but note: the guide is not intended to be a tutorial. I think there are some - older - blog posts that explain step-by-step how some users added a hash... but we can't really recommend them here... they might very quickly get out of date etc... so we want to stick to the dev guide).
Thank you very much

**Comment by matrix** [comment]
@MG-302, I'm working on your request :)



```
OpenCL API (OpenCL 1.2 (May  7 2020 00:10:14)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz, 8128/8192 MB (2048 MB allocatable), 4MCU
* Device #2: Iris, skipped

Benchmark relevant options:
===========================
* --opencl-device-types=1
* --optimized-kernel-enable

Hashmode: 25200 - SNMPv3 HMAC-SHA1 (Iterations: 1)

Speed.#1.........:      541 H/s (2.82ms) @ Accel:1024 Loops:1 Thr:1 Vec:4
```

**Comment by matrix** [comment]
I have implemented 3 modules, based on the code of John The Ripper.
Following the benchmark (pure kernels):

```
OpenCL API (OpenCL 1.2 (May  7 2020 00:10:14)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz, 8128/8192 MB (2048 MB allocatable), 4MCU
* Device #2: Iris, skipped

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 25000 - SNMPv3 HMAC-MD5 or HMAC-SHA1 (Iterations: 1)

Speed.#1.........:      404 H/s (4.51ms) @ Accel:1024 Loops:1 Thr:1 Vec:4

Hashmode: 25100 - SNMPv3 HMAC-MD5 (Iterations: 1)

Speed.#1.........:      862 H/s (1.46ms) @ Accel:1024 Loops:1 Thr:1 Vec:4

Hashmode: 25200 - SNMPv3 HMAC-SHA1 (Iterations: 1)

Speed.#1.........:      551 H/s (2.82ms) @ Accel:1024 Loops:1 Thr:1 Vec:4

```

**Comment by jsteube** [comment]
We need to wait for @matrix to fix the issue described in the comments of the PR. If they are fixed we can merge it.

**Comment by matrix** [comment]
Hi, we can close this issue.
Bonus: a modified tool from Applied Risk to extract SNMPv3 hashes in hashcat format here https://github.com/matrix/snmpv3brute
