### ISSUE TITLE
hashcat破解出的密码为什么显示的hex形式？

### ISSUE THREAD

**Issue by ly20180228** [hashcat/hashcat#2409]
前面部分忽略.......6911a0c7a980ac36b4a1fa3d50:$HEX[4a59696e673035323732313a2926]

**Comment by philsmd** [comment]
please only use english on this github issue tracker . we can't be able to speak all the languages of this world. it would be best to only have english issues/posts on hashcat's github/forum . thank you very much for understanding.

Furthermore, questions like this should belong to the forum. It's not a hashcat source code problem/bug/error. You are just asking a user question (which was already answered dozens of times on the hashcat forum).

if $HEX[...] is within the output of hashcat, it means that the part between the square brackets is encoded with hex... you need to hex decode it. for the output file, you could also use `--outfile-autohex-disable` (but it's not allowed/possible for the hashcat.potfile).

The password is encoded with hexadecimal characters because it contains the separator character `:` which is normally used to delimit hashes from salts and also user names from hashes. If it wasn't encoded with hex in the potfile, the potfile support wouldn't work correctly (because otherwise hashcat would need to guess a lot and probably fail to do so on where to split the hashes and salts etc).

Thank you very much for understanding and please do not forget to **close this issue**.

---

BTW: almost forgot to mention, the password in your example is just `JYing052721:)&`
