### ISSUE TITLE
Minimize CPU usage

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#2411]
How to minimize CPU usage when hashcat working ? GPUs show ~70% of potential hashspeed, CPU loaded 100%.

**Comment by philsmd** [comment]
more details needed. What hardware ? which devices are in use (CPU and GPU enabled ? ) ? which drivers (driver version, OpenCL vs CUDA, etc etc) ? Which hashcat version ? beta ? Which hash type you are running ?

I think problem reports like this, especially if they do not mention any technical details or explanation of what you are doing, what you have, what you are trying to do, if it worked before, what changed, etc etc etc should be better discussed on the hashcat forum, instead of this bug/error tracker on github.
This seems to be either an user problem or a configuration/setup problem... not really a hashcat source code bug (at least it's not clear what your main problem even is). Please close and explain every detail on the hashcat forum. Thx
