### ISSUE TITLE
-m 2500 fails on amd radeon rx 590

### ISSUE THREAD

**Issue by alexmo1997** [hashcat/hashcat#2426]
I am on Arch Linux and have xf86-video-amdgpu (19.1.0-2), opencl-mesa (20.0.7-3) and opencl-amd (20.10.1048554-1) installed.
Running on -m 0 works fine with both opencl versions.
But running -m 2500 gives me this error message:
```
* Device #1: ATTENTION! OpenCL kernel self-test failed.

Your device driver installation is probably broken.
See also: https://hashcat.net/faq/wrongdriver

Aborting session due to kernel self-test failure.

You can use --self-test-disable to override this, but do not report related errors.
```
I'm pretty sure I did everything right while installing the drivers, so I think this is a hashcat issue.

**Comment by philsmd** [comment]
hey,

why do you believe that this is the right way of installing the drivers ? The requirements on https://hashcat.net/hashcat only talk about ROCm for AMD GPUs... I don't think mesa or anything like this is even close to the correct configuration/setup.

I would instead suggest to try with beta from https://hashcat.net/beta (you didn't even mention the hashcat version you use) and the ROCm driver... before that you need to cleanly uninstall all these open-source drivers and packages (also refer to https://hashcat.net/faq/wrongdriver ).

Another problem here is that this doesn't really seem to be a source code bug/problem, but rather just an user question or configuration/installation issue... These types of problems are normally better suited for the hashcat forum.. because we can't really do anything here except of explaining that it's the wrong way of installing the drivers etc (again this is something that several hashcat forum threads already try to explain: https://hashcat.net/forum/ ).

Thank you very much for you understanding. and hopefully with the correct requirements and new hashcat beta version etc everything is working perfectly fine for you. Have a nice day. Thx
(and do not forget to close this issue, thank you very much)

**Comment by alexmo1997** [comment]
> why do you believe that this is the right way of installing the drivers ? The requirements on https://hashcat.net/hashcat only talk about ROCm for AMD GPUs... I don't think mesa or anything like this is even close to the correct configuration/setup.

I didn't look into that page, thanks for the link, I just refered to https://wiki.archlinux.org/index.php/GPGPU#OpenCL_Runtime. I just included mesa to also tests it, but I overlooked the rocm one,

> I would instead suggest to try with beta from https://hashcat.net/beta (you didn't even mention the hashcat version you use) and the ROCm driver... before that you need to cleanly uninstall all these 
open-source drivers and packages (also refer to https://hashcat.net/faq/wrongdriver ).

Yeah, sorry for that, I used 5.1.0 out of the arch repos.

> Thank you very much for you understanding. and hopefully with the correct requirements and new hashcat beta version etc everything is working perfectly fine for you. Have a nice day. Thx
> (and do not forget to close this issue, thank you very much)

Ok, tried that now. With the hashcat 5.1.0, I get `clCreateCommandQueue(): CL_OUT_OF_HOST_MEMORY`, but I suppose this is already fixed given that it works with the beta you linked, so I'll close this now.

**Comment by mj789-98** [comment]
use --deprecated-check-disable
