### ISSUE TITLE
No devices found/left

### ISSUE THREAD

**Issue by Goldleman** [hashcat/hashcat#2428]
~# `hashcat -I `
hashcat (v5.1.0) starting...

`* Device #1: Not a native Intel OpenCL runtime. Expect massive speed loss.`
`You can use --force to override, but do not report related errors.`

**No devices found/left**

Started: Sat May 30 08:58:07 2020
Stopped: Sat May 30 08:58:07 2020

**Comment by philsmd** [comment]
What hardware do you have ? What driver you have installed ? We need more details

You could also test with beta from https://hashcat.net/beta/ (but it won't fix a problem with missing or wrong drivers etc).

Do you only have an Intel GPU ?

We always advise users to search for answers or if nothing can be found ask questions like this in the hashcat forum, it's much more suited for these type of questions... because these github issues are used as a bug/problem tracker, not a general forum for user questions (or installation/setup/configuration problems). Thx

**Comment by Goldleman** [comment]
~# `clinfo`
```
Platform Name                Portable Computing Language                   
Number of devices            1
Device Name                  pthread-Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
Device Vendor                GenuineIntel
Device Vendor ID             0x6c636f70
Device Version               OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-ivybridge
Drive Version                1.2
Device OpenCL C Version      OpenCL C 1.2 pocl
Device Type                  CPU

```

I think i have to install the drivers, but I don't know how to install.

**Comment by Goldleman** [comment]
> Qual hardware você tem? Qual driver você instalou? Precisamos de mais detalhes
> 
> Você também pode testar com a versão beta em https://hashcat.net/beta/ (mas não corrigirá um problema com drivers ausentes ou errados, etc.).
> 
> Você tem apenas uma GPU Intel?
> 
> Sempre aconselhamos os usuários a procurar respostas ou, se nada for encontrado, faça perguntas como esta no fórum hashcat, é muito mais adequado para esse tipo de perguntas ... porque esses problemas no github são usados ​​como rastreador de bugs / problemas, não como fórum geral para perguntas do usuário (ou problemas de instalação / instalação / configuração). Valeu

**Comment by fran-dev-front** [comment]
sudo rmmod nvidia_uvm
sudo modprobe nvidia_uvm
