### ISSUE TITLE
[Request] MD5BASE64MD5 Algorithm implemention

### ISSUE THREAD

**Issue by netsecprogrammer** [hashcat/hashcat#2445]
Hi Hashcat Team,

I would like to request a hashcat implementation for MD5BASE64MD5.

Thank you!

**Comment by philsmd** [comment]
what is the exact algorithm here
Is it:
```
md5_hex (base64 ( md5_bin ($pass)))
```

Is there no salt involved ?
Any examples with hash:pass pairs ?

Where is this algorihtm used in ? Is this used in some popular software or CMS ?

Please also see this guide on what is needed and how to request some new algorithms/features: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this

Any other good argument why this should be added ? Can a lot of hashcat users profit from this algorithm because it's widely used ? where exactly ? where are these hashes from etc ?

**Comment by philsmd** [comment]
any update here ?

We would at least need to know what algorithm you are requesting here. How can be implement something that we are not even sure what exactly we should code ?

Please give more details about this feature request, otherwise we would need to mark this github issue as INVALID and close it.
Thx

**Comment by jsteube** [comment]
No response from OP, feel free to reopen with new information.
