### ISSUE TITLE
Hascat always crash in my Windows 10

### ISSUE THREAD

**Issue by anakmetro** [hashcat/hashcat#2446]
hashcat always crach, i was try with v5.1.0 and beta version too.
i was disable WDDM recovery :
https://hashcat.net/wiki/doku.php?id=timeout_patch

hashcat.exe -I
hashcat (v6.0.0) starting...

CUDA Info:
==========

CUDA.Version.: 11.0

Backend Device ID #1 (Alias: #3)
  Name...........: GeForce RTX 2080 Ti
  Processor(s)...: 68
  Clock..........: 1650
  Memory.Total...: 11264 MB
  Memory.Free....: 9248 MB

Backend Device ID #2 (Alias: #4)
  Name...........: GeForce GTX 1080
  Processor(s)...: 20
  Clock..........: 1898
  Memory.Total...: 8192 MB
  Memory.Free....: 6769 MB

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: NVIDIA Corporation
  Name....: NVIDIA CUDA
  Version.: OpenCL 1.2 CUDA 11.0.186

  Backend Device ID #3 (Alias: #1)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: GeForce RTX 2080 Ti
    Version........: OpenCL 1.2 CUDA
    Processor(s)...: 68
    Clock..........: 1650
    Memory.Total...: 11264 MB (limited to 2816 MB allocatable in one block)
    Memory.Free....: 9216 MB
    OpenCL.Version.: OpenCL C 1.2
    Driver.Version.: 451.22

  Backend Device ID #4 (Alias: #2)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: GeForce GTX 1080
    Version........: OpenCL 1.2 CUDA
    Processor(s)...: 20
    Clock..........: 1898
    Memory.Total...: 8192 MB (limited to 2048 MB allocatable in one block)
    Memory.Free....: 6720 MB
    OpenCL.Version.: OpenCL C 1.2
    Driver.Version.: 451.22

always crash when use -d 1 (GeForce RTX 2080 Ti GPU/OCL)

**Comment by philsmd** [comment]
I would suggest that you start with this guide on how to cleanly install the drivers: https://hashcat.net/faq/wrongdriver

It also seems that this is not really a hashcat bug/problem, but just a question about how to install/configure your system/drivers. These type of questions are better suited for the hashcat forum. We use the github issue tracker mainly for source code bugs/problems, where we can add/delete/change (part of) the hashcat source code to improve it.

There are many things you could try, including re-installing the drivers or even operating system (probably not needed), but also testing just with OpenCL instead of both OpenCL and CUDA etc etc

Do not forget to close the issue if you agree to move this to the hashcat forum or even already have fixed it by (cleanly) re-installing the driver etc. Thx
