### ISSUE TITLE
macOS AMD can't use multiple GPUs

### ISSUE THREAD

**Issue by singe** [hashcat/hashcat#2460]
(from https://github.com/hashcat/hashcat/issues/2083#issuecomment-645307417)

Looks like the latest 6.0.0 release and commit prevents macOS from using both GPUs simultaneously. I did a quick check, and applying the same patch @matrix did earlier to allow --force fixes it, so there's no technical reason why it shouldn't work, just looks like an error in the selection logic I haven't had time to dig into yet.

The diff:

```
diff --git a/src/backend.c b/src/backend.c
index 80fdbb38..e0c9246d 100644
--- a/src/backend.c
+++ b/src/backend.c
@@ -6606,7 +6606,7 @@ int backend_ctx_devices_init (hashcat_ctx_t *hashcat_ctx, const int comptime)
     // using force here enables both devices, which is the worst possible outcome
     // many users force by default, so this is not a good idea
 
-    //if (user_options->force == false)
+    if (user_options->force == false)
     //{
     backend_ctx_find_alias_devices (hashcat_ctx);
     //{
```

For completeness sake, here's the output from hashcat 5.1.0, 6.0.0 and 6.0.0 with my patch and --force:

5.1.0 (homebrew)

```
/usr/local/Cellar/hashcat/5.1.0/bin/hashcat -m1000 --benchmark
hashcat (v5.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz, skipped.
* Device #2: Intel(R) HD Graphics 530, 384/1536 MB allocatable, 24MCU
* Device #3: AMD Radeon Pro 455 Compute Engine, 512/2048 MB allocatable, 12MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 1000 - NTLM

Speed.#2.........:   739.5 MH/s (32.47ms) @ Accel:128 Loops:32 Thr:256 Vec:1
Speed.#3.........:  4081.5 MH/s (95.39ms) @ Accel:512 Loops:256 Thr:256 Vec:1
Speed.#*.........:  4821.0 MH/s

Started: Wed Jun 17 13:01:44 2020
Stopped: Wed Jun 17 13:01:55 2020
```

```
6.0.0

./hashcat -m1000 --benchmark
hashcat (v6.0.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL API (OpenCL 1.2 (May  3 2020 20:15:19)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz, skipped
* Device #2: Intel(R) HD Graphics 530, 1472/1536 MB (384 MB allocatable), 24MCU
* Device #3: AMD Radeon Pro 455 Compute Engine, skipped

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 1000 - NTLM

Speed.#2.........:   669.5 MH/s (73.83ms) @ Accel:1024 Loops:256 Thr:8 Vec:1

Started: Wed Jun 17 13:00:49 2020
Stopped: Wed Jun 17 13:00:54 2020
```

6.0.0 patched with --force
```
./hashcat -m1000 --benchmark --force
hashcat (v6.0.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

You have enabled --force to bypass dangerous warnings and errors!
This can hide serious problems and should only be done when debugging.
Do not report hashcat issues encountered when using --force.
OpenCL API (OpenCL 1.2 (May  3 2020 20:15:19)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz, skipped
* Device #2: Intel(R) HD Graphics 530, 1472/1536 MB (384 MB allocatable), 24MCU
* Device #3: AMD Radeon Pro 455 Compute Engine, 1984/2048 MB (512 MB allocatable), 12MCU

Benchmark relevant options:
===========================
* --force
* --optimized-kernel-enable

Hashmode: 1000 - NTLM

Speed.#2.........:   674.1 MH/s (73.28ms) @ Accel:1024 Loops:256 Thr:8 Vec:1
Speed.#3.........:  4171.1 MH/s (95.53ms) @ Accel:1024 Loops:512 Thr:64 Vec:1
Speed.#*.........:  4845.2 MH/s

Started: Wed Jun 17 13:01:06 2020
Stopped: Wed Jun 17 13:01:11 2020
```

**Comment by philsmd** [comment]
yeah, but this is just some strange/bad workaround. not really a solution for the root of the problem.

We can't just ask the users to use --force because we added a condition that with --force a (very important alias) check is **not** performed. That would be just very, very weird and **wrong**.

instead, I think the discussion over here: https://github.com/hashcat/hashcat/pull/2086#issuecomment-516020380 will be much more dedicated/specific to the root of the problem... we need to find out how the devices can be distinguished to not incorrectly mark them as aliases. I think the main problem was that the Apple drivers or OS doesn't really give enough info to make it very clear that they are using different PCI slots etc: https://github.com/hashcat/hashcat/pull/2086#issuecomment-516022651 ... so the information is not good enough for hashcat to decide that they are not the same device...

If there is really no other way to distinguish them, I would rather let hashcat assume that if we detected an Apple device or even apple OS (macOS) that we assume that there are no different OpenCL platforms for the same device (and therefore no aliases)... but my hope is still that there is some way to identify the different devices by some means (IDs / type / name / GPU vs CPU etc). It just needs to be reliable and also working on other operating systems etc.

maybe we could start with a clinfo output and see if there is somehow a way to distinguish them ?

**Comment by singe** [comment]
I'm obviously not suggesting --force as a permanent solution, it was merely used to demonstrate that there were no other technical reasons preventing 6.0.0 from using both.

I agree, that this is the same as the original problem, and your references to past comments makes sense. I was merely following @jsteube's suggestion.

The good news is, I re-applied https://github.com/hashcat/hashcat/commit/57a149276c5a20d5af1b2364628b3a305772ab3d which had been commented out, and it's working without the need for --force:

```
./hashcat -m1000 --benchmark        
hashcat (v6.0.0-1-g9b3cda2d+) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL API (OpenCL 1.2 (May  3 2020 20:15:19)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz, skipped
* Device #2: Intel(R) HD Graphics 530, 1472/1536 MB (384 MB allocatable), 24MCU
* Device #3: AMD Radeon Pro 455 Compute Engine, 1984/2048 MB (512 MB allocatable), 12MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 1000 - NTLM

Speed.#2.........:   603.4 MH/s (74.05ms) @ Accel:256 Loops:1024 Thr:8 Vec:1
Speed.#3.........:  4084.1 MH/s (97.22ms) @ Accel:1024 Loops:512 Thr:64 Vec:1
Speed.#*.........:  4687.5 MH/s

Started: Fri Jun 19 19:34:12 2020
Stopped: Fri Jun 19 19:34:27 2020
```

If you're happy with that, I'll resubmit that as a PR?

**Comment by singe** [comment]
Submitted as https://github.com/hashcat/hashcat/pull/2466

**Comment by philsmd** [comment]
With the above pull request (PR) I think the problem should be gone now. The processor count shouldn't be the same amongst these devices. I think this is a better fix compared to the other ones suggested, because it doesn't really undo other changes (previous commits/changes), it just adds additional checks/rules to the alias detection.

Could you test the changes I suggested or when available latest beta from https://haschat.net/beta/ (must be a beta newer than hashcat-6.0.0+25 ).

Thx
