### ISSUE TITLE
--status-automat - input mode

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#247]
Hello. When use --status-automat  param, output data  not contains input mode. 
For example: if i run mask brute ?l?l?l?l?l?l with --increment --increment-max=6 --increment-min=1 
when in human mode (without --status-automat) i will see always current input mode. First it will be ?l, after that ?l?l, ?l?l?l, etc.
With --status-automat i see only progress, but i don`t know progress of what i see now.

**Comment by philsmd** [comment]
I think I understood the problem you are describing above, but in your case if you want to just get the information on when exactly the mask changed etc it should be enough to just read/parse the oclHashcat.log file (or monitor it the same way you monitor the --status output).

I'm not sure if it makes sense to print the mask/dictionary each and every time when the status timer (--status-timer) triggers and showing the change only when there was a change makes the format of the --status output much less easier to parse.
On the other hand, we probably shouldn't make too many changes in the output of --status-automat because some 3rd-party wrappers already use it heavily and changing it may break their parser. (of course when we really thing we need to change the format, we definitely should do so AND document it appropriately).

I think the .log file is exactly what you are looking for, it tells you when exactly there was a change in mask/dict etc. The format of the .log file is also more appropriate for this kind of information, the status-automat is more or less just about the current speed/number of cracks etc.

Do you think this (.log file reading/parsing/monitoring) works for you?
Thx

**Comment by ghost** [comment]
Hello. Thanks. I think it good solution because a log-file contains a 
dict, mask, rule information. It`s all what i need for known current 
brute step.

02.03.2016 10:34, philsmd пишет:

**Comment by jsteube** [comment]
That logfile exists and is build so that it can be parsed by a machine

**Comment by philsmd** [comment]
@AntonKuzminRussia Can you please close this issue if the solution with the (already available) .log file feature is working for you?
Thx

**Comment by ghost** [comment]
Yes. Big thanks! All information what i need i found in .log/.
