### ISSUE TITLE
"Token length exception" when cracking a JWT

### ISSUE THREAD

**Issue by wadim-al** [hashcat/hashcat#2470]
Steps:
1. Using hashcat 6.0.0 on Windows 10 x64
2. Create a jwt.txt file containing:
eyJ1c2VyIjoidGVzdCJ9.EdXhug.bYN820Aw9UnaPwa5Pt88Hu77w30
3. Run hashcat -a3 -m 16500 jwt.txt in cmd.

Expected:
No errors, algorithm detected correctly.

Actual:
"Token length exception" error is shown.

Files:
[cmd.log](https://github.com/hashcat/hashcat/files/4829814/cmd.log)
[hashcat.log](https://github.com/hashcat/hashcat/files/4829815/hashcat.log)
[jwt.txt](https://github.com/hashcat/hashcat/files/4829816/jwt.txt)

**Comment by philsmd** [comment]
Is this a valid hash length ? the last part seems to be very short compared to our example hashes (see https://hashcat.net/wiki/example_hashes) :
```
bYN820Aw9UnaPwa5Pt88Hu77w30
```
^ this seems to be too short

**Comment by wadim-al** [comment]
I have no idea what hash it is. Alg is not set at all in this JWT.

**Comment by philsmd** [comment]
yeah, I think we can't do anything here. It's just an **invalid** JWT "hash".

I've now spend some time testing a few perl/python/php libraries and with each and every library that I tried I got an error that this is a malformed JWT token and signature. There are required fields like "alg" missing and the last part the signature is way too short (even if you try the different supported signature algorithm).

I'm afraid, but there is absolutely nothing we can do here. It's just a malformed/corrupted JWT and therefore if not even other parser can load/verify it, how could hashcat do it ?

Do you even have the password for this ?
The payload normally is also in JSON ("{...}") format, while your example just has random (base64url decoded) bytes. It seems to be completely fabricated. Maybe it was just a test by somebody... the first part (base64url decoded: `{"user":"test"}` ) even indicates that this was just some testing/debugging... maybe somebody just constructed this string by themself without using any library and NOT following the specs etc.... 

Where does this JWT come from ? Any software ?


With all that said, I think the best thing we can do here is to close this issue, because it seems completely invalid... this is NOT a hashcat bug.. this seems to be just a malformed string, which doesn't even validate as a valid JWT. I hope/think you agree !?

Please close. Thanks

**Comment by wadim-al** [comment]
Closing as this is not a correct JWT but a custom token for capture-the-flag intended to be analysed and cracked manually.

**Comment by philsmd** [comment]
but how can you crack it... I'm curious about this. Is the signature algorithm known ? it's way to short for any supported HMAC hash. Could you please explain the details/specs ?
what's the password ?

Maybe this information could help you in the future if we come across some "Short" JWT again. An update with more details would be great here. Thx

**Comment by wadim-al** [comment]
This is from a CTF, still unsolved by me so far.

**Comment by philsmd** [comment]
maybe you could give a quick update here in the future whenever you learn / get the solution for this task ?
Would be interesting to know if this is really malformed and why ? and what the password and algorithm is.
Thx

**Comment by wadim-al** [comment]
Sure!
