### ISSUE TITLE
LUKS: hashcat cannot crack headers

### ISSUE THREAD

**Issue by Banaanhangwagen** [hashcat/hashcat#2477]
When doing some tests for https://github.com/hashcat/hashcat/issues/2476, I noticed that Hashcat isn't able to crack LUKS-headers, as generated with `cryptsetup`

I tested it with cryptsetup v2.3.3
I used latest hashcat v6.0 from website

Let me explain what I did, so you can reproduce this:
1) Create a new file with random data
`dd if=/dev/urandom of=TEST bs=1M count=50`
2) format this file with LUKS; chosen passphrase is **x**
`cryptsetup luksFormat test --type=luks1`
3) check it 
```
cryptsetup luksDump TEST

LUKS header information for TEST
Version:       	1
Cipher name:   	aes
Cipher mode:   	xts-plain64
Hash spec:     	sha256
Payload offset:	4096
MK bits:       	512
MK digest:     	81 9e 30 e8 75 1c 14 5c ef 57 c3 da ea da 1a 78 fe 66 23 41 
MK salt:       	62 6e 7a 33 1f 19 f0 c7 c4 54 82 09 8e ac 9b ac 
               	46 24 8b 9f 87 79 63 7c 1e 41 d1 09 2f f6 1c 0e 
MK iterations: 	83485
UUID:          	6a0d053b-7f36-48de-a441-eefffbe129d4

Key Slot 0: ENABLED
	Iterations:         	1432480
	Salt:               	b3 70 32 f1 7b cc af 65 ad 11 e1 87 72 17 1a 1f 
	                      	e9 4c d2 22 ce 90 f6 eb 17 cd e6 21 c4 70 b5 05 
	Key material offset:	8
	AF stripes:            	4000
Key Slot 1: DISABLED
Key Slot 2: DISABLED
Key Slot 3: DISABLED
Key Slot 4: DISABLED
Key Slot 5: DISABLED
Key Slot 6: DISABLED
Key Slot 7: DISABLED
```
We expect Hashcat to support this since we are dealing with Luks1, AES, XTS-plain64 and SHA256

4) Hashcat could not crack it:
```
hashcat -m14600 TEST -a3 x
hashcat (v6.0.0-4-g5628317d) starting...

Session..........: hashcat
Status...........: Exhausted
Hash.Name........: LUKS
Hash.Target......: TEST
Time.Started.....: Tue Jun 30 14:12:29 2020 (1 min, 35 secs)
Time.Estimated...: Tue Jun 30 14:14:04 2020 (0 secs)
Guess.Mask.......: x [1]
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:        0 H/s (4.03ms) @ Accel:16 Loops:64 Thr:64 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 1/1 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:1432448-1432479
Candidates.#1....: x -> x
Hardware.Mon.#1..: Temp: 44c

Started: Tue Jun 30 14:12:26 2020
Stopped: Tue Jun 30 14:14:04 2020
```

5) JtR does not crack it either; the error there is `Error: UTF-16 BOM seen in input file`

6) Passware was able to crack it as expected
![image](https://user-images.githubusercontent.com/25983612/86125620-41a39600-badd-11ea-804d-0c2bf9446ad4.png)

Finally, when using `cryptsetup v1.6.6` and making a Luks1 with the default values (AES, xts-plain64, Sha1), again Hashcat and JtR couldn't crack it but Passware did it.

Am I making an error somewhere?
Any ideas?

**Comment by philsmd** [comment]
If I'm not totally wrong, you are missing an important step when creating the LUKS volume/container/partition/disk etc, i.e. there must be some valid data that the crackers can validate.

The details are also explained here: https://hashcat.net/forum/thread-6225.html

This is the most important step what regards this issue:
```
mkfs.ext4 /dev/mapper/tmp
```

or whatever other file system you want to use instead of "ext4".

That means that the underlying LUKS data must be formatted or (what is normally the case anyways) have some valid data within the volume/parition/container/file.

Again, details are explained in the above link/description. The crackers do check for some non-random data after decrypting it and if the entropy is "low enough" we got the correct key for sure.

I'm not sure what you mean by the term "LUKS header", but I'm sure that valid real-life LUKS containers in practice always have some file system and formatted data within the LUKS container and therefore this method ALWAYS work.

That only means that your testing is flawed, you didn't create the volume/container/disk/partition correctly with valid data.

The problem is that luksFormat is a little bit misleading, it doesn't touch the underlying data (it only does the steps needed for the LUKS stuff, not formatting the raw data that will be decrypted). The mkfs is an extra step required to make the volume valid... BTW: this is also explained in several LUKS tutorials, that you need to format the disk/data after creating a new LUKS volume. It doesn't have only to do with the crackers.

That also implies that the reason JTR and hashcat failed is (in my opinion) only a proof that they are correct and doing it the right way... while the fact that passware is cracking the volume shows that it doesn't use the "shortcut"/optimization required to do the cracking fast (again, see the forum thread above). If a cracking tool cracks the hashes without the underlying data being correctly formatted, it implies that it's not optimized and not using the attack/optimization. Doing the full computation (like you suggest passware is doing) slows the whole process down tremendously and doesn't make sense in general for real word LUKS volumes.

I think this is just a misunderstanding, please do not forget to close if you agree.

**Comment by Banaanhangwagen** [comment]
Thank you for your answer.

Your explanation is spot on: I missed a step by not formatting the LUKS container, since Hashcat uses this as an optimization. 
I got mislead by the term `luksFormat`

Note to myself to more carefully RTFM. ;)

**Comment by FloatingLizard** [comment]
I closed the Unable to crack the known Luks password #3250  by accident.
What about a live session taking all the same criteria where I do not know the password.  How can I know that it is properly working, because it seems hopeless.   I use Vast.ai that has a docker that can be imported running Hashcat because I do not have the resources GPU and ect.     

BTW I am located in the same city. 🥇
