### ISSUE TITLE
/usr/bin/OpenCL/: No such file or directory

### ISSUE THREAD

**Issue by Rust64** [hashcat/hashcat#2483]
Hi,

I didn't download the OpenCL files because I'm running an AMD CPU and evidently OpenCL is for Intel.  Has anyone had this problem and if so do you know how to fix it?  Here's what I've tried so far...

sudo hashcat --benchmark
[sudo] password for ubuntu:
hashcat (v6.0.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

**/usr/bin/OpenCL/: No such file or directory**

Started: Fri Jul  3 19:48:12 2020
Stopped: Fri Jul  3 19:48:12 2020

sudo hashcat --benchmark --force
hashcat (v6.0.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

You have enabled --force to bypass dangerous warnings and errors!
This can hide serious problems and should only be done when debugging.
Do not report hashcat issues encountered when using --force.

**/usr/bin/OpenCL/: No such file or directory**

Started: Fri Jul  3 19:50:28 2020
Stopped: Fri Jul  3 19:50:28 2020

hashcat -a 0 -m 0 example0.hash example.dict -r rules/best.rule
hashcat (v6.0.0) starting...

**/usr/bin/OpenCL/: No such file or directory**

Started: Fri Jul  3 20:07:21 2020
Stopped: Fri Jul  3 20:07:21 2020

**Comment by philsmd** [comment]
Hey,
no, you are wrong.

OpenCL (see https://en.wikipedia.org/wiki/OpenCL) is a programming language and a framework. Most modern CPUs and GPUs support OpenCL and have compilers and runtimes for the OpenCL kernels.

For hashcat you need the OpenCL kernels for all the supported devices (mainly CPUs and GPUs, see https://hashcat.net/hashcat/).

It's wrong that CPUs can't deal with OpenCL and also wrong that CPUs can't run OpenCL code. You need the folders and the OpenCL kernels inside the `OpenCL/` folder for hashcat to run.

The old (now **deprecated***) cpu hashcat (hashcat-legacy) supported CPU cracking without OpenCL runtime, see https://github.com/hashcat/hashcat-legacy/ and https://hashcat.net/files/hashcat-2.00.7z . Again, this old hashcat-legacy hash cracker is deprecated and not supported/recommended anymore.

Since this is just an user question and a misunderstanding of what `OpenCL` is, I suggest closing this github issue. Please do not forget to close @Rust64 . Thx

---

BTW: it's actually strange, but for AMD CPUs like Ryzen etc we recommend to install the `Intel OpenCL Runtime for Xeon and Core Processors` (see https://software.intel.com/content/www/us/en/develop/articles/opencl-drivers.html#cpu-section and https://hashcat.net/hashcat/), because it's the fastest runtime and best compiler for CPUs in general (also with support of running this Intel compiler/runtime on AMD CPUs)

**Comment by Rust64** [comment]
Hello Mr. Phil,

You mentioned to a user you have a C code to crack aescrypt encrypted files.  You asked if he had Linux.  I have Ubuntu 20.04... will that work?  Would your code be better or easier to use than attempting to use Perl along with the new development of hashcat beta (discussed here: https://hashcat.net/forum/thread-8874.html)

Also, you mentioned for your C code the Requirement is to have all the passwords you want to try in a file what if all the passwords in the file are wrong, what happens then?

I’m sure you have guessed I have ZERO knowledge and understanding of programming or anything hashcat, Perl, etc. and to be honest, I don’t have an interest in learning it at my age.  I just need to crack an AEScrypt file in the form of aescrypt_file.txt.aes

I know your super busy, but could you offer any assistance as it would be greatly appreciated.

Thank you,
Chuck

On Jul 5, 2020, at 3:49 AM, philsmd <notifications@github.com> wrote:

﻿

Hey,
no, you are wrong.

OpenCL (see https://en.wikipedia.org/wiki/OpenCL) is a programming language and a framework. Most modern CPUs and GPUs support OpenCL and have compilers and runtimes for the OpenCL kernels.

For hashcat you need the OpenCL kernels for all the supported devices (mainly CPUs and GPUs, see https://hashcat.net/hashcat/).

It's wrong that CPUs can't deal with OpenCL and also wrong that CPUs can't run OpenCL code. You need the folders and the OpenCL kernels inside the OpenCL/ folder for hashcat to run.

The old (now deprecated*) cpu hashcat (hashcat-legacy) supported CPU cracking without OpenCL runtime, see https://github.com/hashcat/hashcat-legacy/ and https://hashcat.net/files/hashcat-2.00.7z . Again, this old hashcat-legacy hash cracker is deprecated and not supported/recommended anymore.

Since this is just an user question and a misunderstanding of what OpenCL is, I suggest closing this github issue. Please do not forget to close @Rust64<https://github.com/Rust64> . Thx

**Comment by philsmd** [comment]
now it's getting a little bit off-topic here: maybe you can explain your exact problem on the hashcat forum and somebody will hopefully answer with the detailed instruction what you can/should do about the newly supported "AES Crypt" hash type (see announcement of hashcat 6.0.0 here: https://hashcat.net/forum/thread-9303.html , the latest release version already supports "AES Crypt" and has a tool `tools\aescrypt2hashcat.pl` that can convert the files to hashes, search for the `aescrypt2hashcat.pl` in the tools folder of latest hashcat version)

**Comment by Rust64** [comment]
It’s unfortunate that you thought it necessary to put so many Error statements in your aescrypt2hashcat.pl script because the darn thing can’t even run without returning an Error message!  What’s even more irritating is that the aescrypt2hashcat.pl script somehow “thinks” that my definite and proven .aes crypt file (in the form of file.aes) is not an .aes file, returning the Error message “The file doesn’t seem to be a correct aescrypt file”.  By the way, just how does your aescrypt2hashcat.pl script determine one way or the other that a particular file is or isn’t an aescrypt file when the file is encrypted and the file’s extension is .aes?  It would seem to me the file would be an indeterminate/unrecognized file since it was encrypted.  Anyway, it’s a bummer your script doesn’t work on my file.  It would have been nice to see what it came up with if it only could’ve completed to the end.

Also, with the use of perl aescrypt_hello_world.pl rockyou.txt after searching in the forum, I can’t find anything discussing in depth or how to obtain these important criteria (iv, enc_iv, enc_key, HMAC) even after examining the info on aescrypt.com/aes_file_format.html , it’s no help or even after googling there’s no info on these terms/criteria.

I would be happy to post all these issues on hash.net forum but you’re the one who wrote the aes cracking script aescrypt2hashcat.pl (right?) and others in the forum don’t seem to have the knowledge about cracking an aescrypt file.  And Paul E. Jones (a guy over at github who has written a C code script to crack aes files) is so busy he doesn’t have the time to respond to my requests for help.

Chuck

On Jul 7, 2020, at 2:35 AM, philsmd <notifications@github.com> wrote:

﻿

now it's getting a little bit off-topic here: maybe you can explain your exact problem on the hashcat forum and somebody will hopefully answer with the detailed instruction what you can/should do about the newly supported "AES Crypt" hash type (see announcement of hashcat 6.0.0 here: https://hashcat.net/forum/thread-9303.html , the latest release version already supports "AES Crypt" and has a tool tools\aescrypt2hashcat.pl that can convert the files to hashes, search for the aescrypt2hashcat.pl in the tools folder of latest hashcat version)

**Comment by philsmd** [comment]
I guess this `fatcat` user from the hashcat forum is you: https://hashcat.net/forum/thread-9368.html !?

I already explained that the file format description and explaination of the specification of how a file **must** look like is very clear and the perl tool just correctly verifies that the file is not corrupt and respects the file format specification.

While developing that tool, I of course did generate a few dozens of example files and all of them did verify correctly.

That means, that if you get an error message saying that the file does not have the correct format, it most likely is the case that your file was either not created by the `AES Crypt` tool or it's a corrupted file (e.g. not starting with "AES" at the beginning of the file etc).

I don't think we should remove any code that verifies whether the file is correct or not, this is a crucial test to check if the user is providing the correct input (an .aes file created by AES Crypt).

I would highly recommend that you compare your file against the file format description to see what is wrong.
In addition to that you can also download a fresh copy of AES Crypt and create some test files and see if the perl script works with them... then you compare it with the `AES Crypt` version of the software you initially used and see if there are some differences etc... this is crucial information and this testing is needed.

You can't just blame the tools that are following the specs and correctly verifying if the file does respect the file format specifications (and therefore check whether it is a **valid** .aes file created by `AES Crypt`)

Thx

**Comment by Rust64** [comment]
Yes, that is me on hashcat.com

Unfortunately, I must go a different route now because I let bitcoin core download the entire blockchain and when I rescanned my wallet.dat file, the balance was 0.  This makes sense since the timestamps on the mbhd.wallet.aes are approximately 2 hours after the wallet.dat file was created.  I believe my son must have moved the bitcoin from the wallet.dat(private keys) to 3 separate mbhd.wallet.aes wallets, each 27Kb in size.  I should have paid better attention to this fact instead of wasting so much time on bitcoin core!  Now I must somehow crack these mbhd.wallets.aes or attempt the below avenue. I have no idea if OpenSSL is the way to go or not.

I found a Python script that supposedly when ran can provide the 12 wallet words that one can use to restore a Multibit HD wallet.  If this works (at the moment it’s not working), I will be able to see if the 3 mbhd.wallet.aes have private keys and regain access to bitcoin if any exist.  So the deal is you download and install the Python 3.4.x and you download this decrypt_bitcoinj_seed.pyw script and double click it and it’s supposed to generate the secret seed or wallet words.  The problem is when I double click on the script, nothing happens.  It was developed in 2017 so the support for it is weak.  A window is supposed to pop up and you’re supposed to point it to the mbhd.wallet.aes file but something is wrong and since I have very limited knowledge about Python and this decrypt_bitcoinj_seed.pyw script there’s no way for me to figure out what’s wrong.  Have you ever heard about this method of wallet words/seed retrieval?  It seems like it would be huge and a game changer if it worked because I could just login to multibit hd and recover my wallets using the seeds. Anyway, I don’t know what your thoughts are but I was hoping this would work.

Thanks,
Chuck

On Jul 21, 2020, at 3:24 AM, philsmd <notifications@github.com> wrote:

﻿

I guess this fatcat user from the hashcat forum is you: https://hashcat.net/forum/thread-9368.html !?

I already explained that the file format description and explaination of the specification of how a file must look like is very clear and the perl tool just correctly verifies that the file is not corrupt and respects the file format specification.

While developing that tool, I of course did generate a few dozens of example files and all of them did verify correctly.

That means, that if you get an error message saying that the file does not have the correct format, it most likely is the case that your file was either not created by the AES Crypt tool or it's a corrupted file (e.g. not starting with "AES" at the beginning of the file etc).

I don't think we should remove any code that verifies whether the file is correct or not, this is a crucial test to check if the user is providing the correct input (an .aes file created by AES Crypt).

I would highly recommend that you compare your file against the file format description to see what is wrong.
In addition to that you can also download a fresh copy of AES Crypt and create some test files and see if the perl script works with them... then you compare it with the AES Crypt version of the software you initially used and see if there are some differences etc... this is crucial information and this testing is needed.

You can't just blame the tools that are following the specs and correctly verifying if the file does respect the file format specifications (and therefore check whether it is a valid .aes file created by AES Crypt)

Thx

**Comment by philsmd** [comment]
The main problem here is that you are very uncertain what you did and what software you used etc.
This uncertainty is very bad in general and in particular for trying to explain/troubleshoot/test things etc.

First you were very / 100% certain that `AES Crypt` was used, now you say that the .aes file has something to do with bitcoin etc.
This just contributes to further confusion and it shows that you are very uncertain about what file you have, how to recover the passwords, what software was used etc etc etc

Let's be honest, the fact that the `aescrypt2hashcat.pl` always warned you about the wrong file format, was probably the best thing that could happen: it not only checked that the file wasn't corrupt, but also literally saved you from trying to attack an uncrackable "hash" (otherwise you would have wasted hundreds of hours trying to crack an `AES Crypt` hash, which wasn't even generated by that software and of course other resources too - power consumption etc - not only time). You can be **very lucky**. Maybe next time instead of **blaming** a tool, you just try to think about why it does these checks and realize that something could be wrong.

---

Now let's come back to the (presumably) MultiBit file (are you even sure about this now ? do you have this software installed etc ? when was it installed and last used etc ?):
hashcat recently added support for the
-m 22700 = `MultiBit HD (scrypt)`

hash type, see: https://github.com/hashcat/hashcat/issues/2383 and https://github.com/hashcat/hashcat/pull/2388

if you use `multibit2john.py` (from https://raw.githubusercontent.com/magnumripper/JohnTheRipper/bleeding-jumbo/run/multibit2john.py ,  you need to download this python script), you can extract the hashes (if and only if it is a valid MultiBit HD (scrypt) wallet file):
```
python multibit2john.py mbhd.wallet.aes
```

hashcat expects a slightly modified "hash" (look for 22700 in https://hashcat.net/wiki/example_hashes).

This means that the hash line must start with: `$multibit$2*` (no file names etc within the hash line).

The problem with this hash type is that it uses SCRYPT internally and therefore is very difficult to crack... you must have a good strategy on how to attack this hash, maybe know part of the password or a list of password candidates that could / should work.

---

another hint: if you really think that there was a bitcoin transaction from one account to the other and you have the original/first wallet file, you should at least be able to check if there are some outgoing transaction and find out if the MutiBit files also have to do with the receiving bitcoin address etc.... it's much better to do some verification steps before wasting time again.

Again, I think this is kind of off-topic here and we should probably stop discussing this problem here on a `software bug tracking web site` (this is just a set of very weird user questions that have nothing to do with hashcat bugs etc).
Thx

**Comment by Rust64** [comment]
Hi,


I was able to run multibit2john.py with success and obtain the hash for $multibit$2* but as you mentioned and quoting you, “The problem with this hash type is that it uses SCRYPT internally and therefore is very difficult to crack... you must have a good strategy on how to attack this hash, maybe know part of the password or a list of password candidates that could / should work.” I believe it will be almost impossible to move forward because I am unable to ask my son anything.  With that said, I may need to give up on this endeavor since it would take over ten years to crack this hash according to the message line in the code - (“Time.Estimated”) with the following shell command:

.\hashcat.exe -m 22700 -a 3 hashes.txt “guess password with all kinds of ?u?l?l?l?d?s “ etc., etc.

The only real possibility is if there was a way to know if I had the first character correct and that would give me an idea of the password, however isn’t it true that it is “all or nothing” such that you have to get the whole password correct to break the hash?  Anyway, again I’m not sure if there’s anything left to try but thanks for all your input.

Chuck


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by philsmd** [comment]
I don't think this is a good idea on how to try to solve problems.

`scrypt` is indeed a slow hash type, but that doesn't mean that you should give up immediately (well, it's up to you, but at least trying to find a better solution would be much more appropriate in my opinion).

As you might know, most passwords do not come directly from /dev/urandom , they are not really a random sequence of characters, but very often they are chosen by a human (and most humans still have difficulties to understand what makes a password secure and therefore difficult to crack). humans choose passwords with words within them that are related to their real life (pet names, given names, last names, other common words in dictionaries etc etc etc) very often.

The idea of just "brute-forcing" a hash is quite outdated and not very efficient, let alone very clever. Even for fast hashes like NTLM (another hash type, very fast) it's most often only the **last resort** . You only try to `mask attack` (a special/improved type of `brute force`) hashes if all other attacks like dictionary attack (-a 0), rule based attacks (-a 0 -r my.rules), combinator attacks (-a 1), hybrid attacks (-a 6, -a 7), prince attack (see princeprocessor), keyboard walks, etc etc etc fail.

Even if sometimes it seems that the speed of mask attack is faster (mainly because the password candidates are directly generated on the GPU and therefore the I/O - disk and PCI speed - bottleneck is NOT a problem), other attacks might still get you password recovered much more efficiently and quicker (trying **each and every** combination of every possible character combined with other "random" characters, is often not what leads to the discovery/recovery of the password very quickly, instead it's often a waste of time and resources).

Therefore, my advice is to at least think about what the password could be... if it could be some dictionary word etc or if the passwords really come from a random source  (passwords generated by a password manager etc) and try a rule based attack instead:
https://hashcat.net/wiki/doku.php?id=rule_based_attack

```
hashcat -m 22700 -a 0 -w 3 -D 1 -r rules\best64.rule hash_file.txt rockyou.txt
```

The file `rockyou.txt` could/should of course be replaced by a dictionary file (wordlist) that you think contains very many likely password candidates that could be the "right ones" to crack the hash.

The rule file `rules\best64.rule` could also be replaced by rules that make most sense to you... maybe the appended special characters that you mentioned above with `?s` etc.

As you can see I used `-D 1` (or the long option `--opencl-device-types 1`) above. This only makes sense in cases like scrypt were your CPU cracking speed could be faster than your GPUs (of course you need to have the `Intel OpenCL Runtime for Core and Xeon Processors` installed as mentioned in https://hashcat.net/hashcat to run hashcat on your CPUs).
It's worth a try to test if your CPU is faster compared to your GPU(s). scrypt is a very special hash type which is very difficult to attack with GPUs.... but this also depends a lot on what hardware and which amount of GPUs vs CPUs you have (cracking system tend to have even 8+ GPUS, but rarely have more than one CPU installed, so the total cracking speed might be much faster with 8 GPUS compared to the CPU of course).

Again, I wouldn't give up that quickly... you should step back a little bit and think about the problem more carefully and with an open mind and see if you can remember more about how the password could look like and try some more **dedicated** attacks (instead of just `brute-forcing` it, which again is most often only the **last resort**).

Good luck cracking

**Comment by Rust64** [comment]
Thank you for the encouragement.  Upon further review and investigation, I have decided to take a leap of faith and try AWS EC2 instance using p3.16xlarge. And frankly, I am extremely surprised that more folks haven’t looked into this and seriously considered using this amazing machine for all cracking needs.  It is perfect for hashcat since hashcat is designed to handle extreme speeds.  As you may know, this technology is almost too good to be true and the p3.16xlarge can crack any 8 character password in 4.2 hours or less because of it’s ridiculous power and speed. This has been proven mathematically and is well documented.  Now it will cost me $24.48/hr but that’s a fair exchange for a possible nice reward. Have you looked into this yourself?  All of the architecture and utilities are available (OpenCL etc.) if you choose the correct setup.  For example, if you choose Ubuntu 18.04 and the p3.16xlarge all you have to do install the necessary packages then test and of course download hashcat and you’re good to go to start cracking your hash.  Since my hash is difficult to crack, as you pointed out, it may take longer than normal to crack so I have to be prepared for that.  Let me know what your thoughts are.

Oh and I don’t mean to count my chickens before they’re hatched but I thought of a question... if I decrypt the mbhd.wallet.aes file and it has what you referred to as a dump of private and public keys... will they be associated with addresses in the wallet? How would I get the bitcoins using these keys?

Thank you,
Chuck

On Jul 28, 2020, at 3:50 AM, philsmd <notifications@github.com> wrote:

﻿

I don't think this is a good idea on how to try to solve problems.

scrypt is indeed a slow hash type, but that doesn't mean that you should give up immediately (well, it's up to you, but at least trying to find a better solution would be much more appropriate in my opinion).

As you might know, most passwords do not come directly from /dev/urandom , they are not really a random sequence of characters, but very often they are choosen by a human (and most humans still have difficulties to understand what makes a password secure and therefore difficult to crack). humans choose passwords with words within them that are related to their real life (pet names, given names, last names, other common words in dictionaries etc etc etc) very often.

The idea, of just "brute-forcing" a hash is quite outdated and not very efficient, let alone very clever. Even for fast hashes like NTLM (another hash type, very fast) it's most often only the last resort . You only try to mask attack (a special/improved type of brute force) hashes if all other attacks like dictionary attack (-a 0), rule based attacks (-a 0 -r my.rules) combinator attacks (-a 1), hybrid attacks (-a 6, -a 7), prince attack (see princeprocessor), keyboard walks, etc etc etc fail.

Even if sometimes it seems that the speed of mask attack is faster (mainly because the password candidates are directly generated on the GPU and therefore the I/O - disk and PCI speed - bottleneck is NOT a problem), other attacks might still get you password recovered much more efficiently and quicker (trying each and every combination of every possible character combined with other "random" characters, is often not what leads to the discovery/recovery of the password very quickly, instead it's often a waste of time and resources).

Therefore, my advice is to at least think about what the password could be... if it could be some dictionary word etc or if the passwords really come from a random source (passwords generated by a password manager etc) and try a rule based attack instead:
https://hashcat.net/wiki/doku.php?id=rule_based_attack

hashcat -m 22700 -a 0 -w 3 -D 1 -r rules\best64.rule hash_file.txt rockyou.txt


The file rockyou.txt could/should of course be replaced by a dictionary file (wordlist) that you think contains very many likely password candidates that could be the "right ones" to crack the hash.

The rule file rules\best64.rule could also be replaced by rules that make most sense to you... maybe the appended special characters that you mentioned above with ?s etc.

As you can see I used -D 1 (or the long option --opencl-device-types 1) above. This only makes sense in cases like scrypt were your CPU cracking speed could be faster than your GPUs (of course you need to have the Intel OpenCL Runtime for Core and Xeon Processors installed as mentioned in https://hashcat.net/hashcat to run hashcat on your CPUs).
It's worth a try to test if your CPU is faster compared to your GPU(s). scrypt is a very special hash type which is very difficult to attack with GPUs.... but this also depends a lot on what hardware and which amount of GPUs vs CPUs you have (cracking system tend to have even 8+ GPUS, but rarely have more than one CPU installed, so the total cracking speed might be much faster with 8 GPUS compared to the CPU of course).

Again, I wouldn't give up that quickly... you should step back a little bit and think about the problem more carefully and with an open mind and see if you can remember more about how the password could look like and try some more dedicated attacks (instead of just brute-forcing it, which again is most often only the last resort).

Good luck cracking
