### ISSUE TITLE
No hashes loader and token length exception for wallet.dat

### ISSUE THREAD

**Issue by Qalander** [hashcat/hashcat#2489]
So,  I am a new bitcoin hashsing issue, the code i got after running bitcoin2john is  but it is less in one decimal because the other hash got from different wallet has one digit longer  and that one is loading in hashcat 6.0.0 but not this one. 

I get error message that no hashes loader and token length exception, should I use SHA256 instead of bitcoin wallet here. while brut forcing, please help.

$bitcoin$64$9de529051d808b5d34c679c43020a233e6b5161de2e85070127009d61e4c24c8$16$09792b4786f368cb$49019$2$00$2$00    113 characters
--
 this code is loading.

$bitcoin$64$50bb9ef9cad87bf2b865b060e80c72c52f5ff496dbefa0bcfc6c3b5e0b86050e$16$f63cb4696e604d94$128289$2$00$2$00   114 characters
--

**Comment by jsteube** [comment]
Both hashes work fine for me. What's the password?

**Comment by philsmd** [comment]
I've also tested to run these 2 hashes and they load perfectly fine for me: no error message, no problem loading them. nada.

Maybe you have some whitespace (spaces at the end for instance) within you hash lines ?
We also always recommend using **hash files** because several users seem to have problems understanding their shell/cmd and don't understand that certain characters need to be escape if the hashes are directly specified on the command line (without using a hash file).

Anyway, it doesn't seem to be a problem / bug, but just an user error (pebcak). We also didn't get any further response, so I would suggest that we close this issue as WORKSFORME / INVALID. Please close

**Comment by philsmd** [comment]
Again I do **not** see any problem here. I tried it and everything is working correctly with the latest versions.

please close this issue @jsteube / @Qalander 

Thx

**Comment by djjec** [comment]
> So, I am a new bitcoin hashsing issue, the code i got after running bitcoin2john is but it is less in one decimal because the other hash got from different wallet has one digit longer and that one is loading in hashcat 6.0.0 but not this one.
> 
> I get error message that no hashes loader and token length exception, should I use SHA256 instead of bitcoin wallet here. while brut forcing, please help.
> 
> ## $bitcoin$64$9de529051d808b5d34c679c43020a233e6b5161de2e85070127009d61e4c24c8$16$09792b4786f368cb$49019$2$00$2$00 113 characters
> this code is loading.
> 
> ## $bitcoin$64$50bb9ef9cad87bf2b865b060e80c72c52f5ff496dbefa0bcfc6c3b5e0b86050e$16$f63cb4696e604d94$128289$2$00$2$00 114 characters

What's the password?
