### ISSUE TITLE
Hashmode: 3200 - bcrypt $2*$, Blowfish (Unix) - CL_BUILD_PROGRAM_FAILURE on MacOS 15.5.6

### ISSUE THREAD

**Issue by emwinkler** [hashcat/hashcat#2490]
This issue has been around since 5.1, but just getting around to reporting it.  See below:

./hashcat -m 3200 -b -d 3        
hashcat (v6.0.0-35-gb9f6777f) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

Kernel /Users/emwinkler/Desktop/hashcat/OpenCL/m03200-optimized.cl:
Optimized kernel requested but not needed - falling back to pure kernel

OpenCL API (OpenCL 1.2 (Jul  5 2020 01:14:53)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz, skipped
* Device #2: Intel(R) Iris(TM) Plus Graphics, skipped
* Device #3: AMD Radeon RX Vega 64 Compute Engine, 8112/8176 MB (2044 MB allocatable), 64MCU

Benchmark relevant options:
===========================
* --backend-devices=3
* --optimized-kernel-enable

Hashmode: 3200 - bcrypt $2*$, Blowfish (Unix) (Iterations: 32)

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

SC failed. No reason given.
* Device #3: Kernel /Users/emwinkler/Desktop/hashcat/OpenCL/m03200-pure.cl build failed.

**Comment by DeadPackets** [comment]
This happens with me too on version v6.1.1 on macOS 10.15.7 with the following devices:

* Device #1: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz, skipped
* Device #2: Intel(R) UHD Graphics 630, 1472/1536 MB (384 MB allocatable), 24MCU
* Device #3: AMD Radeon Pro 5500M Compute Engine, 4016/4080 MB (1020 MB allocatable), 24MCU

**Comment by jsteube** [comment]
I debugged this a bit since I got access to some mac computer recently. 

It seems the JiT fails without a reason (Not complete without reason, but the reason is "SC failed. No reason given.") if the kernel allocates the full local memory reported back by its own driver. In my case this is 64k. You can find our using clinfo, see the column "Local memory size". Latest versions of hashcat respect this value and optimizes bcrypt kernel before sending it to the JiT, but older versions of hashcat do not.

When you mentioned that with hashcat 5.1.1 it worked I checkout out that version and indeed it was working. But this version is very old and uses lots of static values. In this case, it (luckily) used a fixed thread count of 8 for bcrypt. So I checkout out master and limit the thread count to 8 as well (-T 8) and voila, it worked! In theory, this should work on your systems, too.

So there's only one thing that influence the code before it goes to the JiT that is also affected by the thread and that is the total local memory allocation. It seems if we limit ourselves to only 32k, even if we 64k, the JiT survives and works. So I will add a workaround soon.

**Comment by jsteube** [comment]
Workaround added with commit https://github.com/hashcat/hashcat/commit/8a3eee3fe5b6cd2a88d154ea95bcd0a5422d57d3
