### ISSUE TITLE
feature: skip instead of abort on BOM detection

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#2504]
When processing a large number of files, it would be useful to skip files with they Byte Order Mark (BOM) and move on to the next wordlist/mask/etc, instead of completely aborting the hashcat run.

**Comment by solardiz** [comment]
FWIW, in JtR we currently don't even skip such files - we merely warn, but continue trying to process the rest of the file anyway (for both password hash and wordlist files). I think hashcat can do the same, and thus handle this problem gracefully not only when run on multiple files. Recent JtR fix: https://github.com/openwall/john/pull/4306

**Comment by jsteube** [comment]
This has been addressed with commit https://github.com/hashcat/hashcat/commit/254e33c473a7775fcdb1b5ac1e4dd0936ed91df4 as discussed. Skip the BOM instead of abort.

We could add some more text to the warning, for instance telling the user the BOM was ignored and they should use --encoding-from but OTOH we could automatically do it, too. For instance if we detect a BOM in a wordlist, but we would need some sort of mapping between the detected BOM and the ascii-string taken from internal iconv. I am wondering if iconv has some header files we could use for that because I want to avoid to reinvent the wheel.
