### ISSUE TITLE
[Feature Request] Bitwarden keyHash / "nested" PBKDF2-HMAC-SHA256

### ISSUE THREAD

**Issue by 0x6470** [hashcat/hashcat#2505]
In Bitwarden's local save files a `keyHash` value can be found, which is derived from the master password.
The default location depends on the operating system and on the used "kind" of Bitwarden (CLI, Browser, Android...), full list can be found here: [https://bitwarden.com/help/article/where-is-data-stored-computer/](https://bitwarden.com/help/article/where-is-data-stored-computer/).
The "keyHash" value is computed via two PBKDF2-HMAC-SHA256 operations one after the other.
In Python this looks something like this:
`pepper  = hashlib.pbkdf2_hmac(sha256, pass = master_password, salt = email, rounds = 100000, dklen = None)` The actual number of iterations can be adjusted in the Bitwarden vault and is saved in Bitwarden's local save files under `kdfIterations`.
`keyHash = hashlib.pbkdf2_hmac(sha256, pass = pepper, salt = master_password, rounds = 1, dklen = None)` There is only one iteration here (always).
`keyHash = base64.b64encode(keyHash).decode()`
If this value matches the `keyHash` value in Bitwarden's files, the supplied master password is correct. The email is saved in those file(s), too (`userEmail`).
I wonder, if this kind of "nested derivation" could be implemented into hashcat.

**Comment by philsmd** [comment]
I guess we would need to have full examples and also the details on how you verify that the password was the correct one (verification step).

From the post above, I see that you are a good coder and should be able to write a full POC (proof of concept) that demonstrate with a "hash" + password how to determine if the password is correct (if you implement it with python code, it's perfectly fine for the demonstration). Would you be willing to do this (implement a POC) ?

We would also need to decide on what the "hashes" look like, normally we use formats like this nowadays:
```
$bitwarden$hash_format_version*software_version*iterations*salt*....*digest
```
or similar.

Thanks

**Comment by 0x6470** [comment]
I just wrote a small poc at [https://github.com/0x6470/poc_Bitwarden2Hashcat/](https://github.com/0x6470/poc_Bitwarden2Hashcat/) for demonstration purposes in python.
It should make a few things clear (at least I hope so).

Regarding the hash-format, I am not sure, whether the Bitwarden team will ever change this procedure or make them different on different platforms.
Therefore, I would call this "version" version 1. I would recommend something like this:
`$bitwarden$hash_format_version*iterations*email*digest`
or in my example poc:
`$bitwarden$1*100000*ziwexztkonxxrtyflv@awdrt.com*Lws4aYds9v2JirbGTOeOSh+wdt6oW+XRbv/hqNhG4Bs=`

**Comment by philsmd** [comment]
Hey thanks for your great POC, this helps / helped a lot !

I've now coded this new hashcat module https://github.com/hashcat/hashcat/pull/2515 that is able to crack these hashes.

The hash format is as suggested above. I only have one small doubt about the format, i.e. what if the email address contains a asterisk (*), that would be a little bad for the hash parsing code ? We have similar cases already, but in theory email addresses very unlikely contain stars, therefore I probably would leave it AS-IS for now (we should just remember that this could be a problem in the future).

There is one further problem: we currently have no extraction tool for theses hashes... I'm pretty sure John THe Ripper (JTR) currently doesn't support this hash format... 

We would need some tool like `bitwarden2hashcat` that easily generates the above hashes from the .json file (or whatever file from Bitwarden that is needed).
Maybe you could help us with that tool too because I see you are much more familiar with the underlying data of `Bitwarden` etc ?

Thank you so much. The tool was very helpful

**Comment by 0x6470** [comment]
Glad to hear that I could help.
I'm already working on a `bitwarden2hashcat` tool rn.
We could change the separation symbol to `:` or `;` as they are very unlikely to occur in an email address.
The format specification of email addresses states: `space and special characters "(),:;<>@[\] are allowed with restrictions (they are only allowed inside a quoted string, as described in the paragraph below, and in addition, a backslash or double-quote must be preceded by a backslash);` [Wikipedia](https://en.wikipedia.org/wiki/Email_address#Local-part)
So maybe we could change the format to something like
```
$bitwarden$hash_format_version:iterations:email:digest
```

**Comment by philsmd** [comment]
yeah, the idea isn't bad, but we actually try to avoid using different separators to be consistent with the generic hash format (that nowadays follow the rules mentioned above).

I therefore suggest that we just switch to base64 encoded salt (base64 encoded email address). It's kind of the obvious choice in my opinion because also the digest is in base64.

Of course there is a slight disadvantage of this: the users can't immediately see what the last and second to last fields are at the first glance... but I think that's totally acceptable because we always try to force users to use the `*2hashcat` or `2john` tools anyway, i.e. every user should use `bitwarden2hashcat.py` and they will be fine.

Could you implement that conversion/extraction tool `bitwarden2hashcat.py` with the email/salt converted to base64 ?

I've already pushed the changes for hashcat (https://github.com/hashcat/hashcat/pull/2515/commits/035df28c8abecf59e4cec61925394ecd208023d2) and examples are also in the `--example-hashes` output or in the source code.

```
$bitwarden$1*100000*bm9yZXBseUBoYXNoY2F0Lm5ldA==*zAXL7noQxkIJG82vWuqyDsnoqnKAVU7gE/8IRI6BlMs=
```
password is
```
hashcat
```
if you base64 decode `bm9yZXBseUBoYXNoY2F0Lm5ldA==` you get `noreply@hashcat.net`, exactly as it should be.

Thx

**Comment by 0x6470** [comment]
A base64 encoded salt would have been my second choice as well.
I just uploaded a small `bitwarden2hashcat` tool at [https://github.com/0x6470/bitwarden2hashcat](https://github.com/0x6470/bitwarden2hashcat).
On my machine, it works just fine right now. Yet, it's possible that bugs will occur in newer Firefox versions.
I will try everything (bitwarden2hashcat.py and the new hashcat together) the next days.
Thanks for the good cooperation.

**Comment by philsmd** [comment]
Hey,
I had a quick glance at your tool and I must say I'm impressed.
I didn't think there were so many possibilities to extract the "hashes" and that this software had that many alternative implementations (browser vs desktop application etc).

It seems that this was a lot of work. I didn't expect that. Didn't want to give you that much work. I thought this was a matter of extracting the file from a simple .json file (parsing the JSON file and constructing the hash line).

Thank you very much for you work !

There are only 2 things that come to my mind that we might consider changing (or leave them AS-IS, it's not that important, I just want to throw them out to have some discussion):
1. It would be great if the tool would allow to specify a path (see https://github.com/0x6470/bitwarden2hashcat/issues/1) or even allow to run the tool on multiple files at once (python bitwarden2hashcat.py /tmp/bitwarden/*.json > m23400_hashes.txt)
2. The AGPL GNU LICENSE is probably a little bit limiting... I don't think it's a major problem here because we can (and this was also our intention from the start) just point the users to this tool... but if some MIT/BSD licensed project like hashcat (or even a tool like JohnTheRipper) would want to integrate or ship this tool, it would probably not be compatible with their specific license (if not GPL licensed themself). I'm not 100% sure about the compatibility, but in most cases GNU licenses and other open source lisences (non-GNU) are kind of incompatible, if not dual-licensed. The free software movement (and therefore GNU GPL) limit the distribution and integration with other open source project (non GPL) a lot. I know that free software like GPL would be in theory the ideal license for some projects, but unfortunately several projects can't have all those "freedoms" (for several reasons) and therefore are "open source" licensed with an other license (non-GPL or similar).
Maybe you could consider a change to a MIT/BSD LICENSE and/or dual-license it.

Thx again. This is very much appreciated

**Comment by philsmd** [comment]
Thanks @0x6470 . All the points from above were addressed in https://github.com/0x6470/bitwarden2hashcat/issues/1 and https://github.com/0x6470/bitwarden2hashcat/commit/e4554702b845dbb315269090dc524dcf649f11ba .

This is perfect. Great ! Good job
