### ISSUE TITLE
New Kernel

### ISSUE THREAD

**Issue by trounce1** [hashcat/hashcat#2549]
Hi,

Im writing a new kernel that is pbkdf-sha512 followed by 1 round of sha256.

Which is the best kernel for me to modify to make a new one?

Cheers

**Comment by philsmd** [comment]
first of all, thanks for the interest in contributing to hashcat.
I think that questions like this are more suitable for the hashcat forum (developers section), because over here we normally only accept bug/issue reports and new feature/hash requests.

I think -m 7100 or -m 12100 (which use the same kernel file) are a good start... but remember, that the iteration count and output length etc must be adjusted too. I would probably start with the module and kernel file of 7100 and adapt that, after that add the sha256 computation within the comp () kernel function of the OpenCL/CUDA kernel code.

Thx again and please don't forget to close the issue

**Comment by philsmd** [comment]
Please close @trounce1 , @jsteube
