### ISSUE TITLE
Error `/usr/share/hashcat/OpenCL/inc_rp_optimized.h: No such file or directory` on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by TR-SLimey** [hashcat/hashcat#2562]
<details><summary>System Information</summary>

**OS**: `openSUSE Tumbleweed - Snapshot: 20200928`  
**Hashcat Version**: `v6.1.1`
**Hardware (as reported by lspci)**:

- `Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon Pro WX 4130/4150]`

- `Intel Corporation UHD Graphics 630 (Mobile)`

**Linux Kernel Version**: `5.8.10-1-default`  
</details>

I'm getting the aforementioned error when I'm trying to run `hashcat -b`. It may be worth noting that the file `inc_rp_optimized.cl` exists in that directory, just not `inc_rp_optimized.h`.

**Comment by jsteube** [comment]
Sorry, but not a hashcat problem, because hashcat does not install to /usr/share (only to /usr/local/share). This means you have some mixed version installations somehow, maybe some from distribution mixed with some manual installation. 

Also GitHub is for Bug Reports and Feature Requests only. Please use hashcat forum instead.

**Comment by rfrohl** [comment]
@TR-SLimey  FYI: that looks like a packaging error on the openSUSE side. I opened a bug for it: https://bugzilla.opensuse.org/show_bug.cgi?id=1177190

From the packaging side it looks like you could manually install the `hashcat-devel` package to work around the issue until there is a permanent fix. If you have further questions lets continue in the mentioned bugzilla bug.

**Comment by TR-SLimey** [comment]
@rfrohl installing hashcat-devel does indeed work. Thanks for the help and for reporting the bug :D
