### ISSUE TITLE
mask advice

### ISSUE THREAD

**Issue by trounce1** [hashcat/hashcat#2563]
Hi i would like to know if hashcat has a way to generate passwords like this

%milliseconds%S%M%H%d%m%Y'

it will look something like this "31505151811062020"

hashcat reduces my speed from 676M hashes to 1M hashes if i pipe it in from a simple python script

```python
for i in range(2020, 2021):

	i = str(i).rjust(4,'0')

	for j in range(1,13):

		j = str(j).rjust(2,'0')

		for k in range(1,32):

			k = str(k).rjust(2,'0')

			for l in range(1,24):

				l = str(l).rjust(2,'0')

				for m in range(0,61):

					m = str(m).rjust(2,'0')

					for n in range(0,61):

						n = str(n).rjust(2,'0')

						for o in range(0,1000):

							o = str(o).rjust(3,'0')

							print(o+n+m+l+k+j+i)
```
precomputing these for 6 years is a huge file ~10tb so i was looking to see if there are any better ways to generate.

Cheers

**Comment by philsmd** [comment]
In general, I would say that questions as general as this and where we can't really do much except answering an user question, should go to to hashcat forum.

This github issue tracker is mainly used for bug/issue reports and feature/algo requests... it shouldn't be misused for this kind of user "problems" / questions. Most of the questions like this indeed are already answered dozens of times in the hashcat forum/wiki/faq etc.

Please **close** (don't forget to close it, only you - the author/OP of the issue - and the owner of the repo can close github issues) this questions and find/ask for an answer in the hashcat forum at https://hashcat.net/forum/

To make this post a little bit more useful, I will give you some hints here (but this is an exception, normally we should just close them as invalid `issues`):
You could use several masks in a `hashcat mask file` (see https://hashcat.net/wiki/doku.php?id=mask_attack#hashcat_mask_files and https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#what_is_a_hashcat_mask_file)

I also see several problems with your definition, for instance I think this would be the correct way (and your definitions are wrong):
```
%H in 00-23 (hours),   (wrong was 01-23)
%M in 00-59 (minutes), (wrong was 00-60)
%S in 00-59 (seconds), (wrong was 00-60)
```
There must always be either an hour `24` or an hour `0` (more likely `0`).... also it's very unlikely that there is a minute `60`, normal clocks only have `59` as the max minute, but start with `0`. The same holds for seconds... your definition of %S (seconds) makes absolutely no sense to me, there can't be any, for instance, 12 o'clock and `60` seconds. that would be 1 minute after 12 o'clock and `0` seconds (max should be `59` seconds).

So I would define it like this instead:
```
%milli%S%M%H%d%m%Y
```
where:
```
%milli in 000-999
  %S in 00-59
    %M in 00-59
      %H in 00-23
        %d in 01-31
          %m in 01-12
            %Y in 2020-2021
```

BTW: I assume at least 2 years here: 2020 and 2021 for instance, but this is just an example (your definition only allowed 1 year: 2020). the min and max in my example are both included, unlike your python definition where the max is not within the set, I assume.

This could be written also as this in terms of built-in and custom charsets in hashcat (just one of the possibilities that should be correct):
```
%milli %S   %M   %H       %d              %m           %Y
?d?d?d ?1?d ?1?d ?2?d+2?3 0?4+1?d+2?d+3?2 0?1+10+11+12 2020+2021
```

(ATTENTION: note the `+` here is not a valid hashcat syntax, it's kind of a pseudo-code here, I just want to indicate that you need to use all the sub-masks that are combined with `+` here... this is just a way to express what is needed, not how the hashcat syntax works !!!)

where this could be the custom charsets (just one of the possibilities that should be correct):
```
-1 012345
-2 01
-3 0123
-4 123456789
```

Note: hashcat has a max. limit of 4 custom charsets, but it doesn't really matter much here, we can always use separate lines in the `.hcmask` file to work around this. That is why for some of the definitions above I used the `+` to conceptualise what needs to be done and how to approach this "problem".

Another way to express it would be this:
```
%milli
?d?d?d

%S
?1?d

%M
?1?d

%H
?2?d AND 2?3

%d
0?4 AND 1?d AND 2?d AND 3?2

%m
0?1 AND 10 AND 11 AND 12

%Y
2020 AND 2021
```
Here I just replaced the `+` with an `AND` to make it very clear that sometimes multiple masks are needed (most of the time because of the 4 custom charset limit, but also due to some of your masks having some "strange" limit like `23` for hours, so you need to combine at least 2 masks)

This (almost pseudo-code) definition can be converted into a `.hcmask` file like this (I can't guarantee that it's 100% correct and that you don't need to adapt it slightly, but it should give you an idea how to combine the different masks into a hashcat mask file):
```
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d0?40?12020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d0?40?12021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d0?4102020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d0?4102021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d0?4112020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d0?4112021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d0?4122020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d0?4122021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d1?d0?12020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d1?d0?12021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d1?d102020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d1?d102021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d1?d112020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d1?d112021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d1?d122020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d1?d122021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d2?d0?12020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d2?d0?12021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d2?d102020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d2?d102021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d2?d112020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d2?d112021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d2?d122020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d2?d122021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d3?20?12020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d3?20?12021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d3?2102020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d3?2102021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d3?2112020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d3?2112021
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d3?2122020
012345,01,0123,123456789,?d?d?d?1?d?1?d?2?d3?2122021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?30?40?12020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?30?40?12021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?30?4102020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?30?4102021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?30?4112020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?30?4112021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?30?4122020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?30?4122021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?31?d0?12020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?31?d0?12021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?31?d102020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?31?d102021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?31?d112020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?31?d112021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?31?d122020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?31?d122021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?32?d0?12020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?32?d0?12021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?32?d102020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?32?d102021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?32?d112020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?32?d112021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?32?d122020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?32?d122021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?33?20?12020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?33?20?12021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?33?2102020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?33?2102021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?33?2112020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?33?2112021
012345,01,0123,123456789,?d?d?d?1?d?1?d2?33?2122020
012345,01,0123,123456789,?d?d?d?1?d?1?d2?33?2122021
```

Please note that it often makes sense to prioritize some of the masks, for instance you could run all `2020` masks before the `2021` masks etc... this is up to the user to decide which one should be run first (I don't have this info what masks are more likely to crack the hashes etc, it's up to the user).

Also note that all the custom charset definitions (-1, -2, -3, -4) must be within the hashcat mask file (not outside on the command line). This is also explained in the wiki and FAQ.

I think this should give you enough hints to get it working and adapt it.

Please remember that next time you should ask questions like this in the hashcat forum **and do not forget to close** the issue.

Thanks

**Comment by trounce1** [comment]
This is really good advice @philsmd. Thanks
