### ISSUE TITLE
install_folder behaviour doesn't make sense

### ISSUE THREAD

**Issue by tautology0** [hashcat/hashcat#2572]
I've just spent ages trying to work out why hashcat insists on using the directory it is stored in instead of $HOME for its working files, such as *.pid, *.session and the kernels. We don't want to sully the hashcat directory and we don't want it to run as root.

So, as far as I can work it out, I **have** to install it in /usr/local/bin for this behaviour, which is set at compile time. This isn't documented any where; even the code is quite windy and there're no comments on what the expected behaviour is.

So if I want to run hashcat for multiple non-root users and follow the FHS then I need to recompile hashcat from source which is a tad overkill.

What would be expected is for hashcat to use $HOME as a default, or at least provide a switch to alter the base working directory. At the very least can we document this behaviour as it is counter-intuitive?

**Comment by tautology0** [comment]
What makes it worse is that as the code uses realpath() to check whether it's being run from install_folder you can't even use soft link magic to get it working.

**Comment by jsteube** [comment]
I think everything is fine here. Just run make install. 

If a user runs hashcat, no matter if root or not, the path described here will be used: https://github.com/hashcat/hashcat/pull/2456#issuecomment-855208179

Keep in mind that you can do something like this: make install PREFIX=/tmp

There's plenty of Linux distributions use the install target of hashcat.

**Comment by tautology0** [comment]
Hold on; the whole point is that users should be able to install standard hashcat not have to recompile it just to change the host directory. We're no longer in the 90s.

As a user of a *ix utility I'd expect a utility to store all of its working files in $HOME/.utility irrelevant of where the utility is stored. Just like pretty much every *ix utility. 

Worse case scenario at least allow the use of soft links, or *document* the behavior in the install guide. Having to hunt through the source to find out why the utility's behavior is counterintuitive doesn't make any sense.

**Comment by jsteube** [comment]
Wait, that is also how it was in the past. I also had to learn recently that using $HOME/.utility is outdated. Instead files should be stored in folders like .cache and .local and others. Before that, hashcat was writing to $HOME/.hashcat as you described.

For the other point, there's no way around hardcoding the install path into the binary. This is not an ancient mechanism, it's the oppsite. The only reason hashcat is checking that path is to find out if it should apply the "shared" folder mode or not. Basically hashcat has this "portable" mode, where no install target being used and all files are create in that folder where the hashcat binary is located in. 

It is a bit different that regular tools. We want to be friendly to new and unexperienced users who download the binary package from hashcat.net so that they can just run the binary and directly start working with the tool . The price for that is that experienced users have to recompile if they want to change the install folder, but they are experienced user so they should be able to do so. OTOH, many experience users enjoy the portal way, too. It is a trade-off.
