### ISSUE TITLE
Save all attempts into a .potfile 

### ISSUE THREAD

**Issue by okazymyrov** [hashcat/hashcat#2574]
I have not found an option to save "uncracked" attempts into a .potfile. The are plenty supported modes without salt. A very common example is NTLM. Tradeoff attacks would be very huge benefit in such scenarios.

User story/case: I would like to perform pre-computation of the passwords agains one algorithm (obviously without a salt). Then use multiple hash files with a large .potfile to speedup the attack.

**Comment by philsmd** [comment]
The problem is that this is not the goal of a password **cracker**.

What your a looking for is a hash generation tool. Fortunately, hashcat has a tool that generates hashes too (for testing purpose: our test framework): it's `tools/test.pl`

With the `passthrough` command of `tools/test.pl` you can generate hashes.

So why can't hashcat output all the hashes it computes? Because it would just be absurd. I/O (input and output) is just a huge problem: we call it the bottleneck. You can't have the fastest password cracker generate hashes as quickly as it is supposed to do and print all of them or store them to disk at the same time (with the same speed). It just doesn't work mathematically/physically (GPU register speed, RAM speed, SSD speed, they are significantly different and having a speed that is slower by a factor of thousands or more is of course very, very bad).

Furthermore, I think the concept that you are generally talking about is a `rainbow table` and professional password cracker actually do NOT use it since years/decades, because in most of the cases it doesn't make sense (the extra cost and only in very, very specific cases it's a little bit faster.... but mostly with slow-algo and salted hashes with fixed/static salts etc, like the algorithm design flaw in 7-Zip, which normally use an empty salt, or similar). The cost of storing and maintaining a `rainbow table` is often not worth it, because you can just crack the hashes almost as quickly by just launching a password cracker, that computes the hashes on-the-fly. ... and of course with salted hashes (long random salts) it doesn't really make any sense and doesn't work to attack the hashes with a rainbow table.

Therefore, I suggest to use `tools/test.pl` which is actually also very fast (because again I/O, outputting/storing the data is the bottleneck) and do not forget to **close** this issue. Thx
