### ISSUE TITLE
Feature Request: Better checkpointing for salted hashes

### ISSUE THREAD

**Issue by llamasoft** [hashcat/hashcat#2575]
When dealing with massive salted hash lists (1M+ hashes) it can take _hours_ to reach a checkpoint.

This seems to be an indirect consequence of a few different factors:

- Checkpoints appear to be based on completing candidate batches.
- Candidate batches can be rather large (over 500k entries by my estimate).
- A candidate batch isn't considered complete until it's been tried against _every_ salt.
- The attack order seems to be salt-first instead of candidate-first.
  - Salt-first being akin to `for (batch in batches) { for (salt in salts) { for (word in batch) { ... } } }`
  - Candidate-first being akin to `for (batch in batches) { for (word in batch) { for (salt in salts) { ... } } }`

When taken together, these cause the checkpoint rate for salted hashes to be orders of magnitude slower than unsalted hashes.

Personally, I'd love to see the option to do candidate-first attack ordering.  While it doesn't make sense for most situations, it does make sense when the number of salts exceeds the number of candidates in a batch.  It's also incredibly helpful when you have a wordlist that's sorted by success rate, where a vast majority of hashes can be cracked within the first few thousand words.  This has the benefit of getting the "easy" hashes out of the way first allowing you to apply more elaborate rules to the "hard" hashes.  Candidate-first ordering would also make it so that batch size wouldn't affect performance as much.

For the time being I've worked around this by splitting my wordlist into chunks small enough to force a smaller candidate batch size, but this comes with the drawback of a considerably hash rate penalty.

**Comment by Wingman4l7** [comment]
In general, I'm surprised there's not a command-line flag you can add to customize how frequent checkpointing is, to prevent being stuck between deciding to either waste hours of hashing time or be forced to leave a session running.

**Comment by jsteube** [comment]
The reason why hashcat works the way is because wordlist sizes can be of arbitrary size. Some wordlists consists of 100GB an more and there's simply no GPU which can load the full wordlist content in one piece. 

IOW, hashcat has to create chunks of words from the wordlist (what you call batches) and copy this data over PCI-Express and then restart the cracking kernel on GPU. But the copy of this data is very costly. For details see here: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#does_the_pci-express_speed_have_any_influence_on_cracking_speed

> If you go for wordlist based attacks, the only difference is how long it takes for your host system to copy new wordlist data to your GPU. While it copies the data, the GPU is busy and can not compute. For example with PCI-E v2.0 x1 we can do 4 Gbit/s and with x16 we can do 64 Gbit/s. This sounds like alot, but it's not. First this number is bits not bytes and more important this is the speed per second. We also meassure guessing speed in X per second, that means if we take a full second to transfer a specific amount of data the guessing speed is 0. That means, to not influence with guessing speed we need to be able to transfer our wordlist data in less than a percent of a second.

IOW, this is so significant that it reduces all the GPU power to a level the GPU will be no much faster than a CPU (unless it's a slow hash). The only way to workaround this issue is by using amplifiers. So, if we'd put the salt iteration to the outer loop, this would multiply the PCI-E transfer time by the number of unique salts. If there are amplifiers involved, the effect of this copy probably can be workarounded, but this enforces the user to use amplifiers. Especially when it comes to large salted hashlists this is what you want to avoid, because it will multiply on top of the salt multiplier. 

The trick by using the words first is that this removes the need for an amplifier. Because the number of unique salts is typically in a range that is not that large that we can fully store it on GPU memory, we only transfer that information once in the beginning. The iteration through the salts now acts like a fake amplifier because there's no data being copied. In the end, this is he best architecture to achieve high GPU utilization.

---

The other thing is that you want to reduce the checkpoint. Well, that's not possible because of the above optimization. So you want to be able to check out while in the midst of an salt inner loop. But this would break restore logic. Lets say we processed 100/1000 words and run in steps of 100, so we're now at position 100. The inner salt iteration loop is running at 20/50 and now you want to checkpoint quit. So the restore file stores only 100/1000. We can make it to store either 100/1000 or 200/1000. But both cases would be bad. For the first you will simply lose all the progress already being done and depending on attack parameters this can be days of work. And if you go to 200/1000 you maybe missed valid positives and false negatives is really a no go. 

Now you can say then store 100/1000 and 20/50 so that hashcat can restart simply at this position. That's in theory possible and in the very first version of hashcat it was implemented like this. But we dropped it, because in reality it becomes too complex, especially because of the rejects. It is possible that from that 100/1000 words there was 99 words which were rejected because of password length restrictions. If we restart we lose this "information", but it is important otherwise the ETA will be incorrect. We could add the position of the word which was rejected, but the number of words that would be affected by rejected is arbitrary because the wordlists have arbitrary sizes. So in theory a restore files could become as big as a wordlist, that is 100GB or more.

---

The best way to deal with this situation to make better attacks. Keep in mind that -S is really good when having small wordlists with large amplifiers or simply to not use amplifiers. Finally you can also use the hashcat API to do that salt based outer loop yourself.

**Comment by llamasoft** [comment]
Thanks for the feedback @jsteube.  I fully understand that transferring data to the GPU can be a massive bottleneck especially when the number of salt iterations is comparatively low.  Ideally we don't want it to happen _too_ often, otherwise we spend more time transferring data than calculating hashes.  However, the extreme inverse of this isn't good either.  If we're transferring chunks too infrequently then checkpoints are going to end up being hours apart.

Maybe there's some sort of middle ground compromise that doesn't require changing the loop ordering?  For example, adjusting the chunk size based on the number of salt iterations so that `(words_in_chunk * salt iterations) / hashrate = target_checkpoint_interval`?  It doesn't even need to be an exact calculation, just an approximation to make sure that the chunk copy interval isn't orders of magnitude longer than the checkpoint interval.

But I know ideas are easier than implementation.  I'll defer to your expertise on how feasible this approach is.
