### ISSUE TITLE
OpenCL kernel self-test failed

### ISSUE THREAD

**Issue by AgataImiolek** [hashcat/hashcat#2580]
Hi,

Could someone help me resolve the issue shown on the print screens below? I am completely new to hashcat and github, I've been trying to learn how to use hashcat from youtube videos and articles that I found online. I feel like I have followed every step that I was supposed to, however, I keep on getting this message. I am not sure what to do, I have tried my best to figure this out but nothing seems to be working. I am using Acer Extensa 2540, processor: Intel(R) Core(TM) i5-7200U CPU @2.50GHz 2.70GHz, 4.00GB RAM, 64-bit Operating System, x64-based processor.

Kind regards,

Agata 
![image](https://user-images.githubusercontent.com/72476073/95898042-5eab5e80-0d86-11eb-8863-5244b9daacd7.png)

![image](https://user-images.githubusercontent.com/72476073/95898087-6e2aa780-0d86-11eb-8944-365dc02dd3f0.png)

**Comment by philsmd** [comment]
Unfortunately, there is little we can do here.

It seems like a driver problem / bug, because the exact same code works on very many other OpenCL-compatible devices and with many, many other OpenCL-compatible drivers (NVIDIA, AMD, CPU drivers etc).

You could use `-D 1` (upper-case D 1)  for now and make sure that the OpenCL driver for your CPU is correctly installed (it seems that you have already installed this).

It's also discouraged to use notebooks for hash cracking jobs (at least if you do it for several hours/days). They don't have the cooling solutions required for such heavy tasks like hash cracking.

Please test with `-D 1` and do not forget to **close** this issue

Thx

**Comment by AgataImiolek** [comment]
I've figured it out and got it to work :)Thank you anyway!

**Comment by Vedant0704** [comment]
@AgataImiolek  How did it worked? can you please tell. I have the same issue

**Comment by AgataImiolek** [comment]
@Vedant0704 Hey, I ended up using a virtual machine and running the hashcat on there. Also, I got a new laptop. I recommend David Bombal's youtube channel, he has a lot of useful tutorials on there and it is one of the main resources that I use for learning new things. ( Fyi I am not an expert on this, I am just a chemistry student trying to get my head around things in my free time so probably not the best person to ask 😅).
