### ISSUE TITLE
add ranges to charset lists

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#2581]
Ironically, I've encountered a few cases where people misunderstood what the fully-enumerated character sets mean. I'd like to propose adding some abbreviated ranges as well.

Maybe

```
  l | [a-z]    - abcdefghijklmnopqrstuvwxyz
  u | [A-Z]    - ABCDEFGHIJKLMNOPQRSTUVWXYZ
  d | [0-9]    - 0123456789
  h | [0-9a-f] - 0123456789abcdef
  H | [0-9A-F] - 0123456789ABCDEF
  s |  !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
  a | ?l?u?d?s
  b | 0x00 - 0xff

```
or

```
  l | abcdefghijklmnopqrstuvwxyz [a-z]
  u | ABCDEFGHIJKLMNOPQRSTUVWXYZ [A-Z]
  d | 0123456789                 [0-9]
  h | 0123456789abcdef           [0-9a-f]
  H | 0123456789ABCDEF           [0-9A-F]
  s |  !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
  a | ?l?u?d?s
  b | 0x00 - 0xff
```
... could work.

**Comment by philsmd** [comment]
I'm not really against it. but also not sure if it really helps a lot (does the average hashcat user understand the bracket syntax better, should we maybe add multiple columns and a table header to explain the columns etc ?)

In my experience, the most weird requests / questions I got about this list is that users tried to run ?h as it was ?1 where -1 is defined as `-1 ?d?l`)... so for some reasons users think `0123456789abcdef` means `0123456789abcdef...` (all letters instead of only hexadecimal).

Maybe we could just add some notes above and below the list (to explain what the list means and afterwards what you could do if what the user wants is not exactly within that list) to make it very clear how to use custom charset and maybe also add the ?d?l example etc

Thx for the request

**Comment by jsteube** [comment]
Lets keep it simple and see what's happening. Added with commit https://github.com/hashcat/hashcat/commit/2aff6cba512dfa79c14a66467561cf49fef7b934
