### ISSUE TITLE
MSSQL (2012, 2014) hash generate code support

### ISSUE THREAD

**Issue by CptGuo** [hashcat/hashcat#2588]
Hello Master
  I need to use python to generate MSSQL(2012 2014) hash, do u mind support example code.
  3Q.

**Comment by philsmd** [comment]
Hey,

normally we do not allow / reply to request like this in the github issue section (because this is mainly used for problem/bug fixes or algorithm/feature requests).

The hashcat forum (there is even a developer section), is much much more suitable for such requests.

Anyway, the code should be something like this:
```python
#!/usr/bin/env python3

from hashlib import sha512

password = "hashcat"
salt     = b'\x37\x88\x00\x67' # or unhexlify ("37880067") or bytes.fromhex ("37880067")

password_utf16 = password.encode ("UTF-16LE")

digest = sha512 (password_utf16 + salt).digest ()

# conversion to upper case hex is not required for hashcat, but MSSQL uses uppercase

salt_hex   = salt  .hex ().upper ()
digest_hex = digest.hex ().upper ()

output = ("0x0200%s%s" % (salt_hex, digest_hex))

print (output)
```

We also have a perl test framework which is also very easy to understand and easy to read, so you could just have a look at this for any similar doubts/questions:
https://github.com/hashcat/hashcat/blob/15bf8b7302fd2febd93845eb26d60efed6255bae/tools/test_modules/m01731.pm#L23

Please do **not** forget to close this issue. Only you and the owner of the github project are able to close issues (permissions).

Thx

**Comment by CptGuo** [comment]
Thx a lot.
I won't do it agent, sorry.
