### ISSUE TITLE
Wrong limits for -m 20710 = sha256(sha256($pass).$salt)

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#2595]
This hash type was introduced with commit https://github.com/hashcat/hashcat/pull/2128 and some users found out in the forum that the limits (only salt ?) are quite strange/wrong: see https://hashcat.net/forum/thread-9561.html

It's not clear what the exact limits of salt type are and it also seems that the module doesn't restrict the salt type for optimized kernel (-O runs).

This is also strange:
https://github.com/hashcat/hashcat/blob/15bf8b7302fd2febd93845eb26d60efed6255bae/tools/test_modules/m20710.pm#L13

why should there be this limitation `[16,16]` ? why can't the salt be for instance only 1 (or even 0) char long for such a generic hash type ? A range of 16-16 makes no sense for me.

I'm also not convinced about this line in the optimized kernels (all of them, -a 0, 1, 3):
https://github.com/hashcat/hashcat/blob/15bf8b7302fd2febd93845eb26d60efed6255bae/OpenCL/m20710_a0-optimized.cl#L385

why do we need this check, special case ? Shouldn't the optimized kernel just allow everything below such special cases ? Should we really need to have this in an **optimized** kernel ?

All in all, I wanted to answer the forum post with a clear explanation, but it turns out I'm myself confused about the limits and why there are no clear limits defined in the hash module for maximum salt length for optimized kernels and why we need such special cases.

Maybe somebody can troubleshoot / investigate this and/or maybe @matrix can fix and explain this problem.

Thanks a lot

**Comment by matrix** [comment]
Hi @philsmd, how are you ? I hope all is well.

The constraints of 20710 it's a typo, the good one most likely it is the following:

`
sub module_constraints { [[0, 256], [0, 256], [0, 55], [0, 51], [-1, -1]] }
`

as hashcat print when it starts, at least (I hope) those are correct :)

For the second issue, these "if" can be removed in all optimized kernels.

I do some testing as soon as possible and then send out a patch to fix both.

I hope it's clearer to you now, otherwise I'll come to IRC one of these evenings and we'll talk about it.

Thanks to you,
matrix

**Comment by jsteube** [comment]
Fix was merged
