### ISSUE TITLE
Started a business and forgot passwords

### ISSUE THREAD

**Issue by JeromeMcGinn** [hashcat/hashcat#2604]

**Comment by NathanielJS1541** [comment]
You might have more help looking/asking on the [hashcat Forum](https://hashcat.net/forum/), as far as I'm aware the issues tab is usually to report bugs or errors. Your issue is also not clear at all. There's a description box for a reason: things you've already tried, what specifically you're having trouble with etc. Have you looked at the WiKi for example? Currently your issue does not seem to be related to hashcat at all so does not belong here.
