### ISSUE TITLE
Feature: Set BRAIN_ENABLED value when compiled with/without brain

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#2611]
Currently when compiling, WITH_BRAIN is checked to know whether or not to include the BRAIN related features, allowing users to disable/remove brain related features at compile time. When this happens, any code wrapped in a conditional to check for WITH_BRAIN will be left out if it is not present, however we do not set anything specifying that the brain features have been disabled. We should set a value in the context that can be queried to check if brain is enabled, e.g. hashcat_ctx->brained_enabled = "false". This is especially useful to users building from libhashcat who may want to support installations with/without brain enabled and need to be able to check this quickly and cleanly.

**Comment by ventaquil** [comment]
That would be nice 👍 

I think that brain features should be moved away from `hashcat_ctx_t` because size of this struct is different when brain is enabled or disabled.

**Comment by ventaquil** [comment]
@jsteube what do you think about creating some `brain_ctx_t` struct with brain-specified options (at least `enabled: bool` field)?

It's difficult to handle it when Hashcat is used as a library because `hashcat_ctx_t` struct has different sizes depending on compilation flags.

**Comment by jsteube** [comment]
Yeah, it makes sense. The question is the exact way how to do it.

**Comment by jsteube** [comment]
I just double checked the hashcat_ctx_t struct, but I don't see why brain feature should have an influence on its size. This is a snippet from current master:

```
typedef struct hashcat_ctx
{
  bitmap_ctx_t          *bitmap_ctx;
  combinator_ctx_t      *combinator_ctx;
  cpt_ctx_t             *cpt_ctx;
  debugfile_ctx_t       *debugfile_ctx;
  dictstat_ctx_t        *dictstat_ctx;
  event_ctx_t           *event_ctx;
  folder_config_t       *folder_config;
  hashcat_user_t        *hashcat_user;
  hashconfig_t          *hashconfig;
  hashes_t              *hashes;
  hwmon_ctx_t           *hwmon_ctx;
  induct_ctx_t          *induct_ctx;
  logfile_ctx_t         *logfile_ctx;
  loopback_ctx_t        *loopback_ctx;
  mask_ctx_t            *mask_ctx;
  module_ctx_t          *module_ctx;
  backend_ctx_t         *backend_ctx;
  outcheck_ctx_t        *outcheck_ctx;
  outfile_ctx_t         *outfile_ctx;
  pidfile_ctx_t         *pidfile_ctx;
  potfile_ctx_t         *potfile_ctx;
  restore_ctx_t         *restore_ctx;
  status_ctx_t          *status_ctx;
  straight_ctx_t        *straight_ctx;
  tuning_db_t           *tuning_db;
  user_options_extra_t  *user_options_extra;
  user_options_t        *user_options;
  wl_data_t             *wl_data;

  void (*event) (const u32, struct hashcat_ctx *, const void *, const size_t);

} hashcat_ctx_t;
```

Or did you mean that the size would change for the future case in which we would have added this brained_enabled flag? It wasn't so clear to me from your description. But even then, the size would not change because the bool flag would be always present, otherwise it would make no sense.

---

However, when it comes to struct sizes that could be relevant, there are other structs like user_options_defaults where the brain feature has an influence:

```

typedef enum user_options_defaults
{
  ADVICE_DISABLE           = false,
  ATTACK_MODE              = ATTACK_MODE_STRAIGHT,
  AUTODETECT               = false,
  BENCHMARK_ALL            = false,
  BENCHMARK                = false,
  BITMAP_MAX               = 18,
  BITMAP_MIN               = 16,
  #ifdef WITH_BRAIN
  BRAIN_CLIENT             = false,
  BRAIN_CLIENT_FEATURES    = 2,
  BRAIN_PORT               = 6863,
  BRAIN_SERVER             = false,
  BRAIN_SESSION            = 0,
  #endif
  DEBUG_MODE               = 0,
  FORCE                    = false,
....
```

For some of them, we could lift this if clause, but it's important to understand why we are so picky about brain features.

1. In server mode it creates a listening socket, which makes it vulnerable to all sort of network based attacks. Of course, the network code is written with high attack resistance, but there can never be a guarantee
2. In client mode it still has to call socket() and this creates a lot more attention to the hashcat process by AV/Security products in general. Here's the policy more like why going there if it's not needed

We could life some of the if clauses (like the above) because they are not directly related to any socket/network code, but then we have a half/half situation. I would prefer not to change anything to the if clauses unless there's a real good scenario to do so. @ventaquil if you have anything in mind please let me know!

---

Coming back to the original request from @Chick3nman which I still find valid. I'll push some changes later.

**Comment by jsteube** [comment]
Added with commit https://github.com/hashcat/hashcat/commit/dcaba1f4737176334a80461f145fa31657bb481f

**Comment by ventaquil** [comment]
Sorry @jsteube - my fault. The problem was in `user_options_t` struct - it causes errors when you used brain-enabled user options in your program by using brain-disabled library - and vice versa as far as I remember.

I am not sure that dcaba1f fix it out. I am going to prepare some demos in my spare time.
