### ISSUE TITLE
UnRAR dependency licensing

### ISSUE THREAD

**Issue by xvitaly** [hashcat/hashcat#2614]
Please make UnRAR dependency optional. UnRAR is a non-free software. Most of GNU/Linux distributions cannot package and redistribute it.

Now we cannot even use the official tarball due to the bundled UnRAR sources.

**Comment by xvitaly** [comment]
@jsteube Please fix this legal issue. As a Fedora maintainer, I'm unable to update hashcat to 6.2.0.

**Comment by jsteube** [comment]
Hey there I was away for a while and I just found your issue since you had it updated. The license clearly allows the distribution:

```
      Distribution of modified UnRAR source code in separate form
      or as a part of other software is permitted, provided that
      full text of this paragraph, starting from "UnRAR source code"
      words, is included in license, or in documentation if license
      is not available, and in source code comments of resulting package.
```

However if it's more easy for to workaround this dependency I can make it optional. The questions is just how. So for example we could add an option in the Makefile, something like USE_UNRAR=1, which you can set to zero and it will not compile the relate plugin.

But still, the source would be in the deps/unrar/ folder of the GitHub hashcat repository. Is that a problem for you? In that case we'd need to wget the unrar sources during the compilation phase and patch it afterwards. That's not so nice for several reasons. The user would need to have an internet connection and is also possible the sources move away from the http location we will define in the Makefile.

**Comment by xvitaly** [comment]
> The license clearly allows the distribution:

This is a proprietary license aka "freeware". Fedora, Debian and most of other GNU/Linux distributions strictly forbid shipping non-free components even in source tarballs.

> However if it's more easy for to workaround this dependency I can make it optional. The questions is just how. So for example we could add an option in the Makefile, something like USE_UNRAR=1, which you can set to zero and it will not compile the relate plugin.

`USE_UNRAR ?= 1` will be okay, IMO.

> But still, the source would be in the deps/unrar/ folder of the GitHub hashcat repository. Is that a problem for you?

Yes. I will need to manually strip tarball and make my own without unrar sources. This is normal and easy to automate.

**Comment by jsteube** [comment]
I just pushed commit https://github.com/hashcat/hashcat/commit/ce90f83b655070d10e6cffea425a7dbc1f77575e

The variable name is ENABLE_UNRAR. You can set it to zero and it will not compile -m 23800 module. Please let me know if it works for you so I can create hashcat 6.2.1.

**Comment by xvitaly** [comment]
> The variable name is ENABLE_UNRAR. You can set it to zero and it will not compile -m 23800 module

Great. Many thanks.

> Please let me know if it works for you so I can create hashcat 6.2.1.

I will try to build with this patch soon.

**Comment by xvitaly** [comment]
> Please let me know if it works for you so I can create hashcat 6.2.1.

Works fine. Thanks.

**Comment by jsteube** [comment]
OK, new release is up. Please close issue if everything is ok.
