### ISSUE TITLE
Veracrypt the maximum password length is larger than 64

### ISSUE THREAD

**Issue by Sh-Eng** [hashcat/hashcat#2616]
Vearcrypt can support 128 bytes password length now.
So far, the latest version support 64 bytes password length, trying to support up to 128 bytes, unfortunately, failed.
can give some suggestion? thanks

**Comment by ventaquil** [comment]
If you have module file (in example `src/modules/module_13711.c`) there is `module_pw_max` function which determines password max length as far as I know.

**Comment by Sh-Eng** [comment]
thanks, yes, but it doesn't work well if only change the module_pw_max value up to 128 bytes, maybe need  to modify some function code in module_13711.c or in module_13711.cl, I have no idea.

**Comment by ventaquil** [comment]
I see that `64` is used in some places in kernel files so it needs more work to change 😢

**Comment by Sh-Eng** [comment]
It looks like this work will take some time, do you have any plans to upgrade it, hope you will do :)
Or, can you give some guide to the kernel file modification

**Comment by ventaquil** [comment]
I can to try it but I need one or two weeks.

Can you put here some reference about change from 64 to 128 length password in VeraCrypt?

**Comment by Sh-Eng** [comment]
[samples.zip](https://github.com/hashcat/hashcat/files/5612640/samples.zip)
thanks, here is some samples with different mode, please check it.

**Comment by ventaquil** [comment]
Change password length from 64 to 128 bytes comes from VeraCrypt 1.24 release from 6th October 2019 - [Release Notes](https://www.veracrypt.fr/en/Release%20Notes.html).

**Comment by jsteube** [comment]
VeraCrypt: Increase password length support for non-boot volumes from 64 to 128 with commit https://github.com/hashcat/hashcat/commit/62397283c107f79f37acfa6f21147a1d069a49a5

This change was more work intense than expected, mainly because key files have a weird effect on how passwords > block size are handled compared to how passwords > block size are handled without key files. 

In total 3453 lines of source code were changed. The change does not only include the support for 128 byte passwords. I also refactored the code handling key files in general to easier react to changes to key file handling in case VeraCrypt changes something again in the future.

The only thing I was unsure is how to deal with RipeMD160. Attention @Sh-Eng this is about the change to the 13711 mode, the one you wanted to change. This hash seems to have been removed as a selection for non-boot volumes in VeraCrypt before the extension to 128 byte passwords was added. While this hash would also support passwords of length 128 (the same way as for instance SHA256 does) it was never implemented as such at the time when it was still supported. For that reason I did not touch RipeMD160 password limit simply because it's not expected to face RipeMD160 volumes with passwords > length 64 and hashcat users will benefit from automatic password rejects for passwords > length 64. However, I had prepared the RipeMD160 module and kernel the same way. If we find out that there's actually support for RipeMD160 with passwords > 64 and with this new commit, then we only need to update the module from 64 to 128 the @Sh-Eng tried to do in the initial post.

For the boot volumes I saw from the VeraCrypt sources the 64 byte limit is still in place. For them I also did not change the limit. It would be nice if someone can do same real life tests, because creating these kind of artificial headers is not that simple.
