### ISSUE TITLE
--runtime= progress report in dictionary attacks (-a 0) not correct hashcat version >= v4.1.0 for certain attack modes

### ISSUE THREAD

**Issue by cryptolovi** [hashcat/hashcat#2629]
The method of using --runtime=XXX of hashcat and measuring the keyspace progress is partly broken since hashcat v4.1.0 for dictionary attacks (and sometimes bruteforce) in atleast the VeraCrypt modes, and possibly others. The problem is that the progress is reported as zero, even with runtimes of upto 600 seconds or more where there should have been progress.
The use of runtime benchmark in distribution frameworks like hashtopolis can be used because speed-only benchmark can spike too much at the beginning of an attack which results in faster speeds reported in the begin then after a while.

reproduction steps in a form for easy copy&paste;
(getting and compiling version v6.1.1, v4.1.0 and v4.0.1)
```
git clone http://github.com/hashcat/hashcat.git --branch v6.1.1 hashcat-v6.1.1;cd hashcat-v6.1.1;make;cd ..
git clone http://github.com/hashcat/hashcat.git --branch v4.1.0 hashcat-v4.1.0;cd hashcat-v4.1.0;git submodule update --init;make;cd ..
git clone http://github.com/hashcat/hashcat.git --branch v4.0.1 hashcat-v4.0.1;cd hashcat-v4.0.1;git submodule update --init;make;cd ..
```
(getting example key material)
`wget https://hashcat.net/misc/example_hashes/vc/hashcat_ripemd160_aes_13711.vc`
(optional: check each version finding the password with bruteforce -a 3)
```
./hashcat-v6.1.1/hashcat -m 13711 --potfile-disable -a 3 hashcat_ripemd160_aes_13711.vc hashca?l
./hashcat-v4.1.0/hashcat -m 13711 --potfile-disable -a 3 hashcat_ripemd160_aes_13711.vc hashca?l
./hashcat-v4.0.1/hashcat -m 13711 --potfile-disable -a 3 hashcat_ripemd160_aes_13711.vc hashca?l
```
(check runtime progress on bruteforce, the progress is highlighted bold but within a code block so it defaults to ** xx **)

**v6.1.1** bruteforce ?l?l?l --runtime=300;
`./hashcat-v6.1.1/hashcat -m 13711 --potfile-disable -a 3 hashcat_ripemd160_aes_13711.vc ?l?l?l --runtime=300
`
```
Session..........: hashcat                       
Status...........: Aborted (Runtime)
Hash.Name........: VeraCrypt RIPEMD160 + XTS 512 bit
Hash.Target......: hashcat_ripemd160_aes_13711.vc
Time.Started.....: Thu Dec  3 13:43:45 2020 (5 mins, 0 secs)
Time.Estimated...: Thu Dec  3 13:57:50 2020 (9 mins, 5 secs; Runtime limit exceeded)
Guess.Mask.......: ?l?l?l [3]
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:       21 H/s (0.16ms) @ Accel:16 Loops:7 Thr:1024 Vec:1
Recovered........: 0/1 (0.00%) Digests
**Progress.........: 6084/17576 (34.62%)**
Rejected.........: 0/6084 (0.00%)
Restore.Point....: 0/676 (0.00%)
--snip, removed Candidates and HWMON--

```

**v4.1.0** bruteforce ?l?l?l --runtime=300
`./hashcat-v4.1.0/hashcat -m 13711 --potfile-disable -a 3 hashcat_ripemd160_aes_13711.vc ?l?l?l --runtime=300
`
```
Session..........: hashcat                       
Status...........: Aborted (Runtime)
Hash.Type........: VeraCrypt PBKDF2-HMAC-RIPEMD160 + XTS 512 bit
Hash.Target......: hashcat_ripemd160_aes_13711.vc
Time.Started.....: Thu Dec  3 13:55:42 2020 (5 mins, 0 secs)
Time.Estimated...: Thu Dec  3 14:03:40 2020 (2 mins, 58 secs; Runtime limit exceeded)
Guess.Mask.......: ?l?l?l [3]
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#2.....:       38 H/s (0.38ms) @ Accel:32 Loops:16 Thr:256 Vec:1
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
**Progress.........: 10816/17576 (61.54%)**
Rejected.........: 0/10816 (0.00%)
Restore.Point....: 0/676 (0.00%)
--snip, removed Candidates and HWMON--
```

**v4.0.1** bruteforce ?l?l?l --runtime=300
./hashcat-v4.0.1/hashcat -m 13711 --potfile-disable -a 3 hashcat_ripemd160_aes_13711.vc ?l?l?l --runtime=300

```
Session..........: hashcat                                
Status...........: Aborted (Runtime)
Hash.Type........: VeraCrypt PBKDF2-HMAC-RIPEMD160 + XTS 512 bit
Hash.Target......: hashcat_ripemd160_aes_13711.vc
Time.Started.....: Thu Dec  3 14:08:02 2020 (5 mins, 0 secs)
Time.Estimated...: Thu Dec  3 14:15:17 2020 (2 mins, 15 secs; Runtime limit exceeded)
Guess.Mask.......: ?l?l?l [3]
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#2.....:       40 H/s (1.51ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
**Progress.........: 12168/17576 (69.23%)**
Rejected.........: 0/12168 (0.00%)
Restore.Point....: 0/676 (0.00%)
--snip, removed Candidates and HWMON--
```

As you can see progress in each attack, but now for dictionary attacks (adjusting runtime to 200 because 300 is full keyspace in v4.1.0, and adjusting to 100 because runtime 200 is full keyspace in v4.0.1: point is, if runtime is reached progress should be reported)

**v6.1.1** dictionary example.dict (from hashcat) --runtime=200
`./hashcat-v6.1.1/hashcat -m 13711 --potfile-disable -a 0 hashcat_ripemd160_aes_13711.vc ./hashcat-v6.1.1/example.dict --runtime=200`

```
Session..........: hashcat                       
Status...........: Aborted (Runtime)
Hash.Name........: VeraCrypt RIPEMD160 + XTS 512 bit
Hash.Target......: hashcat_ripemd160_aes_13711.vc
Time.Started.....: Thu Dec  3 14:44:16 2020 (3 mins, 20 secs)
Time.Estimated...: Thu Dec  3 14:52:37 2020 (5 mins, 1 sec; Runtime limit exceeded)
Guess.Base.......: File (./hashcat-v6.1.1/example.dict)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:      426 H/s (1.62ms) @ Accel:16 Loops:7 Thr:1024 Vec:1
Recovered........: 0/1 (0.00%) Digests
**Progress.........: 0/128416 (0.00%)**
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/128416 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:434763-434770
--snip, removed Candidates and HWMON--
```

**v4.1.0** dictionary example.dict (from hashcat) --runtime=200
`./hashcat-v4.1.0/hashcat -m 13711 --potfile-disable -a 0 hashcat_ripemd160_aes_13711.vc ./hashcat-v6.1.1/example.dict --runtime=200 `

```
Session..........: hashcat                       
Status...........: Aborted (Runtime)
Hash.Type........: VeraCrypt PBKDF2-HMAC-RIPEMD160 + XTS 512 bit
Hash.Target......: hashcat_ripemd160_aes_13711.vc
Time.Started.....: Thu Dec  3 14:37:27 2020 (3 mins, 20 secs)
Time.Estimated...: Thu Dec  3 14:45:16 2020 (4 mins, 29 secs; Runtime limit exceeded)
Guess.Base.......: File (./hashcat-v6.1.1/example.dict)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#2.....:      476 H/s (6.67ms) @ Accel:32 Loops:16 Thr:256 Vec:1
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
**Progress.........: 0/128416 (0.00%)**
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/128416 (0.00%)
--snip, removed Candidates and HWMON--
```

**v4.0.1** dictionary example.dict (from hashcat) --runtime=200
`./hashcat-v4.0.1/hashcat -m 13711 --potfile-disable -a 0 hashcat_ripemd160_aes_13711.vc ./hashcat-v6.1.1/example.dict --runtime=100
`
```
Session..........: hashcat                                
Status...........: Aborted (Runtime)
Hash.Type........: VeraCrypt PBKDF2-HMAC-RIPEMD160 + XTS 512 bit
Hash.Target......: hashcat_ripemd160_aes_13711.vc
Time.Started.....: Thu Dec  3 14:53:04 2020 (1 min, 40 secs)
Time.Estimated...: Thu Dec  3 14:55:14 2020 (30 secs; Runtime limit exceeded)
Guess.Base.......: File (./hashcat-v6.1.1/example.dict)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#2.....:      985 H/s (8.66ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
**Progress.........: 98304/128416 (76.55%)**
Rejected.........: 0/98304 (0.00%)
Restore.Point....: 49152/128416 (38.28%)
```

As you can see only for version v4.0.1 progress is reported when runtime is reached.

PS. I could have chosen a larger dictionary so I wouldn't have to adjust runtime.

**Comment by jsteube** [comment]
Thank you for the comprehensive description. From my perspective everything works as it should.

One need to understand that hashcat can only save the progress in case all password candidates from a workload chunk were processed in full. In this mode 13711 (and without a user defined pim) that means that hashcat needs to reach KDF iteration 655331 in order to save it. But from your screenshot it's clearly below that:

```
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:434763-434770
```

I think the main confusion is caused by two different factors which add up.

1. Older hashcat version do not support cracking of dynamic PIM ranges. They are therefore slightly faster because they do not need to store intermediate values in global memory. The slow down causes by this is minimal, it just looks like a drastic performance drop in case the attack (such as the mask you use) is bad because it creates too less work items. If you select a normal mask, such as ?l?l?l?l?l?l?l?l you will find it's just a few percent. In the end I had this added because it is a beneficial trade off.
2. Using hashcat in -a 3 mode creates too low work item count to have the GPU running in full utilization. Have a look at the hardware monitor output and compare the device utilization between the wordlist and the ?l?l?l mask. You will find the mask to be used much lower. So the utilization is lower, but that means that less candidates can be processed faster. IOW, they reach the 515000 iterations much faster. But that doesn't make it faster in general - only in underutilized cases. If you run the attack with a mask that is largely enough so that hashcat has enough workitems to reach a 99% utilization, then you will find that the total number of password guessed per second is higher and that's what's important.

So what's actually happening is that the 4.x version is sooner to reach the finish line while the others did not reach it in time. But that's not a bug or a general slow down. It's just a badly designed attack configuration. If you want a quick test for that wordlist scenario, just set a lower pim. For instance --veracrypt-pim-start 100 --veracrypt-pim-stop 100 (or just --veracrypt-pim 100 in older hashcat versions).

Feel free to reopen if there's anything missing.
