### ISSUE TITLE
Enhancement: Hashcat brain performance ("send attack positions")

### ISSUE THREAD

**Issue by 0xVavaldi** [hashcat/hashcat#2631]
Currently, hashcat brain performs well for salted hashes but quickly bottlenecks for unsalted hashes.

  # | Features
 ===+========
  1 | Send hashed passwords
  2 | Send attack positions
  3 | Send hashed passwords and attack positions

The current feature 2, for sending attack positions bottlenecks severely, even though all it does is send the progress of the attack. Currently, my 1080Ti performs 3MH/s on a 9 length mask attack which should be significantly higher.
Basing my use case on example 2 from https://github.com/hashcat/hashcat/blob/master/docs/hashcat-brain.md

I'd like to see if it's possible to get a feature that does exactly that, calculate progress for attacks - but perhaps with a higher delay or less overhead such that not so much speed gets lost trying to send out data. I also need to point out that in this case, the hashcat brain server is external so network overhead exists as well.

Sharing positions every X seconds is a lot more efficient than trying to do it every X candidates. This also scales better with higher performance. If I don't correctly understand how hashcat brain works, please help me understand but as I see it now, just sending over the progress of a specific attack should not warrant such a delay in attack speed.

**Comment by jsteube** [comment]
Is not possible. The general reason why we can do something like brain server goes back to slow candidate modes. So we need to generate the candidates on the host and send them via PCI-e to compute device and that's what's causing the slow down. The brain server could easily handle it otherwise:

https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#does_the_pci-express_speed_have_any_influence_on_cracking_speed

We can't send progress number for non slow candidates because the division into base and modifiers. This is the only reason we can achieve high rates on GPU, because it efficiently enables the PCI-e bottleneck to work around. However, this division can be different for each executed attack and based on many different factor of which some of them depend on the user command line. Meaning that positioning that you want to have tracked are directly depending on the command line. Meaning that if different user work on the same hash and they use different hardware (and different command lines) they will end up in incompatible attack ranges.

For slow candidate generation this problem does not exist, because there's no division. If you want to dig deeper into this PCI-e bottleneck workaround please refer to the developer guide.

Instead it's much more clever to have a 3rd party application (like hashtopolis) to control several hashcat instances on multiple compute nodes (of several users) using -s and -l parameter.
