### ISSUE TITLE
[FR] Add -S automatically for slow hashes?

### ISSUE THREAD

**Issue by adrastee** [hashcat/hashcat#2696]
Hi,
Using mode 14800, I get around 10 H/s with a 3080.
When  I add "-S"  (--slow-candidates ; Enable slower (but advanced) candidate generators) the speed is way better (~200 H/s)

My 2 cents : Can hashcat add "-S" automatically to slow hashes like 14800 (itunes >10) ? When using "-w 4" we expect an offensive speed tuning, so adding -S should be part of this tuning?

**Comment by jsteube** [comment]
Yes, I like the idea, but -S disables -a 1 and -a 9. We need a mechanism to enable the user to use them. 

So maybe by adding another option like --fast-candidates -F. Then we can set slow hashes by default to -S and fast hashes to -F, but the user can use -F to override the default in slow hash mode, which then enables them to use -a 1 or -a 9. 

What you think?

**Comment by Chick3nman** [comment]
Setting -S costs some resources on the host side and the effect is not consistent between systems, especially with more GPUs. With a properly sized wordlist, switching -S should have little to no positive effect on the cracking speed. The issue it solves typically comes from very small attacks, often highly targeted wordlists mixed with many many rules. There are simply not enough base candidates to create enough work(see: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed) to keep the GPU utilization up. While -S fixes it in this case, i don't think it makes sense to switch it by default as it depends heavily on your host configuration and a slow enough host can lower effective speeds in many of the "slow" hash kernels.

We current throw a soft warning message in other attacks that links to the above FAQ page and describes some easy ways to increase cracking speed. Since we can detect the size of the wordlist, via the dictionary cache, I would propose throwing a warning when we detect a dictionary that is too small that suggests adding -S, but ultimately leave it up to the user to add. Since the benefit of -S is specific to the attack setup and not "free" due to the kernel itself, it would seem out of place to switch it by default as users may counter intuitively see lower speeds after creating an attack with a proper amount of work.

**Comment by jsteube** [comment]
As discussed, implemented with commit https://github.com/hashcat/hashcat/commit/58ffef45804777ca6e8f3a6e4f8511f43ca71e88
