### ISSUE TITLE
How to build hashcat in Termux

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#2718]
![Screenshot_20210224_200404_com termux](https://user-images.githubusercontent.com/61009000/108998340-bf0abf00-76db-11eb-807f-cce6fe9d6ac0.jpg)
I tried to compile in Termux, but it gave an error

**Comment by jsteube** [comment]
OK, with latest version of hashcat on GitHub master or hashcat v6.2.0 release version there's an option in src/Makefile to set ENABLE_UNRAR to 0 if the user wishes to do so. Since this compile error comes from unrar sources, this should help you with the compile error, too.

Please retry by either settings ENABLE_UNRAR to zero in src/Makefile to do run "ENABLE_UNRAR=0 make" instead of just "make" and close the issue if it worked.

**Comment by jsteube** [comment]
No response from OP, therefore closing. Feel free to reopen and update with new information.
