### ISSUE TITLE
[Request] Early Murmurhash

### ISSUE THREAD

**Issue by korenkonder** [hashcat/hashcat#2738]
Can you add this algorithm to hashcat?
[Code for it](https://tanjent.livejournal.com/756623.html)
Has seed, and outputs 32-bit value

**Comment by jsteube** [comment]
Should be not too complicated by using CRC32 as template

**Comment by korenkonder** [comment]
Maybe I could do it myself, but I'm not familiar with codebase of hashcat nor GPU programming itself so I'm asking you to do this

**Comment by matrix** [comment]
@korenkonder you can use the following as template, it is quite simple (if you know C).

https://github.com/matrix/hashcat-SolarWindsHack

**Comment by jsteube** [comment]
I just took a look at this. What's a bit problematic is that this hash seems to have many different implementation with only slight differences. So I don't know which one to implement actually.

From the page which @korenkonder linked there's a little snippet in which is does this:

```
h += 0xdeadbeef;
```

So I went to find a perl module in order to prepare the unit tasks and found  Digest::MurmurHash. If you take a look into the C code of the module, you see a slightly different implementation, with the `h += 0xdeadbeef;` missing.

My concerns are now that whatever we implement possibly lead to some inconsistent results because there's no real MurmurHash standard. Also @korenkonder it would be nice to have some example hash:seed:password pairs to verify we are talking about the same. It would also be nice to know where this algorithm (and especially which version) is used in. Please clarify then I will add the plugin for you.

**Comment by korenkonder** [comment]
This algorythm is used in games that I interested in:
> Hatsune Miku Project Diva F 2nd [PCSB00554]
> Hatsune Miku Project Diva X [PCSB01007]

PCSB00554 is version of game for PS Vita. Arch is ARMv7 with Thumb and NEON. Function offset is 0x814D7A9C
PCSB01007 is also for PS Vita. Arch is same. Function offset is 0x8134C304

In game it's used for hashing strings for faster access to some. But some strings can't be found in any file but their hashes are here. I wanted to recover some of those knowing the structure of other strings

But there's one significant difference between algo on LiveJournal and algo that I had reversed. In both games it has ability to reverse stream of data (from Big Endian to Little Endian) and to shift `lowercase` latin to `UPPERCASE`
[murmurhash_code.txt](https://github.com/hashcat/hashcat/files/6497195/murmurhash_code.txt)

Example hash:seed:password (both games are hardcoding seed to 0)
[murmurhash.txt](https://github.com/hashcat/hashcat/files/6497152/murmurhash.txt)

I also tried to write code for hashcat on my own but I don't think that it's fast enough. Or maybe it's just wrong in terms of OpenCL programming
[murmurhash_module.txt](https://github.com/hashcat/hashcat/files/6497217/murmurhash_module.txt)
[murmurhash_opencl_a3.txt](https://github.com/hashcat/hashcat/files/6497218/murmurhash_opencl_a3.txt)

**Comment by jsteube** [comment]
I think there's a huge bug in the implementation in https://tanjent.livejournal.com/756623.html

It works well, but only for strings with a length that is not a multiple of 4. So strings of length 1,2,3,5,6,7,9,10,11 and so on. 

Here's a POC to reproduce:

```
#include <stdio.h>
#include <stdint.h>
#include <string.h>

unsigned int MurmurHash ( const unsigned char * data, int len, unsigned int h )
{
	const unsigned int m = 0x7fd652ad;
	const int r = 16;

	h += 0xdeadbeef;

	while(len >= 4)
	{
		h += *(unsigned int *)data;
		h *= m;
		h ^= h >> r;

		data += 4;
		len -= 4;
	}

	switch(len)
	{
	case 3:
		h += data[2] << 16;
	case 2:
		h += data[1] << 8;
	case 1:
		h += data[0];
		h *= m;
		h ^= h >> r;
	};

	return h;
	h *= m;
	h ^= h >> 10;
	h *= m;
	h ^= h >> 17;

	return h;
}


int main(int argc, char *argv[])
{
  char *s = "eff_pv704_c58_circle";

  // results in       08c81a07
  // murmurhash.txt   CEF1504E

  printf("%08x\n", MurmurHash (s, strlen(s), 0));

  return 0;
}
```

So that means I can crack only 845/1115 hashes from murmurhash.txt. Maybe that's the reason you're not finding the strings you are looking for.

If you take a look at the switch() statment it is obvious that the case 0 is missing. I think there's the problem.

**Comment by jsteube** [comment]
OK, support was added with commit https://github.com/hashcat/hashcat/commit/aa7c579736c4f1cd5e3fdb3b15df31c184e56ce2

Note that you have to uppercase the candidates yourself. It's not clever to convert them inside the kernel and in case there's a MurmurHash implementation somewhere that does not automatically uppercase, it wouldn't be able to crack. For automation with wordlists you can use command line switch "-j u" and for masks simply do not use lower case letter or ?l. Use ?u instead.

**Comment by jsteube** [comment]
Speed on RTX2080Ti: 268.9 GH/s !!!

```
atom@msi:~/hashcat$ ./hashcat.exe -b -m 25700
hashcat (v6.2.1-19-gaa7c57973) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

CUDA API (CUDA 11.3)
====================
* Device #1: NVIDIA GeForce RTX 2080 Ti, 10137/11264 MB, 68MCU

OpenCL API (OpenCL 3.0 CUDA 11.3.70) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce RTX 2080 Ti, skipped

OpenCL API (OpenCL 2.1 WINDOWS) - Platform #2 [Intel(R) Corporation]
====================================================================
* Device #3: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz, skipped

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 25700 - MurmurHash

Speed.#1.........:   268.9 GH/s (7.76ms) @ Accel:32 Loops:1024 Thr:1024 Vec:1

Started: Tue May 18 11:04:27 2021
Stopped: Tue May 18 11:04:36 2021
```

**Comment by jsteube** [comment]
I've also put binary beta in case someone want to try without waiting for release hashcat.net/beta
