### ISSUE TITLE
Feature: Flag to disable kernel caching for use during plugin development 

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#2750]
When working on a plugin you will often have to make changes to the kernel, then rerun some tests to verify them. If a cached kernel exists, hashcat will select it instead of rebuilding with the latest changes to the kernel source. Deleting this can be both tedious as well as easily forgotten leading to quite a few hiccups during kernel development. Proposed flag would disable this cache hit, forcing hashcat to rebuild the kernel every time. 

`module_jit_cache_disable` already exists in module_ctx but may not be the best way to go about this. Setting something from the hashcat_ctx similar to other global options seems more proper, especially if certain warnings or other options need to be aware of this flags status prior to module/kernel load to alter their behavior, such as a related warning during the startup output.

Proposed flag: `--kernel-cache-disable`

**Comment by jsteube** [comment]
I like the Idea, but the problem is the implementation. I think this is where it fails to work out in a beneficial situation for developers.

While we have kernels/ folder where most of the compiled bytecode is stored, that's not everything. For example we have $HOME/.nv for NVIDIA, we have $HOME/.cache for POCL, and for AMD it changes multiple times already. So the first problem is that we have folder which are (theoretical) not under the responsibility of hashcat. If we start to modify these files this can have unpredictable results to other tools using them. Therefore we can't simply delete these files. The second problem is that vendors maybe change the folder path in the future and we don't know about the change.

If we add this kind of flag, both above problems could lead the plugin developer into a false impression of security. This false impression is probably worse than what we have now.

Maybe there's an even more clever solution?

**Comment by Chick3nman** [comment]
Is it possible to avoid caching the kernels at all? Or force hashcat to ignore the cached kernels? I don't see this as being any different than `module_jit_cache_disable`, just a way to set it globally. Also i do agree that it may cause a false sense of security, though it would likely be employed along side `--force` and `--self-test-disable` anyway, so adding another warning to the output seems fine since it's oriented at developers and not general users.

**Comment by jsteube** [comment]
We could automatically set the module_jit_cache_disable to True if the src/Makefile has the DEBUG flag set. How about that?

**Comment by Chick3nman** [comment]
That works for me, i like that idea.

**Comment by jsteube** [comment]
The change was pushed. Also note that some OpenCL runtimes support disable the cache using an environment variable. If DEBUG is set, it will also set these environment variables to inform the OpenCL runtimes.

**Comment by Chick3nman** [comment]
Thanks, closing as added/fixed.
