### ISSUE TITLE
Hashcat 6.1.1 won't start, Windows 10, Nvidia 465.89

### ISSUE THREAD

**Issue by xl2480** [hashcat/hashcat#2751]
PS C:\Users\xxxx> nvidia-smi
Sun Apr 11 21:18:10 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.89       Driver Version: 465.89       CUDA Version: 11.3

PS C:\Users\xxxxx\Desktop\tools\hashcat-6.1.1> .\hashcat.exe -I
hashcat (v6.1.1) starting...
(that's it, it won't run)

PS C:\Users\xxxxx\Desktop\tools\hashcat-6.1.1> .\hashcat.exe -b
hashcat (v6.1.1) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

PS C:\Users\xxxxxx\Downloads\Programs> .\clinfo.exe
Number of platforms                               2
(Nothing else)

And in Windows eventviewer, I can see both clinfo and hashcat crashed because "C:\WINDOWS\SYSTEM32\OpenCL.dll".

Tried to follow "https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_may_have_the_wrong_driver_installed_what_should_i_do", uninstall drive, clean everything, reinstall, installl older version, none of them work.

Hashcat 5.1.0 worked a few month ago and it doesn't work now anymore. 

Any idea?

**Comment by jsteube** [comment]
NVIDIA introduced OpenCL 3.0 with their latest driver and this caused multiple tools to stop working. I found a way to workaround the problem and commit it git GitHub master hashcat repository and also added a beta to hashcat.net/beta/. Feel free to compile from source or to try the beta binary. Chances are good it will work for you. I did not create a release version despite the high pressure created by this NVIDIA issue because I have the  hope they will fix it with the next driver version themself. If that's not the case we might need to add the workaround to a new release version.

**Comment by xl2480** [comment]
> NVIDIA introduced OpenCL 3.0 with their latest driver and this caused multiple tools to stop working. I found a way to workaround the problem and commit it git GitHub master hashcat repository and also added a beta to hashcat.net/beta/. Feel free to compile from source or to try the beta binary. Chances are good it will work for you. I did not create a release version despite the high pressure created by this NVIDIA issue because I have the hope they will fix it with the next driver version themself. If that's not the case we might need to add the workaround to a new release version.

C:\Users\xxxxx\Downloads\Compressed\hashcat-6.1.1>hashcat.exe -I
hashcat (v6.1.1-210-gee2680513) starting...
(same thing, so maybe I shall just wait for NVIDIA for a fix. This sucks.)

**Comment by arandintday** [comment]
Same here bro
