### ISSUE TITLE
Incomprehensible mechanism of skip and limit for mask-only strings

### ISSUE THREAD

**Issue by ventaquil** [hashcat/hashcat#2767]
I am trying to deal with `--skip` and `--limit` in distributed computing and I am using `--stdout` option to verify that I am correct. I found something interesting 🤔 

```
$ ./hashcat --skip 0 --limit 3 --stdout --attack-mode 3 --markov-disable '?d'
0
1
2
3
4
5
6
7
8
9
```

Shouldn't it be just `0 1 2`? For example next command gives no output.

```
$ ./hashcat --skip 1 --limit 3 --stdout --attack-mode 3 --markov-disable '?d'
```

When I change mask from `?d` into `a?d` then everything is working fine.

```
$ ./hashcat --skip 0 --limit 3 --stdout --attack-mode 3 --markov-disable 'a?d'
a0
a1
a2
$ ./hashcat --skip 1 --limit 3 --stdout --attack-mode 3 --markov-disable 'a?d'
a1
a2
a3
```

Let's check this too.

```
$ ./hashcat --skip 1 --limit 3 --stdout --attack-mode 3 --markov-disable '?d?d'
01
11
21
31
41
51
61
71
81
91
02
12
22
32
42
52
62
72
82
92
03
13
23
33
43
53
63
73
83
93
```

It looks that for mask-only string `--skip` and `--limit` are working strange for me.

**Comment by Chick3nman** [comment]
This has to do with a misunderstanding of what --skip and -- limit actually interact with. They do NOT interact directly with the number of candidates produced by any given attack, they interact with the keyspace. Keyspace in this context is a value calculated within hashcat that relates to the way work is split up, not the amount of total work(candidates) in the end. If you look at the status output for the ?d?d mask you will see that while progress is N/100, restore points are N/10.  This is because the keyspace as calculated in hashcat is being divided into 10 chunks(for efficiency or similar reasons), so there are only 10 places you can skip to or start from. You have completed 3 of those chunks in your last example, set by --limit 3, starting from chunk 1.

There is no issue here as far as i can see, if you would like to discuss this further please visit the forums or ask in the IRC channel. Unless you have something else that's broken, please close.

**Comment by ventaquil** [comment]
Thank you @Chick3nman for explaining it. I haven't doing a deep dive into source code yet.

Then maybe there is a need to update `--help`.

```
hashcat (v6.1.1) starting...

Usage: hashcat [options]... hash|hashfile|hccapxfile [dictionary|mask|directory]...

- [ Options ] -

 Options Short / Long           | Type | Description                                          | Example
================================+======+======================================================+=======================
 -m, --hash-type                | Num  | Hash-type, see references below                      | -m 1000
 -a, --attack-mode              | Num  | Attack-mode, see references below                    | -a 3
 -V, --version                  |      | Print version                                        |
 -h, --help                     |      | Print help                                           |
...
 -s, --skip                     | Num  | Skip X words from the start                          | -s 1000000
 -l, --limit                    | Num  | Limit X words from the start + skipped words         | -l 1000000
...
```

According to what you have said - you cannot skip `1000000` chunks if there is at most 10 of them.

**Comment by Chick3nman** [comment]
I think you may have misunderstood what i meant as well, there are only 10 chunks in _your specific example_. There can be many many more in any given attack, that was just your mask that had 10. The --help text is correct.

**Comment by ventaquil** [comment]
Okay, got it!
