### ISSUE TITLE
ERROR: cuModuleLoad() 301

### ISSUE THREAD

**Issue by ubuntutest** [hashcat/hashcat#277]
xxxx xxxx # hashcat.bin -m 0 -a 0  /home/xxxx/hashes/hashes.txt /xxxx/rockyou.txt
cudaHashcat v2.01 starting...

Device #1: GeForce GT 740M, 2047MB, 1032Mhz, 2MCU
Device #1: WARNING! Kernel exec timeout is not disabled, it might cause you errors of code 702

Hashes: 5 hashes; 5 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
- Zero-Byte
- Precompute-Init
- Precompute-Merkle-Demgard
- Meet-In-The-Middle
- Early-Skip
- Not-Salted
- Not-Iterated
- Single-Salt
- Scalar-Mode
- Raw-Hash
  Watchdog: Temperature abort trigger set to 90c
  Watchdog: Temperature retain trigger set to 80c

ERROR: cuModuleLoad() 301

---

I'm using cudaHashcat-2.01

I read all the existing posts on the web about this issue, unfortunately I can not fix it, any ideas?

**Comment by epixoip** [comment]
I don't understand why you would open an issue on Github for this problem, especially when you're using the release version and didn't test against the code that's actually in Github (cudaHashcat doesn't even exist in this repository anymore.) Questions like this belong on the forums or IRC.

Anyway this error is addressed in our FAQ, http://hashcat.net/wiki/doku.php?id=frequently_asked_questions#what_does_the_cumoduleload_301_error_mean

**Comment by ubuntutest** [comment]
Sorry if it is not the right place but i opened an issue on GitHub just because I read the FAQ and I have not solved

---

If the problem still exist:

Solution: Open an issue on github. We will add your GPU with the next release.

---

Could you tell me the address of IRC? thank you so much

**Comment by epixoip** [comment]
You have an old GPU that has been supported by oclHashcat for nearly 3 years now, so that is definitely not applicable in this case. 

301 == "File Not Found" so either you're not using "7z x" to extract the archive, or you're trying to run cudaHashcat from outside of its directory, or something along those lines. But either way it is an issue with your setup and not a bug in cudaHashcat, and therefore a bug report should not be opened for it -- especially when cudaHashcat doesn't even exist in this Github repository anymore.

IRC channel is listed on our website.

**Comment by ubuntutest** [comment]
Thanks for your help, I solved the problem, I had some wrong directory, browsing the web I have found no information that would make me think of a wrong path.
