### ISSUE TITLE
crash with mode 2811, optimized kernel, attack mode 9, similar to closed issue 2769

### ISSUE THREAD

**Issue by realSnoopy** [hashcat/hashcat#2782]
maybe somehow related to this closed issue
[https://github.com/hashcat/hashcat/issues/2769](url)

hashcat (v6.1.1-298-g95489b047)
CUDA.Version.: 11.3

same problem with crashing on optimized kernel -O (hash 2811) with these outputs

cuMemcpyDtoH(): an illegal memory access was encountered
cuMemFree(): an illegal memory access was encountered
cuEventDestroy(): an illegal memory access was encountered
cuStreamDestroy(): an illegal memory access was encountered
cuModuleUnload(): an illegal memory access was encountered

funny stats-output:
Progress.........: 3139618/79484 (3950.00%)
Rejected.........: 3099876/3139618 **(98.73%)**

unoptimized kernel is working

dont know wether this is related or just ANOTHER BUG in attack mode 9, already cracked hashes in potfile are ignored AND found hashes are only stored/printed to outputfile/output but not stored in potfile

**Comment by jsteube** [comment]
> maybe somehow related to this closed issue
> [https://github.com/hashcat/hashcat/issues/2769](url)

Is not the same issue, only the same error message.

> 
> hashcat (v6.1.1-298-g95489b047)
> CUDA.Version.: 11.3
> 
> same problem with crashing on optimized kernel -O (hash 2811) with these outputs

Is not the same problem

> 
> cuMemcpyDtoH(): an illegal memory access was encountered
> cuMemFree(): an illegal memory access was encountered
> cuEventDestroy(): an illegal memory access was encountered
> cuStreamDestroy(): an illegal memory access was encountered
> cuModuleUnload(): an illegal memory access was encountered

I can't reproduce this with my artficially generated hashlist. Since you did not attach them I had to generate some myself.

> 
> funny stats-output:
> Progress.........: 3139618/79484 (3950.00%)
> Rejected.........: 3099876/3139618 **(98.73%)**

That might be a problem

> 
> unoptimized kernel is working

Same for me. But for me pure works, too.

> 
> dont know wether this is related or just ANOTHER BUG in attack mode 9, already cracked hashes in potfile are ignored AND found hashes are only stored/printed to outputfile/output but not stored in potfile

Attack-mode 9 clearly stated it is not supporting potfile, neither read or writte. How can it be, because needs to be aligned. If potfile removes one entry, synchronization would be broken. What other bug in attack-mode 9 are you talking about?

**Comment by realSnoopy** [comment]
[mode-2811-user.txt](https://github.com/hashcat/hashcat/files/6423026/mode-2811-user.txt)
[mode-2811-id-hash-salt.txt](https://github.com/hashcat/hashcat/files/6423027/mode-2811-id-hash-salt.txt)

there are 3 or 4 users with a single space as hint

sry, the another was misleading, was not meant to the attack itself

with potfile, sry makes sense but didnt found it on the forum / thread

**Comment by jsteube** [comment]
OK, thanks for the files. I have deleted the comment including the files. I now can reproduce the problem.

**Comment by jsteube** [comment]
OK, this should be fixed with commit https://github.com/hashcat/hashcat/commit/3543094591fd718f69b218604bc51dd622e0e92d

I have also put up a new binary beta to hashcat.net/beta

I did not make a note into changes because -a 9 attack did not exist in 6.1.1 release and it would confuse user who do not use beta versions.

Thanks for reporting!

Please verify and confirm by closing the issue.

**Comment by realSnoopy** [comment]
did some test
first of all it seems to work like intended, but after comparing results, i found one strange thing ( i think it is a rule based problem, see below)
i compared the results pure kernel (old beta git 298) with your new beta 304 optimized (sorted before)

no rules no diff
best64 no diff
dive  found diff

diff pure.old opt.new
612d611
'< 271923ee7c0989e0873c3d398a7ba5ad:Kcv?v:00000000000000000000000000000000'
2650a2650
'> ab81d0869ba7575420f2f61f1a6f66eb:f,QS{:johndeere'

optimized mode found johndeere, (the old pure kernel not?)
im not sure whether this 00000 style pw is true or not, im at home and using laptop and ugly rdp + remote software,  i can double check tomorrow when im back at work

**Comment by jsteube** [comment]
For the 271923ee7c0989e0873c3d398a7ba5ad everything is fine:

base: 00000000000000000000000000 [26]
pw:   00000000000000000000000000000000 [32]
rule: $0 Z5

Visualization:

```
$ cat > p
00000000000000000000000000
$ cat > r
$0 Z5
$ ./hashcat --stdout p -r r 
00000000000000000000000000000000
$ ./hashcat --stdout p -r r -O
000000000000000000000000000
```

The reason it was not reported in -O is because the final password length 32 is one character too much to handle.
Optimized kernel can't crack it, but pure kernel can crack it because it supports up to 256.

---

For the ab81d0869ba7575420f2f61f1a6f66eb is also fine:

base: Johnderre
pw:   johndeere
rule: ,6 p4 l

So the problem here is that after apply the p4 the password becomes password length 45 and optimized kernel can't handle it. 
It skips the rule in optimized mode while pure kernel does not skip it. 

However, that's the problem. Because only by not applying the p4 it will result in the correct password.
This is why the optimized kernel can crack it and the pure kernel can not.

Visualization:

```
$ cat p
Johnderre
$ cat r
,6 p4 l
$ ./hashcat --stdout p -r r 
johndeerejohndeerejohndeerejohndeerejohndeere
$ ./hashcat --stdout p -r r -O
johndeere
```

**Comment by realSnoopy** [comment]
thank you for the detailed answer, this attack is really awesome
