### ISSUE TITLE
[Linux - Manjaro] the provided PTX was compiled with an unsupported toolchain

### ISSUE THREAD

**Issue by keybreak** [hashcat/hashcat#2799]
**Describe the bug**
~~~
cuLinkAddData(): the provided PTX was compiled with an unsupported toolchain.

* Device #1: Kernel /usr/share/hashcat/OpenCL/shared.cl link failed. Error Log:

ptxas application ptx input, line 9; fatal   : Unsupported .version 7.3; current version is '7.2'



* Device #1: Kernel /usr/share/hashcat/OpenCL/shared.cl build failed.

~~~

**Hardware/Compute device (please complete the following information):**
- Compute device name: GeForce GTX TITAN X (GM200)
- OpenCL/CUDA driver name: NVIDIA DRIVER
- OpenCL/CUDA driver version: 460.80
- OpenCL/CUDA driver source:  repository

**Hashcat version (please complete the following information):**
 - OS: Linux
 - Distribution: Manjaro
 - Version 6.2.1+46+g3faad47b4-1 (`hashcat-git` AUR)

**Comment by jsteube** [comment]
Not a hashcat error. You need to update CUDA SDK.

**Comment by keybreak** [comment]
@jsteube 
But it's latest available on Manjaro Stable (`cuda 11.3.0`), where could one update it further?

**Comment by jsteube** [comment]
Do not use the distribution provided CUDA SDK, because it breaks compatibility by not using the correct driver. This is a problem in your linux distribution package, not hashcat.

For CUDA 11.3 you need driver 465.19.01, see Table 2 here: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html


CUDA Toolkit | Toolkit Driver Version
-- | --



CUDA 11.3.1 Update 1 | &gt;=465.19.01 | &gt;=465.89
-- | -- | --
CUDA 11.3.0 GA | &gt;=465.19.01 | &gt;=465.89
CUDA 11.2.2 Update 2 | &gt;=460.32.03 | &gt;=461.33
CUDA 11.2.1 Update 1 | &gt;=460.32.03 | &gt;=461.09

**Comment by kenorb** [comment]
Make sure you don't set `LD_LIBRARY_PATH` in shell or have in your _rc_ files (mine was pointing to `/usr/local/cuda-11.7/bin`).

Or run the command with `LD_LIBRARY_PATH= hashcat ...`. It worked for me.

If your distribution supports Apt, look for any package incompatibilities (`dpkg -l | grep -i nvidia | grep ^ii`), version should match. Otherwise try to upgrade all CUDA/GPU related packages to the same version (e.g. `sudo apt-get upgrade \*nvidia-\*`).

**Comment by ret2src** [comment]
To all the Google passers-by: If this happens to you on Arch Linux, install the [`downgrade`](https://aur.archlinux.org/packages/downgrade) utility. It allows you to downgrade your CUDA version to match your Nvidia drivers:

```bash
$ yay -S downgrade
...

$ sudo downgrade cuda
```
