### ISSUE TITLE
Add support for data extracts for Blockchain (12700/15200)

### ISSUE THREAD

**Issue by orweinberger** [hashcat/hashcat#2830]
Hashcat can currently handle hashes originating from Blockchain wallets via modules 12700/15200. To produce the hash candidate we use `blockchain2john.py`.

Is it possible to add support for using a different hash format, as given by BTCRecover's extract scripts?

Some work have been done already when Hashcat built support for a similar hash format for Blockchain's second password (18800).

In detail:

Currently, for Blockchain v0/v1 (12700) formats, the following hash format is accepted:

```
$blockchain$288$713253722114000682636604801283547365b7a53a802a7388d08eb7e6c32c1efb4a157fe19bca940a753d7f16e8bdaf491aa9cf6cda4035ac48d56bb025aced81455424272f3e0459ec7674df3e82abd7323bc09af4fd0869fd790b3f17f8fe424b8ec81a013e1476a5c5a6a53c4b85a055eecfbc13eccf855f905d3ddc3f0c54015b8cb177401d5942af833f655947bfc12fc00656302f31339187de2a69ab06bc61073933b3a48c9f144177ae4b330968eb919f8a22cec312f734475b28cdfe5c25b43c035bf132887f3241d86b71eb7e1cf517f99305b19c47997a1a1f89df6248749ac7f38ca7c88719cf16d6af2394307dce55600b8858f4789cf1ae8fd362ef565cd9332f32068b3c04c9282553e658b759c2e76ed092d67bd55961ae
```

For Blockchain v2/v3 (15200) formats, the following hash format is accepted:

```
$blockchain$v2$5000$288$324724252428471806184866704068819419467b2b32fd9593fd1a274e0b68bf2c72e5a1f5e748fd319056d1e47ca7b40767136a2d97d7133d14faaeca50986f66cdbc0faec0a3fabbd0ba5d08d5322b6b53da021aacfc439c45bec0e9fe02ad81db82f94e9bd36a7d4d76b505c2339fcd46565d3abab958fbeb1de8bfc53beb96cde8fe44128965477c9ef0762c62bbb1d66532b4888e174ea949db54374a2ed9686a63eb0b5b17ae293f7410bb4ae5106f108314a259c5fd097d558515d79350713412159103a8a174cd384a14f3da45efe18044e1146036000231f6042577d0add98fc959d265368e398dc1550b0bc693e9023cd9d51b40e701bd786e19c3a281a90465aa6ea3f9e756d430164ab2eb43be5b6796d7ac15b2fe99217410f2
```

For Blockchain second password (18800), the following hash format is accepted (originating from BTCRecover's `extract-blockchain-second-hash.py`):

```
YnM6WYERjJfhxwepT7zV6odWoEUz1X4esYQb4bQ3KZ7bbZAyOTc1MDM3OTc1NjMyODA0ECcAAD3vFoc=
```

What I would like to be able to do, is to provide the following hash format for the main Blockchain hash (originating from BTCRecover's `extract-blockchain-main-data.py`) to either modes 12700/15200, or a new mode that would accept it, but perform eventually the same cryptographic calculation:

```
Yms69Z9y1J66ceYKkrXy11mHR+YDD8WrPJeTNaAnO7LO7YgAAAAAbnp7YQ== // (correct pass for testing: btcr-test-password
```

The only format differences that I'm aware of, between the second hash and the main data are the digest length (32 in second pass, 16 in main data) and the signature (`bs:` in second pass, `bk:` in main data)

**Comment by philsmd** [comment]
so this request is just for convenience ?

I'm I right that you can easily convert from one hash format to the other with a simple script (externally/outside of hashcat) ?

**Comment by orweinberger** [comment]
Is that possible? I'm actually not sure myself. If you try running hashcat on the `blockchain2john.py` output that is received when running it against the data extract, it errors out on a token length exception.

Could you possibly explain how I can take the data extract and run it correctly against 12700/15200, even in a non-convenient way?

**Comment by philsmd** [comment]
so you trying to convert the base64 encoded `bk:` hash ?

I think you need to look here what the format looks like
https://github.com/3rdIteration/btcrecover/blob/e3247f14726a6fbdcaeaf63223457f0acd7fa37b/extract-scripts/extract-blockchain-main-data.py#L85-L88

with that information the format should be easy to convert from one hash format to the other (of course you need working examples to test with for which you know the password, but there are actually some of them in both JTR, hashcat and btcrecover source code).

----

I've investigated/researched this now a little bit closer and it seems the main problem is that this `bk:` (btcrecover) format only has 16 bytes of encrypted data within it's hash format.  Since hashcat is doing only a check for valid json data (ascii data, non-random basicaly) it's too little data for hashcat's verification (btcrecover only checks for "guid" it seems) i.e. it could generate false positives with that speed and little data length.

Here is some of my investigation output (btcr-test-password):
```
echo -n Yms69Z9y1J66ceYKkrXy11mHR+YDD8WrPJeTNaAnO7LO7YgAAAAAbnp7YQ== | base64 -d | xxd -g1
00000000: 62 6b 3a f5 9f 72 d4 9e ba 71 e6 0a 92 b5 f2 d7  bk:..r...q......
00000010: 59 87 47 e6 03 0f c5 ab 3c 97 93 35 a0 27 3b b2  Y.G.....<..5.';.
00000020: ce ed 88 00 00 00 00 6e 7a 7b 61                 .......nz{a
```

The meaning of the fields:
```
62 6b 3a                                         bk:                // bk:

         f5 9f 72 d4 9e ba 71 e6 0a 92 b5 f2 d7     ..r...q......   // encrypted data
59 87 47                                         Y.G

         e6 03 0f c5 ab 3c 97 93 35 a0 27 3b b2     .....<..5.';.   // IV
ce ed 88                                         ...

         00 00 00 00                                ....            // iter
                     6e 7a 7b 61                        nz{a        // crc32 checksum
```

(note iter of 0 means that the old default of 10 iterations is used, like -m 12700 =  Blockchain, My Wallet)

also note the crc32 checksum is computed like this (it's just a checksum of the hash format's data itself, nothing to do with cracking):
```
crc32 (hex2bin ("626b3af59f72d49eba71e60a92b5f2d7598747e6030fc5ab3c979335a0273bb2ceed8800000000")) => 0x617b7a6e
```

so to answer the question about the feasibility of conversion: it's for now only possible to convert the hashcat format into the "bk:" format (because btcrecover's format uses less encrypted data bytes). The other way around is not possible for now.

I've also tested to see what changes are required to make hashcat crack with less bytes and it seems it's working by changing this:

https://github.com/hashcat/hashcat/blob/05125eb67c9da98e349dabea50f81f24080f6347/OpenCL/m12700-pure.cl#L344

to

```c
for (u32 i = 4; i < 8; i += 4)
```
(note that this change of course only works with this specific version of blockchain hashes, i.e. -m 12700)

i.e. just compare much less data. This of course is discouraged, because it leads to false positives and maybe other problems too. (and you would still require to have all 144 hex bytes.... you could just add random or 0x00 bytes for padding ... to let parse the hash correctly.... otherwise you would need to modify the hash parser too and allow shorter hashes).

Anyway, I'm not really convinced about this format and changes... we already had some problems (and user reports) about just searching for "guid:"... so I think our current approach with at least 144 hex bytes and valid JSON data check is more robust and this can't be done with the `bk:` hash format.

What do you guys think ?

**Comment by philsmd** [comment]
I think we can/should close this because an explanation why we prefer the other format (more data, less likelihood of false positives), how to generate hashes in the hashcat-supported format and how to "work around" the problem when you really don't have the original data (but still want/need to use hashcat) was given.

Thx
