### ISSUE TITLE
Generate Kaspersky Password Manager passwords based on time range in which they might have been created

### ISSUE THREAD

**Issue by RichiH** [hashcat/hashcat#2868]
Kaspersky Password Manager used to generate passwords with current time being the only source of entropy. As such, knowing in which time range a user may have created a password is enough information to fully exhaust the possible keyspace.

**Describe alternatives you've considered**
None known

**Provide an example hash/database/file and a known correct password**
U[Gt6MjzWxdg

**Explain how the cryptographic schema is implemented**
https://donjon.ledger.com/kaspersky-password-manager/ is not perfect, but currently the best resource I am aware of.

**Describe the known limitations of the algorithm**
It's seeded only with time.

**Where do you typically find the algorithm**
All passwords generated by Kaspersky Password Manager until recently.

CC @epixoip @Ledger-Donjon @matthewdgreen @roycewilliams
Cross-reference: https://github.com/hashcat/hashcat/issues/1058

**Comment by jsteube** [comment]
I'm not sure if this request is appropriate to hashcat. It depends on what you are looking for. 

1. If you are looking for a plugin in order to crack KPM, that would be a valid request. However, there's no information known about the algorithm being used, as well there's no kpm2hashcat tool. We need both to start working. In this case you should leave the FR open and ideally provide the required information.
2. If you are looking for a password generator in order to optimize the ordering of the candidates based on the article on the website, then this is not a valid request for hashcat. Instead this tool should be a standalone generator, such as maskprocessor or princeprocessor. In this case you should close the issue.

**Comment by RichiH** [comment]
I am not **certain** myself, but I think it's a case of 1. as those passwords will be used in many places. I am not yet aware of more detailed information than what https://donjon.ledger.com/kaspersky-password-manager/ provides, but I expect more eyes will look into this as it's an area of current interest. When/if I find them, I would link to them from here.

The CCs might help pull additional information in.

**Comment by jsteube** [comment]
Wait, just for clarification, the KPM is a tool like KeePass where users store their personal passwords in an encrypted database, right?

If so, the goal is to find the master password that protects the database. But technically, these are two different functions. One function is to protect the database with some encryption and one function to generate (good) passwords.

OK, there is a chance that the KPM user used KPM password generator not only to generate the passwords for the users' logins to different websites, but also to generate the KPM master password. But even in this case the right strategy would be to have:

1. A hashcat plugin to crack the database
2. An external tool to generate the password and to feed (1) with it
 
We are back to what I am asking in my first comment. If that is the goal, what we need is information about the KDF that used in KPM and a way to test if the produced key is the correct one. The website does not describe this in any way, but you are referencing it as an answer my questions? I really don't get it. It only answers questions in case you are looking for (2), but this should be implemented in a standalone solution for better performance and flexibility.

**Comment by RichiH** [comment]
After some reflection, I believe you are right. Closing.
