### ISSUE TITLE
Association attack error : "word count is not in sync with salt count" 

### ISSUE THREAD

**Issue by loic-bellinger** [hashcat/hashcat#2944]
**Describe the bug**
Hashcat throws this error when trying the new -a 9 attack : "word count is not in sync with salt count. Words: 691, salts: 1". Still, I'm sur the hashes list and the hints list got the same number of lines.

**To Reproduce**

`hashcat -m 0 "C:\Users\X\Documents\Hacking\Password hacking\asso_hashes.txt" "C:\Users\X\Documents\Hacking\Password hacking\asso_hints.txt" -a 9` on Windows 10 X64.

**Expected behavior**
The attack should start.

**Hardware/Compute device (please complete the following information):**
- Compute device name: RTX2080 super with Max-Q design
 - Nvidia driver version: 461.40

**Hashcat version (please complete the following information): v6.2.3
 - OS Name: Microsoft Windows 10 Home
 - Distribution: Version 10.0.19043 Build 19043

**Comment by 0xVavaldi** [comment]
That's because -m0 (a.k.a. MD5) does not have salts. So it returns the error that your salt count and word count is not aligned.
Long story short, if you don't have salts, you can't perform the candidate optimization that this mode uses.

Performing a candidate attack on unsalted lists is something that's very unlikely to be implemented as well in the near future - it's been brought up a few times before but has been shot down multiple times.
