### ISSUE TITLE
{algorithm request} native support for eap-md5

### ISSUE THREAD

**Issue by thesle3p** [hashcat/hashcat#296]
Currently a hacky-script exists to allow hashcat to crack eap-md5 but it is less then ideal in performance and flexibility (can't dynamically pass hashcat rules and wordlists when using it and I feel it could be a lot faster) Would it be possible to add native support for cracking eap-md5, while a deprecated algorithm it is still very common.

**Comment by jsteube** [comment]
What exactly do we have to do?

**Comment by thesle3p** [comment]
I would think add to the .hccp format to support storing eap-md5 challenge
responses and a kernel to parse that and crack it.

**Comment by wiire-a** [comment]
@jsteube @thesle3p 

A little write-up on EAP-MD5:

**Cons**:
- Cannot be used for Wi-Fi as does not support key generation (only used for allowing access)
- Doesn't provide mutual authentication (vulnerable to MITM)
- The challenge and response mechanism is in plaintext and goes over the air unencrypted
- Uses MD5 as hashing algorithm
- Only available from Windows Vista and below, because considered deprecated/unsecure

Passive air sniffing is enough to perform an offline attack.

**Pros**:
- Provides protection against replay attacks

**Client authentication process**:

```
Client           Access Point        Radius server
   |    EAPoL-start    |                   |
   |------------------>|                   |
   |  EAP-Request/ID   |                   |
   |<------------------|                   |
   | EAP-Response/ID   |    Radius/ID      |
   |------------------>|------------------>|
   | EAP-MD5/Challenge | EAP-MD5/Challenge |
   |<------------------|<------------------|
   | EAP-MD5/Response  | EAP-MD5/Response  |
   |------------------>|------------------>|
   | EAP Success/Fail  | EAP Success/Fail  |
   |<------------------|<------------------|
```

**Algorithm** (|| means concatenation):

_Client response hash_ [16 bytes] = _md5(eapid || password || challenge)_

```
eapid:     id of the EAP response frame [1 byte]
password:  user password
challenge: server challenge [16 bytes]
```

As I understood it, "eapid" should be a 1-byte session identifier, however in many cases it's fixed to the default value 0x02. It can be found in Wireshark by selecting the EAP-MD5/Challenge (Request) packet (_802.1X Authentication > Extensible Authentication Protocol > Id_)

As for the password I don't think there's a minimum or maximum length.

Rather than a .hccap file I'd suggest to use a simple string like: `$eapmd5$id:challenge:hash`

It's simplier and one could manually parse it.

Sample data provided with **eapmd5pass** (link in the sources):

```
EAP Id:    02
Challenge: 00000000000000000000000000000000
Response:  9920418b3103652d3b80ffff04da5863
Password:  bradtest

MD5($HEX[02627261647465737400000000000000000000000000000000]) = 9920418b3103652d3b80ffff04da5863
```

**Sources**:
http://www.willhackforsushi.com/?page_id=67
http://www.securitytube.net/groups?operation=view&groupId=9
http://dl.ifip.org/db/conf/wistp/wistp2012/LiuX12.pdf

Also, while writing this I found: https://twitter.com/hashcat/status/425555173428064256

**Comment by thesle3p** [comment]
I saw the blog post you linked to(the twitter one) and that method is
incredibly inflexible, you have to modify the wordlist each attempt and it
is considerably slower then if done natively. Also I have seen it used for
wireless and heavily for 802.1X (NAC)
On May 13, 2016 2:09 PM, "wiire" notifications@github.com wrote:

@jsteube https://github.com/jsteube @thesle3p
https://github.com/thesle3p

A little write-up on EAP-MD5:

_Cons_:
- Cannot be used for Wi-Fi as does not support key generation (only used
  for allowing access)
- Doesn't provide mutual authentication (vulnerable to MITM)
- The challenge and response mechanism is in plaintext and goes over the
  air unencrypted
- Uses MD5 as hashing algorithm
- Only available from Windows Vista and below, because considered
  deprecated/unsecure

Passive air sniffing is enough to perform an offline attack.

_Pros_:
- Provides protection against replay attacks

_Client authentication process_:

Client           Access Point        Radius server
   |    EAPoL-start    |                   |
   |------------------>|                   |
   |  EAP-Request/ID   |                   |
   |<------------------|                   |
   | EAP-Response/ID   |    Radius/ID      |
   |------------------>|------------------>|
   | EAP-MD5/Challenge | EAP-MD5/Challenge |
   |<------------------|<------------------|
   | EAP-MD5/Response  | EAP-MD5/Response  |
   |------------------>|------------------>|
   | EAP Success/Fail  | EAP Success/Fail  |
   |<------------------|<------------------|

_Algorithm_ (|| means concatenation):

_Client response hash_ [16 bytes] = _md5(eapid || password || challenge)_

eapid:     id of the EAP response frame [1 byte]
password:  user password
challenge: server challenge [16 bytes]

As I understood it, "eapid" should be a 1-byte session identifier, however
in many cases it's fixed to the default value 0x02. It can be found in
Wireshark by selecting the EAP-MD5/Challenge (Request) packet (_802.1X
Authentication > Extensible Authentication Protocol > Id_)

As for the password I don't think there's a minimum or maximum length.

Rather than a .hccap file I'd suggest to use a simple string like:
$eapmd5$id:challenge:hash

It's simplier and one could manually parse it.

Sample data provided with _eapmd5pass_ (link in the sources):

EAP Id:    02
Challenge: 00000000000000000000000000000000
Response:  9920418b3103652d3b80ffff04da5863
Password:  bradtest

MD5($HEX[02627261647465737400000000000000000000000000000000]) =
9920418b3103652d3b80ffff04da5863

_Sources_:
http://www.willhackforsushi.com/?page_id=67
http://www.securitytube.net/groups?operation=view&groupId=9
http://dl.ifip.org/db/conf/wistp/wistp2012/LiuX12.pdf

Also, while writing this I found:
https://twitter.com/hashcat/status/425555173428064256

**Comment by wiire-a** [comment]
@thesle3p 

Sorry when I wrote "Cannot be used for Wi-Fi as does not support key generation" I meant to say it doesn't provide key material for WEP or WPA (https://w1.fi/wpa_supplicant/).

A quote from the book "CWSP Certified Wireless Security Professional Official Study Guide":

> EAP-MD5 has for a long time been used for port authentication on wired networks and therefore was one of the very first EAP types used with WLANs. Many organizations were already using EAP-MD5, and it was a logical progression to leverage it for WLANs because RADIUS servers already supported it.

Also I linked that article just for information. The ideal solution is obviously to have it natively implemented and since it's basically just MD5 (with salts) I reckon it shouldn't be too difficult.

**Comment by ZerBea** [comment]
Additional information about EAP-MD5:
The attack is described here:
http://www.willhackforsushi.com/?page_id=67
source code available here:
http://www.willhackforsushi.com/code/eapmd5pass/1.4/eapmd5pass-1.4.tgz
sample hash taken from the readme:

username:  jwright
challenge: d7ec2fff2ada437f9dcd4e3b0df44d50
response:  1ffc6c2659bc5bb94144fd01eb756e37

password:  beaVIs

Cheers
ZerBea

**Comment by jsteube** [comment]
This is already supported with mode 4800:

```
   4800 | iSCSI CHAP authentication, MD5(CHAP)             | Network Protocols
```

Examples:

```
root@ht:~/hashcat# ./hashcat -m 4800 9920418b3103652d3b80ffff04da5863:00000000000000000000000000000000:02 -a 3 ?l?l?l?l?l?l?l?l --quiet
9920418b3103652d3b80ffff04da5863:00000000000000000000000000000000:02:bradtest
root@ht:~/hashcat# 
```

```
root@ht:~/hashcat# cat hash
1ffc6c2659bc5bb94144fd01eb756e37:d7ec2fff2ada437f9dcd4e3b0df44d50:02
root@ht:~/hashcat# ./hashcat -m 4800 hash -a 3 beaVIs --quiet
1ffc6c2659bc5bb94144fd01eb756e37:d7ec2fff2ada437f9dcd4e3b0df44d50:02:beaVIs
```
