### ISSUE TITLE
Warnings are written in stdout

### ISSUE THREAD

**Issue by s77rt** [hashcat/hashcat#3003]
**Describe the bug**
Warnings are written in stdout

**To Reproduce**
any command that trigger warnings and redirect stderr to null
(expecting warnings to be redirected to /dev/null too)
`hashcat.bin -b --force 2> /dev/null`
but warnings are still there in stdout: `You have enabled --force to bypass...`

**Expected behavior**
Warnings to be written in stderr
`hashcat.bin -b --force 2> /dev/null`
should not return the warning 

**Hashcat version:**
 v6.2.4-83-g07e58631a

**Comment by Chick3nman** [comment]
There are different levels of messages present in the output. We have ADVICE, WARNING, ERROR, etc. I'm not so sure WARNING level messages belong in stderr, though ERROR messages certainly do. The warnings, especially the one related to `--force`, are there for the user to read, they are not errors and are not meant to be logged necessarily. If you are experiencing them, it's best to resolve the issue at hand over simply sending them away. If you wish to send them away still, then you can use some of the current flags to do so, such as `--quiet`, which disables output like those warnings. For the purpose of completing a benchmark on an unstable system, this solution will work. I still highly recommend solving the underlying issue instead of simply bypassing it and the warnings but if you understand the risks of running with a flag like `--force` then it should do what you are after.

**Comment by s77rt** [comment]
Thanks for your reply
`--force` is just an example
and it just feel that warning belongs to stderr, but that's probably a subjective matter
(INFO + ADVICE => stdout, WARNING + ERROR => stderr) may be better?

glad you mentioned `--quiet` command, i was going to initially report a bug about it
see https://github.com/hashcat/hashcat/issues/3004

**Comment by Chick3nman** [comment]
Is there any reason you find warnings better in stderr? Again, these warnings are presented for the user to read and are typically not blocking or necessarily errors. I think maybe there is some confusion on the intent of a WARNING level message versus an ERROR level message maybe?

**Comment by s77rt** [comment]
stdout should be used for outputs that may be parsed; the real hashcat output (founds)
any user info message should go to stderr

building on this
hashcat status should go to stderr except when using `--machine-readable` goes to stdout
founds goes to stdout
everything else goes to stderr

`--quiet` should simply suppress stderr

**Comment by Chick3nman** [comment]
I don't believe that style will work with the current way the front end of hashcat is designed. We present a form of interactive terminal with buttons the user can interact with during a running session. That sort of style may be conventional for simple command line tools that do not present any form of interactivity, but hashcat does not behave this way in its current form. Is there a use case you are after where this makes sense? If you are trying to wrap hashcat in a new front end that requires parsing the command line outputs please take a look at the API as wrapping the front end of hashcat is not the correct way to do this. If the API is too difficult, there are options such as `--machine-readable` and `--status-json` which provide an easier to parse output but they will likely have similar problems to what you are currently experiencing.

**Comment by s77rt** [comment]
makes sense
thanks for your time
closing this for now.
