### ISSUE TITLE
segfault in status screen

### ISSUE THREAD

**Issue by hops** [hashcat/hashcat#302]
When pressing enter instead of 's' to show the status screen oclHashcat segfaults.
I tracked that down to the following lines in the thread_keypress function:

``` C
#ifdef _POSIX
if (ch != '\n') 
#endif

hc_thread_mutex_lock (mux_display);
```

If compiled with -D_POSIX and ch is '\n' the if statement prevents oclHashcat from locking the mutex.
This causes a segfault when unlocking the not locked mux_display at the end of thread_keypress.

To me the ifdef looks useless but I leave that to the experts.

**Comment by jsteube** [comment]
That section looks like an incomplete refactorization of an older pre-OSS phase. There's two ways to fix it: Remove the branch or add the same branch to the unlock() a few lines below. Since I agree to OP here I'll remove it by commenting it and we'll see how it goes. If it turns out it was necessary we'll remove the comment and add another branch.
