### ISSUE TITLE
m4510 and m4710 don't support as long salts as they are supposed to

### ISSUE THREAD

**Issue by piwvvo** [hashcat/hashcat#3029]
I noticed that optimized kernels for modes: 4510 and 4710 don't support salt length they are supposed to support (51 max length in both cases). Seems like there is an error with sha1 transform because whenever data block size is bigger than 55 bytes hash won't be cracked even if correct hash, salt and plain is given. This sadly leaves us with max salt length 15 (m4510) and 23 (m4710). This has been tested on hashcat 6.2.4 but it looks like kernels haven't been modified for 13 months so I assume hashcat version isn't the issue here.

Examples

m4510:
```
$ head hash wlist
==> hash <==
544e097cf251ead8026c29ba28f0e876227d1df6:15_chars_salt11
23b5d168c5c5300321632f4dd14126190b405f3c:16_chars_salt111
==> wlist <==
hashcat
```
```
>hashcat.exe -m 4510 -d 1 -O hash wlist --potfile-disable --quiet
544e097cf251ead8026c29ba28f0e876227d1df6:15_chars_salt11:hashcat
```

And just as a proof that both hashes will be cracked when pure kernel is used

```
>hashcat.exe -m 4510 -d 1 hash wlist --potfile-disable --quiet
544e097cf251ead8026c29ba28f0e876227d1df6:15_chars_salt11:hashcat
23b5d168c5c5300321632f4dd14126190b405f3c:16_chars_salt111:hashcat
```

m4710:
```
$ head hash wlist
==> hash <==
d113b48ce29728b725be9ecb7b93a8fe4904c720:23_chars_salt1111111111
94c7b92fac25bb2858c39dd355b59687cf944023:24_chars_salt11111111111
==> wlist <==
hashcat
```
```
>hashcat.exe -m 4710 -d 1 -O hash wlist --potfile-disable --quiet
d113b48ce29728b725be9ecb7b93a8fe4904c720:23_chars_salt1111111111:hashcat
```
```
>hashcat.exe -m 4710 -d 1 hash wlist --potfile-disable --quiet
d113b48ce29728b725be9ecb7b93a8fe4904c720:23_chars_salt1111111111:hashcat
7e8a694f715d95869ed0741963daee3a61776468:24_chars_salt11111111111:hashcat
```
I tested some different salts length which were above 15 (m4510) and 23 (m4710) char and they don't crack either. Basically I believe that there is something wrong with the second transform, I have tried finding fix for this issue by looking at m20710 kernel but I didn't succeed.

https://github.com/hashcat/hashcat/blob/d85ca3a752f08ae3d100d6b7814576da1a944e20/OpenCL/m04510_a0-optimized.cl#L1673
https://github.com/hashcat/hashcat/blob/d85ca3a752f08ae3d100d6b7814576da1a944e20/OpenCL/m04710_a0-optimized.cl#L483

As philsmd noticed is also a mistake in in module constraints more info can be found in his post https://hashcat.net/forum/thread-10432-post-54029.html#pid54029

https://github.com/hashcat/hashcat/blob/d85ca3a752f08ae3d100d6b7814576da1a944e20/tools/test_modules/m04510.pm#L13
https://github.com/hashcat/hashcat/blob/d85ca3a752f08ae3d100d6b7814576da1a944e20/tools/test_modules/m04710.pm#L14

**Comment by philsmd** [comment]
I've investigated this now a little bit and the problem seems that with the optimized kernels and the `SHA1M_A` up to `SHA1M_E` substractions, we also need to deal with these difference in the kernel when entering the `>= 56 branch`.

I've now proofed this (for only -m 4510 and -a 0 kernel), note: only optimized kernels are affected:
```diff
diff --git a/OpenCL/m04510_a0-optimized.cl b/OpenCL/m04510_a0-optimized.cl
index bbcbb4cef..de183605d 100644
--- a/OpenCL/m04510_a0-optimized.cl
+++ b/OpenCL/m04510_a0-optimized.cl
@@ -1015,6 +1015,11 @@ KERNEL_FQ void m04510_m04 (KERN_ATTR_RULES ())
     wf_t = hc_rotl32 ((wc_t ^ w7_t ^ w1_t ^ wf_t), 1u);
     SHA1_STEP (SHA1_F1, b, c, d, e, a, wf_t);
 
+    b += digest[1] - SHA1M_B;
+    c += digest[2] - SHA1M_C;
+    d += digest[3] - SHA1M_D;
+    e += digest[4] - SHA1M_E;
+
     COMPARE_M_SIMD (d, e, c, b);
   }
 }
@@ -1117,7 +1122,7 @@ KERNEL_FQ void m04510_s04 (KERN_ATTR_RULES ())
    * reverse
    */
 
-  const u32 e_rev = hc_rotl32_S (search[1], 2u);
+  // const u32 e_rev = hc_rotl32_S (search[1], 2u);
 
   /**
    * loop
@@ -2025,18 +2030,27 @@ KERNEL_FQ void m04510_s04 (KERN_ATTR_RULES ())
     wb_t = hc_rotl32 ((w8_t ^ w3_t ^ wd_t ^ wb_t), 1u);
     SHA1_STEP (SHA1_F1, a, b, c, d, e, wb_t);
 
-    if (MATCHES_NONE_VS (e, e_rev))
-      continue;
+    // if (MATCHES_NONE_VS (e, e_rev))
+    //   continue;
 
     wc_t = hc_rotl32 ((w9_t ^ w4_t ^ we_t ^ wc_t), 1u);
     SHA1_STEP (SHA1_F1, e, a, b, c, d, wc_t);
     wd_t = hc_rotl32 ((wa_t ^ w5_t ^ wf_t ^ wd_t), 1u);
     SHA1_STEP (SHA1_F1, d, e, a, b, c, wd_t);
+
+    if (MATCHES_NONE_VS (e + digest[4] - SHA1M_E, search[1]))
+      continue;
+
     we_t = hc_rotl32 ((wb_t ^ w6_t ^ w0_t ^ we_t), 1u);
     SHA1_STEP (SHA1_F1, c, d, e, a, b, we_t);
     wf_t = hc_rotl32 ((wc_t ^ w7_t ^ w1_t ^ wf_t), 1u);
     SHA1_STEP (SHA1_F1, b, c, d, e, a, wf_t);
 
+    b += digest[1] - SHA1M_B;
+    c += digest[2] - SHA1M_C;
+    d += digest[3] - SHA1M_D;
+    e += digest[4] - SHA1M_E;
+
     COMPARE_S_SIMD (d, e, c, b);
   }
 }
diff --git a/src/modules/module_04510.c b/src/modules/module_04510.c
index 7bb55f131..2ef1e5b69 100644
--- a/src/modules/module_04510.c
+++ b/src/modules/module_04510.c
@@ -46,6 +46,13 @@ u32         module_salt_type      (MAYBE_UNUSED const hashconfig_t *hashconfig,
 const char *module_st_hash        (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return ST_HASH;         }
 const char *module_st_pass        (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return ST_PASS;         }
 
+u32 module_salt_max (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra)
+{
+  const u32 salt_max = 64;
+
+  return salt_max;
+}
+
 int module_hash_decode (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED void *digest_buf, MAYBE_UNUSED salt_t *salt, MAYBE_UNUSED void *esalt_buf, MAYBE_UNUSED void *hook_salt_buf, MAYBE_UNUSED hashinfo_t *hash_info, const char *line_buf, MAYBE_UNUSED const int line_len)
 {
   u32 *digest = (u32 *) digest_buf;
@@ -225,7 +232,7 @@ void module_init (module_ctx_t *module_ctx)
   module_ctx->module_pwdump_column            = MODULE_DEFAULT;
   module_ctx->module_pw_max                   = MODULE_DEFAULT;
   module_ctx->module_pw_min                   = MODULE_DEFAULT;
-  module_ctx->module_salt_max                 = MODULE_DEFAULT;
+  module_ctx->module_salt_max                 = module_salt_max;
   module_ctx->module_salt_min                 = MODULE_DEFAULT;
   module_ctx->module_salt_type                = module_salt_type;
   module_ctx->module_separator                = MODULE_DEFAULT;
diff --git a/tools/test.pl b/tools/test.pl
index 0c909d0ae..986fe2ed6 100755
--- a/tools/test.pl
+++ b/tools/test.pl
@@ -409,7 +409,9 @@ sub init_db_salt_rand
     # #define SALT_MAX_OLD        51
     # salt_max = SALT_MAX_OLD;
 
-    $len_max = ($len_max >= 51) ? 51 : $len_max;
+    # DEBUG:
+    # TODO: do NOT touch this, just testing it
+    # $len_max = ($len_max >= 51) ? 51 : $len_max;
 
     $len_min = ($len_min < $len_max) ? $len_min : $len_max;
   }
diff --git a/tools/test_modules/m04510.pm b/tools/test_modules/m04510.pm
index d016b6483..5256895ec 100644
--- a/tools/test_modules/m04510.pm
+++ b/tools/test_modules/m04510.pm
@@ -10,7 +10,7 @@ use warnings;
 
 use Digest::SHA qw (sha1_hex);
 
-sub module_constraints { [[0, 256], [0, 256], [0, 55], [0, 15], [-1, -1]] }
+sub module_constraints { [[0, 256], [0, 256], [0, 55], [0, 64], [-1, -1]] }
 
 sub module_generate_hash
 {
```

Attention: please note that `tools/test.pl` doesn't need to be modified in case we apply a similar patch (it's just done here to really test all the cases up to 64 bytes of salt)... also we could debate if we really need to support 64 of salt or just use the usual 51 bytes limit (so also `module_salt_max` could be skipped if we decide to do so).

The main problem lies in the `b += digest[1] - SHA1M_B` calculation.... this is only needed for the `>= 56 branch` because we have a further transformation there and therefore need to adjust `b` (otherwise, i.e. in the usual / short salt case,  `digest[1]` would just be the same as `SHA1M_B` and therefore we would just add 0 (nothing).

A patch similar to this would also need to be applied for all the `*_a0-optimized.cl`,  `*_a1-optimized.cl` and `*_a3-optimized.cl` kernels for -m 4510 and -m 4710.

While checking this bug I was also trying to look for further problems in other hash types (e.g. by searching like this `grep -r '>= 56' OpenCL/ | grep a3 | grep optimized`), but I'm not sure if other hash types are affected similarly (only -m 13500 and -m 20710 seem to have similar >= 56 branches, but they are kind of different).

Maybe @jsteube could have a further look at this and maybe also double-check if no further hash types are affected by similar bugs

Thanks for the report, it really seems like you found a bug here (with both how and what we test and also the main problem about unsupported longer salt).

Thx guys
