### ISSUE TITLE
Charset not  existe Ñ or ñ 

### ISSUE THREAD

**Issue by bc0d3** [hashcat/hashcat#3047]
**Describe the feature**
If you create a password that contains the letter `ñ" and select the brute force mode you can not find the password.

Because there is no ñ in the configuration.

![imagen](https://user-images.githubusercontent.com/29527937/144061036-2477522e-0a33-4d02-8ba5-7bbad06e2fba.png)

if you use this hash MD5:
`aa15457d671c87e3ebd6367a0ed022b9` = "año" in english is "year"

![imagen](https://user-images.githubusercontent.com/29527937/144061270-db30da8e-2e3b-438f-9c09-c03cc6c2be12.png)

The password was not found because there is no "ñ" in the options.

why not add this ñ in "Charset"

**Comment by Xanadrel** [comment]
You wouldn't report an issue where your hash isn't cracked because the char isn't included in the charset you told hashcat to use, wouldn't you ?

hashcat has enough built-in charsets, it also comes with extra charset files in the "charsets" folders, including ones for languages, including spanish.
And if that is not enough, nothing prevents you from defining custom charset / charset files to suit your needs.

Also: that hash can be cracked using ?b?b?b?b.
