### ISSUE TITLE
-m 3000 = LM does not support $HEX[] word lists (-a 0,1,6,7)

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#3050]
When using -m 3000 = LM hashcat does cut the password candidate line input at position 7 (maximum password length for LM).
This is done before the $HEX{aabbcc...] is checked within the input file (dict/wordlist), therefore `$HEX[]` isn't parsed correctly at all.

For devs: this probably has to do with `get_next_word_lm()` and that `convert_from_hex ()` is called AFTER the truncation (in `get_next_word_lm()`). We would need to make sure to do the $HEX-conversion always before the truncation (and line reading limits).

This can be tested with very simple password candidates like `$HEX[6a6b]` (fun fact: you will notice that this is both cut/truncated and also upper-cased and you will see very strange password candidates in the status prompt, like `$HEX[6A -> 6B]`).

Thanks

**Comment by b0lek** [comment]
You are correct.  
There are two ways of giving password candidates:
- with `$HEX[...]` notation - just one item between normal passwords in a wordlist
- with "--hex-wordlist" flag - whole wordlist is then in hex without using `$HEX[...]` notation

Additionally I've found another problem with this hash-type. When the line with passwords is longer than 7 characters it is split into few words of 7 chars so line:
`aaaaaaabbbbbbbcc`
will be split into 3 password candidates
`aaaaaaa` `bbbbbbb` `cc`
And even more surprising case of line:
`dddddddeeeeeeefffffff`
will result in 4 password candidates (if I see it correctly):
`ddddddd` `eeeeeee` `fffffff` `<empty>`
with empty string as last one.
This is a performance issues as we check unwanted password candidates in case of this hash-type

I'm working on a fix for all of these problems.

**Comment by jsteube** [comment]
I've checked the patch in the PR from @b0lek  using the examples provided from @philsmd but it doesn't crack. 

The reason is that the 'jk' word has to be upper cased (because `6a6b` is in lower case), but the get_next_word_lm_gen() doesn't upper case values if they are in hex (and so it doesn't convert it tot `4a4b`). There's many ways how to solve this, but the safest way I think is using hex_to_u8(), and then do the check a to z, and then convert back with u8_to_hex().

I'd also suggest to use is_hexify() since it covers almost all the code to validate if the given string is $HEX[]. It also checks if the values in between the [] are valid hex combinations, which makes it safer to use the hex_to_u8() afterwards. The only problem is that the sz value is the remaining data length of the entire buffer not the word so we can't do the length even/odd check. To workaround that, we need to call it like this and then it should be fine:

```
const bool is_hex = is_hexify ((const u8 *) buf, sz & ~1);
```

@b0lek Could you please update the PR accordingly?

**Comment by b0lek** [comment]
Thanks @jsteube for your comments. 

Converting to upper case in $HEX[] notation is the thing I've missed. Now it's added.

Regarding suggestion to use is_hexify() I see a problem with this one. It checks also last character in the string:
`if (buf[len - 1] != ']') return (false);`
That is why we need to give a real `len` to is_hexify(). I didn't want to impact other code than used in LM hash.
Let me know if have any any suggestions how to refactor this code. I don't like it too much but I haven't found a better way as for now.

So see the updated PR.

**Comment by jsteube** [comment]
All good the patch works fine, many thanks for the PR!
