### ISSUE TITLE
Support for PeopleSoft's PS_TOKEN SHA1

### ISSUE THREAD

**Issue by fgaudreault** [hashcat/hashcat#306]
Would love to see a new mode added for that. There is one for the application password, but if we could get a sha1($salt.utf16le($pass)) to break the SHA1 signature of the token, that would be great. The salt length is very long, 130-150bytes, so we can't really use any existing mode.

**Comment by jsteube** [comment]
Wait, they have a 130 byte long salt on start? hihihi I guess they didn't read my post about how not to salt a hash :) https://hashcat.net/forum/thread-4429.html

Please give us an exact number for the salt length range

**Comment by fgaudreault** [comment]
It will be hard to give you an exact bracket or a fixed number, the salt length will vary depending of variables such as the username, the node name, the date, etc. :/ The other thing is that the salt will contain null bytes.

**Comment by jsteube** [comment]
The null byte shouldn't be a problem. You can encode the salt in hex and use --hex-salt or we're creating a special parser for the mode. I'd recommend the 2nd in case the different salts are not concatinated into a single long string.

**Comment by fgaudreault** [comment]
Ok, that make sense. I actually created a new parser yesterday on a local copy, but now I have to figure out how to change the algorithm (which is almost identical to -m 140), except that the salt is bigger and the password is encoded in utf16le.

**Comment by jsteube** [comment]
you need to create a new kernel to make and because of this you can't use the -m 140 address space for it. use the next free -m

**Comment by jsteube** [comment]
i can help you with the kernel details once you pushed the parser and kernel template

**Comment by fgaudreault** [comment]
Ok, so I will prepare a pull for the parser code (which is basically a copy of 140, but with higher min/max salt length constants), and a copy of the 140 kernels as a base. My local test picked the salt, but the core was not able to crack the password. I believe that's normal nice the kernels are not able to handle that data yet. I used -m 134 since the PeopleSoft application passwords were -m 133.

**Comment by jsteube** [comment]
Please don't use * here

    #define DISPLAY_LEN_MIN_13500 40 + 1 + 16 * 2
    #define DISPLAY_LEN_MAX_13500 40 + 1 + 512 * 2

Simply do:

    #define DISPLAY_LEN_MIN_13500 40 + 1 + 32
    #define DISPLAY_LEN_MAX_13500 40 + 1 + 1024

Sorting of this:

    13400,
    13500,

Should be:

      133,
    13500,

You're still using an invalid option for the salt which you need to remove:

    | OPTS_TYPE_ST_ADDBITS15;

The following optimization is not possible since our data buffer is > length 55, you need to remove it:

    | OPTI_TYPE_PRECOMPUTE_MERKLE

This code:

    memset(pstoken_tmp, 0, mysalt_len + 1);

Is wrong in two ways. First you should use sizeof():

    memset (pstoken_tmp, 0, sizeof (pstoken_tmp));

Another problem is that you're using a value which is unknown at compile time to declare a number of elements in an array.

Instead of:

    u8 pstoken_tmp[mysalt_len + 1];

You should do:

    u8 pstoken_tmp[512 + 1];

More problems with snprintf():

    snprintf((char *)(pstoken_tmp + i), (size_t)2, "%02x", pstoken->salt_buf[i]);

Problem 1, the "%02x" does not match salt_buf[] which is 32 bit, not 8 bit. You propably need to something like this befoire you can use it:
  
    u8 *salt_buf_ptr = (u8 *) pstoken->salt_buf:

    ... and then use salt_buf_ptr[i] in the snprintf()

Problem 2, the casting of pstoken_tmp from u8 * -> char * is not necessary. 

    Just declare pstoken_tmp as char *.

Suggestion:

    The use of snprintf() is slow, take a look bin_to_hex_lower (). This is not always useful but sometimes it is.

Inside the parser you do:

    u8 pstoken_tmp[DISPLAY_LEN_MAX_13500 - 40 - 1];

    memset(pstoken_tmp, 0, DISPLAY_LEN_MAX_13500 - 40 - 1);

I'd recommend to use the same declaration as in ascii_digest instead:

    u8 pstoken_tmp[512 + 1];

    memset (pstoken_tmp, 0, sizeof (pstoken_tmp));

This optimization does not work here, because we need a 2nd call to sha1_transform because of the length > 55. You need to remove it:

    digest[0] -= SHA1M_A;
    digest[1] -= SHA1M_B;
    digest[2] -= SHA1M_C;
    digest[3] -= SHA1M_D;
    digest[4] -= SHA1M_E;

That was easy stuff so fow, but now in test.pl it's getting real problematic. From your original issue you said:

> Would love to see a new mode added for that. There is one for the application password, but if we could get a sha1($salt.utf16le($pass)) to break the SHA1 signature of the token, that would be great. The salt length is very long, 130-150bytes, so we can't really use any existing mode.

What you totaly did not mention is the use of DES inside the algorithm. Now I'm very confused. Please explain in words how DES is involved in the process. It's important to write a proper kernel.

**Comment by jsteube** [comment]
OK I've added kernel functionality and other host changes so that it should crack now: https://github.com/hashcat/oclHashcat/commit/aef8dc2b0181d865b8f684c9e3af4fd9dba81012

What's still missing is the verify functionality in the test.pl. Please add it so that this kernel integration can be called "finished".

Here's a screenshot seeing in action: http://pastebin.com/QzkVfCyh

**Comment by fgaudreault** [comment]
Awesome!! Sorry you had to rewrite some of our code :/  For the verify, I added the mode 13500 to the hash:salt portion.. unless we have additional stuff to add? Let me run it and see whats missing.

**Comment by jsteube** [comment]
It was just minor changes to your code, nothing to worry. The verify command is used to check an existing hash and a known password to be "correct". The important part here is that the verify command uses the salt (which usually changes per hash) is used as salt in the calculation of the hash. Otherwise you can't check for correctness. So if you want to know if your change worked correctly just create two files. 1 with just the hash, then another one with that hash with and the salt appended and then let run the verify command

**Comment by jsteube** [comment]
If you send in a PR of what you've done so far i can finish it

**Comment by fgaudreault** [comment]
Ill look at it this morning. When I tried yesterday, I couldnt get it to work.

**Comment by fgaudreault** [comment]
Ok. I just added the missing portion. The rest was already there. I will do a pull request. Actually, the hash file had to be hash:salt, and the crack hash:salt:word in order for the script to work properly. Pull request is open.

**Comment by jsteube** [comment]
OK, should be done now. Thanks for the PR. I also had to patch a small bug when running on AMD.
