### ISSUE TITLE
New tool available - password to mask (do the inverse of hashcat attacks)

### ISSUE THREAD

**Issue by sensei-hacker** [hashcat/hashcat#3150]
I made a little utility that does the mask attack in reverse.  That is, it does the inverse.
Given sample strings / passwords, it generates the matching masks.  Example:

```
$ echo -e "Hashcat\nJens2015" | pw2mask 
?u?l?l?l?l?l?l
?u?l?l?l?d?d?d?d
```

I intend to add other types of attacks, so the utility can do the inverse of whatever hashcat does.
So the inverse hybrid attack will accept as input "ILoveYou9876" and output "{dict}?d?d?d?d".
```
$ echo "ILoveYou9876" | pw2hybrid
{dict}?d?d?d?d
```

In other words, given a set of sample passwords, the tooling will tell you which rules / techniques would be used for them.
Would this be of interest to others perhaps?  Perhaps useful to the Hashcat team?

**Comment by roycewilliams** [comment]
Thanks for the offer! Good idea, and a good exercise in figuring out how to do it right. There are already other standard tools we usually rely on in this space - statsgen from iphelix/PACK (Python 2) / fork Hydraze/PACK (Python 3), and a faster (Rust) implementation (hops/pack2 with its 'statsgen' subcommand).

**Comment by roycewilliams** [comment]
I see that you've expanded your description of the tool's scope a bit - interesting!

**Comment by kost123** [comment]
Not sure if this is a hashcat issue but yea, can you expand on how your tool identifies when to use a dictionary? Does it check for X amount of ?l/?u in a row?

**Comment by sensei-hacker** [comment]
> 

That's an interesting question. I'm open to ideas / suggestions. I'll probably implement dictionary tomorrow or so.  I've thinking check for more than four letters in a row, then check something like it matches anything in the dictionary, with no more than one character replaced. I've built an indexing tool for the dictionary to make lookups very fast, if it's more or less an exact match.

 Any thoughts you have, I'm all ears.

Full Levenshtein distance may be too resource intensive.  I need to look at exactly what people generally do with a dictionary with hashcat.

I'm stepping through each attack and figuring out how to do the inverse one attack at a time. :)

I'm doing some things PACK can't do, as far as I can tell. Today I coded checking to (quickly) count how many character classes are in each password. One use of that is identifying those that meet the typical requirements regarding upper case, lowercase, digits, and punctuation ("special characters").

**Comment by philsmd** [comment]
This is indeed interesting.
... but now I'm wondering if we need this github issue here... this is more an information that this tool exists , right ? Or am I understanding this incorrectly ?

Maybe you could make a hashcat forum post/thread and link it here and close this github issue ? Is that a good and acceptable strategy in your (@MorrisR2) opinion ? Thanks for the contribution with your tool

**Comment by sensei-hacker** [comment]
@philsmd  Originally I was asking if it might be appropriate to do a PR to add these tools to hashcat, so that was the purpose:

> Would this be of interest to others perhaps? Perhaps useful to the Hashcat team?

More recently, I learned that I had largely re-created the existing PACK toolset.
I'm now thinking the best place to put my contributions would be as PRs for PACK.
If that's agreed, I think this issue can be closed and I'll move my efforts to PACK.

I'll also have a separate repo that combines the tooling in a new way - as a password strength meter. If a candidate password match a mask that's likely to be checked, it's not a good password. :)
Similarly, if it would be cracked using a dictionary and rule set similar to what is typically used for cracking, we'll call it not a strong password.  But that will be a different repo entirely.

Unless someone suggests otherwise, I'll plan on sending my changes / additions to the PACK repo.

**Comment by philsmd** [comment]
yeah, sounds like a good idea. not sure how active the `PACK` maintainers/owners/contributers are these days, I remember there was a time when there were no changes in months/years, but suddently at some time they had some major updates to python 3 etc (as far as I remember). it's also okay if it is and remains a completely separate (github) project and tool, if you don't get any replies by the `PACK` authors.

Don't hesitate to mention your github links here and maybe also on the hashcat forum (it's best to have it also there).

I think I will close this for now because there is little the owners/contributers of `hashcat` can do here (for now)... but again, that doesn't mean that we don't appreciate all your effort, it's the opposite, we always felt that these sometimes small and tiny, but sometimes also little more complex 3rd party tools that always had a very nice goal that they achieved, help the cracking community a lot... this is why we support and work together with such tools and authors a lot (see `hcxtools` or `hashtopolis` etc).

Thanks
