### ISSUE TITLE
PDF (10700) Optimized Kernel broken on Nvidia

### ISSUE THREAD

**Issue by s3inlc** [hashcat/hashcat#3151]
The changes introduced in commit 1d33b5714474439b2bd81f882ef02ca947b253fb seem to break the kernel (partially) for Nvidia cards, resulting in memory errors (illegal memory accesses). 

The error seems to be independent of the driver version and which Nvidia Card is used. 

Example command to reproduce:
```
./hashcat -m 10700 <example-hash> example.dict -r rules/dive.rule -O
```

The error behavior is the same for a freshly pulled version from the repository.
When running using the previous commit (https://github.com/hashcat/hashcat/commit/d85ca3a752f08ae3d100d6b7814576da1a944e20) to the above mentioned one, the errors do not happen.

**Comment by philsmd** [comment]
could this be a problem with "`const`" (because some functions declare it as const but call other functions that do not have const and modify the `sc` buffer)? if so, where exactly do we need to remove the `const` ?

Could you try it without the `const` modifiers ? (do not forget to `make clean` or run `rm -r kernels/`.

Thanks for the report

cc: @jsteube , maybe `const` problem ?

**Comment by s3inlc** [comment]
Thanks for looking into the issue. I assume you mean the const modifiers at these two positions, correct?
https://github.com/hashcat/hashcat/blob/master/OpenCL/m10700-optimized.cl#L274
https://github.com/hashcat/hashcat/blob/master/OpenCL/m10700-optimized.cl#L304

I'm not completely sure if I understand everything happening there, but is the buffer sc really modified inside these two functions (or the called functions like hc_perm.. etc.)? If not, the const should not really make a difference here.

I tested with removing the const modifier on these two functions, but there is no difference. But when I tested some more things I noticed something else. It seems to depend on the number of rules, no matter if I use a small or large wordlist, if I use dive.rule, it crashes after few seconds running. 
So I tested with more of the rule files of Hashcat and it seems that only dive.rule and generated2.rule are large enough to produce this error. The errors printed when it stops are of these kind (each of them printed many times):
```
cuEventSynchronize(): an illegal memory access was encountered
cuMemcpyDtoHAsync(): an illegal memory access was encountered
cuMemFree(): an illegal memory access was encountered
cuEventDestroy(): an illegal memory access was encountered
cuStreamDestroy(): an illegal memory access was encountered
cuModuleUnload(): an illegal memory access was encountered
```

**Comment by philsmd** [comment]
Hey @s3inlc ,

you are absolutely right. I back then just looked at the diff (https://github.com/hashcat/hashcat/commit/1d33b5714474439b2bd81f882ef02ca947b253fb) and looking at that diff only the `const` looked a little bit suspicious...

but now I was able to reproduce it (it's even possible to reproduce it with just a very long word and several word duplicate rules)... the problem is all about password lengths and how the passwords affect the `sc`/`s_sc` buffer/variable, see:
https://github.com/hashcat/hashcat/blob/8bc4a920892185ab52e5b05b92378a4658fc0864/OpenCL/m10700-optimized.cl#L227-L233

it's basically a buffer overflow and the diff that seemed to have introduce a bug wasn't actually the culprit, but it triggered the bug  and a driver exit/crash even "better" (most probably due to the use of the - restricted / limited - shared memory ).

Very nice find !

It should be fixed with my patch, I've tested it carefully (even running the unit tests `test.sh` dozens of times and the `rule tests` didn't result in any further problems).

Thanks and kudos

**Comment by s3inlc** [comment]
Very nice, thanks for the fix and your work. I guess it was not the easiest thing to find, especially as it was not really introduced by the commit I referenced and I was not able to provide what exactly caused the issue.

I didn't manage to test it yet, but I very much trust that you tested it well, I'll try to test it within the next days and report back.

**Comment by s3inlc** [comment]
I tested it out today, and it seems to be work correctly now. Thanks again for fixing.
