### ISSUE TITLE
In the Github relase, profile_dir is equal to install_dir

### ISSUE THREAD

**Issue by AdrianVollmer** [hashcat/hashcat#3165]
I am using the releases hosted in this Github repository and noticed that the potfile and session files are stored in the install_dir instead of the profile_dir, unlike the FAQ says. According to this [line](https://github.com/hashcat/hashcat/blob/ee2d50d3413741d1fc0b05c10492cda945dbbd21/src/folder.c#L435), this happens when `_POSIX` is not set.

However, I am using hashcat on Debian 9, so I'd expect these files to end up in `~/.hashcat`. This would also be my preference, because I'm sometimes running different versions of hashcat and I want them to share a potfile. This behavior is confirmed for these versions:

* 5.1.0
* 6.2.1
* 6.2.3
* 6.2.4

Is this behavior intended? Were your releases built on Windows? Would you recommend that I build hashcat myself instead or find a workaround, e.g. with symlinks?

Many thanks!

**Comment by philsmd** [comment]
but you do not use `make install` ? When you do not use this, the current directory is normally priorized (the readme actually mentions the paths only in case of an "Install": https://github.com/hashcat/hashcat/blob/master/BUILD.md#install-hashcat-for-linux).

how did you download and "install" hashcat ?

**Comment by AdrianVollmer** [comment]
I downloaded [the zipped release from Github](https://github.com/hashcat/hashcat/releases) and unzipped it. Then I created a symlink in `~/.local/bin` to the hashcat binary. The zipfiles do not contain a Makefile. Are they not meant to be used?


```
$ wget -q https://github.com/hashcat/hashcat/releases/download/v6.2.5/hashcat-6.2.5.7z ; 7z x hashcat-6.2.5.7z > /dev/null ; find hashcat-6.2.5 -name Makefile
$
```

**Comment by philsmd** [comment]
to have the `Makefile` within your working directory, you need to use the `source code` archives from https://github.com/hashcat/hashcat/releases (e.g.  `Source code (zip)` or `Source code (tar.gz) `) or use the git version: (`git clone https://github.com/hashcat/hashcat`), otherwise there are only binaries and the most important config or example files (rules, dicts, masks etc) within the downloaded archive.

When you have the source code downloaded, you could just use `make` followed by `sudo make install` and it should work.
Please test this approach. thx

**Comment by AdrianVollmer** [comment]
I'm afraid there is a misunderstanding. I'm not building hashcat at all, I'm using the binary releases in `hashcat-6.2.5.7z` which the hashcat project is providing right here on github: https://github.com/hashcat/hashcat/releases/download/v6.2.5/hashcat-6.2.5.7z

I am also not intending to build hashcat myself. I know how to build hashcat, that is not the question. But I would like to avoid it if it is not necessary, as I'm using it in a restricted environment and getting the necessary dependencies there is non-trivial. These releases are working just fine for me besides this one issue of the profile folder being equal to the install folder.

I propose one of the following three options.

1. You fix the binary releases on github so the profile folder behaves as documented.
2. You document this behavior properly for the releases because it deviates from the documentation.
3. If those release are not intended to be used, as you seem confused that I'm using hashcat without ever building it myself, I suggest the releases being removed.

Obviously I prefer option 1, but I could live with option 2 or 3 and resort to building it myself anyway.

**Comment by philsmd** [comment]
I think the idea is that either the person that compiles hashcat (using the `Makefile` file) tells which paths should be used or the linux distribution authors (like `ubuntu` linux). both these "installed" versions should use the path that were mentioned during "compilation", otherwise the current directory is used.

I'm not sure which exact documentation you mean exactly, we only have mentioned these path in the `BUILD.md` file (which indeed is meant for users that are compiling it themself or are compiling the binaries for a distribution with known paths)...

(as far as I remember this is exactly how it was intended to work - at least back then -, maybe it changed over time or I missed how users use it or want to use it these days...  the idea was that anybody who downloads the binaries is using the current directory, otherwise you need to "install" it)

btw: on ubuntu/debian `sudo apt install hashcat` should work, but of course we are not the maintainers of the linux distro packages, so we can't guarantee if these packages are always up to date etc... therefore many users just use the latest version from the hashcat website and use the local directory.

I guess also other users/contributers could jump in here to mention how they use it and how it is (nowadays) supposed to work in their opinion... but the idea back then was exactly as described (either cwd with download or system paths on LINUX when installed with `Makefile` or distro tools, on windows only the local path/pwd/cwd works for now).

Does this make sense for you ? ... of course we could discuss if we should change all this behaviour and path management (again), but I think there were already a couple of (github/forum) issues back then, and the general consensus was to just have these 2 alternatives and they worked for all/most of the users, I guess. that's why we used this approach. That doesn't mean that we couldn't improve things if we have a much more clever idea.... but the problem with paths is also sometimes that users otherwise don't find the important (session) files etc... and this approach worked best to not confuse the users where the files are stored in etc.

I think other owners/contributers/users mentioning the facts what is going on under the hood and also opinions what the ideas /arguments were back then (issue history links) etc could help here to make it clear how it works nowadays and how it should work... maybe somebody else jumps in here to confirm how it (should) work. but in general, I think the idea is pretty clear and stayed the same even if we didn't touch this behaviour a lot lately.

I'm still interested in the documention that you are mentioning, because maybe the documentation files are not up to date (that's easily possible). Thanks again

**Comment by AdrianVollmer** [comment]
Thanks for taking the time to go into this.

> I'm not sure which exact documentation you mean exactly, we only have mentioned these path in the BUILD.md file (which indeed is meant for users that are compiling it themself or are compiling the binaries for a distribution with known paths)...

The one you linked: https://github.com/hashcat/hashcat/blob/master/BUILD.md#install-hashcat-for-linux

According to this documentation, the potfile should end up in either `$HOME/.hashcat`, `$XDG_DATA_HOME/hashcat/`, `$XDG_DATA_HOME/hashcat/`, `$HOME/.local/share/hashcat/`, or `$HOME/.local/share/hashcat/`.

That is not the case with your builds. The potfile ends up in `$HOME/hashcat/hashcat-6.2.5` (my install dir). Or in `$HOME/hashcat/hashcat-6.2.1`, where I installed another version of your builds. That's my issue, I want them to share the same potfile.

> btw: on ubuntu/debian sudo apt install hashcat should work,

I know, that's what I'm doing on most of my systems, but this one system I'm using hashcat on purposefully has no connection to the internet. And again, that is not the issue. I know how to use `make` and `apt`.

Hopefully the issue now a bit clearer.

**Comment by philsmd** [comment]
I think I understand your "problem" now, but as said the documentation literally says "BUILD" so these are the paths when using a "install version" of hashcat.

I would suggest to just use the other link e.g. `https://github.com/hashcat/hashcat/archive/refs/tags/v6.2.5.zip`, unzip it, `cd` into it and run `make` and `make install`... this version afterwards should use the paths that are mentioned within the Makefile instead of the pwd.
Please test this approach and see if it works for you

**Comment by AdrianVollmer** [comment]
Yes, that works. Besides the point, still, but I will just make an internal note not to use your builds then. Thanks again for your time.
