### ISSUE TITLE
hashcat fails to start on Windows 11 - error on OpenCLOn12.dll

### ISSUE THREAD

**Issue by itismo** [hashcat/hashcat#3216]
Hello,

I am having this issue starting hashcat, it freezes upon start and I get this in the event logs.
I have tried installing a different version of Microsoft OpenCL and OpenGL Compatibility Pack but I get the same result.

GPU : Nvidia GeForce RTX 3050 Laptop CPU

Faulting application name: hashcat.exe, version: 0.0.0.0, time stamp: 0x62274b67
Faulting module name: OpenCLOn12.dll, version: 0.0.0.0, time stamp: 0x618d36bf
Exception code: 0xc0000409
Fault offset: 0x00000000000e429d
Faulting process id: 0x2e1c
Faulting application start time: 0x01d834331d42392d
Faulting application path: c:\Tools\hashcat-6.2.5+308\hashcat-6.2.5\hashcat.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.D3DMappingLayers_1.2112.2.0_x64__8wekyb3d8bbwe\x64\OpenCLOn12.dll

**Comment by philsmd** [comment]
try to uninstall it and install the driver from https://www.nvidia.com/Download/index.aspx?lang=en

questions like this are more suitable for the hashcat forum (https://hashcat.net/forum). on github we try to focus on source code problems / bugs, new features etc (not user questions like this).

I will close this here, but feel free to ask questions on the forum if you are still unable to run hashcat after installing the correct drivers for your GPU (also see https://hashcat.net/faq/wrongdriver ). It should work after installing the correct version.

**Comment by itismo** [comment]
Installed latest driver but same issue, posted on the forums.
Thanks and hope to get this resolved :)

**Comment by philsmd** [comment]
This was the hashcat forum post that @itismo is referring to: https://hashcat.net/forum/thread-10658.html

**Comment by LuKePicci** [comment]
It's an hashcat bug. It doesn't handle exceptions in "reading" multiple device info's and crashes as soon as any of the gpu has missing/broken compute toolkit. The correct expected behavior would be to get correct listing of working gpus (Nvidia in the case above) and get a polite errors about other missing compute (opencl for the integrated Intel adapter in this case).

Meanwhile, you can just guess the Nvidia device I'd and run hash at directly on that device without listing them first.
