### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by Neret** [hashcat/hashcat#3226]
hi,i have a problem with hashcat on arch,output of hashcat is segmentation fault in any command,in the dmesg i've strange output on hashcat
  652.942714] hashcat[7484]: segfault at 10 ip 00007f15108ed688 sp 00007fffb99990e0 error 4 in libhsa-runtime64.so.1.5.50002[7f1510800000+15c000]
why?i have installed opencl-amd

**Comment by philsmd** [comment]
seems that this is a problem with your installation. Could you please ask this question in the hashcat forum at https://hashcat.net/forum ? It's more likely that a hashcat user that uses the same operating system and hardware is able to help you there.

You should of course also mention what type of computer and hardware you have (all the details needed). does `clinfo` work for you etc ? all these detailed answers should be mentioned in a new hashcat forum post and hopefully somebody there is able to help you as soon as possible.

I will close this `github` issue for now, because it doesn't seem that this is really a `hashcat`-specific problem for which a developer needs and could jump in - not dev specific - (some of your runtimes / drivers are crashing and probably it's just a mix of incorreclty installed drivers and/or operating-system-specific problem). Thx
