### ISSUE TITLE
Adding potfile founds as wordlist

### ISSUE THREAD

**Issue by b8vr** [hashcat/hashcat#3280]
It could be really nice to be able to use the potfile(s) as wordlists, like adding something like --potfile-wl, maybe combined with the existing --potfile-path, which would remove the hashes from the potfiles and use the cracked passwords as a wordlist. 

In my mind, it would be like using --username, just removing the hash instead, leaving the cracked password.

**Comment by Chick3nman** [comment]
This is sorta already implemented internally for hashes that are removed from the current target list by the potfile when using --loopback, but I'm not sure it could be easily implemented elsewhere. The potfile stores many different algorithms/formats and unless you invoke a specific module parser to indicate which hash formats you are trying to collect the plaintexts from. This can be _approximately_ achieved outside of hashcat by doing a `cat hashcat.potfile | rev | cut -d':' -f1 | rev` but I'm not sure how it would be done within hashcat.

**Comment by b8vr** [comment]
Yes, it's sorta implemented, but only if the target contains the same hash as the one present in the potfile, right?
I don't know the inner workings of hashcat, but as you mentioned yourself, it can be achieved quite easy on the commandline. But you would have to do it - in principal - every time you have new founds, that you would want to add to the potfile wordlists.
Again, without knowing the details of the inner workings, I just imagine that if it's possible to use a hashlist with usernames, where you just supply --username to not use them as part of the hash, it should be possible to do something similar with potfiles - and founds-files btw.
Wouldn't it just be like reading the line from file, reverse it, cut the first part, reverse it again (like the command you mentioned), do the hash calc and compare and then on to the next line until EOF?

**Comment by Chick3nman** [comment]
It's only possible to do `--username` because of the way the module parser works. It essentially just adds a token to the parsing logic on the front end. But how would you invoke the module parser if you dont know what kind of hash you are looking for? Like i said, the potfile contains many different hashes. So if you are trying to find the plaintext from a hash such as unsalted MD5, it's just `hash:plain`. But if the line is salted MD5, then its `hash:salt:plain`. The way it works right now with loopback is that it uses the module parser for the mode you have selected to find the hashes that correlate to the ones in your target list. But it wouldn't be able to pull the plaintext off of other hash formats in the potfile that it doesn't know how to parse at that point. If you do the rev|cut|rev trick, you aren't actually guaranteed to get the full/correct plaintext. It's likely to work, but it's not guaranteed, hence calling it approximate. You could do that with rules even, in theory, but it would not be perfect still.

**Comment by b8vr** [comment]
That makes sense I guess, seeing that passwords could also contain the : character. 
Passware does a lookup on previously cracked passwords, but those passwords are also stored in json (or a db, can't remember), so that makes it a lot easier of course.
Alright. I'll close the request.
