### ISSUE TITLE
Build fails on OS X - cannot find gmp.h

### ISSUE THREAD

**Issue by cablebox** [hashcat/hashcat#334]
Building per the instructions in [https://github.com/hashcat/oclHashcat/blob/master/BUILD.md](BUILD.md) on OS X errors from gmp.h not being found. Terminal output attached.

Running 10.11.4. GMP is already via Brew, however I tested this on a machine without it and the result was the same.

[failedcompile.txt](https://github.com/hashcat/oclHashcat/files/264776/failedcompile.txt)

**Comment by philsmd** [comment]
Are you sure that you are reporting this problem to the correct project?
This is the OpenCL version (https://github.com/hashcat/oclHashcat).
All the errors mentioned in your output seem to be related to cpu hashcat (https://github.com/hashcat/hashcat).

Just to make it very clear, you cannot build cpu hashcat with the instructions mentioned within the BUILD.md file of oclHashcat. These are 2 very different projects.

Fortunately, in the future we might not have to tell users that hashcat != oclHashcat, because the main goal for the near future is to have only 1 hashcat binary (1 for each supported platform), that supports all OpenCL compatible CPUs and GPUs.

I would say, that this problem is completely unrelated to oclHashcat. Do you agree?

**Comment by cablebox** [comment]
Weird. I just ran 'make' again, and it compiled without issues (confirmed I was doing it in oclhashcat).
