### ISSUE TITLE
Feature request: add progress command line option (at least percent)

### ISSUE THREAD

**Issue by pbies** [hashcat/hashcat#3345]
Session and restore is fine way to store progress of cracking,
but I think it would be very nice - if someone forget session and overwrite hashcat.restore file - to add command line option to choose progress at which hashcat should continue cracking - at least at percent resolution.

**Comment by Chick3nman** [comment]
This is already a feature, that's what `--skip` and `--limit` do.

**Comment by pbies** [comment]
There should be percents as an easier method. No multiplying/dividing needed.

**Comment by Chick3nman** [comment]
Percent would not be very precise, and isn't generally represented the way I think you are expecting. "Progress" tracks how far you are into the total attack space, but `--skip` and `--limit` operate on the "Restore Point" value, which is a different value.

**Comment by pbies** [comment]
I know what these values are and percent, even if not precise, would be very appropriate for hashcat restore function.

**Comment by Chick3nman** [comment]
Hashcat doesn't restore based on the "Progress" value though, it restores based on the bases, which is represented as the "Restore Point" value. Which, again, `--skip` and `--limit` _already_ operate on. Your value of "percent complete" would not necessarily line up between how far you have gotten into the total attack space vs how far you have gotten into the bases. If you want "percent of progress" you will need to choose _which_ "progress" value you actually mean, due to them being different. I'm not understanding how using a percentage, especially given the above, would be appropriate here.

**Comment by pbies** [comment]
I mean percent of progress that at particular moment has been made and it is one value always. It is appropriate here if user does not want to restore from file, but give specific value on the command line. I've already explained that. Brute-force space that is.
Hashcat can compute how far he is in progress in space, user shouldn't be the one to give specific value. Percent is enough. Optionally it can be given with 2 digits after dot.

**Comment by Chick3nman** [comment]
> I mean percent of progress that at particular moment has been made and it is one value always.

If you are referring to the "Progress" value that is visible in the status output then this is not necessarily true nor is it how hashcat restores from restore file. We store a restore point value based on the number of bases, the actual divisible base candidates. The "Progress" value that is shown in the status output is **NOT** this value if rules, salts, etc. are present in that specific session. You will NOT be able to restore based on the "Progress" value due to this difference. ONLY the restore point value can be used to skip into the attack and return to where hashcat last got work. `--skip` already gives the user the ability to specify how far into the attack they would like to start, but this value MUST be based on the bases, the "Restore Point" value. If you try to use the value for "Progress" for this, it won't work properly.

**Comment by pbies** [comment]
I am sorry, but I do not understand what you are writing. Choosing percent at which to start cracking should be a part of hashcat. If you don't like the idea just please stay out of my feature request. I am not here to discuss with you your personal view on the needed function (if to make such a function), but how.

**Comment by roycewilliams** [comment]
I agree with chick3nman here, and also think that it's inappropriate to tell him to stay out of the discussion, considering he is an official developer of this project (and would be one of the people who might actually be able to implement what you're asking for, if it was worth the trade off!) You are "biting the hand that feeds you".

While I understand that it would be useful to not have to do the calculation - and I say that sincerely, as someone who often advocates for better user experience here - doing the calculation with a script or wrapper and then passing that to hashcat is trivial, and would be the recommended approach. 

That being said, if enough of the user base feels strongly that this functionality should be in hashcat itself, a good pull request could be considered. But because the workaround is trivial, and developer attention is limited, and the number of users who need this is likely limited ... simplicity is favored over complexity, and this is therefore less likely to be accepted into hashcat itself.

**Comment by roycewilliams** [comment]
So to restate what it sounds like the ask is:

If I'm looking at my status output and I see that I have 38% progress when hashcat died or whatever, then if I could just tell it to resume at 37% progress, then you don't miss anything and it would be significantly easier than calculating skip and limit.

Yes, it would be dependent on the attack type, but you could code for each attack type to match what the user would do to do the equivalent, at least in some cases.

So imagine you could have a flag that did this and then if it was an unsupported attack type, it would simply tell you that and exit. But if it was a supported attack type, it could do the rough math necessary, and maybe round down slightly to ensure that no key space was missed.

I defer to the core developers about whether this would be worth the effort vs the existing method and the potential confusion or user impact it might produce.

For example, given this output:

```
Restore.Point....: 2880000/511615591 (0.56%)
```
... the precise (and no-loss way) to resume is with 

```--skip 2880000```

... because this works exactly right _regardless of whether the percentage was rounded up or down_.  Supplying the literal percentage shown in the status output may be inaccurate. It would also be very expected that users would try to use the 'Progress' percentage instead, which would result in even more loss of keyspace (and potential false negatives).

**Comment by roycewilliams** [comment]
Discussion on this looks like it's unlikely to be implemented - closing.
