### ISSUE TITLE
nintendos(?) sarc hash support

### ISSUE THREAD

**Issue by steventylerseanherr** [hashcat/hashcat#3388]
**Is your request based on a publicly known cryptographic schema and where can we find information about?**

while i dont think this is technically a "publicly known cryptographic schema"
and i dont know if nintendos the one that actually created it
info into the hashing system (and fileformat) can be found here: https://mk8.tockdom.com/wiki/SARC_(File_Format)#File_Name_Hash
at the file name hash section

**Describe alternatives you've considered**

the only one alternative solution ive found is switch toolbox:https://github.com/KillzXGaming/Switch-Toolbox
it has a hash calculator and bruteforcer but its ever limited in what it can do sadly
another option is a script ive made myself which offers a lot more specifics
but im by no means a decent coder (please dont make me show my if statements lol)

**Provide an example hash/database/file and a known correct password**

all official uses of this hash has used a key of 101
though the key could be anything really

string				hash
a				97
b				98
c				99
...
aa				9894
ab				9895
ac				9896
...
test				120556948
World/Actor/AppleRed.bch	179838759

**Explain how the cryptographic schema is implemented**

hash = character + hash * key;
(repeat for each character in the string)

**Describe the known limitations of the algorithm**

im not sure but theoretically theres a soft limit to the length of the string

 
**Where do you typically find the algorithm**

nintendos sarc archive format

**Additional context**
nothing to add except im sorry if i didnt fill this out correctly lol

**Comment by jhwgh1968** [comment]
Hi @steventylerseanherr,

I'm not a member of the dev team, but an active user of this tool. I wanted to jump in and suggest why your issue has remained quiet, and offer alternatives.

Hashcat is a tool designed to work on *cryptographic* hashes. This is what is implied by the term "cryptographic schema" at the top of the issue you filled out.

These algorithms have been widely studied by cryptographers around the world, and anyone who attempted to crack them or reverse them thew up their hands. That is why they can be trusted with great secrets.

The hash algorithm you describe is not in this class.

SARC's hashing algorithm is a common style of *non-cryptographic* hash. It has certain mathematical properties designed for making hash tables fast, but it is designed for speed. It is not designed for secrecy.

Because of this, there are several basic techniques that can allow an analysis much faster that brute force. I will highlight two approaches if you are interested, in the hopes it will get you thinking.

<details>
First, there is differential cryptanalysis. Doing a simple version, I generated random strings that were 16 characters long, and binned them based on the bottom 8 bits of their checksum value.

I let it run for a couple minutes, and then sorted by frequency. This is the table I got:

```text
n = 52,000,000
=========
211 => 204372
72  => 204279
88  => 204191
111 => 204178
158 => 204138
81  => 204137
10  => 204088
227 => 204051
[...]
189 => 202306
6   => 202300
67  => 202287
212 => 202236
137 => 201884
205 => 201825
90  => 201720
239 => 201573
```

The difference between the top and bottom row is 1.3%. Or in other words, there is a systematic bias *toward* 211, and *away* from 239, which is on the order of 1%. And that's a very cursory analysis.

If you did the same analysis with a larger number of bins, you could find patterns for a given string length that caused them to go in there (based on the fact that carries "cancel out" in the successive multiplications). From there, you can eliminate many thousands of guesses for a given string based on which bin it falls into, and try your "best guesses" first.



The second technique is to use a pre-image attack.

Consider what happens if you make a specific one-bit flip in our input, and apply it to two completely different messages:

```text
h('World/Actor/AppleRed.bch') = 0179838759
h('World/Actor/AqpleRed.bch') = 1810313440
                ^
1810313440 - 0179838759 = 1630474681

h('orld/Actor/AppleRed.whut') = 1636591455
h('orld/Actor/ApqleRed.whut') = 3267066136
                ^
3267066136 - 1636591455 = 1630474681
```

In other words, one bit change in the input of a certain length causes a *predictable* change in the output *no matter what the input string is*.

This lets you build a table, start with a known value, and then apply these "patterns" to see "how far apart" the unknown value might be. It is also likely that this will extend all the way to a factor analysis (since the core is multiplication), but I haven't dug that far.


Cryptographic hash algorithms are not only immune to both of these techniques among others, they are specifically designed to resist them. That is why Hashcat uses brute force, and you do not need to.
</details>

I say this to make an earnest suggestion: you or someone in the home-brew community should instead focus on improving that Switch toolbox tool. There are approaches to optimize its search by several orders of magnitude compared to the brute force calculation Hashcat would do:

1. Build a statistical table to based on [differential cryptanalysis](https://en.wikipedia.org/wiki/Differential_cryptanalysis).
2. Use a known dictionary to eliminate possibilities through a [pre-image attack](https://en.wikipedia.org/wiki/Preimage_attack).
3. It is also likely possible to optimize things even more through either "de-concatenating" strings or finding deeper patterns based on the [Chinese remainder theorem](https://en.wikipedia.org/wiki/Chinese_remainder_theorem).

I hope this inspires you, and wish you luck.

**Comment by steventylerseanherr** [comment]
hi!
ngl i figured a hash was a hash lol

and since making this i have learned a bit of lua
that coupled with a rather long list of strings that was made from the games code
i was able to build a simple bruteforcer that served me well for a bit
killz (the guy that made switch toolbox) even got in on it and made a tool to guess the hash via strings inside the files (eg a models internal name might be the same as its hash name)
and that helped tons with the tedium
the rest i used my lua bruteforcer and general guessing to solve
i got the majority of them for the games assets (1587 hashes about)
and im working on the localization files now

thanks for the response and im honestly interested in what you posted
