### ISSUE TITLE
Add any algo+algo

### ISSUE THREAD

**Issue by mobola1edu** [hashcat/hashcat#3401]
it would be nice to be able to combine several algorithms at once
example:
I want md5(sha256($pass))
Or sha512(sha1($pass))
Or ntlm(md5(sha1($pass)))
But no such method

solution:
hashcat -m1 0 -m2 1400 hash wordlist.txt
hashcat -m1 1700 -m2 100 hash wordlist.txt
hashcat -m1 1000 -m2 0 -m3 100 hash wordlist.txt

It will not be necessary to develop algo(algo($pass)), this solution is enough in the form -m1 -m2 -m3...

**Comment by philsmd** [comment]
The problem here (and we already discussed something like this already several times in forum and on `github`) is that it's not easy to optimize this (if possible at all) and therefore we prefer to have dedicated hash-modes for some (the most requested in general, but also some other interesting and not that important) combinations of algorithms.
Please have a look at the `--help`  output or `--hash-info` output to see a list of combined algorithms. We already have support for many of them.

I understand that this method would be much more flexible for the user, but speed also matters (sometimes at least ;) ).

Thanks
