### ISSUE TITLE
"Recovered.New" not shown when only one hash is cracked

### ISSUE THREAD

**Issue by sadreck** [hashcat/hashcat#3419]
**Describe the bug**
When running a session `Recovered.New` is only displayed when the number of cracked hashes during that run is more than 1 (so 2 and above) instead one and above.

**To Reproduce**
Create any session but make sure only one hash is ever cracked, `Recovered.New` will never appear.

**Expected behavior**
`Recovered.New` should be displayed even when 1 hash is cracked.

**Hashcat version (please complete the following information):**
 - OS: Linux
 - Distribution: Ubuntu 20.04
 - Version: v6.2.5-384-g2e148a216

**Comment by Chick3nman** [comment]
My guess is that you only have 1 salt in your list(same value for no salts for unsalted algorithms) and the check here: https://github.com/hashcat/hashcat/blob/master/src/terminal.c#L2340 needs to be updated to >=. Can you confirm?

**Comment by sadreck** [comment]
I believe so, yes, it's NTLM hashes I'm working with at the moment.

But if it was due to the salt wouldn't that be caught here? https://github.com/hashcat/hashcat/blob/05eff0d683dc9eef547ad14d01d8580a9b2a1dde/src/terminal.c#L2378

**Comment by jsteube** [comment]
According to the code what can happen is if there was no entry in a potfile (or no potfile at all) which matched any of the entries in the hashlist which is currently running. In this case there is no Recovered.New...: status entry. 

This behavior could be easily misinterpreted since one would assume to have a counter listed under Recovered.New.... if there's a new crack shown by hashcat. So note exact wording here. There could be a potfile with entries, but none of them matched. This is relevant.

I'm going to patch this by adding the entry even if this is just redundant information, however it should eliminate the confusion discussed above.

**Comment by jsteube** [comment]
https://github.com/hashcat/hashcat/commit/8668694daf6020dfc245bf07316818aac36cce78
