### ISSUE TITLE
double setting of --status option

### ISSUE THREAD

**Issue by UnrelatedWorks** [hashcat/hashcat#3450]
**GitHub is for bugs and features - not for support**
For support, please use the hashcat forums https://hashcat.net/forum/

**Check the FAQ**
Some items that might appear to be issues are not issues. Please review the hashcat FAQ https://hashcat.net/wiki/doku.php?id=frequently_asked_questions before submitting a bug report.

**Describe the bug**
when setting the --status-timer=x option the --status also has to  be set 

**To Reproduce**
does not display status:
hashcat --status-timer=30 -a 3 -m 0 example0.hash ?a?a?a?a?a?a 
does display status:
hashcat --status --status-timer=30 -a 3 -m 0 example0.hash ?a?a?a?a?a?a 

**Expected behavior**
hashcat --status-timer=30 -a 3 -m 0 example0.hash ?a?a?a?a?a?a 
should display updated status after 30 seconds. If the user explicitly wants an output after x seconds it does not make sense to also require that a status is needed at all. 

**Hardware/Compute device (please complete the following information):**
Not important, on any hardware 

**Hashcat version (please complete the following information):**
Not important, any version

**Comment by roycewilliams** [comment]
Looks like this should be added to the command-line sanity checking, so that hashcat quits early and explains that `--status-timer` requires `--status`.

**Comment by Chick3nman** [comment]
The problem is that --status-timer doesn't set the value for --status. I can sorta see both sides to it, if you've set a status-timer value, you have implied that you want --status on. The question is if that is enough reason to set --status or if we still want explicit direction from the user. Is there ever a time when the timer would be set but --status would not? If not, I'm comfortable changing the logic to flip both if the timer value is changed.

**Comment by UnrelatedWorks** [comment]
Before posting the issue I also went through a couple scenarios where a user might not want to see the status but still set a time for it. 

The only way this makes sense if we add a --pipe-temp, --pipe-progress ... option that feeds out the information. I use hashcat in headless environments where I cannot interact so the timer is essential to check for progress, temps etc. I don't mind "sifting" through the whole status screen but for some they might want to get their values "cleaner". Then it would make sense to keep --status-timer and --status in place. 

I don't see a sanity check like @roycewilliams pointed out working in the long term. It will just frustrate new users when defining their options.

**Comment by Chick3nman** [comment]
We have other status output formats, --machine-readable and --status-json, both good for parsing. But I agree, there's no real time when --status-timer is set that we don't want --status set. I'll PR that change later and we can see if it fixes your issue.

**Comment by Chick3nman** [comment]
Following the short conversation in the above PR that was closed, perhaps not. @roycewilliams what do you think?

**Comment by roycewilliams** [comment]
I'm okay with feedback as the only remedy, but I can see the argument for automatically setting it when the timer is requested. I could go either way, but if we do go the automatic setting direction, I feel that we would need to do that for a number of other flags at the same time, rather than be inconsistent.

**Comment by Chick3nman** [comment]
Yeah, the consistency was my concern. We expect explicit directives in most cases, firing a blocking warning during sanity checking is what we do elsewhere. It's also more in line with many of our other options, setting some modifier flag doesn't switch the enable/disable flag. Seems like we may need to just add this to https://github.com/hashcat/hashcat/issues/3254 and continue with a command line sanity check overhaul of sorts.

**Comment by UnrelatedWorks** [comment]
The problems mentioned in #3254 are different. Users don't know what each option does intuitively and they contradict each other at times. 
I suggest we implement it directly. Users will see the error screen so often (wrong hash, wrong driver, wrong attack mode) we don't need to add another step. Plus it makes the final command look neater. 
What other options are you referring to? Since when defining the location for the outfile it automatically creates it. 
I sadly don't have the time atm to create a RP, but I hope you can implement an auto flag set.

**Comment by Chick3nman** [comment]
-o for outfile is a bit of a special case because that _is_ the enable flag, it just happens to take an arg as well. That falls more in line with `--generate-rules` which also takes a argument. Those options _can't_ be started without the argument so it makes sense that the enable flag requires it. The status output, however, can be turned on without any modification, which makes it a different case. More comparable flags would be things like `--remove` and `--remove-timer` or `--increment`, `--increment-min`, and `--increment-max`. There's a flag for switching the behavior to "on" and then flags that modify the behavior from the default values. While it may "look" better, it's not as explicit and would be inconsistent with the aforementioned flag behavior. Also, a user seeing the error screen often is not necessarily a bad thing. We add those catches and errors and warnings to help direct users towards writing out explicit commands. In https://github.com/hashcat/hashcat/issues/3254 I was simply pointing out that we are currently not doing enough command sanity checking, the examples there are not the only ones in scope for the issue. This issue would fall in scope since the fix should probably be adding it to the sanity checks, at least initially while we decide whether or not we like the change in behavior.

**Comment by UnrelatedWorks** [comment]
created a PR #3454 with sanity check. But this is just a hot fix for all the "wrong" option mixes that can be set.
