### ISSUE TITLE
hash_filename computation

### ISSUE THREAD

**Issue by davidbolvansky** [hashcat/hashcat#3465]
I would like to understand more how hashcat computes hash_filename as I would like to (auto)generate dictstat2 file.

I found relevant lines in souce code: https://github.com/hashcat/hashcat/blob/master/src/wordlist.c#L480

Consider the dictionary with name "example.dict". Run attack with this dictionary.

Hashcat produces dicstat2 file ending with these bytes:
![image](https://user-images.githubusercontent.com/22410393/191119193-e648a545-be38-48bd-a206-eef9d66748a0.png)

But why such data? I would expect truncated value of sha1("example.dict) - 055aa29b6fbaf1b2810232bd2be4434a6971edb4

Something like:
![image](https://user-images.githubusercontent.com/22410393/191119707-a911a99d-25d7-4e98-9129-1ab2e8792f87.png)

**Comment by davidbolvansky** [comment]
Any tips, @jsteube ?

**Comment by jsteube** [comment]
The goal is to avoid re-reading the full file content since this can take a lot of time. As an alternative it compares only the meta data related to that file. This is not 100% accurate, but good enough for us. Some filesystems create problems, especially network shares, but we recommend to the user to not store any wordlists on network shares.

**Comment by davidbolvansky** [comment]
Yes, I understand the concept but my question is more related to technical side of this feature. 
Motivation: In distributed password cracking system we would like to create such dictstat2 file for hashcat to speed things up.

I was (almost) able to create this file manually (saving relevant structure to file) but I have a problem with the field hash_filename. I see that hashfile is computed as first 16 bytes of sha1 hash of dictionary filename. But the value computed by hashcat is different than the one computed by my little small tool.

So for "example.dict" (*) I would expect "055aa29b6fbaf1b2810232bd2be4434a" but hashcat computes a different sha1 hash and then hashcat uses first 16 bytes - "f180ccd6ae5fbaea0b6e6a7e11ab37f9" - as a computed hash_filename. So something is wrong and I cannot produce same hash_filename as hashcat.

* sha1 hash for "example.dict" is 055aa29b6fbaf1b2810232bd2be4434a6971edb4

**Comment by jsteube** [comment]
Oh, sorry! Now I understand what you meant. I've just misread your post. Basically we're just not swapping the input buffer according to SHA1 specs - because internally it's not needed since we're the only consumer of this data. However, I can see how it makes things hard to read this file from external tools, so I'll change the code in hashcat.

**Comment by davidbolvansky** [comment]
@jsteube Amazing! Thank you so much!
