### ISSUE TITLE
QNX 7 Sha512 

### ISSUE THREAD

**Issue by raulperdomo** [hashcat/hashcat#3470]
Hi, @raulperdomo - can you provide a reference hash (known plaintext "password" or "hashcat" or whatever) to check against?

_Originally posted by @roycewilliams in https://github.com/hashcat/hashcat/issues/35#issuecomment-1167861682_
      

-------

@roycewilliams Sorry about the delay. I was finally able to get a working development environment to create a hash. Here is the relevant line from the shadow file. The password is 'password'. (no quotes).

root:@S@3Ug2rfx/+py7iE9BZQv2zHlrOF+AX1ixsRrjopRKMsyYOoliq6ErfpaQvgj59Fa29SL+6eo1vmXimgddoPgr/A==@ZDQxMzJmN2M0OTg1YTMyMGYzNDk1NzRhZjFiMmRhNzc=:1577844502:0:0:0:0:0:0

It seems to me that what ever misimplemetation of sha512 existed in QNX 6 has been resolved in QNX 7. Now I believe a new module needs to be created to handle QNX 7 password hashes. I have attached a sample hash generated on a QNX7 development system with a known password to help this task along.

**Comment by jsteube** [comment]
According to this official document https://www.qnx.com/developers/docs/7.0.0/index.html#com.qnx.doc.neutrino.user_guide/topic/accounts_etc_shadow.html the iteration count is now 4096 (was 1000 before). 

However, they also state that "s" hashes (with the lower case "s") are sha256 hashes. Therefore, your example hash should be SHA256 and not SHA512. But then there's the length of your hash and if you base64 decode the hash portion it ends up in 64 byte, which matches only to SHA512.

Anyway I was not able to get a match for @s@3Ug2rfx/+py7iE9BZQv2z... I removed the way how the bug is handled and then tried to brute force 1..100000 iterations. Unless we have access to sources we can't do anything.

**Comment by raulperdomo** [comment]
I don't know what happened to that hash. When I posted it in the other thread it has a capital S. Maybe it is because I didn't use a code block here. Would it help for me to repost it again to see if there is a match? Or you could try the one I posted on this thread. 
https://github.com/hashcat/hashcat/issues/35#issuecomment-1167861682

**Comment by jsteube** [comment]
OK, thanks for the update. The main problem still exist that it seems the algorithm changed more than just the salt length, the encoding and the iteration count. The hash doesn't crack to 'password'. We need more information, but I don't know where to get it from.

**Comment by roycewilliams** [comment]
Was this addressed by #3875 ?

**Comment by jsteube** [comment]
Yes, it's implemented into -m 19210
