### ISSUE TITLE
Ability to specify length of the desired hash to match

### ISSUE THREAD

**Issue by mar232320** [hashcat/hashcat#3483]
Hello,

I thought that it would be nice to have this feature in hashcat:

You could specify a length (in bytes) of the part of the hash to match with your input

For example you give the following MD5 hash as input:
8743b52063cd84097a65d1633f5c74f5 (**hashcat**)

However, instead of cracking the full hash, hashcat print the result after first n chars match. (n <= digest length)
**hashcat -a 3 -m 0 --part 10 8743b52063cd84097a65d1633f5c74f5** would accept everything that, when hashed begins with 8743b52063cd84097a65 (first 10 chars of the digest)

This feature would help a lot in finding partial 'collisions' - the chosen prefix or suffix.

**Comment by jsteube** [comment]
Not sure if a global option makes sense. For example, what would be the use of cracking 7zip or VeraCrypt with a wrong password? As a result, it appears that only a limited number of hash modes would benefit from it. For these hash-modes it is better to slightly modify the existing hashcat kernel to support the requested function, also because it is advantageous for performance reasons.
