### ISSUE TITLE
Feature request:Bitcoin HEX private key

### ISSUE THREAD

**Issue by Cr1merrr** [hashcat/hashcat#3487]
Hashcat has mode 28501 ( Bitcoin WIF private key (P2PKH), compressed ). Works great, great speed! But the problem is that my private key is in HEX format  with missing characters, so i can't use 28501 mode and i can't convert my Hex private key with missing characters to WIF format to use it with mode 28501.
For example - 28501 mode:
1PNsAQsneakL4CJyhDMoX7goq76MvXzAGm:L1ULo4htHVh1Vanw6YTNGWpjZrnXjTC5T1mJZFNozRZkzZEU2M6B
New Hash mode:
1PNsAQsneakL4CJyhDMoX7goq76MvXzAGm:7ee05e336a5303dee1df768c2520a46de16f4830eef4648447c3654c403d6f61

Thanks!

**Comment by philsmd** [comment]
This is an interesting request, but I also see some drawbacks here.

The base58 encoding (of the other/supported variant) actually allows us to do some quick checks (early rejects, early exits, ignore wrong checksums) very quickly. I think to support this we would need to skip all these early rejects and basically test every combination (because all hex combinations are now allowed). This isn't impossible to implement (actually the OpenCL/CUDA/GPU kernel  would get rid of quite a bit of code and branches, but it might at least feel/look slower for the user and we could need to have a variant/"almost-copy" for each and every bitcoin address type (P2PKH, P2WPKH, P2SH(P2WPKH)) and attack mode (-a x, i.e. -a 0, -a 1, -a 3).
Again, not impossible, but still a lot of work.

Is there any particular software/bitcoin-client that uses these type of format instead of base58/WIF ? Where are these hex keys stored ?

**Comment by philsmd** [comment]
any updates here ?

I think, according to my little research I just did now, that you can export "raw bitcoin private keys" (that are in hexadecimal format) with some client/wallet software. So maybe this is kind of a valid request.

Any updates or any other interested person here for this request ?

**Comment by Cr1merrr** [comment]
Hey, @philsmd ! Sorry for not getting back to you sooner!

Yes, there are many wallets that accept raw/hex private keys, for example armory wallet, bitaddress.org

I think this implementation is "must have" for a hashcat. For example - if we lost the last 11 characters raw/hex private key, it's very fast can be recovered even on a weak gpu, but almost impossible to recover in WIF format, because in WIF format the same 11 hex characters turns into 15 characters , because of checksum.

So i'm still very interesed!

**Comment by Cr1merrr** [comment]
Let's say our private key is:

18b2f96f2073f52019fbd3a11a1b1aa23e6897dbe64f852edb9c34e5995f554d

We lost the last 11 symbols for a some reason, so now our private key looks like this - 18b2f96f2073f52019fbd3a11a1b1aa23e6897dbe64f852edb9c3...........

So the range for brute force starts:
from 18b2f96f2073f52019fbd3a11a1b1aa23e6897dbe64f852edb9c300000000000
end's 18b2f96f2073f52019fbd3a11a1b1aa23e6897dbe64f852edb9c3fffffffffff

Hex charset is - 0123456789abcdef

In theory we can convert our damaged hex private key to WIF format and start bruteforce in WIF, but our range for searching will be huge!

Let's convert our HEX/RAW range to WIF:

18b2f96f2073f52019fbd3a11a1b1aa23e6897dbe64f852edb9c300000000000
Kx3isYwr7KVWSxqGa6vvi66qsA9wMx1ArGUa6**uFnxSETHmdszGtm**
18b2f96f2073f52019fbd3a11a1b1aa23e6897dbe64f852edb9c3fffffffffff
Kx3isYwr7KVWSxqGa6vvi66qsA9wMx1ArGUa6**yDuxXfZuyQcxT46**

WIF format start range Kx3isYwr7KVWSxqGa6vvi66qsA9wMx1ArGUa6(**uFnxSETHmdszGtm**), end range Kx3isYwr7KVWSxqGa6vvi66qsA9wMx1ArGUa6(**yDuxXfZuyQcxT46**), it's a 15 characters.

Bitcoin base58 charset - 123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz

As you can see, in WIF format our mission will be impossible

**Comment by philsmd** [comment]
Hey @Cr1merrr 

I have good news for you today.

I've spent some time to implement all these new host and kernel changes, see #3561 .

There were (as expected) of course a lot of files to change and most importantly add (6 new hash modes, of which 4 * 3 - for -a 0/a1/a3 - new optimized OpenCL/CUDA kernels - note that the other 2 * 3 are just different address encoding (Bech32) -, host code x6, tests x6). Was of course a lot of work.

The speed of course (as expected) is not comparable with the WIF formats, because the base58check (checksum) testing for -m 28501 to -m 28506 of course rejects a lot of "wrong" password candidates very quickly/easily/immediately.

The new code and speed looks good to me with this first test.

possible optimizations: try to move some `is_valid_hex ()` and hex decoding (`hex_to_u32 ()` / hex_to_u8 ()`) into outer code (avoid doing it in the main loop), for every *byte* we already know (e.g. everything except w[0] for -a 3, or known/fixed part for -a 0/-a 1). Could be easy optimization, but maybe the speed change is not that significant.
something like:
```diff
diff --git a/OpenCL/m30901_a3-pure.cl b/OpenCL/m30901_a3-pure.cl
index 6df675272..32a773fb4 100644
--- a/OpenCL/m30901_a3-pure.cl
+++ b/OpenCL/m30901_a3-pure.cl
@@ -125,6 +125,13 @@ KERNEL_FQ void m30901_mxx (KERN_ATTR_VECTOR ())
    * loop
    */
 
+  u32 t2[8] = { 0 };
+
+  for (u32 i = 1, j = 2; i < 8; i += 1, j += 2)
+  {
+    t2[i] = hex_u32_to_u32 (w[j + 0], w[j + 1]);
+  }
+
   u32 w0l = w[0];
 
   for (u32 il_pos = 0; il_pos < IL_CNT; il_pos += VECT_SIZE)
@@ -142,10 +149,15 @@ KERNEL_FQ void m30901_mxx (KERN_ATTR_VECTOR ())
 
     u32 tmp[16] = { 0 };
 
-    for (u32 i = 0, j = 0; i < 8; i += 1, j += 2)
-    {
-      tmp[i] = hex_u32_to_u32 (w[j + 0], w[j + 1]);
-    }
+    tmp[0] = hex_u32_to_u32 (w[0], w[1]);
+
+    tmp[1] = t2[1];
+    tmp[2] = t2[2];
+    tmp[3] = t2[3];
+    tmp[4] = t2[4];
+    tmp[5] = t2[5];
+    tmp[6] = t2[6];
+    tmp[7] = t2[7];
 
     u32 prv_key[9];
 
@@ -272,6 +284,13 @@ KERNEL_FQ void m30901_sxx (KERN_ATTR_VECTOR ())
    * loop
    */
 
+  u32 t2[8] = { 0 };
+
+  for (u32 i = 1, j = 2; i < 8; i += 1, j += 2)
+  {
+    t2[i] = hex_u32_to_u32 (w[j + 0], w[j + 1]);
+  }
+
   u32 w0l = w[0];
 
   for (u32 il_pos = 0; il_pos < IL_CNT; il_pos += VECT_SIZE)
@@ -289,10 +308,15 @@ KERNEL_FQ void m30901_sxx (KERN_ATTR_VECTOR ())
 
     u32 tmp[16] = { 0 };
 
-    for (u32 i = 0, j = 0; i < 8; i += 1, j += 2)
-    {
-      tmp[i] = hex_u32_to_u32 (w[j + 0], w[j + 1]);
-    }
+    tmp[0] = hex_u32_to_u32 (w[0], w[1]);
+
+    tmp[1] = t2[1];
+    tmp[2] = t2[2];
+    tmp[3] = t2[3];
+    tmp[4] = t2[4];
+    tmp[5] = t2[5];
+    tmp[6] = t2[6];
+    tmp[7] = t2[7];
 
     u32 prv_key[9];
 
```
For me this isn't really faster (neighter on CPU, nor on GPU), probably also due to the extra buffer `t2[]` and extra copying.

A whole different **approach**/**alternative**: we could think to only allow full byte inputs (0x00-0xff). Problem: the user couldn't try just some unknown nibbles (4 bits) only: 0x0-0xf. In general, this approach could be a bit faster because we would avoid the `is_valid_hex ()` checks and hex decoding. We would have larger charsets 0x00-0xff, but less flexibility. This way, instead of `?h` charsets, we would work with `?b` charsets.

I think this implementation is still wanted by most of the users (even though the full-byte-level cracking could be slightly better, performance-wise and easier to optimize).

What do you think ? I hope you are able to test it with `git` or whenever the pull request #3561 is merged, a new beta will be available under https://hashcat.net/beta probably soon.

Thanks

**Comment by Cr1merrr** [comment]
Hey, @philsmd !

Wow, that's awesome, amazing job!

I did a quick test and seems that everything works smoothly!

But what about speed, should it be low like this? My GPU - GeForce GTX 1660 Super

 Benchmark relevant options:

===========================
* --optimized-kernel-enable

-----------------------------------------------------------------
* Hash-Mode 30902 (Bitcoin raw private key (P2PKH), uncompressed)
-----------------------------------------------------------------

Speed.#1.........:   897.6 kH/s (291.07ms) @ Accel:128 Loops:16 Thr:256 Vec:1

Started: Wed Jan  4 17:16:12 2023
Stopped: Wed Jan  4 17:16:17 2023




 Benchmark relevant options:

===========================
* --optimized-kernel-enable

---------------------------------------------------------------
* Hash-Mode 30901 (Bitcoin raw private key (P2PKH), compressed)
---------------------------------------------------------------

Speed.#1.........:   405.0 kH/s (80.27ms) @ Accel:1024 Loops:16 Thr:32 Vec:1

Started: Wed Jan  4 17:12:33 2023
Stopped: Wed Jan  4 17:12:38 2023



Thanks!

**Comment by philsmd** [comment]
Yeah, the speed seems to be good... of course you can't compare it with 2850x, because for this hash mode we need to test **each and every** password candidate and do the ECC secp256k1 elliptic curve multiplication on basically every pass, while for 28501-28506 we had **a lot** of rejected passwords due to the `base58check` validation (this 4-byte checksum did remove a lot of candidates which is not possible here with the raw key).

Also note, we started some discussion about speed also here: https://github.com/hashcat/hashcat/pull/3561#issuecomment-1377073885 , I've also added my test with binary input (to get rid of hex conversation), but the speed didn't change significantly as already expected (because the curve multiplication is the most heavy part and it is already very, very fast, because everything works on GPU !).

btw: you could also play around a little bit with the `-T`, `-u`, `-n` (as discussed also on the pull request posts) tuning options (by enabling `--force`), but I don't think it will change speed a lot (autotuning should work quite well, I hope).

--- 

**update**: we added another tuning option as default, see: https://github.com/hashcat/hashcat/commit/d19882ff71ad14cb2c252b47b1329bb39ad65fdd and https://github.com/hashcat/hashcat/pull/3576 (please test with newest git code when merged)

**Comment by Julienbxl** [comment]
I made a tool to recover partial HEX BTC/ETH adress : https://github.com/Julienbxl/Hydra

Around 1200Mkeys/s in BTC mode with a RTX 5060

Missing nibbles don't need to be consecutive
