### ISSUE TITLE
-aes-256-cbc

### ISSUE THREAD

**Issue by kost123** [hashcat/hashcat#349]
Is it possible to add that algo with an extra command option to input the known contents?

**Comment by epixoip** [comment]
That's a cipher, not a hash, and you aren't going to crack a 256 bit AES key.

**Comment by kost123** [comment]
I have a CPU program that does just that.

Wordlist attack ofcourse but still.

**Comment by epixoip** [comment]
Ok but this is hashcat, not ciphercat

**Comment by kost123** [comment]
Hashcat already decrypts AES-256-cbc in a few algos, blockchain for instance.

**Comment by epixoip** [comment]
Hashcat targets the use of a password-based key derivation function in that algorithm, not AES itself.

**Comment by jsteube** [comment]
This is not like DES or RC4 ciphers of which a complete search through the entire keyspace would be possible. Therefore there's no sense in this request. People don't use Passwords in combination with AES directly, there's always a KDF in between. KDF's are supported with hashcat.

**Comment by kost123** [comment]
I don't understand but I guess that is just my limited knowledge xD

Like.. this decrypts my aes encryption..

openssl enc -d -aes-256-cbc -in hash.txt -a -k password

So if that can do it? hashcat can't? that is a directly encrypted password(cipher whatever) with aes no?

**Comment by Amblypygid** [comment]
The key difference here is that you are telling openssl to decrypt your AES ciphertext. You are giving it a key with the password variable. This is a simple process.

You are requesting of Hashcat that it _break_ the AES cipher or guess the password. I can't tell which it is you want, but neither is possible.

As for breaking AES, the best cryptographers in the world have been trying since it was invented. It has been 20 years and it is still unbroken. With some knowledge of what you're attacking, password searches can be sped up about a factor of 4, but that's the best you can hope for.

As far as guessing the password, with a 256-bit key there are literally 2^256 possibilities, which is over 10^77. All the GPUs in the world won't guess it in ten billion years, and that is a generous estimate.

If you have good knowledge of the plaintext, good knowledge about the way the password was chosen, and are the NSA, then you have some hope.

All that aside, I hope you have solved the problem with that file.

**Comment by kost123** [comment]
This is over a year old but yea.. I know this stuff by now :)
