### ISSUE TITLE
Duplicate rule appears to be broken

### ISSUE THREAD

**Issue by fse-a** [hashcat/hashcat#3537]
**Describe the bug**
The duplicate rule appears to be broken in the 6.2.6 version.

**To Reproduce**
 - ./hashcat  --stdout  -m 99999 -a 0 mini-wordlist.txt -r duplicate.txt

**Expected behavior**
Input from mini-wordlist:
Aap
Noot
Mies

Expected Duplication:
AapAap
NootNoot
MiesMies

Actual Output:
AapA
NootOoow
MiesMies

**Hashcat version (please complete the following information):**
Tested on the release and on the current master (15 december 2022)

**Additional context**
[duplicate.txt](https://github.com/hashcat/hashcat/files/10238427/duplicate.txt)
[mini-wordlist.txt](https://github.com/hashcat/hashcat/files/10238446/mini-wordlist.txt)

Also tested previous versions but it appears to be broken from the 6.2.6 version.

**Comment by Chick3nman** [comment]
Confirmed, there is something impacting the rule processing in Release 6.2.6, thought the behavior is not consistent with how your output shows, but it's definitely the same issue. Investigating.

**Comment by Chick3nman** [comment]
After some quick testing it doesn't look like this is the fault of the rule processor(s). This appears to be an issue with --stdout specifically, the rules are processed correctly during normal attacks from when using -j/-k, -r, and -r w/ -O. However, when using --stdout to collect the outputs, -j/-k work properly, but -r rules produce a mangled output.

**Comment by Chick3nman** [comment]
I have thoroughly debugged this issue and it appears to be due to a loop in `stdout.c` that reuses a buffer which is being overwritten when the loop executes the `apply_rules` function and processes the candidates on the computing device. Seems like it's incorrectly appending all of the remaining block(s) of candidate data to the buffer after the first execution instead of iterating through the candidate blocks correctly.

This bug was introduced here: https://github.com/hashcat/hashcat/commit/edf7365cdabd0c9b0ee4d9c29cc56c78d11720ab

I worry that a quick fix may not be the best option given the code changes in that commit are performance related and I'd like to get input from @willcrozi before patching it.

Further, it appears that `test_rules.pl` failed to catch this bug due to there only being 1 test password in the test case and this bug requires there to be at least 2 passwords loaded. Thanks to @hops for spotting that issue, our test cases perhaps need some review for edge cases like this.

**Comment by willcrozi** [comment]
Apologies for the bug, I should have thought to test with rules! :grimacing: 

> I have thoroughly debugged this issue and it appears to be due to a loop in `stdout.c` that reuses a buffer which is being overwritten when the loop executes the `apply_rules` function and processes the candidates on the computing device. 

Agreed.

>Seems like it's incorrectly appending all of the remaining block(s) of candidate data to the buffer after the first execution instead of iterating through the candidate blocks correctly.

Yes, the code was copying 64 `u32`s (256 bytes) from the block regardless of the pwd length but despite this inefficiency the correct length was being passed to `apply_rules` and so I was expecting it to be fine. The root cause is a bit more subtle I think. It seems code within `apply_rules...()` relies on the src buffer (i.e. `plain_buf`) having a certain amount of trailing zeroes after the password data. This _was_ the case before my optimisation work when we retrieved each password with a separate device->host memcpy, but optimising those copies meant passwords were packed a la `pws_comp / pw_idx_t` style.

Perhaps this is related to `apply_rules...()` and code called within it being included from `.cl` files and somehow having different a memory model/context? (cc @jsteube?)

I have implemented what I think is the best way to fix: https://github.com/willcrozi/hashcat/commit/2f48ae842a7e17e8a40d265c8bbf135611d7be29

This commit eliminates the needless copying past the pwd length into the output buffer and memsets it to zero after pushing to stdout. Clearing the entire output buffer between pwds seems the safest way: I tried appending a single trailing `0` and it failed some way into testing against example.dict as input . With the reduced copying it ends up somewhat faster on my machine anyway. Possibly a win-win ?!

This commit also eliminates the unneeded copying for the other stdout attack modes that involve device->host copying but I didn't include the memset/zeroing for those other modes since AFAICT they don't call into the `.cl` strangeness like `apply_rules...()` does and so would likely be needless overhead. Maybe further testing required to be sure? 


Testing:

```
$ git log --oneline -n 1
2f48ae842 (HEAD -> bugfix-stdout-rules-#3537) stdout mode: zero output buffer between rules (fixes #3537)

$ ./hashcat --stdout -m 99999 -a 0 bug-#3537/mini-wordlist.txt -r bug-#3537/duplicate.txt
AapAap
NootNoot
MiesMies

$ while IFS='' read -r line; do echo "${line}${line}"; done < example.dict | md5sum
8647554c52ac0baa17148983479df0af  -

$ ./hashcat --stdout -m 99999 -a 0 example.dict -r bug-#3537/duplicate.txt | md5sum
8647554c52ac0baa17148983479df0af  -
```

Performance:

master (with bug):
```
$ git log --oneline -n 1
1154272d6 (HEAD -> master, origin/master, origin/HEAD) Normalize initial out_buf line in encoder in -m 30700

$ time for i in $(seq 1 100); do cat example.dict; done | ./hashcat --stdout > /dev/null

real	0m12.519s
user	0m11.412s
sys	0m2.743s

$ time for i in $(seq 1 100); do cat example.dict; done | ./hashcat --stdout > /dev/null

real	0m8.478s
user	0m7.824s
sys	0m2.326s

$ time for i in $(seq 1 100); do cat example.dict; done | ./hashcat --stdout > /dev/null

real	0m8.414s
user	0m7.706s
sys	0m2.502s

```

with fix:
```
$ git log --oneline -n 1
2f48ae842 (HEAD -> bugfix-stdout-rules-#3537, github/bugfix-stdout-rules-#3537) stdout mode: zero output buffer between rules (fixes #3537)

$ time for i in $(seq 1 100); do cat example.dict; done | ./hashcat --stdout > /dev/null

real	0m7.510s
user	0m7.119s
sys	0m2.326s

$ time for i in $(seq 1 100); do cat example.dict; done | ./hashcat --stdout > /dev/null

real	0m7.445s
user	0m7.087s
sys	0m2.321s

$ time for i in $(seq 1 100); do cat example.dict; done | ./hashcat --stdout > /dev/null

real	0m7.302s
user	0m6.964s
sys	0m2.382s
```

**Comment by Chick3nman** [comment]
> Perhaps this is related to `apply_rules...()` and code called within it being included from `.cl` files and somehow having different a memory model/context?

Is it perhaps the loop being unrolled and executed in parallel on the GPU when apply_rules is called? That was my first hunch but I'm not sure. When we do this step in attack kernels we create a temp buffer within the inner loop, which means if its executed in parallel, each execution has it's own unique temp buffer and they don't overwrite eachother.  But in this case the buffer is the same for all executions of the loop so it may be overwritten if executed this way.

**Comment by willcrozi** [comment]
> Is it perhaps the loop being unrolled and executed in parallel on the GPU when apply_rules is called? That was my first hunch but I'm not sure. 

I was thinking along similar lines but the code is definitely running on the CPU and not being dispatched in any kind of OpenCL context. `apply_rules` and associated rule processing code appears to be used from both device and host contexts and in this case  (stdout-mode) it's used on the host.

Investigating further it seems this is indeed a simple case of passing a buffer without trailing zeroes where they are required. In this particular case (duplication rule) `apply_rules` calls into `append_..._bytes` functions in `inc_rp.cl` which all assume trailing zeroes in order to merge appended bytes using bitwise OR operations.

https://github.com/hashcat/hashcat/blob/4c90d371ecb7f3c0962b0ba537510ab063a25181/OpenCL/inc_rp.cl#L61-L62

E.g. the incorrect appended bytes (`"Ooow"`) for the second line of the test case above are the result of ORing `"Noot"` with the first 4 bytes of the next password (`"Mies"`) instead of trailing zeroes:
```
(char[4]) (*(u32*){'N', 'o', 'o', 't'} | *(u32*){'M', 'i', 'e', 's'}) = {char [4]} 

 [0] = {char} 79 'O' [0x4f]
 [1] = {char} 111 'o' [0x6f]
 [2] = {char} 111 'o' [0x6f]
 [3] = {char} 119 'w' [0x77]
```

**Comment by Chick3nman** [comment]
I had also noticed the bitwise OR taking place causing the outputs and had assumed it was due to the buffer being overwritten during parallel execution of the loop.

> I was thinking along similar lines but the code is definitely running on the CPU and not being dispatched in any kind of OpenCL context. `apply_rules` and associated rule processing code appears to be used from both device and host contexts and in this case (stdout-mode) it's used on the host.

I don't think this is 100% true. We are definitely executing this on the computing device as far as I can tell, we invoke kernel 2000, which is an empty kernel, and use the included functions directly. You can see the difference in behavior by specifying different backend runtimes/devices. For example, currently my Intel Runtime is experiencing issues and crashes out before it can generate any candidates but using -D 2 -d 1 allows me to specify my CUDA GPU and get the expected behavior. This is what lead me down the loop-unrolling path. I do agree that the buffer lacking trailing zeros is probably the cause of this particular issue, not the unrolling, however.

**Comment by willcrozi** [comment]
My thinking is that normally (i.e. non-stdout mode) the rule-processing get run within an OpenCL/CUDA/HIP kernel but with stdout mode there is a shortcut  to execute the rule-processing directly on the host instead of dispatching a device kernel: https://github.com/hashcat/hashcat/blob/6bd5e6f03f5d6499b72fdf24aea7900e09047cb4/src/backend.c#L953-L956 I'm thinking this is to avoid pushing all of the expanded passwords across PCI-E.

In stdout mode I can set a breakpoint in my debugger and successfully break inside the innards of the rule processing, e.g. `append_block` within `inc_rp.cl'. I don't think I'd be able to do this if it was executing within a device kernel.

The stack trace looks like this:
```
[hashcat] append_block inc_rp.cl:143
[hashcat] mangle_dupeword inc_rp.cl:319
[hashcat] apply_rule inc_rp.cl:759
[hashcat] apply_rules inc_rp.cl:810
[hashcat] process_stdout stdout.c:224
[hashcat] choose_kernel backend.c:955
[hashcat] run_cracker backend.c:4081
[hashcat] calc dispatch.c:1558
[hashcat] thread_calc dispatch.c:1661
[libpthread.so.0] start_thread 0x00007ffff7f87609
[libc.so.6] clone 0x00007ffff7d57133
```
Which I'm certain is a standard hashcat 'dispatch' thread running on the host. 

Are you able to do `make DEBUG=1` and break into `append_block` as above when you are forcing a device with `-D 2 -d 1`?

**Comment by l3clelVl** [comment]
I'm still experiencing this issue. Is there a workaround? Below is how to replicate:

┌──(kali㉿kali)-[~/Desktop]
└─$ echo -e ":\nd" > duplicateword.rule
                                                                                                                                                                                                                                 
┌──(kali㉿kali)-[~/Desktop]
└─$ cat duplicateword.rule 
:
d
                                                                                                                                                                                                                                 
┌──(kali㉿kali)-[~/Desktop]
└─$ echo -e "The\nquick\nbrown\nfox\njumps\nover\nthe\nlazy\ndog\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9" > SingleWordsAndNumbers.txt
                                                                                                                                                                                                                                 
┌──(kali㉿kali)-[~/Desktop]
└─$ echo SingleWordsAndNumbers.txt                                                                                         
SingleWordsAndNumbers.txt
                                                                                                                                                                                                                                 
┌──(kali㉿kali)-[~/Desktop]
└─$ cat SingleWordsAndNumbers.txt
The
quick
brown
fox
jumps
over
the
lazy
dog
0
1
2
3
4
5
6
7
8
9
                                                                                                                                                                                                                                 
┌──(kali㉿kali)-[~/Desktop]
└─$ hashcat -r duplicateword.rule SingleWordsAndNumbers.txt --stdout | more                                               
The
TheTyu
quick
quickquic{
brown
brownbrowo
fox
foxfo}
jumps
jumpsjumw
over
over~er
the
thetle
lazy
lazyloy
dog
dogdg
0
00
1
--More--
