### ISSUE TITLE
update message: "Use of --skip/--limit is not supported with --increment or mask files." when --stdout is used

### ISSUE THREAD

**Issue by Shooter3k** [hashcat/hashcat#3580]
when running an attack with --skip, it does not allow the use of --stdout. 

While it does throw this error, can this message be updated to include that? 

Suggestion: "Use of --skip/--limit is not supported with --increment, mask files, or --stdout"

**Comment by Chick3nman** [comment]
Looks like this is a sanity check with a poor warning message. Needs to be updated to either be a separate warning or the suggested warning above.

**Comment by Chick3nman** [comment]
Per a comment from @s3inlc in the related PR, --skip/--limit _should_ work with --stdout, however they _should not_ work with multiple dictionaries and potentially other flags/arguments. The message does need to be updated for clarity in what the actual issue is but the logic does not need to be changed to disallow mixing of --skip/--limit and --stdout.
