### ISSUE TITLE
BUG ?? Multi Threaded CPU list generation not working

### ISSUE THREAD

**Issue by NameTheJew** [hashcat/hashcat#3634]
To be able to fully utilize CPU when generating word lists via Hashcat.

**Current behavior**
>  hashcat wordlist.txt -r examplerule.rule --stdout > pwlist.txt
> only 1 CPU core is maxed, rest are idel

**Expected behavior**
To use all CPU cores while creating word list.
parsort -u will sort with all cores to remove duplicates, but i dont think it speeds up initial list generation.

**Hashcat version (please complete the following information):**
 - OS: Linux and Windows
 - Kali, Windows 10
 - ryzen 5950x & 2700x CPUs
 - hashcat 6.2.6

**Comment by jsteube** [comment]
Hashcat supports 100% usage on all cores in regular cracking mode. You can use this command to verify:

```
$ ./hashcat.bin example0.hash example.dict -O -w 3 -g 10000 -m 0 -D1
```

But in --stdout mode is it limited to one core. But that's fine, because it's the output file descriptor itself which creates a bottleneck in multicore usage (no matter if stdout or a file).

A good way to demonstrate this is this:

```
$ (./mp64.bin 0?a?a?a?a?a & ./mp64.bin 1?a?a?a?a?a & ./mp64.bin 2?a?a?a?a ?a & ./mp64.bin 3?a?a?a?a?a & ./mp64.bin 4?a?a?a?a?a & ./mp64.bin 5?a?a?a?a?a a?a & ./mp64.bin 6?a?a?a?a?a & ./mp64.bin 7?a?a?a?a?a &) | wc -l
```

Now this should (in theory) occupy 100% of the CPU on an 8-core machine since there are 8 processes involved - but it doesn't. The reason is that the system is too busy merging the writes to the single file description output.

The workaround would be to use multiple output handles, but you can already do that by running multiple hashcat instances in parallel - and later merging the contents of the output files into one. So in the end there is no benefit in having multi-core support.
