### ISSUE TITLE
test.sh splitting

### ISSUE THREAD

**Issue by jsteube** [hashcat/hashcat#3653]
Something is going wrong in test.sh for hashes which include space characters.

To reproduce:

```
tools/test.sh -t multi -a 0 -m 31400 -V1
```

```
[ test_1679595827 ] > Init test for hash type 31400.
! unhandled return code, see test_1679595827/logfull.txt or test_1679595827/test_report.log for details.
```

The error log says for all hashes in the hashfile:

```
Hashfile 'test_1679595827/31400_hashes.txt' on line 1 (S:"Config): Token length exception
...
```

However, the test module and test.pl created them correctly:

```
$ head -1 test_1679595827/all.sh
echo 316                             | ./hashcat ${OPTS} -a 0 -m 31400 'S:"Config Passphrase"=02:f051ef12b9b0da6aeb1830344c619e3c86b9e66b49a0d9c1380a2e6530eb25a51f60392fb850226992f7d87670262210'
```

I guess it's just some splitting that went wrong.

@philsmd @matrix Could you have a look at the script please?

**Comment by ventaquil** [comment]
Possible problem is with this line.

https://github.com/hashcat/hashcat/blob/04e7f84dafe87506e4aa22342b102e6b5a7dfbd2/tools/test.sh#L570

My test script

```sh
#!/usr/bin/env bash

pass='xyz'
echo "testing \"${pass}\""
cmd="echo -n ${pass} | wc --bytes"
echo "testing \"${cmd}\""
output=$(bash -c "${cmd}")
echo "output ${output}"

pass='abc '
echo "testing \"${pass}\""
cmd="echo -n ${pass} | wc --bytes"
echo "testing \"${cmd}\""
output=$(bash -c "${cmd}")
echo "output ${output}"
```

Result

```
testing "xyz"
testing "echo -n xyz | wc --bytes"
output 3
testing "abc "
testing "echo -n abc  | wc --bytes"
output 3
```

After change `echo -n ${pass}` into `echo -n '${pass}'`

```
testing "xyz"
testing "echo -n 'xyz' | wc --bytes"
output 3
testing "abc "
testing "echo -n 'abc ' | wc --bytes"
output 4
```

Final test script

```sh
#!/usr/bin/env bash

pass='xyz'
echo "testing \"${pass}\""
cmd="echo -n '${pass}' | wc --bytes"
echo "testing \"${cmd}\""
output=$(bash -c "${cmd}")
echo "output ${output}"

pass='abc '
echo "testing \"${pass}\""
cmd="echo -n '${pass}' | wc --bytes"
echo "testing \"${cmd}\""
output=$(bash -c "${cmd}")
echo "output ${output}"
```

I do not have time for more tests now but it's the possible problem.

**Comment by philsmd** [comment]
The above fix (https://github.com/hashcat/hashcat/pull/3659) should emphasize and solve the root of this new problem. `awk` did of course split on every space field and therefore the hashes were truncated. There are some alternatives to my suggested patch/solution (using `awk`), for example by using the unix tool `cut` etc... but they need other work-arounds too, i.e. setting the delimiters with -d correctly otherwise the 10th field would not be the correct one... (but while setting all options of `cut` corrrectly, the advantage would be to just use `-f10-` which indicates every field after the 10th field).

I think this patch is still better because it does only change the current code in a very minimal way and works for me for all inputs (while `cut` splits "differently" depending on the `-d` settings etc).

Thanks

---

btw: this syntax would also work:
```bash
awk '{t=$10;for(i=11;i<=NF;i++){t=t" "$i};print t}'
```
