### ISSUE TITLE
Hashcat cannot get the correct result, when the compressed text file is larger than 16kb.

### ISSUE THREAD

**Issue by jondya** [hashcat/hashcat#3665]
**Describe the bug**
I use 7-zip to compress a text file of about 80kb into a zip file, the encryption algorithm is ZipCrypto, and the password is 5678. Then I use zip2john.exe to get the password hash value, and use "hashcat.exe -a 3 -m 17200 hash.txt ?d?d?d?d -o password.txt " to crack, but not success. The output is as follows：
<img width="485" alt="屏幕截图 2023-03-31 152610" src="https://user-images.githubusercontent.com/63438039/229052596-8107cbc3-bf91-47ad-94c4-966d6e1b18b3.png">
After that I tried many times with the same method and found that when the text file is less than 16kb, hashcat can get the correct result, but when the file becomes bigger, hashcat can't get the correct result.

**To Reproduce**
Origin data：[random_chinese.txt](https://github.com/hashcat/hashcat/files/11119214/random_chinese.txt)
zip：[random_chinese.zip](https://github.com/hashcat/hashcat/files/11119309/random_chinese.zip)
hash：[hash.txt](https://github.com/hashcat/hashcat/files/11119224/hash.txt)

**Hashcat version**
 - OS: Windows10
 - Version: 6.2.6

**Comment by hops** [comment]
The main culprit here seems to be zip2john. See #2719 for more details (TL;DR: bugs were fixed and `$pkzip2$` format deprecated). There has also been some bug fixes in the PKZIP modules on the hashcat side since version 6.2.6 was released.
Your test zip cracks fine with a build from the current master of hashcat and zip2john from the [bleeding-jumbo](https://github.com/openwall/john/tree/bleeding-jumbo) branch.
Here's the hash extracted with the latest zip2john.
[random_chinese-hash.txt](https://github.com/hashcat/hashcat/files/11127315/random_chinese-hash.txt)
There's also beta builds of hashcat to be found [here](https://hashcat.net/beta/) in case it doesn't crack with version 6.2.6

Since the `$pkizip2$` format is deprecated maybe a warning (or even error) should be added on the hashcat side to inform users about potential false negatives with their extracted hash.

**Comment by jondya** [comment]
> 

Thank you for your reply. The beta version of hashcat has indeed addressed this issue.
