### ISSUE TITLE
hashcat -g does not generate the ~ character

### ISSUE THREAD

**Issue by Shooter3k** [hashcat/hashcat#3688]
to reproduce: 

echo test > wordlist
echo test= > hashlist

hashcat -m99999 hashlist wordlist -g1000000 --generate-rules-func-min=1 --generate-rules-func-max=1  ## cracked immediately

-----

echo test > wordlist
echo test~ > hashlist

hashcat -m99999 hashlist wordlist -g1000000 --generate-rules-func-min=1 --generate-rules-func-max=1  ## never cracked

------------------------------------

Makes me wonder what other characters that are missed/missing?

**Comment by Chick3nman** [comment]
Current "values" appear to be limited to 0x20 - 0xFE, and "positions" 0-B. It does appear to be either intentional or simply a mistake setting the limit that didn't account for the range being non-inclusive. This may not be a "bug" though, as the range is intentionally restricted regardless. We may want to extend the available positions and/or values.
