### ISSUE TITLE
Mode 4500 double sha1 definition is confusing

### ISSUE THREAD

**Issue by BobForCat** [hashcat/hashcat#3804]
Hi,

Just got myself confused after looking for the right format for double-sha1. 

Regarding the help page I thought it would be [4500 - `sha1(sha1($pass))`][4500] but after failures to crack the password I was sure about, I found that MySQL is a double-sha1 and so I tried it's [300][300] mode and I got my successes

To be less confused by that I tried the example hashes given, and the 4500 `sha1(sha1($pass))` is more like a `sha1(hex(sha1($pass)))`

```python
>> sha1(sha1(b"hashcat").digest()).hexdigest()
'fcf7c1b8749cf99d88e5f34271d636178fb5d130'            # match the MySQL4.1/MySQL5 hash of mode 300

>> sha1(sha1(b"hashcat").hexdigest().encode()).hexdigest()
'3db9184f5da4e463832b086211af8d2314919951'            # match the sha1(sha1(pass)) of mode 4500
```

Have I missed a part in the documentation that states that when using multiple cryptographic function it should be considered that the output of one given to another is in hexadecimal ? while the output is natively bytes and the input of the other is natively bytes too

Thanks !

[4500]: https://github.com/hashcat/hashcat/blob/master/src/modules/module_04500.c
[300]: https://github.com/hashcat/hashcat/blob/master/src/modules/module_00300.c

**Comment by ghost** [comment]
`MySQL4.1/5` would be named `sha1(sha1_bin($pass))`.

**Comment by Chick3nman** [comment]
I agree with @justpretending that the MySQL mode would instead be described as sha1(sha1_bin($pass)), and 4500 would retain it's current naming. The precedent we have set with our naming is that if you want the "raw" or "binary" intermediate value in a layered construction, you label it as such. Other "arbitrary" layering is assumed to be lowercase hex in the vast majority of cases. In a few specific cases, we have uppercase hex intermediate values or even other encodings, but they are labeled as such in most cases.

**Comment by BobForCat** [comment]
@Chick3nman so do I open a PR to name the 300 mode  `MySQL4.1/MySQL5/sha1(sha1_bin($pass))` ?

**Comment by Chick3nman** [comment]
MySQL4.1/MySQL5 is already the name used for that algorithm, it's not just a generic algorithm, it only happens to match that description and function for that purpose. We don't have descriptive names for many of our modes because they were named for the specific implementation they were created to handle. It's for the same reason we haven't renamed `NTLM` to `NTLM/NT hash/MD4(UTF16LE($pass))`.  If anything, this may be something we can change in documentation, such as providing more descriptions of the underlying algorithm on the example hashes page here: https://hashcat.net/wiki/doku.php?id=example_hashes but I don't see any reason to go through and rename the modes as they are in hashcat itself.

**Comment by BobForCat** [comment]
Ok got it, thanks for the explanations

**Comment by roycewilliams** [comment]
I've dropped an interim note at the top of the example-hashes page, but seeking a better approach is reasonable - we'll try to figure one out.
