### ISSUE TITLE
Kernel Build Failure when running -m 2500

### ISSUE THREAD

**Issue by derhornspieler** [hashcat/hashcat#381]
./hashcat.app -a 3 -m 2500 /Users/xxxxxxx/Downloads/XP_German/16444_1466388154.hccap ?d?d?d?d?d?d?d?d?d?d
hashcat (v3.00-beta-199-gadb170f+) starting...
# OpenCL Platform #1: Apple               
- Device #1: Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz, skipped
- Device #2: GeForce 320M, 128/256 MB allocatable, 6MCU

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Applicable Optimizers:
- Zero-Byte
- Single-Hash
- Single-Salt
- Brute-Force
- Slow-Hash-SIMD
- Device #2: Kernel m02500.26259659.kernel not found in cache! Building may take a while...

=== Build failed, retry with optimization disabled ===

ERROR: clBuildProgram() : -11 : CL_BUILD_PROGRAM_FAILURE

=== Build Options : -I "/Users/Shared/oclHashcat/./OpenCL/" -I '/Users/Shared/oclHashcat/./OpenCL/' -I /Users/Shared/oclHashcat/./OpenCL/ -I"/Users/Shared/oclHashcat/./OpenCL/" -I'/Users/Shared/oclHashcat/./OpenCL/' -I/Users/Shared/oclHashcat/./OpenCL/ -DVENDOR_ID=2147483648 -DCUDA_ARCH=0 -DVECT_SIZE=1 -DDEVICE_TYPE=4 -DKERN_TYPE=2500 -D_unroll -cl-std=CL1.1 ===

=== Build Log (start) ===
Error getting function data from server
=== Build Log (end) ===
- Device #2: Kernel /Users/Shared/oclHashcat/./OpenCL/m02500.cl build failure. Proceeding without this device.

Cheers mate!

**Comment by jsteube** [comment]
It's a compiler error, not hashcat's fault. Ther error "Error getting function data from server" can be found numerous times on the web, it seems no one know about a workaround.

@magnumripper I see JtR had to deal with this kind of error, too. Did you found a workaround?

**Comment by magnumripper** [comment]
Yeah I've struggled with these for years. Early Maverick was very very poor, then it got better and better and right before Yosemite, all JtR formats worked fine (partly because of workarounds but also a lot better driver). Then for some idiot reason, Yosemite made it just as bad as Maverick in 2012 and that's about where we are still.

Here are some outrageous examples:
- Having two spaces in a row anywhere in in build options (as in `-Dthis -Dthat  -Ipath`) triggered a fatal error in some version(s)!
- A header file that missed the last line's LF, when #included, was mixed with the sourcing file's next line, causing havoc!
- Several times I've seen I needed some kind of barrier like this _even though there is absolutely no reason AFAICS - and only Apple needed it_:

``` c
#if __OS_X__ && gpu_nvidia(DEVICE_INFO)
    /*
     * Driver bug workaround. Halves the performance :-(
     * Bug seen with GT 650M version 10.6.47 310.42.05f01
     */
    barrier(CLK_GLOBAL_MEM_FENCE);
#endif
```

...and sometimes there's not even any normal barrier that does the trick. Here's a crazy workaround actually in use in JtR in some place. _Note that the condition is never true!_

``` c
#if __OS_X__ && gpu_intel(DEVICE_INFO)
/*
 * Ridiculous workaround for Apple w/ Intel HD Graphics. I tried to
 * replace this with a barrier but that did not do the trick.
 *
 * Yosemite, HD Graphics 4000, 1.2(Jul 29 2015 02:40:37)
 */
    if (get_global_id(0) == 0x7fffffff) printf(".");
#endif
```
- The below replaces a function with more or less an exact copy of the same function. For some crazy reason that works around some bug:

``` c
#ifdef __OS_X__
        /* This is the weirdest workaround. Using sha1_final()
           works perfectly fine in the RarFinal() subkernel below. */
        PUTCHAR_BE(tempin, pwlen + 11, 0x80);
        for (i = pwlen + 12; i < 56; i++)
            PUTCHAR_BE(tempin, i, 0);
        tempin[14] = 0;
        tempin[15] = (blocklen * (round + 1)) << 3;
        sha1_block(tempin, tempout);
#else
        sha1_final(tempin, tempout, blocklen * (round + 1));
#endif
```

...and these were just some examples. In my darkest moments I deemed Apple even worse than AMD, but to be honest they are still not THAT bad 😄

**Comment by magnumripper** [comment]
Oh, and many many other times (unfortunately not documented) I've had great success just shuffling code around in a way that _shouldn't_ make any difference whatsoever. It's extremely frustrating to have to resort to "throw things at it and see what sticks".

**Comment by jsteube** [comment]
So this is clearly some OSX OpenCL runtime issue. I don't see a way to workaround this, therefore closing the issue. Thanks @magnumripper for explanations.
