### ISSUE TITLE
Do the modes -m 28501 ... 28506 actually work?

### ISSUE THREAD

**Issue by YetAnotherRussian** [hashcat/hashcat#3861]
Hi, I was unable to make this working...

Device #1: AMD Radeon RX 6750 XT, 12160/12272 MB (12016 MB allocatable), 20MCU
Hashcat 6.2.6

hashcat.exe 0800fc577294c34e0b28ad2839435945 -m 0 -a 3
>>> 0800fc577294c34e0b28ad2839435945:hash

From wiki:

hashcat.exe 1Jv6EonXm9x4Dw4QjEPAhGfmzFxTL7b3Zj  -m 28501 -a 3
>>> Invalid mask.

hashcat.exe 1L9nr4GX4Zmd7gDL1UT75QPUqxSgNTvdHb  -m 28502 -a 3
>>> Invalid mask.

Other example:

public P2PKH 1LhFXCGReUCuARYpqdj6x8kf1Pe1n2Ns18
private key 5KbeS8qxKHMYtYfb1iPUQwHJ7kjY2AVFvMNVRAStftqrP72H3ma

hashcat.exe  -a 3 -m 28501 1LhFXCGReUCuARYpqdj6x8kf1Pe1n2Ns18 -1 123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz  ?1?1?1?1S8qxKHMYtYfb1iPUQwHJ7kjY2AVFvMNVRAStftqrP72H3?1?1

>>> Skipping mask '?1?1?1?1S8qxKHMYtYfb1iPUQwHJ7kjY2AVFvMNVRAStftqrP72H3?1?1' because it is smaller than the minimum password length.

>>> Started: Mon Sep 04 12:59:57 2023
>>> Stopped: Mon Sep 04 13:00:01 2023

Adding a single extra character to this mask leads to an integer overflow.

What should be changed for this group of modes? Thanks.

![image](https://github.com/hashcat/hashcat/assets/4670472/40b52524-2741-463e-8907-a358c6fee7eb)

**Comment by PenguinKeeper7** [comment]
They work fine, you're just using them incorrectly. Your mask has to be 52 characters long in order to be valid, hence why Hashcat rejects it (Yours is 51), this question is better suited to the [Hashcat Forum](https://hashcat.net/forum/) as it's a usability problem, not a bug. Also, the mode is only really meant for if you forgot a small few characters of the key, not trying to bruteforce large parts of it

**Comment by Chick3nman** [comment]
Please ask questions like this on the forums, not github.
