### ISSUE TITLE
--keyspace won't run if another oclHashcat process is running

### ISSUE THREAD

**Issue by devils-advocate213** [hashcat/hashcat#389]
When trying to get an estimate of how many keys/passwords will be tried, this error message occurs:

ERROR: already an instance ./oclHashcat64.bin running on pid 1041

Given a dictionary, and optionally, rulesets, can this error be done away with in the event that "--keyspace" is specified at the command line?

When using "--keyspace", I only care about obtaining a number so that a time estimate can be calculated for the total run time.

**Comment by jsteube** [comment]
Try adding a --session

**Comment by devils-advocate213** [comment]
Well, that gets rid of the first error, but doesn't provide a correct calculation.

Here's an example:

./oclHashcat64.bin -m 2500 SSID.hccap english_and_1_to_4.txt -r /home/user/Desktop/oclHashcat-2.01/princeprocessor-master/rules/prince_optimized.rule --keyspace --session=keyspace

Shouldn't it multiply the number of lines in english_and_1_to_4.txt by the number of rules applied in the rule file and give a number?  It only provides the number of lines in english_and_1_to_4.txt.

**Comment by jsteube** [comment]
No, why should it? it should return the number of lines which are compatible to hashcat. In other words, a number that is equal or less than the number of lines in english_and_1_to_4.txt

**Comment by philsmd** [comment]
also see our FAQ section for this (and yes it is indeed a frequently asked question, very easy to find thousands times within the forum/web): https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#what_is_a_keyspace

(hashcat's definition of keyspace is not the same as "number of all password candidate combinations" as you might think)

**Comment by devils-advocate213** [comment]
Why should it?  Good question.  Answer: to provide a more accurate number for how many keys/passwords will be tried given the dictionary input and any rules that might be applied.

The problem is this. "cat english_and_1_to_4.txt | wc -l" gives the same number as this: "./oclHashcat64.bin -m 2500 RB.hccap english_and_1_to_4.txt -r /home/user/Desktop/oclHashcat-2.01/princeprocessor-master/rules/prince_optimized.rule --keyspace --session=keyspace"

The rules in the rule file aren't accounted for at all, it seems.

I suppose this has to be done manually.  One of the above commands will do for a line count of the input dictionary file.

Some command line will give me the other number.
cat prince_optimized.rule | grep -v ^# | grep -v "^[[:space:]]*$" | wc -l

It is simple multiplication from there.  line_count_of_dictionary_file \* number_of_rules

After reading the FAQ, I notice that the CPU version of hashcat actually does exactly this.  Was that small feature going to make its way over to oclHashcat at some point?  It would be nice.

**Comment by jsteube** [comment]
I think you didn't read the FAQ:

https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#what_is_a_keyspace

**Comment by devils-advocate213** [comment]
line 2 under hashcat says this:  -a 0 + rules – number of words in wordlist multiplied by number of rules in rule file

It seems hashcat already has it, but oclHashcat does not.

**Comment by jsteube** [comment]
hmm maybe you're confused by the naming. hashcat will be renamed to hashcat-legacy soon and oclHashcat becomes hashcat which supports cpu and gpu. At that point, the way how oclHashcat handles this will be active for hashcat, too. there's no way to change this and no one ever had problems with it.

**Comment by devils-advocate213** [comment]
Admittedly, I am just going off the entries that are listed in the FAQ that was linked.  I was looking at line 2 for both hashcat and oclHashcat and noticed that difference between hashcat and oclHashcat.  Just going off the FAQ, it seems rules aren't factored in for oclHashcat.  I might go do a diff on the source between the two and see what I can find.

Thanks anyway.

**Comment by philsmd** [comment]
Again, this is exactly as it is supposed to work.

Keep in mind, --keyspace is a feature that allows one to obtain the correct numbers for distributed cracking, i.e. the maximum threshold for the --skip (-s) and --limit (-l) values.

--keyspace, on the other hand, was never meant to be a "calculate-the-total-number-of-password-candidates-for-me" tool.

It is a special feature to be used before you set the -s and -l values.

If it would just calculate the total number of password candidates (without any particularities), it would be kind of useless, because everyone of us knows how to do the math (e.g. line_number \* rule_number).

So the only thing you need to understand (and it was mentioned dozens of times on forum/irc/wiki/faq), is that hashcat's keyspace feature is NOT a general keyspace calculator ("total number of password candidates").

You can also see these difference by looking at the status output: basically the "Restore.Point:" line shows you how far we are in "hashcat's keyspace", while the "Progress:" line shows you how many password candidates of the total number of password candidates were already tried.

There are many reasons to make this distinction (and why the hashcat's keyspace value is not what you would expect), the most important one being that we can't really reach/set a restore point at every single password candidate try, GPUs try a huge amount of password candidates at once, billions of password candidates per second. Hashcat's keyspace can't be partitioned at an even finer grade than that value. So that is why the hashcat's --keyspace feature was introduced to make it clear how many "restore points" there are (think of it as an outer loop iteration count) and how a large cracking job can be distribution with -s/-l depending on the --keyspace value.

I would say, that everything is exactly as intended. There could be 2 things we could think about here:
1. let --keyspace run without setting --session (circumventing this particular safety-check)
2. think/discuss (again) why people don't seem to understand/can deal with this "keyspace" definition and maybe think of a different name for this flag.

(and yes, hashcat-legacy has a different way (i.e. it is finer-grained) to create "restore points" and yes, in some cases this matches with the "total number of password candidates")
