### ISSUE TITLE
Cracking LUKS v1 maybe broken, false passwords output and/or no output

### ISSUE THREAD

**Issue by realSnoopy** [hashcat/hashcat#3903]
Please also see forum for more informations https://hashcat.net/forum/thread-11679-post-59505.html#pid59505
i used the provided luks-file from the user

Version:        1
Cipher name:    aes
Cipher mode:    cbc-essiv:sha256
Hash spec:      sha1

BUG:
Cracking LUKS mode 14600 and also extracted format 25911 resulting in multiple false password candidates

setup: 
hashcat 6.2.6 (and beta) bruteforce, mode 14600 and mode 25911 (extracted with provided python-tool), different systems, CPU only, opencl 3.0 , 2.1, cuda 12.2 with GTX 3060, mask abcdefg?s?d?d?s, --keep-guessing

runs resulting in outputting 5-10 different passwords per run like 

test_luks:abcdefg#96!
test_luks:abcdefg{30#
test_luks:abcdefg;36~
test_luks:abcdefg=08}

retried the usersetup on my own with WSL, same password, slight different standardsettings for LUKS1

Version:        1
Cipher name:    aes
Cipher mode:    xts-plain64
Hash spec:      sha256

same setups as above, resulting in an uncracked password, no false positives like above

**Comment by ventaquil** [comment]
`14600` and `29511` share same kernel files - only the module is different.

Let's take a look at the verification code that identifies the hypothetical password as valid.

https://github.com/hashcat/hashcat/blob/adbcef6909463aaaf58fe5009aba42618de4fb7a/OpenCL/m14611-pure.cl#L369-L377

Later, I'll examine how it's implemented in cryptosetup. My initial thought is to enhance the entropy check with a more precise algorithm.

**Comment by jsteube** [comment]
I think goes all back to how the user initially created the test drive. Following the forum thread, they simply did not format the the luks drive after it was created, leaving the data untouched. Please read the initial forum thread which describes the correct way of preparing a test-drive (or use a real one): https://hashcat.net/forum/thread-6225.html

Please close this issue as well as mark the forum thread if this turns out to be reason.
