### ISSUE TITLE
Stange behaviour for rule '/' with plains that contain '/' and '\'

### ISSUE THREAD

**Issue by mhasbini** [hashcat/hashcat#391]
command: `hashcat --stdout -r rule.rule plains.txt`

rule.rule:

> /e

1- 
plains.txt:

> abcdef
> \
> abc
> /
> eeeeee

output:

> abcdef
> \
> eeeeee

2- 
plains.txt:

> abcdef
> \
> eeeeee

output:

> abcdef
> \
> eeeeee

3-
plains.txt:

> abcdef
> \
> abc
> eeeeee

output:

> abcdef
> \
> eeeeee

4-

plains.txt:

> abcdef
> \
> ae
> /
> eeeeee

output:

> abcdef
> \  
> ae  
> /  
> eeeeee

5-

plains.txt:

> abcdef
> \
> e
> /
> eeeeee

output:

> abcdef
> \  
> e  
> eeeeee

Expected ouput: all plains that contains `e` should be printed.

**Comment by jsteube** [comment]
OK it seems you were testing old hashcat (CPU) cracker and then posting the error on the GPU version. That's confusing. However I used it for a test with the upcoming hashcat v3.00:

```
root@ht:~/hashcat# cat plains.txt 
abcdef
\
abc
/
eeeeee
root@ht:~/hashcat# cat rule.rule 
/e
```

```
root@ht:~/hashcat# ./hashcat --stdout plains.txt -r rule.rule 
WARNING: Cannot convert rule for use on device in file rule.rule on line 1: /e
abcdef
\
abc
/
eeeeee
```

The error is correct, because the function / is not supported with -r, only with -j and -k. However, it should not print anything here, because there's no valid rules left.

Anyway, if you run it with -j, it shows a valid result:

```
root@ht:~/hashcat# ./hashcat --stdout plains.txt -j /e
abcdef
eeeeee
```

**Comment by mhasbini** [comment]
You are right, look like I was running it with an old version 2.00. Got same ouput as yours when I test it with version 3.00.
BTW are there any documentation for rules that doesn't work with -r or work only with -j and -k ?

**Comment by jsteube** [comment]
Kind of, see here: https://hashcat.net/wiki/doku.php?id=rule_based_attack
- the rules marked with "+"
- the full section "Rules used to reject plains"
