### ISSUE TITLE
Does Hashcat supports Multi-GPU acceleration?

### ISSUE THREAD

**Issue by DeepDream2045** [hashcat/hashcat#3930]
Hi, hashcat dev team.
Hashcat is very useful and currently using hashcat on GPUs
Need to accelerate the process with multiple GPUs.
Current code is using only 3500MB of memory from each GPU.
Is there a way to increase the GPU usage and acceleration through multiple GPUs?
Thank you

**Comment by roycewilliams** [comment]
This is more of a question for the hashcat forums, than a code issue: https://hashcat.net/forum/

hashcat will indeed use multiple GPUs out of the box, no special configuration required (other than the proper GPU drivers). But enough work has to be supplied to use them. The attack has to be large/efficient enough to benefit from being distributed across multiple GPUs.

But by saying "is using only 3500MB of memory from each GPU", your question seems to be different from the subject of this GitHub issue. OpenCL has a known max allocation cap of 1/4 of the GPU's memory per job, which hashcat follows (except for a couple of specific hash types, such as scrypt). The NVIDIA "fix" for this is to use CUDA instead of OpenCL, which allows for larger single allocations.

**Comment by DeepDream2045** [comment]
Thank you for your kind reply.
I am using RTX A6000(48GB Memory) and still allocating 3500MB only.
How to increase it?

**Comment by roycewilliams** [comment]
Use CUDA. Use `hashcat -I` to list the device IDs, and then use `-d [device-id]` with the CUDA ID of the device.

**Comment by Chick3nman** [comment]
This is not an issue, hashcat will use as much memory as it needs to. Using more RAM for no reason will not speed anything up. Please discuss further on the forums or perhaps in the discord.
