### ISSUE TITLE
its say EXHAUSTED but i have correct password in a wordlist when i put it. HOW I FIX IT?

### ISSUE THREAD

**Issue by ciaofradi00** [hashcat/hashcat#3933]
Same Problem its say EXHAUSTED but i have correct password in a wordlist when i put it. HOW I FIX IT?

_Originally posted by @ShadowCyber1 in https://github.com/hashcat/hashcat/issues/2328#issuecomment-1809707183_

**Comment by dmgarry** [comment]
Screenshot... hash type... attack type etc would help... could be a hundred different reasons..

**Comment by Chick3nman** [comment]
I'm not sure I understand this, you've copied someone else's comment and posted it as a github issue, but without any of the information necessary for us to help you. I'm going to close this for now as there's nothing here. If you can provide some supporting information about what the actual issue is, perhaps we can reopen this and figure out what is wrong. Currently there's not enough to determine anything or provide any guidance.
