### ISSUE TITLE
Batch Mode for Hashcat

### ISSUE THREAD

**Issue by Austin-Src** [hashcat/hashcat#3935]
Hey all, in its current form hashcat is an amazing tool, but as it is often paired with active engagements it is an incredibly common situation to have a handful of hashes, dump them into the tool and a few minutes or hours later discover you have more to add. At this point you are faced with two options: kill the crack session and start from scratch, or continue cracking and hope what you already have gives you what you need. Around the 13-15 character limit hashcat starts to really lose likelihood to crack due to the sheer volume of the key space, but it still sometimes has success. I would like to suggest adding a batch mode that allows hashcat to sort of load balance the cracking process. For example, if you have 30 hashes and %0.00001 likelihood to crack and an additional 10 hashes with %0.005 likelihood to crack that came in later the tool could loop back to the easy crack until the time to reward ratio evened out and then jump back to the higher key spaces with both sets of hashes. This would require leaving a marker of sorts tied to each hash that indicated what iterations had already been completed. This would allow maximum efficiency with hardware power and take some of the workload off the tester. Would love to see this added if possible!

**Comment by Chick3nman** [comment]
While I can sorta see the idea here and I think it makes intuitive sense, I don't think this makes sense from a technical perspective with how hashcat works. I'll try to explain with some examples and see if it clears up what I mean.

When you load a list of unsalted hashes, such as NTLM(or NT technically) hashes, into hashcat, the first step is to process all the hashes into a bitmap (or bloom filter) which we use for fast lookups during cracking. Whenever hashcat processes a password or other candidate, it hashes it with your target algorithm and then compares it with the bitmap for all the loaded hashes, and uses that to reject hashes that are certainly not in the target list. This check is very fast and fairly good at filtering hashes and avoiding a hard lookup against the list, but even a hard lookup is fast/computationally cheap compared to the actual hashing. Because of how fast this is it means that adding more hashes to your list is "effectively" free after the first few, at least up to the point where it starts to impact our ability to build and store this bitmap in fast cache on the GPU(thousands or millions of hashes). Now, if we consider your example of "I've found some more hashes, I need to run the first part of the keyspace again for these new hashes before continuing from where I am now" and we consider that the impact of the lookups is so fast that it's negligible, there's essentially no difference in work between 1. running the new hashes separately from the old ones in some separate attack to then later combine them and 2. stopping the attack, loading the new hashes into the existing list, and starting over with all the hashes together. You will complete roughly the same amount of work and it will take roughly the same amount of time combining the lists and "starting over" as if you did it separately. This example should explain why it doesn't really make sense, there's nothing to be saved for unsalted hashes except maybe a handful of ms of lookup time over the entire attack.

However, what about salted hashes? In the case of salted hashes, we must hash every candidate differently per every unique salt, which inflates the amount of work we must do by (keyspace * unique_salts). The "penalty" for loading more salted hashes, specifically only with unique salts(!), does mean that if you found more salted hashes later, combining them and rerunning the attack from the start would redo work unnecessarily for the salts you've already attacked. In that case, it would make sense to attack the salted hashes in separate "batches" and only combine them when they have reached the same "position" in your attack's keyspace. While this example DOES validate your idea conceptually, I'm not so sure within hashcat itself is the right place for it to be handled. This seems like the sort of thing that would be better handled external to hashcat as hashcat's "coherency" between attacks is left mostly up to the user to control as it is right now. We do _some_ things to avoid redoing work, like using the potfile to reject hashes/salts hashcat has already cracked, but the only place where we keep track of actual work done on a hash or rather hash list is within hashcat-brain, and hashcat-brain's limitations, especially regarding the performance limits, show some of the challenges in using that information to increase attack efficiency in this way. That's not to say that it's impossible, there's just some technical challenges to implementing this sort of thing that I'm not sure would make it "worth while" given that it could be done much simpler/easier with an attack planning/tracking framework that just builds on top of hashcat vs within it. This is something that we've already seen from 3rd party tools/frameworks like that as well. Hashtopolis, for example, can be used to track work done on hashes and loading new hashes as a separate list can allow you to effectively queue up and interleave work between the old and new lists without redoing anything from outside of hashcat itself.

I also want to address the point you've made about "likelihood to crack". I'm not so sure I understand what you mean when you say "Around the 13-15 character limit hashcat starts to really lose likelihood to crack". Does this mean you are running some sort of mask attack or other bruteforce attack out to that length? This doesn't sound like an efficient attack setup to begin with and I suspect the gains in efficiency you are trying to achieve with this sort of attack tracking would be far outweighed by the gains made from using a more efficient/effective attack. Intuitively it sounds like it makes sense, more keyspace == less likely to crack, but I'm not so sure that holds true _across_ or _between_ attacks as you can perform additional attacks that also have a high "likelyhood to crack" instead of running an exhaustive attack out to the point of infeasibility. If you want to make efficient use of hardware resources and especially tester effort/time, building better attacks than 13-15 character bruteforce would almost certainly provide more benefit than any time saved in making that sort of attack a little more efficient. That's not to say there isn't some benefit, as my second example with salted hashes touches on, but that it may not be the best area to focus optimization efforts. It seems like it would make more sense to try and raise the overall efficiency and reduce the overall effort and time spent by focusing on creating better/other attacks.

**Comment by Austin-Src** [comment]
@Chick3nman Thank you for the in depth reply! I was unaware of the bitmapping feature and find it very fascinating. Salted passwords were largely what I had in mind, but I was unaware of the Hashtopolis repo. I agree that straight brute force tends to not be very efficient, but if you have the hardware to throw around it can catch random generated passwords that wordlists and rule sets won't. Because there are others working on similar solutions, I'll close this so it doesn't clutter the workload. Thank you!

**Comment by Austin-Src** [comment]
Wrong button, whoops!

**Comment by Austin-Src** [comment]
Wrong button, whoops!

**Comment by Austin-Src** [comment]
Better.
