### ISSUE TITLE
Recover again --pw-min and --pw-max options

### ISSUE THREAD

**Issue by JBalanza** [hashcat/hashcat#4012]
**Describe the feature**
I think this options still makes lot of sense nowadays. In other attacks like dictionary+rules its neccesary to filter out candidates that do not meet minimun password length (i.e.: a domain password that should meet domain requirements as for minimun length) there is no way to filter out candidates that does not meet the requirement and thus, speed up the cracking by avoiding testing wrong candidates in advance.

**Current behavior**
This can be done currently ONLY in mask attacks, using --increase-min and --increase-max. There is no possible way to do that on the other attack modes.

**Comment by Banaanhangwagen** [comment]
Take a look here: https://hashcat.net/wiki/doku.php?id=rule_based_attack#rules_used_to_reject_plains
Or, with for example `awk` and the 'length' parameter, you can optimse your wordlist before feeding it into hashcat.

**Comment by JBalanza** [comment]
Thanks @Banaanhangwagen for replying. The problem I see with the second option is that it only works for cleaning the dictionary but not the final password candidates in case a rule file is specified. Would the first option (using -j) work using dictionary + a rule file + the "-j" parameter?

**Comment by Chick3nman** [comment]
The reason this cannot be done is because it would actually _hurt_ performance, contrary to what you might assume.

Rules are applied at the very last step before hashing on the GPU. All of the slowest things have _already_ taken place by the time rules are applied, including loading the words from host to the GPU and distributing those words to the processing cores to be hashed. By the time rules are applied, there is essentially no time left to save by doing a length check and throwing it away and waiting for new work to be available. In fact, it is often faster to simply continue with the hashing of that candidate even if we know that the candidate isn't what we want it to be. This may seem counterintuitive but it's actually common practice within hashcat already, although it seems to be less than well known about despite my efforts. For example, when we have a rule that can't be processed for some reason, it's too late to ditch and save any time so we simply pass the candidate through and hash it as is, effectively turning the rule into a "no-op", and often times ending up with candidates that are unchanged or duplicates of the output of other rules. The amount of "bad" work your GPU ends up doing is certainly unfortunate, but it's often so much faster to use the GPU processor and deal with this that it ends up being worth it. If your hash is slow enough that this overhead is actually a detriment to your overall attack feasibility, you are better off doing the candidate processing on the host side instead of the GPU, where the length rejections are already possible as @Banaanhangwagen mentioned. If you are unsatisfied with this answer, you can certainly work on optimizing your attack setup to reduce the amount of candidates that are "wrongly" produced by your rule+dict combination, but that's likely to involve vastly more time and effort than ignoring it and letting it run, which is why most aren't doing or aren't even aware of this.

**Comment by JBalanza** [comment]
Hi @Chick3nman. I really appreciate your detailed answer about the insides of Hashcat. Effectively, seems counterintuitive but if that is how hashcat works nothing can be done that implies low effort -> hight impact. Closing the issue.
