### ISSUE TITLE
how to use hashcat v3.0 on the mac osx?

### ISSUE THREAD

**Issue by Tom4t0** [hashcat/hashcat#403]
![image](https://cloud.githubusercontent.com/assets/10905329/16510667/bca10320-3f7a-11e6-98d6-f3d889c5de8b.png)

**Comment by neheb** [comment]
that's a linux binary AFAIK.

**Comment by philsmd** [comment]
You need to clone the repo and compile it. As simple as that.
After that you get a "hashcat.app" binary file that you can execute.

The reason why there is no .app file within the hashcat 3.00 release 7z is that there is no cross-compiler for linux to compile with -framework opencl (and the main devs don't really use OSX/Darwin system and aren't yet fully aware how to best  (let someone else) compile a release binary that works with most if not all the different OSX versions).

I think it is easy enough to just clone and run make (consider reading the build instruction of course), please **close** this ticket if that worked for you.
Thank you very much 

Update: iirc there were a couple of people speaking of OSX-specific "packages" that can very easily be downloaded via brew etc (don't quote me on that because I'm not a OSX expert at all)... but again, we prefer users to use the tagged release versions directly from github and just compile it locally (or if you think nothing could be greater/better than the latest version, also the latest master from github, but of course that is a little bit "dangerous" because it might not always work correctly since it is a preview/development version with the latest changes)

**Comment by Tom4t0** [comment]
thank you
