### ISSUE TITLE
Build errors -m 1800 -m 10700

### ISSUE THREAD

**Issue by th3mechanic** [hashcat/hashcat#405]
benchmark build error ubuntu 14.04.4  

[10700.txt](https://github.com/hashcat/hashcat/files/343455/10700.txt)
[1800.txt](https://github.com/hashcat/hashcat/files/343456/1800.txt)

**Comment by jsteube** [comment]
Which driver are you using? I need to know so that I can reproduce locally

**Comment by th3mechanic** [comment]
amdgpu-pro-16.30   also tested on ubuntu 16.04  still failed

**Comment by jsteube** [comment]
I think it's the " chars in the build options. This should be supported by AMD OpenCL runtime, since it part of the OpenCL specification, but it doesn't. All other vendors do it correctly. Anyway, since I don't have access to a amdgpu-pro compatible GPU, I can not reproduce it. You can try it yourself. Remove the " char from the build options at both sides from the %s and recompile. It should work afterwards. Please give me feedback here if it worked so that we can try to think about a workaround for amdgpu-pro.

**Comment by th3mechanic** [comment]
Sorry for needing the hand holding but in which file do i need to look for it ?   anything i changed so far either failed to build or seg faulted,  pretty much figuring i'm doing wrong.  With other issues i put on the forum it may be best to just hold for a driver update, the pro hasn't changed since the card release, no power draw fix, etc.

**Comment by jsteube** [comment]
Implemented a workaround. Should work now. You can try with latest beta from hashcat.net/beta
