### ISSUE TITLE
Integer overflow in combinator mode with ntlm and ?a?a?a?a?a

### ISSUE THREAD

**Issue by nikaiw** [hashcat/hashcat#4117]
**Describe the bug**

When using combinator attack mode (-a 6) and ntlm (-m 1000) in Hashcat v6.2.6 (64bits) on Debian Bullseye, attempting to combine a wordlist containing a single word (e.g., "hello") with a mask of ?a?a?a?a?a results in "Integer overflow detected in keyspace of mask."

This is quite confusing, maybe I am missing something obvious  ?

**Expected behavior**

I would expected Hashcat to execute the combinator attack without errors, combining the word "hello" from the wordlist with all possible combinations generated by the mask ?a?a?a?a?a. Since the total keyspace (~7.7 billion combinations) looks doable and work if run with -a3 'hello?a?a?a?a?a'

**Hardware/Compute device (please complete the following information):**
- Compute device name: 8 x NVIDIA RTX A5000 (each with 24 GB VRAM)
- OpenCL/CUDA driver name: NVIDIA Driver
- OpenCL/CUDA driver version: 550.78
- OpenCL/CUDA driver source: Official NVIDIA driver installer

**Hashcat version (please complete the following information):**
- OS: Linux
- Distribution: Debian Bullseye
- Version: Hashcat v6.2.6 (64-bit release)

**Comments** 
- Changing the last character in the mask to ?d  works fine.
- Using a wordlist with 900 words and a mask with a custom charset of '?1?1?1?1?1' with -1 '?s?d' works fine.

**Detailled hardware/software Info**

[clinfo.txt](https://github.com/user-attachments/files/17788592/clinfo.txt)
[hashcat.txt](https://github.com/user-attachments/files/17788593/hashcat.txt)
[lspci.txt](https://github.com/user-attachments/files/17788594/lspci.txt)
[nvidia-smi.txt](https://github.com/user-attachments/files/17788595/nvidia-smi.txt)

**Comment by PenguinKeeper7** [comment]
The "integer overflow" message is slightly different in -a 6, in that - as you're seeing - it's significantly smaller than normal -a 3 masks. Anything over 4.2 billion candidates will trigger that message and as you're over 9b, you're seeing that message. The alternative is, as you suggested, to run it as `-a 3`. This is a known limitation of Hashcat, it has been talked about a lot and has been reported before https://github.com/hashcat/hashcat/issues/3611 but unfortunately, it'd be very unlikely to change any time soon, due to the way that -a 6/7 is implemented. This 4.2b limit is here to stay for a good while, sadly

**Comment by nikaiw** [comment]
Thanks @PenguinKeeper7 that's a pity but rather clear, I don't know why but I thought the limit used to be way higher!
