### ISSUE TITLE
2 bugs detected in binaries for Windows

### ISSUE THREAD

**Issue by VOC-LINK** [hashcat/hashcat#418]
1. It creates output file with lines ending only with LF, as it was prepared for Linux/Unix environment - and not with CR-LF, as it should do when used within Windows OS (tested 64-bit version under Windows 10).
2. A friend of mine tested 32-bit version (for Windows); he&#39;s got an  error message: "Procedure RegGetValueA not found in library DLL ADVAPI32.dll"

**Comment by philsmd** [comment]
1. I think you should just use a modern text editor. Almost any text editor can format the output correctly (besides very old "notepad" etc). We also save some unneeded bytes etc.
2. what version of windows is this ? Very old versions, like windows xp, might not work. I don't know. I think we also shouldn't support windows xp anymore, because no driver vendor, nor Microsoft itself officially support them anylonger.

**Comment by VOC-LINK** [comment]
1. But I think the standard should be respected - and DOS/Windows standard is "ending the line with CR-LF". So you say: especially "to save 500 bytes" in output text file I should install text editor, which will occupy several megabytes of my disk space? Just to skip some CRs?
2. Not sure which version he used - but many people still use Windows XP, and they don't care what Microsoft thinks about this. Considering that: "32-bit binary" should be "Windows XP ready", I think.

Anyway: I reported obvious bugs - the rest isn't up to me.

**Comment by neheb** [comment]
1: FWIW only notepad.exe has issues with missing CR = no newline. WordPad and Office do not have this issue. notepad.exe just like many other tools/components in Windows has code in it that has not been touched in at least a decade.

2: The bug is in hashcat's single usage of the RegGetValue function which is supported starting XP 64-bit. The fix would be to use RegQueryValueEx but i'm not sure if anyone's interested in supporting XP.

**Comment by jsteube** [comment]
Should be fixed, binary betas here: https://hashcat.net/beta/
