### ISSUE TITLE
Default Mask Attack behavior

### ISSUE THREAD

**Issue by aress31** [hashcat/hashcat#427]
Hi,

When using a mask attack without specifying any mask the default cudahashcat behavior is to increment the attack from 0 up to +infinite characters which is fine. However, on the terminal in the Input.Mode field the **Mask** looks like:
`Input.Mode.....: Mask (?1?2?2?2?2?2?2?3) [8]`
I have no idea about what are the charset used under these customer charset **-1, -2, -3, -4**. I reckon that they are equivalent of ?a (all poissible charset) and in this case I would suggest to print out the ?a in this Input.Mode field instead of **?1,?2,?3,?4** for clarity.

Best,
Alexandre

**Comment by philsmd** [comment]
No, it's not ?a and it is listed within the wiki:
https://hashcat.net/wiki/oclHashcat#default_values
1. --custom-charset1    ?l?d?u
2. --custom-charset2    ?l?d
3. --custom-charset3    ?l?d*!$@_ 

and default mask: ?1?2?2?2?2?2?2?3?3?3?3?d?d?d?d

This is more like a question that belongs to the forum and not here as a (code) problem/issue (and even when you use the forum for such questions, it's recommended that you first search the wiki/--help/faq and use the forum's search function instead of just asking questions that were already answered).

Please don't forget to close this issue. thx

**Comment by aress31** [comment]
Thanks for this reply @philsmd! 
Could I know why this choice of mask? It would be I think more logical to use **?a** for the default mask to simulate a "pure" bruteforce attack using the default hashcat behavior.
Therefore, as a **code request** for what I judge to be an improvement. I would suggest to change the mask to ?a for the default behavior.
Best,
Alexandre

**Comment by philsmd** [comment]
The main reasons why it is not just only ?a is that:
1. using ?a is most of the times not the best choice and not very clever, passwords are still mostly user-defined (and not generated by passwords managers etc), mask attack is (see definition) a special position-for-position mechanism, using ?a?a?a?a?a?a?a?a?a?a (or even ?b?b?b?b?b?b...) is as we always say "the last thing you should try" (and indeed not very clever)
2. the default mask in hashcat uses a "pattern" that should crack many/most of the user-defined passwords without taking too long. Note: there are of course also some other hash types supported by hashcat, not just md5/sha1/ntml etc... It is kind of a compromise for woking well and still not taking way too long 
3. the default mask also shows how to use mask attack in a more clever way. just "brute-forcing" shouldn't be the idea behind the example/default mask... it should show what is possible and what is reasonable/clever by using also the custom charset at different positions
... (there are of course a huge set of additional reasons and probably there might also be some reasons against it)

One of the possible reasons against using this particular mask/custom charset (-1 ?l?d?u -2 ?l?d -3 ?l?d*!$@_ ?1?2?2?2?2?2?2?3?3?3?3?d?d?d?d), would be indeed that some new users might not immediately understand why some hashes "were not cracked even if they should" (but of course some hashes should not, since we use a reduced keyspace) and as you already noticed that the mask "?1?2?2?2?2?2?2?3?3?3?3?d?d?d?d" in the status display (without the wiki section) doesn't really tell much.
The answer to that is that we recommand that users learn to define and use their own mask (all the time!) as soon as possible and always specify a mask on the command line if you use the mask attack.

As you can see, there are some advantages and disadvantages about the current default mask, but in general it still seems to be a more reasonable mask than a "just brute-force all possible chars" mask.

**Comment by aress31** [comment]
I am happy with this explanation. Thanks for your time!
