### ISSUE TITLE
Problem with LM aad3b435b51404ee

### ISSUE THREAD

**Issue by DidierStevens** [hashcat/hashcat#434]
https://hashcat.net/forum/thread-5636.html

I'm experiencing a problem with LM hash aad3b435b51404ee and hashcat 3.00 on Windows 8.1.

I reduced the original problem I had to this:

file lm: aad3b435b51404ee
Command: hashcat64.exe -a 3 -m 3000 --potfile-disable lm

Output:

Code:
hashcat (v3.00-1-g67a8d97) starting...
# OpenCL Platform #1: Intel(R) Corporation
- Device #1: Intel(R) HD Graphics 5000, 356/1425 MB allocatable, 40MCU
- Device #2: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, skipped

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Applicable Optimizers:
- Zero-Byte
- Precompute-Final-Permutation
- Not-Iterated
- Single-Hash
- Single-Salt
- Brute-Force
  Watchdog: Temperature abort trigger disabled
  Watchdog: Temperature retain trigger disabled

ATTENTION!
  The wordlist or mask you are using is too small.
  Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
  The cracking speed will drop.
  Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_

INFO: approaching final keyspace, workload adjusted

aad3b435b51404ee:X

Session.Name...: hashcat
Status.........: Cracked
Input.Mode.....: Mask (?1) [1]
Hash.Target....: aad3b435b51404ee
Hash.Type......: LM
Time.Started...: 0 secs
Speed.Dev.#1...:        0 H/s (0.15ms)
Recovered......: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.......: 36/36 (100.00%)
Rejected.......: 0/36 (0.00%)

Started: Tue Jul 12 00:32:08 2016
Stopped: Tue Jul 12 00:32:09 2016

Remark this line in the output: aad3b435b51404ee:X
aad3b435b51404ee is the LM hash of the empty string, so I did not expect to see character X.

And when I run this again, I get a different character.

When I use a POT file, it also contains a character for this hash.

I have the sample problem on my laptop and desktop (both Windows 8.1), and with hastcat32.exe and hashcat64.exe.

**Comment by jsteube** [comment]
Issue should be fixed. Don't forget to remove kernels folder before retry

**Comment by jsteube** [comment]
There's also a new beta binary build on https://hashcat.net/beta/

**Comment by DidierStevens** [comment]
Tested with new .cl files. It works now, thanks.

**Comment by mame82** [comment]
Using hascat64.bin Version 3.10 in attack mode 3 with --increment option enabled empty hashes don't geht recognized for LM (hashmode 3000).
This has to be solved manually by switching to straight attack and hitting enter to produce an empty hash, as --weak-hash-threshold doesn't work in attack mode 3 and an empty mask couldn't be used.

**Comment by jsteube** [comment]
weak-hash detection works only in attack-mode 0 and can't be easily ported to other attack-modes. please use the -a 0 mode first

**Comment by mame82** [comment]
I fully understand, but empty hash checking should be done at least for second half of the LM hash in attack mode 3. Otherwise, if password have less than 8 chars they'll never get cracked. According to this issue this has been done in mode 3 on version 3.0.

I've opened a new issue for this, feel free to close it but there should be an advise that straight attack has to be used upfront

**Comment by mame82** [comment]
`INFO: approaching final keyspace, workload adjusted

aad3b435b51404ee:X

Session.Name...: hashcat
Status.........: Cracked
Input.Mode.....: Mask (?1) [1]
Hash.Target....: aad3b435b51404ee
Hash.Type......: LM`

According to this output snippet from the post above, recognizing aad3b435b51404ee for
empty hashes was possible, the only problem was that a wrong plain character gets delivered.

Could you please clarify, if the only option to get a (single concatenated) LM hash with
second half-hash empty, is to run straight attack mode upfront?

Thx in advance

**Comment by jsteube** [comment]
Can't reproduce:

```
root@ht:~/hashcat# ./hashcat -m 3000 hash -a 3 X
hashcat (v3.10-25-gdc30176) starting...

OpenCL Platform #1: NVIDIA Corporation  
======================================
- Device #1: GeForce GTX 750 Ti, 499/1998 MB allocatable, 5MCU

OpenCL Platform #2: The pocl project
====================================
- Device #2: pthread-AMD FX(tm)-8120 Eight-Core Processor, skipped

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Applicable Optimizers:
* Zero-Byte
* Precompute-Final-Permutation
* Not-Iterated
* Single-Hash
* Single-Salt
* Brute-Force
Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 75c

ATTENTION!                                                
  The wordlist or mask you are using is too small.
  Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
  The cracking speed will drop.
  Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

INFO: approaching final keyspace, workload adjusted       


Session.Name...: hashcat
Status.........: Exhausted
Input.Mode.....: Mask (X) [1]
Hash.Target....: aad3b435b51404ee
Hash.Type......: LM
Time.Started...: 0 secs
Speed.Dev.#1...:        0 H/s (0.05ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 1/1 (100.00%)
Rejected.......: 0/1 (0.00%)

Started: Fri Sep  2 11:22:41 2016
Stopped: Fri Sep  2 11:22:44 2016 
```

You sure you're using latest github version?

**Comment by mame82** [comment]
I used the binary from https://hashcat.net/hashcat/ (2016.08.19).
I'm trying to reproduce and report back.

**Comment by mame82** [comment]
```
$ hashcat64 -v
v3.10
```

Testcase test.txt (first hash is empty,second with length 4 "hack")

```
$ cat test.txt 
empty:aad3b435b51404eeaad3b435b51404ee
hack:9d82cdff56b35758aad3b435b51404ee
```

Invoking hashcat  - hashcat64 is a symlink to hashcat64.bin, hashcat.pot was deleted before start.
I was forced to remove libxnvctrl-dev, thus there's a warning (shouldn't matter here).

```
$ hashcat64 -m 3000 -a 3 --username --increment -1 ?u?d?s test.txt ?1?1?1?1
hashcat (v3.10) starting...

OpenCL Platform #1: Intel(R) Corporation
========================================
- Device #1: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz, skipped

OpenCL Platform #2: NVIDIA Corporation
======================================
- Device #2: GeForce GTX 980M, 2028/8112 MB allocatable, 12MCU
- Device #2: WARNING! Kernel exec timeout is not disabled, it might cause you errors of code 702
             See the wiki on how to disable it: https://hashcat.net/wiki/doku.php?id=timeout_patch

WARN: nvmlDeviceGetFanSpeed() 3 Not Supported

WARNING: Failed loading the XNVCTRL library: libXNVCtrl.so: cannot open shared object file: No such file or directory
         Please install libxnvctrl-dev package.

Hashes: 4 hashes; 2 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Applicable Optimizers:
* Zero-Byte
* Precompute-Final-Permutation
* Not-Iterated
* Single-Salt
* Brute-Force
Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 75c

ATTENTION!                                                
  The wordlist or mask you are using is too small.
  Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
  The cracking speed will drop.
  Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

INFO: approaching final keyspace, workload adjusted       


Session.Name...: hashcat
Status.........: Exhausted
Input.Mode.....: Mask (?1) [1]
Custom.Chars...: -1 ?u?d?s, -2 Undefined, -3 Undefined, -4 Undefined
Hash.Target....: aad3b435b51404ee, 9d82cdff56b35758
Hash.Type......: LM
Time.Started...: 0 secs
Speed.Dev.#2...:        0 H/s (0.06ms)
Recovered......: 0/2 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 69/69 (100.00%)
Rejected.......: 0/69 (0.00%)

ATTENTION!                                                
  The wordlist or mask you are using is too small.
  Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
  The cracking speed will drop.
  Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

INFO: approaching final keyspace, workload adjusted       


Session.Name...: hashcat
Status.........: Exhausted
Input.Mode.....: Mask (?1?1) [2]
Custom.Chars...: -1 ?u?d?s, -2 Undefined, -3 Undefined, -4 Undefined
Hash.Target....: aad3b435b51404ee, 9d82cdff56b35758
Hash.Type......: LM
Time.Started...: 0 secs
Speed.Dev.#2...:    22215 H/s (0.05ms)
Recovered......: 0/2 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 4761/4761 (100.00%)
Rejected.......: 0/4761 (0.00%)

ATTENTION!                                                
  The wordlist or mask you are using is too small.
  Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
  The cracking speed will drop.
  Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

INFO: approaching final keyspace, workload adjusted       


Session.Name...: hashcat
Status.........: Exhausted
Input.Mode.....: Mask (?1?1?1) [3]
Custom.Chars...: -1 ?u?d?s, -2 Undefined, -3 Undefined, -4 Undefined
Hash.Target....: aad3b435b51404ee, 9d82cdff56b35758
Hash.Type......: LM
Time.Started...: 0 secs
Speed.Dev.#2...:  1512.1 kH/s (0.87ms)
Recovered......: 0/2 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 328509/328509 (100.00%)
Rejected.......: 0/328509 (0.00%)

9d82cdff56b35758:HACK                                     
INFO: approaching final keyspace, workload adjusted       


Session.Name...: hashcat
Status.........: Exhausted
Input.Mode.....: Mask (?1?1?1?1) [4]
Custom.Chars...: -1 ?u?d?s, -2 Undefined, -3 Undefined, -4 Undefined
Hash.Target....: aad3b435b51404ee, 9d82cdff56b35758
Hash.Type......: LM
Time.Started...: 0 secs
Speed.Dev.#2...: 81599.4 kH/s (11.87ms)
Recovered......: 1/2 (50.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 22667121/22667121 (100.00%)
Rejected.......: 0/22667121 (0.00%)

Started: Fri Sep  2 12:05:44 2016
Stopped: Fri Sep  2 12:05:46 2016 
```

So the mask mode starts with length 1 not 0.
The recognized hash is the one with 4 chars (hack), but the second half stay unrecognized.

```
$ hashcat64 -m 3000 -a 3 --username --show test.txt
hashcat (v3.10) starting...

hack:9d82cdff56b35758aad3b435b51404ee:HACK[notfound]

```

As you can see, second half of "hack" is still declared [notfound] and the empty password for user
empty isn't showing up.

Your log shows the same, as the mask mode should have tested for a password "X" and the result for
target aad3b435b51404ee are 0/1 recovered hashes - so you have already reproduced the issue.

```
Hash.Target....: aad3b435b51404ee
Hash.Type......: LM
Time.Started...: 0 secs
Speed.Dev.#1...:        0 H/s (0.05ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts


```

**Comment by shaaati** [comment]
Just stumbled upon this same behavior in hashcat 6.2.2. As @mame82 described (quite a long time ago, sorry for necroposting), this results in `--show` suggesting that something is still missing (`[notfound]`).

Couldn't the incremental brute force simply start at length 0?

**Comment by matrix** [comment]
hi @shaaati , please re-read the conversation. Your question has already been answered. Thanks

**Comment by shaaati** [comment]
I was referring to the comment by @mame82 that it had been possible in older versions of hashcat (see https://github.com/hashcat/hashcat/issues/434#issuecomment-244321123) and I don't see that part solved or commented on, after their initial posting.

I feel that it is quite counter-intuitive to check against a wordlist in order to find something that most likely won't be in this wordlist at all, just because this mode triggers the weak hash detection.
Wouldn't it be much more reasonable (and easy to implement) to start the mask length of a brute force at length 0. I don't advocate for removing weak hash detection from dictionary mode, just to not "hide" it only in there.
Which, as I understood it, is exactly what @mame82 was commenting on.

**Comment by matrix** [comment]
> I was referring to the comment by @mame82 that it had been possible in older versions of hashcat (see [#434 (comment)](https://github.com/hashcat/hashcat/issues/434#issuecomment-244321123)) and I don't see that part solved or commented on, after their initial posting.
> 
> I feel that it is quite counter-intuitive to check against a wordlist in order to find something that most likely won't be in this wordlist at all, just because this mode triggers the weak hash detection. Wouldn't it be much more reasonable (and easy to implement) to start the mask length of a brute force at length 0. I don't advocate for removing weak hash detection from dictionary mode, just to not "hide" it only in there. Which, as I understood it, is exactly what @mame82 was commenting on.

I talk about the response of your question, made by @jsteube

**Comment by shaaati** [comment]
> > I was referring to the comment by @mame82 that it had been possible in older versions of hashcat (see [#434 (comment)](https://github.com/hashcat/hashcat/issues/434#issuecomment-244321123)) and I don't see that part solved or commented on, after their initial posting.
> > 
> > I feel that it is quite counter-intuitive to check against a wordlist in order to find something that most likely won't be in this wordlist at all, just because this mode triggers the weak hash detection. Wouldn't it be much more reasonable (and easy to implement) to start the mask length of a brute force at length 0. I don't advocate for removing weak hash detection from dictionary mode, just to not "hide" it only in there. Which, as I understood it, is exactly what @mame82 was commenting on.
> 
> I talk about the response of your question, made by @jsteube 
> 

Do you mean the response that (paraphrasing) "weak hash detection only works in attack mode 0"?

That is exactly what I mean. I feel that this behaviour is very unintuitive. I also did a web search for "weak hash detection hashcat" and didn't find any documentation stating that it requires dictionary mode (not to say there isn't any, maybe I am just stupid).

So as an average user I would suspect that weak hashes are checked, even if I don't use a word list.

I am therefore suggesting to at least consider this for a future improvement, instead of closing this issue (or the related #483). Maybe this is much harder than I think due to the inner workings of hashcat, but it is a valid remark nevertheless, isn't it?

**Comment by matrix** [comment]
@shaaati hashcat is open-source, anyone can contribute, even yourself. It might be an interesting challenge for you to add just the functionality you need. What do you think about it?

**Comment by matrix** [comment]
Example (on MacOS):

1. create md5 of empty password

```
$ echo -n | md5
d41d8cd98f00b204e9800998ecf8427e
```

2. check for empty password with attack-mode 0

 ```
echo | ./hashcat -m 0 'd41d8cd98f00b204e9800998ecf8427e' --quiet
d41d8cd98f00b204e9800998ecf8427e:
Session..........: hashcat
Status...........: Cracked
Hash.Mode........: 0 (MD5)
Hash.Target......: d41d8cd98f00b204e9800998ecf8427e
Time.Started.....: Wed Feb 23 21:47:56 2022 (0 secs)
Time.Estimated...: Wed Feb 23 21:47:56 2022 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: Pipe
Speed.#2.........:     7407 H/s (0.01ms) @ Accel:512 Loops:1 Thr:1 Vec:4
Recovered.Total..: 1/1 (100.00%) Digests
Progress.........: 1
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#2...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidate.Engine.: Device Generator
Candidates.#2....:  -> 
Hardware.Mon.SMC.: Fan0: 20%
Hardware.Mon.#2..: Temp: 46c
``` 

@shaaati If that's not enough of an example to show you how simple it is, try connecting on [discord](https://hashcat.net/discord) and asking for help. As has already been answered, doing the same thing in C makes no sense. It only increases the complexity of a program that is already very complex.

Thanks

**Comment by shaaati** [comment]
First of all, I want to emphasize that I don't want to sound ungrateful or demanding. If it came out that way, I apologize! (Not a native speaker).

While I fully understand the reason behind "implement it yourself" responses, I don't see them as a well-suited argument to end a discussion. I am not an experienced developer, especially not in (optimized) C, nor am I involved with the hashcat community and know the typical process of implementing features. This is why I settled on a compromise, to nevertheless help the open source community, which helps me just about every day of my life.
Whenever I use a software and find something that surprises, annoys, frustrates me, or in some other way gets my attention, I try to report it. If I can, I try to debug it as good as I can in order to give proper and detailed feedback.
Because after all, that is how open source should work, too.

In this case, I found something odd when working with hashcat today, and stumbled upon this issue and especially the comments of @mame82, who expressed what I felt. I had the impression that the point was not really discussed and therefore contributed to this issue.
You could say that an issue tracker is not the right place for such a discussion, and maybe you're right. But it certainly is a place to get in touch with people who have the ability to actually change the code.

The way I understand the situation is:
- weak hash detection is not intended to work outside dictionary mode
- if it has ever done so, it was likely due to the initial bug described in this issue (because the empty hash was not reported as such, but instead as a single-character password)

If this is right, my suggestion is:
- evaluate if the limitation to dictionary mode is _reasonable_ (no matter how hard it might be to change it. We should just ask "does it make sense?" For me, I answered this question with "no", which is why I commented).
- evaluate if the hashcat team _wants_ to change this behaviour. It is nice to have the option to contribute to a project, but the "core team" should be willing to accept such a contribution. This is what I would like to find out.
- evaluate how hard it would be to actually change it and then maybe someday implement it.

I hope this clarifies my point. Again, I didn't want to attack anybody. I am incredibly grateful for everyone working on hashcat, I just see that it could use some usability improvements here and there.

**Comment by matrix** [comment]
I'm sorry but I'm not understanding you. This is the third time we're telling you that implementing it inside the program is much more complicated than using it as we've shown you. Since we are the developers all along and since you can't evaluate it yourself, you should at least trust what we say.

That said if you want to continue to discuss this fact, I ask you the kindness to use discord.

Thank you and have a nice day :)
