### ISSUE TITLE
Outfile to support username

### ISSUE THREAD

**Issue by roo7break** [hashcat/hashcat#437]
If --username is in use, could outfile support something like:
- $username:$hash:$plaintext
- $username:$plaintext

**Comment by philsmd** [comment]
I think this should answer the question about how the output can be formatted (and include the username/email etc):
https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_can_i_show_previously_cracked_passwords_and_output_them_in_a_specific_format_eg_emailpassword

This is a question listed within the "frequently asked question" wiki for good reason, i.e. because it was answered already thousands of times within the forum/irc/pms etc.
Maybe this kind of questions fits better on hashcat's forum, instead of a github issue, dunno.

(and you need to use --show, because some users prefer not to have the username within the "normal" output even if --username was specified, they only want to get rid - quickly load - the hash lists)

**Comment by roo7break** [comment]
Thanks for this. Happy to close. 

Nikhil Sreekumar

**Comment by philsmd** [comment]
Thanks for the confirmation. But YOU (or a github user with special priviledges for this repository) needs to close this ticket. Can you close it, please?

Thank you very much
