### ISSUE TITLE
Cracked hashses removed from potfile

### ISSUE THREAD

**Issue by roo7break** [hashcat/hashcat#438]
I am using --potfile and --session for each instance of cracking job. When using -a 0, and switch dictionaries, the previously cracked hashes are removed from potfile (basically resettting it back to 0). 

It would be good if the --potfile merges hashes each time its run. This will help keep all cracked hashes associated with each job in a single potfile. 

Note: I did not use --remove to remove the raw record.

**Comment by philsmd** [comment]
There is no such concept implemented within hashcat such that "hashes are remove from potfile".
The hashes always get appended to the potfile (it won't get overridden, delteted etc)

Can you provide a full example such that it is easier to understand how to reproduce this and what you mean in detail. A minimal step by step example would be perfect, including the content of the potfile after each cracking step.

BTW: there is also the (new) --potfile-path parameter that allows you to specify a very specific potfile (if you have many .pot files, the default one is "hashcat.pot").

**Comment by roo7break** [comment]
Hi,

The simplest way to reproduce is:
- start with potfile-path, session, m 1000, a0, and a word list. 
- once word list is exhausted, add a rule to above command, -r toggle4.rule. 

Just before the "Cache-hit dictionary stats" comes up an info message is printed on screen saying "Removed X hashes found in pot file". 

Thanks and Regards

Nikhil Sreekumar

**Comment by philsmd** [comment]
That sounds about right. Nothing wrong about that.
This behaviour is exacly like it was intended and it seems that it is working correctly.

BTW: you can use --show to display all the cracks (but this is nothing new, it was working exactly like this since years, e.g. already shown cracks won't be outputted again and again and again... which would be kind of useless - at least in most of the cases -), you can use --potfile-disable if you don't want to "remove hashes that are part of the current cracking job but are present in the potfile because already cracked"

**Comment by jsteube** [comment]
So, can we close this?

**Comment by jsteube** [comment]
No response here, closing

**Comment by Aspect9** [comment]
where is the hashcat pot file located? beat me?

**Comment by kenji21** [comment]
see https://hashcat.net/forum/thread-6299.html : ~/.hashcat/hashcat.potfile
