### ISSUE TITLE
Salt length limit of 50 (55 actually) for HMAC-MD5 (key = $pass) -m 50

### ISSUE THREAD

**Issue by bovineLord** [hashcat/hashcat#440]
I'm trying to bruteforce a HMAC-MD5 has of a string of text length 50-100 characters. (Custom application)

Here's the sample hash file (the key is "hash")

```
3c6a3284c47d6a1b73167af9fa56cc4f:123456789012345678901234567890123456789012345678901
2e714ab859aeb116a3c36dfd24da9e37:1234567890123456789012345678901234567890123456789012
97c83e666ded0f73bca104badc080221:12345678901234567890123456789012345678901234567890123
134c2855930a353ea2a06d32d483ffd2:123456789012345678901234567890123456789012345678901234
c0ba88acf8b0d9c26d2fce8e6e70a3b9:1234567890123456789012345678901234567890123456789012345    
e835fa57c623ca65f2d57f4e0037aa55:12345678901234567890123456789012345678901234567890123456    
9eea309517e795406ac30863359af477:123456789012345678901234567890123456789012345678901234567   
17af88fe6c79e9aa289c63cfc29b1d6b:1234567890123456789012345678901234567890123456789012345678  
f4310eeb9ab386d51041bbac9a88c909:12345678901234567890123456789012345678901234567890123456789 
bcda3a7f8bcfda01eef95dff4e9ff553:123456789012345678901234567890123456789012345678901234567890
```

Initially it failed to load with line length issues, i 'fixed' this by modifying shared.c hmacmd5_parse_hash function and created a "DISPLAY_LEN_MIN_70" (Changed char limit to 71, slowly pushing). This allowed me to load the above hash.

```
./hashcat -m 50 test.hash -a3 ?l?l?l?l
```

This gave me results for the hash up to 55 characters. Anything above cannot be hashed properly. What can be done to push this limit to 110 chars ? (Looking to double it.) From what I read this 55 is the limit of a 'block' ?

**Comment by philsmd** [comment]
Well, you would need to modify the kernel to make more than 1 transforms.

The best way would be to use the current kernel - the fastest - to run (as currently implemented) 1 single transform for all password + salts <= 55 ... but have a modified kernel to make exactly 2 transforms and only allow  a total length (password length+salt length) > 55.

A different approach would be more flexible (but probably also much, much slower) is to use a random number of transforms (i.e. implement a single kernel which allows both 1 transform or 2 transforms).

The first approach should of course be prefered. In general, both modified approaches/kernels will be much slower as the current kernel (because more and - if you choose approach 2 - flexible amount of transforms, which of course is a performance killer).

I don't think that this should be implemented by the hashcat devs and committed to this repository, since > 55 passwords are fortunately still kind of rare and because of the speed drop (which will be unavoidable even if the passwords are less than 56).

If the algorithm is used within a specific software/cms/forum software etc, the story is different because it can be implemented as a specific algorithm with specific limits and not as a general algorithm like -m 50 (were speed is the most important factor).

Thanks

**Comment by jsteube** [comment]
If this requires a special kernel, we should name as such. Please open a new Ticket while following this: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this
