### ISSUE TITLE
Hashtype 21 (osCommerce, xt:Commerce) length error

### ISSUE THREAD

**Issue by hack4sec** [hashcat/hashcat#445]
Hello. If try crack hash from xt:commerce, HC write length error, but length is right. For demonstrate you can get example hash from here https://hashcat.net/wiki/doku.php?id=example_hashes
HC write what example hash and any hashes from work xt:Commerce have wrong length.

**Comment by philsmd** [comment]
I can't reproduce this at all.

Maybe the lines have some trailing spaces etc?

If not, what is the command line (and content of the input files) you use ?

**Comment by hack4sec** [comment]
Sorry for less information. Win7, ATI, HC2 and HC3. "75D60B9507A4BCB20DDD0F3ADCAA47E7" - target hash, "374996a5e8a5e57fd97d893f7df79824" - hash of alg 21 from wiki. 

HC2

> C:\hc2>oclHashcat64.exe -m21 -a0 75D60B9507A4BCB20DDD0F3ADCAA47E7 tmp.txt
> oclHashcat v2.01 starting...
> 
> WARNING: Hash '75D60B9507A4BCB20DDD0F3ADCAA47E7': Line-length exception
> 
> ERROR: No hashes loaded
> 
> C:\hc\hc>oclHashcat64.exe -m21 -a0 374996a5e8a5e57fd97d893f7df79824 tmp.txt
> oclHashcat v2.01 starting...
> 
> WARNING: Hash '374996a5e8a5e57fd97d893f7df79824': Line-length exception
> 
> ERROR: No hashes loaded

HC3:

> C:\hc3>hashcat64.exe -m21 -a0 75D60B9507A4BCB20DDD0F3ADCAA47E7 tmp.txt
> hashcat (v3.00-1-g67a8d97) starting...
> 
> WARNING: Hash '75D60B9507A4BCB20DDD0F3ADCAA47E7': Line-length exception
> 
> ERROR: No hashes loaded
> 
> C:\hc3>hashcat64.exe -m21 -a0 374996a5e8a5e57fd97d893f7df79824 tmp.txt
> hashcat (v3.00-1-g67a8d97) starting...
> 
> WARNING: Hash '374996a5e8a5e57fd97d893f7df79824': Line-length exception
> 
> ERROR: No hashes loaded

**Comment by philsmd** [comment]
Since the algorithm of -m 21 = osCommerce, xt:Commerce is "md5 ($salt . $pass)" you need both the hash and the salt to recover the password. This means that the input hash line, like with most other salted hashes, needs to have a salt part, in this case delimited by a colon ":".

The example on the wiki page clearly says that the input includes a salt (the ":36" in this very particular case, meaning: delimiter ":" followed by the salt "36"):

`21        osCommerce, xt:Commerce         374996a5e8a5e57fd97d893f7df79824:36`

The ":36" is not optional, instead is some crucial information, the salt, that is needed. You can't simply skip it and just say that hashcat doesn't accept it and that the example hash is wrong or hashcat has a bug.
The algo is md5 of the password **and** the salt, so hashcat needs both.

I would say this should be close because I don't see any problem here (except this misunderstanding from your side), don't forget to close the ticket if you agree.

Thanks

**Comment by hack4sec** [comment]
Oh, sorry, i thinked 36 it`s a password. Closing ticket.
