### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by aress31** [hashcat/hashcat#451]
Hi,
Could you add a support for using wildcard with hashcat? 
I have let's say 100 wordlists under my wordlist folder, no matter the type of attack I use -a 0, -a 6, etc. I would sometime want to use all my wordlists at once (one running session of hascat) without the hassle to create a big wordlist containing all my wordlists. 
At the moment, I have noticed that using the -a 0 its possible to use a wildcard to run all the wordlists at once, but it isn't the case with the other type of attacks (-a 6 or -a 7 for example, see the output below).

```
.\hashcat64.exe -m 1000 -a 7 --increment --username "AD_dump.txt" ?a?a?a?a .\wordlists\*
hashcat (v3.00-1-g67a8d97) starting...

Usage: C:\Utils\Hashcat\hashcat64.exe [options]... hash|hashfile|hccapfile [dictionary|mask|directory]...

Try --help for more help.
```

Best regards,
Alex

**Comment by philsmd** [comment]
it's possible to specify a directory instead of several files (also for -a 6 and -a 7).
The reason why hashcat doesn't allow wildcards with attack type 6 and attack type 7, is that the format is:
-a 6: dict/directory mask
-a 7: mask disk/directory

If we allow the use of wildcards, we also need to allow much more command line parameters (and random number of those parameters) because the shells (in general) do the file globbing beforehand (even before the hashcat process starts).
For attack type -a 0 it is more or less straightforward, the user can append as many command line parameters (i.e. dicts/directories) as he wants to... but for -a 7 and especially -a 6 it is different, because somewhere the user needs to specify the mask too. In case of -a 6 the last parameter must be the mask.
In addition to that, what should happen if the user specifies several wildcards within the same command?

`E.g. -a 6 dir1/*.txt --increment dir2/*.dict ?a?a?a?a`

or something like this.... It makes the parsing of the command line much more complicated.

I think the directory support should work in most cases, so just try to specify the path to the directory instead of using a wildcard.

**Comment by aress31** [comment]
Understood! :)
An other question in the same line. Why not having only one hybrid attack mode instead of two (-a 6 and -a 7). The relative position of the mask to the wordlist should be easy to parse, isn't? 
For example using
`hashcat -a hybrid_attack_id hashes.txt wordlist mask`would result in wordlist+mask
and
`hashcat -a hybrid_attack_id hashes.txt mask wordlist`would result in mask+wordlist

**Comment by roycewilliams** [comment]
To reduce the complexity caused by positional parameters, could there be specific flags for dictionary files (--dict) and masks (--mask)? They could be specified more than once (just like -r for rules). Would that help?

For backwards compatibility, the default behavior today could be preserved, with the new flags just  disambiguating if needed.

**Comment by aress31** [comment]
> it's possible to specify a directory instead of several files (also for -a 6 and -a 7).

@philsmd I have tried to give a directory instead of wordlists files and it did not work.

**Comment by jsteube** [comment]
Such a feature makes the program unnecesarily complicated. Note that this needs to be maintained over time, too. It makes even less sense since you can do that yourself. Just do cat whatevermask\* > outfile.txt and then use outfile.txt.
