### ISSUE TITLE
Feature Request: Default-on plain output file

### ISSUE THREAD

**Issue by mubix** [hashcat/hashcat#468]
The POT file is great, but parsing it to create a dictionary isn't straight forward, especially if you have cracked multiple types. Having a default on file write (append) for just the found passwords be awesome and make doing #466 simple.

**Comment by ghost** [comment]
You can already do this using by specifying an output file (--outfile) and an outfile format as plain (--outfile-format 2).

**Comment by mubix** [comment]
@usernamestaken aye, knew about those, just was looking for something that was always on and always appending. Updated the title to reflect (wrote this last night from my phone, sorry for not being more succinct :(

**Comment by redongh** [comment]
@mubix while your particular usecase might make it appear more useful to have only the passphrase written to the .pot-file others (such as myself) may prefer different settings for their particular usecases. thats where configurable defaults or user-scripts that contain your favorite parameters come in handy.
changing such default behaviors involves the risk of breaking established workflows and tools reflecting such so I'd be rather hesitant on such change request, especially since as @usernamestaken just suggested the desired behavior is already implemented, working and accessible through `--outfile` and `--outfile-format 2` parameters .
maybe configurable defaults might be a good idea, say by specifying something like a `hashcat.defaults` file that hashcat reads if present in its working-dir where certain parameters can be pre-set in a custom manner like suggested in #469. what do you think about such feature?

**Comment by jsteube** [comment]
I'm not going to change the default, because there's too many workflows depending on that output-file format, as @redongh already mentioned. Therefore I'm going to close this issue. 

However, here's another approach that you might find useful, by adding --show into the mix:

Your command, as however you do it or did it:

```
root@ht:~/hashcat# ./hashcat example0.hash example.dict
```

Now create the wordlist:

```
root@ht:~/hashcat# ./hashcat --show example0.hash -o outfile --outfile-format 2
hashcat (v3.10-3-g13cbe42) starting...

root@ht:~/hashcat# cat outfile    
13LEXON
```
