### ISSUE TITLE
config file for default parameters?

### ISSUE THREAD

**Issue by thesle3p** [hashcat/hashcat#469]
Hi would it be possible to make for hashcat to accept a config file of parameters we frequently pass to hashcat? Like instead of having to pass which OpenCL device types to use  or tuning settings  for a brute force (charset,--increment, etc) every time we want to take a pass at a hash/hash list why not let us define that info in a config file to be prepended to what ever other settings we pass hashcat?

**Comment by jsteube** [comment]
I don't like the idea mostly because I don't want to write a configfile parser. Is there any good libraries for pure C?

**Comment by thesle3p** [comment]
https://github.com/benhoyt/inih inih might do the trick.

**Comment by matrix** [comment]
You can use a script for run hashcat with your custom parameter (see
examples).
Add a config parser is not a good idea (for me).

Bye,
matrix

**Comment by neheb** [comment]
Bashrc is an option as well

**Comment by jsteube** [comment]
I was discussing with @philsmd about this. Here's some important argument collected:
- The use for such a configfile could be worked around in linux using bashrc/alias, but that would reduce it to linux and maybe OSX. Windows users couldn't do it.
- We often have reports like "hashcat did not crack hash XY", but in almost all cases it turns out the problem is the user, not hashcat. In case we have a user who changed for example --markov-threshold to 2 in the config and then wondering why hashcat isn't cracking the hash of which he knows the password, we couldn't see it from him posting only his commandline. We would need to have some "display" of the changes values in the config file on startup but that would only solve the problem if the user posts it. Most poeple will post only the commandline. It would be also ugly, from a design perspective.
- The .restore system could be broken if the user changes the configfile. A theoretical solution to this would be to store some checksum of the config settings with the .restore file and check it in a restore case and complain if it doesn't match. but it's very likely the user can not restore the config file to exact the same one as it was before. We could also store all the settings but that would create some larger change to the restore system at all

**Comment by thesle3p** [comment]
Why not have it ignore config files unless otherwise told to?

**Comment by homes32** [comment]
IMHO for this sort of thing its better to script using batch/bash/etc (you could even accept input before building the hashcat cmd line and executing) or use another tool like Hashacat-GUI (which remembers your options) then to build a config parser into hashcat at this point.
