### ISSUE TITLE
Add support for LUKS - Linux Unified Key Setup

### ISSUE THREAD

**Issue by AllanDaemon** [hashcat/hashcat#481]
When I meet the project I was really expecting to have a LUKS implementation, which surprisingly don't.

LUKS - Linux Unified Key Setup, is used to encrypt partition, full disks and others and is build directly into Linux kernel. It's similar to TrueCrypt/VeraCrypt - which is supported by the Hashcat. As base it uses PBKDF2 / SHA hash. So the the foundation algorithms are already implemented,  and should be fairly easy to implement.

The GPL'ed hashkill supports it (https://sourceforge.net/p/hashkill/code/HEAD/tree/src/plugins/).

**Comment by Gnoxter** [comment]
To extract the key material from any  LUKS header these four hash primitives are needed: SHA1, SHA256, SHA512 and RIPEMD160

I'm not particularly familiar with the hashcat code, but it is my understanding that hashcat does not offer these as simple to use primitives on the host. This would be a prerequisite. 

For the cracking and comparison it needs PBKDF2 with the primitives above and custom iteration count, the symmetric encryption cipher + mode that is used for the FDE. Additionally it needs the hash primitive used for key extraction again, which is always identical with the one used for the PBKDF2. By default this is  aes-xts-plain64 with SHA256 as far as I know. 

From my brief code reading I learned that all the hash primitives and the specified ciphers (aes256, serpent, twofish) are available as OpenCl kernel even as xts modes. But only as -plain not as -plain64 if I understand correctly.

w.r.t hashkill I looked at the luks-plugin and its incomplete/nonfunctional and since its GPL code reuse would not be possible due to License incompatibility.

For reference, the current LUKS specification can be found here: https://gitlab.com/cryptsetup/cryptsetup/wikis/LUKS-standard/on-disk-format.pdf

**Comment by matrix** [comment]
I'm working on that :)

**Comment by Gnoxter** [comment]
@matrix That is great news, because something just disappeared from my to-do list. Looking forward to it!  Hit me up if you need someone to test things.

**Comment by jsteube** [comment]
Support for LUKS has been added. See this thread for details: https://hashcat.net/forum/thread-6225-post-33187.html#pid33187
