### ISSUE TITLE
Possibility to view sample

### ISSUE THREAD

**Issue by drSnuggl3s** [hashcat/hashcat#492]
Hey,

Would it be possible to extend the status menu (when running HC) with the possibility to view a sample of current word/password being tested?

Sometimes you just want to get a feeling if your combination attack with a left join is worth continuing. I'm aware you have the --stdout option.

drSnuggl3s

**Comment by jsteube** [comment]
- That makes no sense for masks, since hashcat uses position-dependant markov-chains anyway. IOW, it's not starting with AAA and ending with ZZZ. It could be G5! and next would be _T4, depending on the training data.
- That makes no sense for wordlists, as they are not processed linearly. On GPU, they are run in parallel. The Host can not know which one is processed at time the user requests an status update.

Please close the issue.

**Comment by drSnuggl3s** [comment]
Ok I think you misunderstood the request but I respect your opinion.
