### ISSUE TITLE
[feature request] option to crack duplicate hashes in list

### ISSUE THREAD

**Issue by thesle3p** [hashcat/hashcat#509]
Any chance of adding the option to waive hashcat's default behavior of expunging duplicate hashes in a list before cracking? not knowing how many time the same hash was in a list can get in the way of generating  statistics post-crack.

**Comment by roycewilliams** [comment]
Hmm - to clarify, as part of this feature, it sounds like you'd want hashcat to:
1. Only attempt to crack one of the duplicates, ignoring the others but accumulating a count of them in some way (otherwise, there would be a massive waste of RAM and processing power), and ...
2. After a hash is cracked, write all duplicate plains to the potfile, so that statistics could be derived directly from the potfile?

I think this is probably not what @jsteube et al will want to do. Removing duplicates keeps the code simple, keeps GPU RAM usage low, etc.

Also, it is trivial to script taking an original hash frequency count and a potfile and generate the statistics. I don't know of a published script, though - it would be nice to have a reference implementation. 

What are you currently doing to get the statistics that you need?

**Comment by thesle3p** [comment]
Currently I Do as you suggested and count hash frequency in the hash list but it would be nice if I could --show --outfile-format 2 -o /path/to/file  a hashlist and pass that to pipal to get frequency count along with pipal's other stats .

-----Original Message-----

**Comment by jsteube** [comment]
Technically it's not much of a problem, because I could mark the number of duplicates per hash in the hashes_t structure. But what I think is confusing is that when hashcat cracks such a hash, what should it do. Should it print the hash N times? That could confuse new users here alot, because they wouldn't expect it. Also, hashcat is a cracking tool, not a statistics generator. As @roycewilliams already said, it should be trivial to do what you want to do from an external script.

**Comment by thesle3p** [comment]
Why not just make it a option that is not turned on by default? I am
just asking that a feature be added to make generating output suitable
for generating statistics easier.

**Comment by roycewilliams** [comment]
I see the appeal. If hashcat optionally accumulated the duplicate count on intake, the duplicate count could be part of an output format, such as:

 16 | duplicatecount:hash[:salt]:plain:hex_plain

@jsteube, would accumulating that duplicate count slow hash loading/dedupe much?

**Comment by thesle3p** [comment]
I was thinking something  more along the lines of a optional --no-dedupe
(maybe change the name) that skips the duplicate check/removal process.
Realistically you would only use this to compare potfile entries to a
hashlist to output all plaintext values of that hashlist after you are
done cracking (maybe have the --help entry specify that if you are
worried about people using that by accident)
, for that wouldn't performance be irrelevant?
