### ISSUE TITLE
Certain File Paths Not Working on Mac

### ISSUE THREAD

**Issue by andrewvaughan** [hashcat/hashcat#510]
Spaces and/or parenthesis cause hashcat to fail.

The `example0.sh` trial worked fine on my machine in the `/tmp` folder, but being run in the `/Users/andrew/Dropbox\ (Personal)/Password\ Encryption\ Tests/hashcat/hashcat-mac/OpenCL` folder caused this error:

```
Initializing device kernels and memory...

ERROR: /Users/andrew/Dropbox\ (Personal)/Password\ Encryption\ Tests/hashcat/hashcat-mac/OpenCL: No such file or directory



ERROR: clSetKernelArg(): CL_INVALID_KERNEL
```

**Comment by magnumripper** [comment]
FWIW: We had a similar problem with JtR recently, that was with `-I /some/path` given to the OpenCL run-time compiler. We now simply enclose the whole path with quotes.

EDIT: It seems that was handled differently in #432.

**Comment by jsteube** [comment]
This is a huge chaos with the -I parameter, because each runtime handles it differently. And by each runtime I mean even different versions. For example the AMD OpenCL runtime < 15.12 understood what a quote it, but the new one based on amd-gpu-pro does not longer. That's why the best workaround I found so far is to chdir() to the folder where the .cl sources are and that's what's hashat is doing atm. That's why I don't understand @andrewvaughan issue here unless he's using an older vresion. 

@andrewvaughan Please try with latest version from github and close the issue if fixed.
