### ISSUE TITLE
Progress and time estimated with --increment option

### ISSUE THREAD

**Issue by Etienne-gh** [hashcat/hashcat#562]
Hi, 

For the moment, when you launch bruteforce with --increment, the status shows the progress and time estimated for the current mask.
It could be nice to change this behavior to show whole session progress and time estimated.
Is there a good reason for this current behavior?

**Comment by magnumripper** [comment]
Personally I like the current behaviour better. I even saw to it that JtR works the same way when using -mask with a length range. Just my two cents.

Specifically, it helps dealing with the "exponential wall" without calculating beforehand. If you are at eg. length 9 and see that it will complete within a day or two, you keep it running. If (using a slower hash) it says it will take three months, you quit and reduce the keyspace.

**Comment by jsteube** [comment]
There's also a technical reason for this. That is because hashcat can not now how fast an attack really is before actually running it. That is because in mask-mode, the mask has to be split in two parts internally and it depends on different factors at which position to split it. That means with a chaning mask (due to increment) the split point changes and if the split point changes, the performance changes. If the performance changes the time estimation changes.
