### ISSUE TITLE
--quiet options silences everything *except* cracked password output

### ISSUE THREAD

**Issue by magnumripper** [hashcat/hashcat#569]
While cracking a humongous list of hashes, I noticed the screen output of every cracked password was slowing HC down to a crawl. I re-started the job with the --quiet option, assuming it would mute that output but to my surprise most everything BUT that was muted.

Is there some other way to achieve this? Could we change the meaning of --quiet or could we add some new option that just mutes cracked password output? I can make a PR but I'm not sure what solution you'd like.

**Comment by epixoip** [comment]
I've always used ''-o /dev/null'' to accomplish this ever since hashcat got potfile support.

**Comment by jsteube** [comment]
The output of a cracked hash to stdout, even in combination with --quiet, is the wanted behavior if you do not specify -o. The event of a cracked hash is too important to get lost/unnoticed. It also goes back to the time when we did not had --machine-readable, the --quiet option was used to help to reduce the number of output to skip/ignore in case output was used from a script. Anyway if you use -o the output should be totally quiet. I think we shouldn't do a change at this point.

The thing with the slowdown is different. There's a couple of things that need to be done when we have a cracked hash and they all slow down the process. I always thought that's ok, because a cracked hash is a rare event. For one, a mutex gets active and blocks all other threads to output more cracked hashes. But I think the biggest slowdown is that the output file is opened and closed every time a new password is cracked. Reason here is that we want to allow the user he can remove the output file safely while hashcat is running. If there's a better solution that allows us to keep the fd open I'm open to change this, but it should support the case that the user removes the outfile while hashcat runs.

**Comment by magnumripper** [comment]
I didn't realize I could use -o for this (in fact I didn't realise the difference between output file and pot file). I'll try using `-o /dev/null`
