### ISSUE TITLE
Support skip and limit options for mask file

### ISSUE THREAD

**Issue by Ins1ghtLabs** [hashcat/hashcat#572]
It would be great if hashcat would support using skip and limit options per mask for mask file.
For example:

line 1 : ?l?l?l?l?l?d?l?l?l?l,100000,10000000
line 2 : ?u?u?l?l?l?l?l?l?l?l,1000000,500000
...

This would allow better distribution to be carried by splitting masks with large keyspace into smaller chunks and evenly distribute the work load using mask files.

**Comment by Ins1ghtLabs** [comment]
Seems I need to somehow add additional parser in mpsp.c and change status_ctx->words_off and 
status_ctx->words_base when the job is starting.

**Comment by Ins1ghtLabs** [comment]
Pull request:
https://github.com/hashcat/hashcat/pull/574

**Comment by magnumripper** [comment]
What's the reason you ended up using `|` instead of `,`? Just curious.

**Comment by Ins1ghtLabs** [comment]
@magnumripper because it's easier to use '|' than ',' , so I won't have to write code to figure out whether that part is a custom charset or mask or skip/limit number, or touch the mask parsing logic.

**Comment by jsteube** [comment]
I don't like this alot, because it creates some inbalance. It would enable to set -s and -l for an iterated attack, but only for one special. For example, this would not work to set -s and -l for a folder full of wordlists, which hashcat supports and which is also an iterated attack.

OTOH I don't see a reason how this helps in a distributed solution. In such a scenario, there should be no iterated attack at all, because it becomes hard to control.

**Comment by Ins1ghtLabs** [comment]
"For example, this would not work to set -s and -l for a folder full of wordlists, which hashcat supports and which is also an iterated attack."

Which attack mode is this? can you elaborate?

**Comment by jsteube** [comment]
Like, every attack that support wordlist also supports wordlist folders, except -a1. 

See here:

```
root@sf:~/hashcat# cat hash
7f306bca1a462127e59b9154599c443a
root@sf:~/hashcat# cat wordlist1.txt 
word1
root@sf:~/hashcat# cat wordlist2.txt 
word2
root@sf:~/hashcat# ./hashcat hash *.txt --quiet                       
7f306bca1a462127e59b9154599c443a:word2 
root@sf:~/hashcat# 
```

That means if we change support for -s and -l we should change it for all attack modes, otherwise this creates confusion. 

On the other hand I still don't see why we should need this in case of a mask file. I see that loading a large hashlist will take time, and restarting hashcat will create some overhead then. But having a large hashlist means you're trying to crack a fast hash, not a list of scrypt hashes. But fast hashes and small masks - this is a waste of time anyway. What I means is there's a misconception here if you try to distribute workload of fast hashes with small masks. This would make sense only if you want to crack a slow hash, but for a slow hash you wouldn't try to crack a large hashlist. Currently, when you use a large mask, the total runtime of the session will take longer and then it will make sense to hashcat to restart and to reload the hashes.

Finally, the implementation is kinda buggy. For example:

line1: ?u?d?d?d?u?d?d?d|30000|20000

Then how could a user create a mask that includes the prefix |30000|20000? Currently this mask would be a valid mask, for good reason. The currect implementation would either be to move those options to the left and create two special (optional) columns for it. Or as alternative, since hashcat has good support for escape characters, why not simply continue to use "," as separator character. If the user actually wanted to use "," as a fixed character in the mask he can escape it. Either way, that's just implementation. The main reason I don't want this is the one state above.
