### ISSUE TITLE
Feature Request: Multiple Truecrypt Containers at one time

### ISSUE THREAD

**Issue by shuckitup** [hashcat/hashcat#575]
Hi,

I know that hashcat is now open source, but unfortunately my coding skills don't allow me to attempt to try this myself. 

It would be great if we could upload multiple Truecrypt containers at one time. I envisage that it may operate something similar to the way Hashcat can parse multiple .hccap files. Would it be possible for us to drop the first 512 bytes of each container into a single file with some type of separator character and load it into Hashcat and have it parse it as multiple hashes to attack at the same time?

Thanks for a great bit of software and for all your hard work.

**Comment by jsteube** [comment]
In theory yes. But this would create some coding effort that I don't really see the sense of it. There's absolutely no performance benefit here. The time it takes would simply multiple by the number of TC volumes you try to crack, like with every salted hash. The difference is that other salted hashes do not come in binary form. So the correct way to implement this would be to rewrite the truecrypt (and so also the veracrypt) parser so that it reads a hash by parsing a hashline, but that would also require some truecrypt2hashcat preloader. I mean this is all possible, but as I said it only creates effort without any benefit so why do it?

**Comment by jsteube** [comment]
No response from OP, closing
