### ISSUE TITLE
WPA mac addresses "flip flopped" in potfile

### ISSUE THREAD

**Issue by vom513** [hashcat/hashcat#586]
What I mean is - when cracking foo.hccap - I may get something like:

foo:001122334455:66778899aabb:password123

But sometimes the crack runs again, and now I have:

foo:001122334455:66778899aabb:password123
foo:66778899aabb:001122334455:password123

It seems that the ordering of client vs. AP mac is not predictable.

**Comment by jsteube** [comment]
You mean, on the same hccap or a different one?

**Comment by vom513** [comment]
Same hccap.  Essentially the crack can run up to two times for the same "hash".  The ordering of the AP and client MACs seem to make it think they are unique hashes, hence the second run.

**Comment by magnumripper** [comment]
Sounds more like a cap2hccap problem

**Comment by pascalqq** [comment]
I hava found this prob since hashcat 2.x.
The display of the AP and client MAC not always in one order.

**Comment by jsteube** [comment]
I'm not certain how the hashes are converted (using cap2hccap) exactly, so it could be like @magnumripper said. Only thing I can say is that hashcat does not longer change the ordering of the mac addresses since v3.00. Here's a snippet from the changes:

> Fixed a bug in implementation of WPA/WPA2: MAC and nonce stay one their original position as in the hccap file

Also note that it's possible you have two handshakes (or more) with the same essid and mac addresses in your hccap dump. You should check if the file is of exactly 392 byte. If that's the case, please send me all data and commandline options I need to reproduce this case and I'll fix it.

**Comment by vom513** [comment]
I see the changelog entry for 3.00.  It could be that I still have some entries in my potfile(s) that have the 'old' ordering, therefore it's not matched on the new (stable) logic in 3.00.

I've just manually edited my potfile to remove all the entries for my test network and recracked it.  After this I've ran hashcat many times against it and it seems to reliably match from the potfile and not recrack.  Looks like the fix was in 3.00 and my potfiles just have 'old' entries.  Sorry for the noise.
