### ISSUE TITLE
cppcheck results

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#594]
https://gist.github.com/neheb/90a5147fd445d8aa57f9ff48aaac2a1f

ran with: cppcheck --enable=all --inconclusive --std=posix -Iinclude/ --force -IOpenCL/ . 2> err.txt

Not everything is an issue given that it was ran with everything enabled.

**Comment by jsteube** [comment]
So far, I've fixed everything (and more) that looked like a real problem. 

There's two error types left that I find somehow invalid:

> Obsolescent function 'usleep' called

I really don't see any reason why to change that. There's no sign of deprecation or whatever. Also it's ideal for us, because both linux and windows have it.

> Resource leak

This is kind of an error report. For example, the first one:

```
[src/cpu_crc32.c:95]: (error) Resource leak: fd
```

I've tracked this down. 
- It's totally not related to any FILE\* so I don't know why it calls the variable "fd". This error repeats
- It complains about the fact that some memory was allocated but the function returned without free() it. That would be ok to complain unless in an error case. We explicitely check with VERIFY_PTR if the memory allocation was successfull and only if not we return. I mean, what else can we do?

> [src/dispatch.c:434]: (style) The scope of the variable 'words_off' can be reduced.

I could fix this pretty easy but I had a nice idea how to rewrite that entire section to be more easy to read. But not before the release, so let it here as kind of a marker.

**Comment by neheb** [comment]
Man page says: 

4.3BSD, POSIX.1-2001. POSIX.1-2001 declares this function obsolete; use nanosleep(2) instead. POSIX.1-2008 removes the specification of usleep().

But yes I agree. It's not much of an issue. It's the std=POSIX parameter that checks that.

**Comment by jsteube** [comment]
OK, good to know. Any reason to let this issue open?

**Comment by neheb** [comment]
Closing when I get home.

**Comment by neheb** [comment]
Looks good
