### ISSUE TITLE
Request to add --limit support to markov attack mode

### ISSUE THREAD

**Issue by recon-ng** [hashcat/hashcat#607]
There currently seems to be no way to exert fine control over the number of candidates markov attacks test. At long mask lengths (13+) a change of 1 in the value of -t results in many-fold differences in the number of candidates generated.

**Comment by jsteube** [comment]
There's no way to do a more fine grained control due to fast hashes
compatibility. What I'm trying to say is that we can not "reject" a
candidate in-kernel, therefore no such mechanism will work.

OTOH, masks of length 13 are kind of bad, too (except if parts of them
are static). You should try to optimize your attack.

Also note that you can use any markov generator of your choice, just
pipe it into hashcat. For slow hashes that should be fine, for fast
hashes maybe add some rules.

Please close the issue.

**Comment by recon-ng** [comment]
Interesting. Thanks for the reply.
