### ISSUE TITLE
Truecrypt examples fail to crack.

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#610]
*hashcat (v3.10-687-gcb6e210)
*Ubuntu 16.04 Server
*Kernel 4.4

I noticed this today when I was testing out my own truecrypt container as it failed to crack besides knowing the encryption and password which lead to the following....

of the 34 truecrypt examples listed, only 8 of them crack.

true_test/hashcat_ripemd160_aes.tc:hashcat
true_test/hashcat_ripemd160_twofish.tc:hashcat
true_test/hashcat_sha512_aes.tc:hashcat
true_test/hashcat_sha512_twofish.tc:hashcat
true_test/hashcat_whirlpool_aes.tc:hashcat
true_test/hashcat_whirlpool_twofish.tc:hashcat
true_test/hashcat_ripemd160_aes_boot.tc:hashcat
true_test/hashcat_ripemd160_twofish_boot.tc:hashcat

I've zipped up a batch script and all the tc examples for you to check out, just drop it into the root of hashcat dir, extract and run ./tc_test.sh

[truecrypt_test.zip](https://github.com/hashcat/hashcat/files/605340/truecrypt_test.zip)

**Comment by jsteube** [comment]
Hey and thanks for your report!

I was really wondering about, because TrueCrypt is such an important algorithm. Anyway I tried to reproduce, but I can not. I'm using kind of the same system for tests:

*hashcat (v3.10-800-g7ca6a45)
*Ubuntu 16.04 Server
*Kernel 4.4

I've run the tc.test.sh and it cracked all 30/30 files, here's the log:

```
true_test/hashcat_ripemd160_aes.tc:hashcat
true_test/hashcat_ripemd160_serpent.tc:hashcat
true_test/hashcat_ripemd160_twofish.tc:hashcat
true_test/hashcat_ripemd160_aes-twofish.tc:hashcat
true_test/hashcat_ripemd160_aes-twofish-serpent.tc:hashcat
true_test/hashcat_ripemd160_serpent-aes.tc:hashcat
true_test/hashcat_ripemd160_serpent-twofish-aes.tc:hashcat
true_test/hashcat_ripemd160_twofish-serpent.tc:hashcat
true_test/hashcat_sha512_aes.tc:hashcat
true_test/hashcat_sha512_serpent.tc:hashcat
true_test/hashcat_sha512_twofish.tc:hashcat
true_test/hashcat_sha512_aes-twofish.tc:hashcat
true_test/hashcat_sha512_aes-twofish-serpent.tc:hashcat
true_test/hashcat_sha512_serpent-aes.tc:hashcat
true_test/hashcat_sha512_serpent-twofish-aes.tc:hashcat
true_test/hashcat_sha512_twofish-serpent.tc:hashcat
true_test/hashcat_whirlpool_aes.tc:hashcat
true_test/hashcat_whirlpool_serpent.tc:hashcat
true_test/hashcat_whirlpool_twofish.tc:hashcat
true_test/hashcat_whirlpool_aes-twofish.tc:hashcat
true_test/hashcat_whirlpool_aes-twofish-serpent.tc:hashcat
true_test/hashcat_whirlpool_serpent-aes.tc:hashcat
true_test/hashcat_whirlpool_serpent-twofish-aes.tc:hashcat
true_test/hashcat_whirlpool_twofish-serpent.tc:hashcat
true_test/hashcat_ripemd160_aes_boot.tc:hashcat
true_test/hashcat_ripemd160_serpent_boot.tc:hashcat
true_test/hashcat_ripemd160_twofish_boot.tc:hashcat
true_test/hashcat_ripemd160_aes-twofish_boot.tc:hashcat
true_test/hashcat_ripemd160_aes-twofish-serpent_boot.tc:hashcat
true_test/hashcat_ripemd160_serpent-aes_boot.tc:hashcat
```

I've noticed it's only 30 executes in the shellscript, not 34!

I've successfully tested *all* of the following hardware/driver combinations with your script:

* GPU NVIDIA 750Ti + Driver 375.20
* GPU NVIDIA 1080FE * 3 + Driver 375.20
* CPU AMD fx6100 + AMDGPU-Pro 16.40
* CPU AMD fx8120 + pocl 0.14-pre, LLVM 3.8.0
* GPU AMD 290x + AMDGPU-Pro 16.40
* GPU AMD rx480 + AMDGPU-Pro 16.40
* CPU Intel 4770k + Intel OpenCL runtime 1.2 (Build 25)

I've even run it on Win7 with a Msys2 environment:

* GPU NVIDIA 980 + Driver 375.95
* CPU Intel 6700 + Intel OpenCL runtime 6.4.0.25

So the question remains why isn't it working for you. Usually that's because of an broken OpenCL runtime / installation. Please add it to this issue, post the output of "./hashcat -I" and if possible also the output of "clinfo". Ideally do a fresh clone of hashcat and do not forget to run "make clean" before compiling because of the changed variables in global memory.

**Comment by ghost** [comment]
Hi
It was 3am so that's my excuse for the miscount :-)

I've done what you suggested and scrubbed the hashcat dir and made a fresh build and yeah it has solved my issue, HC can now crack all 30.  I should have done that before made a report! oh well.
I haven't been messing around with anything within the hashcat dir so goodness knows what happened.

Thanks for your time thought Atom.

**Comment by jsteube** [comment]
OK, good to know, thanks!

Please close the issue
