### ISSUE TITLE
support for (OpenSSL) pkcs and pem private keys

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#74]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details: |  |
| --- | --- |
| Original reporter (OP): | crackall |
| Title: | openssl keys |
| Ticket number: | 447 |
| Date reported: | 2014-05-25T16:48:43+02:00 |
| **Description**: | Please add bruteforce [support for] OpenSSL pkcs and pem format private key with passwd<br>openssl genrsa [-out file.key] [-des | -des3 | -idea]<br>[note:] file.key - [is the] key with passwd, which need[s to be] crack[ed] |

---

| Comments: |  |  |
| --- | --- | --- |
| 1. | atom | please add more descriptions like algorithm, example hashes, etc |

**Comment by mpalmer** [comment]
This request really covers two completely separate things, and I think it's worth making separate "PEM" (PKCS#1/SEC1) and PKCS#8 modules, because they're quite different formats.

As I've started to do with #108, I can write the module-side code to parse keys and setup all the data structures for all these, and give all manner of interpretive advice, but the kernel is *probably* going to be better coming from someone who knows more applied crypto than me.

Here are some rough notes on how the formats hang together, to give anyone a taster of what sort of thing they'd be in for.

# PEM format

This is the one that starts "BEGIN (RSA/DSA/EC) PRIVATE KEY" and, for encrypted keys, has the DEK-Info/Proc-Type lines just under that.  The Proc-Type should always be `4,ENCRYPTED`, and the DEK-Info gives you the cipher and (hex-encoded) salt.  After a blank line, the rest of the body up until the "END (RSA/DSA/EC) PRIVATE KEY" is base64 ciphertext.

The KDF is a [rather unappetising single MD5 over passphrase and salt](https://github.com/openssl/openssl/blob/master/crypto/pem/pem_lib.c#L444).  The cipher can in theory be any ciphersuite someone has thought up and standardised, however because defaults, only a few like DES-EDE3-CBC and AES<various>-CBC are usually seen in the wild.

You can quickly check whether you've got a likely candidate by decrypting the first block of the ciphertext and seeing if it looks like a DER-encoded ASN.1 sequence with about the right length, followed by a DER-encoded ASN.1 integer.  Making *sure* you've cracked the case you need to decode the whole key and verify the padding, but of course that's best done only when decrypting the first block looks solid.

# PKCS#8

This is anything with a "BEGIN ENCRYPTED PRIVATE KEY" header, and everything else is a base64-encoded ASN.1 nightmare.  Everything is configurable, because of course it darned well is, but a typical profile would be PBKDF2 with HMAC-SHA256 2048 times, and AES256-CBC as the cipher.  Candidate checking is, once again, "does it look like a DER sequence of about the right length followed by an integer?", with a full decrypt+padding check for confirmation.

**Comment by jsteube** [comment]
Support was added with v6.2.0
