### ISSUE TITLE
potfile entries containing 4 or more colons are ignored

### ISSUE THREAD

**Issue by EvertDawn** [hashcat/hashcat#899]
While running some hashes through hashcat I noticed that some previously cracked hashes were being cracked more than once, despite already being in the potfile. After some experimenting I found that any potfile entry where the plaintext contains 4 or more colons (:) is not being removed from the target hashes when hashcat reads them before performing an attack. I was able to reproduce on two different machines using hashcat v3.20.

Here are some examples of potfile entries that would be ignored:
```
d77c7b5170e1933fc856d49a4ccbed9e:::::
5b42a3b76af065a7ceedfe79deb09f8a::::::
e901ae2f9efe2048407e33d4b1f474c5:password::::
45af598bbf7feabbd8b6057a02ba07c7:::a::
f2b5d671fb10148fa73086b7f0235071::a:a:a:
fd2352d050905ee5ccdbe823e23da913:my:password:is:very:secure
```
As you can see, the plaintext of each entry contains at least 4 colons, not including the separator.
Entries containing less than 4 colons work as expected:
```
e441fcf4a7686817fe868bf38a5c2c07::::
6a5e9867b6d5079043d1233073802bc0:password:::
165a2542704ebf6855d49508e3ab1f9d::a:a:
12d4a1593afad93656a2fd89a660f946:my:password:is:secure
```
A fix to this issue would help small salted hashlists containing these hashes crack significantly faster, without requiring the --remove option to be used as a workaround. It would also help reduce unnecessary duplicate-clutter from output files. Pretty trivial overall, but a bug nonetheless.

### To Reproduce:
Add the following MD5 hashes and plaintexts to 2 different files.
```
d77c7b5170e1933fc856d49a4ccbed9e
5b42a3b76af065a7ceedfe79deb09f8a
e901ae2f9efe2048407e33d4b1f474c5
45af598bbf7feabbd8b6057a02ba07c7
f2b5d671fb10148fa73086b7f0235071
fd2352d050905ee5ccdbe823e23da913
e441fcf4a7686817fe868bf38a5c2c07
6a5e9867b6d5079043d1233073802bc0
165a2542704ebf6855d49508e3ab1f9d
12d4a1593afad93656a2fd89a660f946
```
```
::::
:::::
password::::
::a::
:a:a:a:
my:password:is:very:secure
:::
password:::
:a:a:
my:password:is:secure
```
Run hashcat with the hashes and dictionary.
```
user@pc:~# ./hashcat64.bin -m0 colons.md5 -a0 colons.dict
...
Recovered........: 10/10 (100.00%) Digests, 1/1 (100.00%) Salts
```
Check the potfile for all 10 entries.
```
user@pc:~# cat hashcat.potfile
d77c7b5170e1933fc856d49a4ccbed9e:::::
5b42a3b76af065a7ceedfe79deb09f8a::::::
e901ae2f9efe2048407e33d4b1f474c5:password::::
45af598bbf7feabbd8b6057a02ba07c7:::a::
f2b5d671fb10148fa73086b7f0235071::a:a:a:
fd2352d050905ee5ccdbe823e23da913:my:password:is:very:secure
e441fcf4a7686817fe868bf38a5c2c07::::
6a5e9867b6d5079043d1233073802bc0:password:::
165a2542704ebf6855d49508e3ab1f9d::a:a:
12d4a1593afad93656a2fd89a660f946:my:password:is:secure
```
Run the same attack again.
```
user@pc:~# ./hashcat64.bin -m0 colons.md5 -a0 colons.dict
hashcat (v3.20) starting...
...
INFO: Removed 4 hashes found in potfile
...
d77c7b5170e1933fc856d49a4ccbed9e:::::
5b42a3b76af065a7ceedfe79deb09f8a::::::
e901ae2f9efe2048407e33d4b1f474c5:password::::
45af598bbf7feabbd8b6057a02ba07c7:::a::
f2b5d671fb10148fa73086b7f0235071::a:a:a:
fd2352d050905ee5ccdbe823e23da913:my:password:is:very:secure
...
```
Only the 4 entries with 3 or less colons were removed. The 6 entries with 4 or more colons were ignored, not removed, and needlessly cracked again.

[Here's an archive with the required files and hashcat v3.20 if that makes reproducing more convenient.](https://github.com/hashcat/hashcat/files/628745/colons.zip)

**Comment by jsteube** [comment]
Thanks for report and the analysis. You're absolutely right about how this works. However not a bug, it's a controlled compromise.

The reason for all this goes back to the problem that the format "hash:password" is a broken format itself, unless CSV would be handled correctly. But that's not the case. Even if hashcat could handle CSV correctly, other tools usually fail, and especially hashdumps you can find in the wild do. That's why I've never thought about adding true CSV parsing in here.

From a technical view, a program can not decide if it parses the string "hash:salt:pass:word" which part of it is the hash, the salt and the password. There's two ways to interpret it:

* "hash" is the hash, "salt" is the salt, "pass:word" is the password
* "hash" is the hash, "salt:pass" is the salt, "word" is the password

So the question is, how should we process is. This becomes very complicated and there's event different approaches. In hashcat we decided to use a strategy that if we split the string, but from the right to the left and not from the left to the right, we iterate through all possible variants and accept the first that makes it through the hash parsing check. To not run through this for an unlimited time, we set a maximum number of so called "MAX_CUT_TRIES". You can find that in include/common.h and it's currently set to 4, which matches your report.

We could increase that value now to something higher, but to which? If we set it to 8, the same problem will occur again if a user runs into the same problem you have but with 8 colons. A much better solutions would be to make the parser more like a real CSV parser that understands escaping. But if we do that, the potfile will become incompatible with out tools like JtR or others.

So we end up in a situation where we can only try to find a compromise and that's what we did.

**Comment by jsteube** [comment]
@magnumripper What do you think, should we add better RFC conform parsing of CSV to hashcat and JtR?

**Comment by magnumripper** [comment]
Honestly I don't think it would end up being used a whole lot IRL. We both already have the workaround of using a different field separator and it's nearly always safe using TAB (but obviously there are exceptions).

Unlike HC, JtR never ever *) use `:` as a salt delimiter, we usually use `$` or `*`. I guess that simplifies it a bit for us. Our pot file will always have the first `:` regarded as a field separator and any remaining ones will be regarded part of the plaintext.

*) Except for cases where eg. the user name field automatically is added as salt, but that's a different story.

**Comment by magnumripper** [comment]
Oh, and for salts containing a `:`, JtR has hex notation $HEX$dead3ababe for input files, similar to your plaintext $HEX[dead3ababe] for output files. I don't know if HC supports that?

**Comment by jsteube** [comment]
That seems to be an elegant solution to this problem, I think I'll add that.

**Comment by jsteube** [comment]
With commit https://github.com/hashcat/hashcat/commit/1342cf2ce34eb7337605fa66cd81035e27b3fa1f we changed the logic to use $HEX[...]  in case the separator character is used in the password. This will solve the problem shown in the initial post but requires the potfile to be build up from scratch.
