### ISSUE TITLE
Add --progress-only to be able to benchmark task related to the keyspace

### ISSUE THREAD

**Issue by s3inlc** [hashcat/hashcat#916]
Similar to the --speed-only feature of hashcat, it should be possible to benchmark a given task but not for the cracking-speed, but for how fast progress is made on the task.

This feature should test, how fast a fixed number of keyspace-steps on a given task is done. With the result it should be possible to be able to get an approximate time, how long the task will take for completion on the benchmarked machine.

The output could for example look like:
5000:14.3

This means that it took 14.3 seconds to make 5000 progress on the given task.

**Comment by jsteube** [comment]
I've add that with commit https://github.com/hashcat/hashcat/commit/ec5610271aae422cfe856bcf4870901baed35641

Please try and close the issue if that works for you.

Output looks like this:

```
root@ht:~/hashcat# ./hashcat example0.hash -a 3 ?a?a?a?a?a?a?a?a -w 3 --progress-only --mac
hashcat (v3.20-27-gf9ba949+) starting in progress-only mode...

1:327680:112190.53
Started: Fri Dec  9 23:46:09 2016
Stopped: Fri Dec  9 23:46:12 2016
```

The output is per device, ideal -l size and the time (in miliseconds). For example, if you want to calculate a runtime of ~ 10 Minutes, you'd do: 

1. (60 * 10 * 1000) / 112190.53 = 5,3480449731363244295218143634761
2. Round the result down, so result = 5
3. 5 * 327680 = 1638400
4. Use -l 1638400

**Comment by s3inlc** [comment]
Thanks a lot for implementing.
It seems to work, but I'm not sure if the result makes sense in this case:
```
$ hashcat/hashcat --machine-readable --opencl-devices=3 --hash-type=2711 hashlists/hl24 -a 0 files/wordlist.txt --progress-only
hashcat (v3.20-29-gf424650+) starting in progress-only mode...

3:131072:9.86
Started: Sat Dec 10 11:10:19 2016
Stopped: Sat Dec 10 11:10:34 2016
```
```
* Device #3: GeForce GT 650M, 256/1024 MB allocatable, 2MCU
```

I'm wondering a bit about the small time of 9.86 ms. If I use your calculation there, it would give me a huge length number which is much bigger than the whole keyspace. The length on this task should be something around 250000 to take ~10 mins on this computer.

**Comment by jsteube** [comment]
Can you please to find out if this is related to the number of salts? I
mean, try if it makes more sense if you use one salt or a non-salted
algorithm.

**Comment by s3inlc** [comment]
It seems to be related with the salts in some way. When I just use one of the hashes, the result will be the same. 
With non-salted algorithms the numbers are correct.

**Comment by jsteube** [comment]
OK, new commit pushed, also new beta up. This should fix the multiple salt issue. It actually was *just* a multiple salt issue. With a single hash, salted or not, the number was already correct as I've expected. 

More important, do not forget to add an amplifier (like rules) for fast hashes, otherwise you'll end up with bad numbers caused by pci-express overhead.

**Comment by s3inlc** [comment]
I tried now with the same salted hashlist again, it works as it should now.
```
$ hashcat/hashcat --machine-readable --opencl-devices=3 --hash-type=2711 hashlists/hl24 -a 0 files/wordlist.txt --progress-only
hashcat (v3.20-30-g367024d+) starting in progress-only mode...

3:262144:534965.57
Started: Sat Dec 10 16:23:32 2016
Stopped: Sat Dec 10 16:32:45 2016
```

As you see the benchmarking took quite some time, nearly as much as a chunk normally would be approximately. Is there a way that the number of keyspace progresses (like 262144 here) could be smaller?

**Comment by jsteube** [comment]
From what I can see from your output, the time to compute the ideal -l
value is around 7 seconds. That also includes initializing OpenCL
devices, compiling the OpenCL kernel, creating the wordlist cache and
doing the autotuning. However, from what you can see in the output, the
chunk will run 534 seconds, that's a lot more. than 7 seconds. I don't
understand why you can say that this is almost the same time?!

One note about the startup time: It will startup faster once the OpenCL
kernel and wordlist stat is cached. Basically each second time you call
a specific command. Anyway even 7 seconds for so much work is pretty
good I think.

I fully agree that a keyspace value should be small, because it makes
the distribution easier. However, a keyspace progress value of 262144 is
really good, but that is because you didn't specify to use -w 3. If you
do not set -w 3, hashcat operates at -w 2 which is the default. It can
be even smaller if you use -w 1, but it will reduce the performance,
too. That's the price of massive parallelized setups like GPU. You need
to have enough work for them. But as I said 262144 is really good. There
shouldn't be any problem with that value in a distributed setup.

**Comment by s3inlc** [comment]
Thanks a lot for explaining and implementing this. 
The changes provide what I need now.
