### ISSUE TITLE
Support for algorithm - pdf v1.1 - 1.3 owner password

### ISSUE THREAD

**Issue by modelkayak** [hashcat/hashcat#929]
Currently Hashcat (3.10) supports the user password, but does not support the owner password.  Can we add support to handle the owner password too?

Owner password can be used to lock down permissions, preventing printing/changing.

PDF info:

- https://www.cs.cmu.edu/~dst/Adobe/Gallery/anon21jul01-pdf-encryption.txt
- http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf, see section 3.5

**Comment by philsmd** [comment]
for you interest, I confirmed here: https://hashcat.net/forum/thread-6233-post-33255.html#pid33255 that the algorithms used for owner password vs user password are just slightly different (the example was with revision 3 PDF 1.4 - 1.6).
Unfortunately we probably have to do it for each and every PDF revision (+ write parser + new hash modes + kernels etc).... furthermore there is very little requests for this type of password recovery (probably because most of the users just simply work around the permission control of PDF and do not care about the owners password).
Well, if you still think it is worth the effort, you should give at least some thumbs up on this issue and we will rethink if we should implement it ;)

**Comment by roycewilliams** [comment]
I've added a thumbs up, but I have no real understanding of the level of effort required.

**Comment by Bobbingbob** [comment]
I too would love to see PDF owner password handling implemented.

**Comment by maxdestructo** [comment]
Just signed up to give a thumbs up. Please add pdf owner passwords to hashcat!

**Comment by ElDavoo** [comment]
Signing up, giving a thumbs up, necroposting and letting you know that someone actually bothered to implement it here https://github.com/hashcat/hashcat/pull/2739/commits/59b4a37355b10f7d15edd71f9c59f57651944972 , but for versions 1.4 - 1.6

**Comment by modelkayak** [comment]
> Signing up, giving a thumbs up, necroposting and letting you know that someone actually bothered to implement it here [59b4a37](https://github.com/hashcat/hashcat/commit/59b4a37355b10f7d15edd71f9c59f57651944972) , but for versions 1.4 - 1.6

Doing the computer god's work. Thanks for the heads up.

**Comment by ElDavoo** [comment]
> Doing the computer god's work. Thanks for the heads up.

I don't think the issue should be closed, though. The issue is about pdf v1.1-pdfv1.3, but the pull request is about 1.4-1.6, which is different.
