### ISSUE TITLE
Cygwin compilation of hashcat.dll

### ISSUE THREAD

**Issue by jsteube** [hashcat/hashcat#946]
Can someone please try if the new hashcat.exe/hashcat.dll concept works on native cygwin as well? 

The following supported OS so far have been tested and work: OSX, Linux, FreeBSD, Windows (Msys2)

@neheb From the CR's I can see you're using cygwin, maybe you can do a test?

**Comment by neheb** [comment]
It compiles fine. Not sure if you want any runtime validation(pthreads is broken for some reason).

**Comment by jsteube** [comment]
I don't understand. Do you mean it's not production ready?

**Comment by neheb** [comment]
No. I'll try working on it later today.

**Comment by jsteube** [comment]
I've just installed CYGWIN and added a few patches (for opencl.dll handling) but it works just fine. No problems with pthreads. Please verify!

**Comment by neheb** [comment]
My pthreads comment applies to SRC/affinity. Currently, I have it #if'd out to return 0. Cygwin doesn't provide any of the CPU_ functions, cpu_set_t or the pthreads function in that file.

Originally, I thought cyOpenCl failed to work properly because of that. But on closer inspection that code shouldn't have anything to do with it.

When I get home, I will do some further testing. That's really interesting that you got the regular Windows runtime to work under cygwin though. My thinking was that you couldn't mix regular win32 DLLs and cygwin(POSIX).

**Comment by neheb** [comment]
Update: alright this actually works great now. I ran cygwin through ssh (ssh 127.0.0.1) and was able to use the s key to pull up the status. No winpty needed.

**Comment by jsteube** [comment]
Yep, I noticed the same and was wondering. Was it different before?

**Comment by neheb** [comment]
For some reason it doesn't actually work with cygOpenCL. Hashcat launches and exits shortly after. I was never able to find the cause.

**Comment by jsteube** [comment]
OK, closing this then
