### ISSUE TITLE
Add option to run for a period of time, then create checkpoint and exit

### ISSUE THREAD

**Issue by chuckfw** [hashcat/hashcat#951]
I am looking into scripting a process to rotate different hashcat jobs, possibly running each one for on the order of 10-100 minutes at a time before switching jobs. The --runtime option to hashcat could be useful for this, but will result in some duplicated work since it exits immediately and the job would be restarted from the last checkpoint.

I suggest adding a command line option (perhaps --runtime-checkpoint) that will run for the specified amount of time, then go in to the "exit at next checkpoint" mode as if the user pressed 'c'. Alternatively, this command line option could be a flag that just indicates what hashcat should do when the time specified by the --runtime parameter is exceeded.

**Comment by jsteube** [comment]
The next version of hashcat (v3.30) which will be released in the next days have an even better solution to this. 

```
- New option --progress-only: Quickly provides ideal progress step size and time to process on the user hashes and selected options, then quit
```

That means you can precompute how to set the -l value. If you want to, for example, let hashcat run for 10 minutes and stop afterwards.

For example:

```
root@sf:~/hashcat# ./hashcat example0.hash -a 3 ?a?a?a?a?a?a?a?a --progress-only --mac
hashcat (v3.20-96-gaa89b8b+) starting in progress-only mode...

1:458752:59219.16
```

That means setting -l to 458752 (in this case) takes 59219.16 ms to progress. The good thing is, if you stick to a multiple of 458752  (in this case) hashcat can guarantee you to always run in full speed. So, if you want it to run for 10 minutes, You'd do something like:

1. ((10 * 60 * 1000) / 59219.16) = 10,131...
2. Either round up or down the result and multiple it with the 458752, ex: 10 * 458752
3. Use -l 4587520 and hashcat should show you a Time.Estimated ~ 10 Minutes
4. Because you have control over -l, you can control -s as well

Please close the issue if this works for you.

**Comment by jsteube** [comment]
Btw here's the issue with the details how it came to this (because it can be useful in distributed computing): https://github.com/hashcat/hashcat/issues/916

**Comment by chuckfw** [comment]
Yes, I think that the --progress-only feature will fit my needs. Thank you much.
