### ISSUE TITLE
insecure relative RPATH handling

### ISSUE THREAD

**Issue by anthraxx** [hashcat/hashcat#956]
hashcat adds a relative RPATH to the current directory, which has security implications and may cross privilege boundaries.
This issue can possibly be exploited by a local attacker to run arbitrary code as some other user if victim user can be convinced to run hashcat in an attacker controlled directory with specially crafted content.
RPATH should never be used for relative or world-writable paths.

**Comment by jsteube** [comment]
This is important to help the not so advanced users to be able to compile a native hashcat binary and run it without using the install target or using LD_LIBRARY_PATH. The only practical way I see to handle this is to remove the RPATH when using the make install target. What do you think?

**Comment by anthraxx** [comment]
well advanced user here or there but this is a security issue and especially non-advanced users are even less aware of the security implication :smile: 
yes, right now i simply strip out the whole rpath to mitigate this threat. stripping it on install would work for those, but the thing is, technically the users not using the install target will still be vulnerable to this problem. in my opinion people need to learn to make things work without the relative rpath to not expose anyone to a potential threat.

how about some kind of simply shell script with a readme block that aids non-advanced users to run it locally without installing it into the system?

**Comment by jsteube** [comment]
Teaching people how to use LD_LIBRARY_PATH is far too big of a goal for the hashcat project. The only solution is that we remove the rpath when the user uses make install target. How exactly did you do it? I see the tools "patchelf" and "chrpath" can do it. Which one would you suggest?

**Comment by anthraxx** [comment]
as said, you don't need to teach anyone about LD_LIBRARY_PATH if you have a wrapper script that does so and uses explicitly the directory where the shared lib was built in. Otherwise its still vulnerable for all people who don't use the install target.
The only solution to this issue is to not use relative rpath at all and add a wrapper script to start hashcat when not being in a 'installed' target, otherwise the users are always vulnerable to unintended code execution.

**Comment by jsteube** [comment]
I kind of agree, but such an wrapper script would confuse new users.
It's not very intuitive, so it's not a good solution. Do you have any
other ideas?

**Comment by anthraxx** [comment]
I don't see the difference, wherever you put you hashcat executable could be the place to have the hashcat wrapper script. Nobody would ever notice the difference if you adjust the install target accordingly and distribute the non-wrapper version instead. I honestly don't see where the problem is.

**Comment by jsteube** [comment]
Well as already discussed, the problem would occur only with the
self-compiled version which then is not used with the make install
target, because this target will have the rpath removed. That means that
an attacker would need to convince the victim to compile hashcat with
"make" but not to install it with "make install". After that, he need to
convince him to execute hashcat but before that, to change the cwd to a
different one first. This folder must be one that the attacker has
write-permission to. Do you agree so far?

If that's the case, only the "local" compiled version is a problem. This
version has the target output file named "hashcat" for purpose. It's
because it's the most intuitive output filename for the binary I can
think of what the user expect to have after the compilation. Now, as you
suggested, imagine we rename this binary to hashcat.bin and additionally
add a wrapper script called "hashcat" which then calls the
"hashcat.bin". New and unexperienced users will call this script before
they would even think about they have to compile hashcat in the first
place. They will execute it and get an error message because hashcat
does not exist. We can make it a good warning to inform the user to
compile the binary first, but most of them do not read. They will simply
close the shell, remove the hashcat folder and never try it again. The
user is probably lost forever. That's why I'm looking for a different
solution.

**Comment by anthraxx** [comment]
Why would they get an error message? You can easily put the wrapper somewhere else and handle it in the compilation step by moving it where the binary would be. No offense but I start having the feeling like you just don't want to solve this at all for people that use a local copy of hashcat and just keep them vulnerable because of "convenience" (where I still disagree that it can't be transparently solved if you really want to).
The concerns you mentioned are understandable, but as I pointed out, each one can be solved individually while still not requiring any rpath. I don't see why you can't have such wrapper and i don't see why it has to be there before having compiled the project.

**Comment by jsteube** [comment]
No absolutely not, I just want to find a good solution, that's all.
Another problem with such a wrapper script is that it needs to be
compatible with all the platforms where hashcat already works on. This
can be tricky to find a script which works for OSX, FreeBSD, Mingw,
MSYS2, Cygwin and Linux all at once. If you want, please send in a
script as PR and I'll merge it.

I also think of another solution. Maybe its better to step back to the
way it was before (statically compiled) but also add the shared library
usecase with a special "shared" Makefile target. Then we can remove the
rpath because people that compile the shared library explicitely also
know how to handle LD_LIBRARY_PATH.

**Comment by anthraxx** [comment]
@jsteube sometimes its hard to get intentions and thoughts of someone else over pure text, but i'm very happy to hear this, so excuse my interpretation :smile_cat: 

Luckily the script doesn't need anything complex, just resolving basedir of itself and use LD_LIBRARY_PATH or DYLD_LIBRARY_PATH before calling the real hashcat binary. While I don't have environments set up to test all those, I can help getting the script and Makefile working... you could then test it in your supported environments.

The latter solution sounds also fine. Is it correct when I would expect the 'shared' make target to produce both artifacts, the libhashcat.so and the hashcat binary that dynamically links to it and the 'default' make target that simply produces a statically linked version? Both solutions sound fine to mitigate the relative rpath... its all up to you're preference :smiley:

**Comment by jsteube** [comment]
I tend to the 2nd version but I need to think about it some more time.

**Comment by jsteube** [comment]
OK, I've implemented as we discussed the 2nd solutions. So we've completely removed rpath :)

**Comment by anthraxx** [comment]
@jsteube cool, thanks :+1:
