### ISSUE TITLE
CL_OUT_OF_RESOURCES

### ISSUE THREAD

**Issue by marukka** [hashcat/hashcat#976]
I am receiving CL_OUT_OF_RESOURCES errors from clFlush() and clEnqueueWriteBuffer() with hashcat64 3.30 in a Windows 10 Enterprise build 1607 virtual machine using the Nvidia 373.06 driver for a pair of EVGA GTX 980 SuperClocked GPUs. The host is running VMware ESXi 6.5, and the virtual machine has latency sensitivity set to high and 100% CPU reservation. This only seems to happen when the second GPU is used. If -d 1 is specified on the command line, hashcat will work. If -d 2 is specified it will not. I noticed that you frequently post "I may have the wrong driver installed, what should I do?" FAQ entry, but after comparing the checksum of C:\Windows\system32\OpenCL.dll with C:\Program Files\NVIDIA Corporation\OpenCL\OpenCL64.dll the files are the same and it has not been overwritten with a different version.

**Comment by jsteube** [comment]
Please do not run any OpenCL application inside a VM, the OpenCL runtimes are instable enough. Please retry on the host directly.

**Comment by marukka** [comment]
Unfortunately this request isnt exactly practicable. If you dont intend on supporting virtualized environments then just close this out. Although I think especially in the future you'll see more and more people run this in those environments.

**Comment by epixoip** [comment]
This isn't a hashcat issue, there is nothing we can do to "support virtualized environments." Your beef is either with ESXi's VGA passthrough, or with the Nvidia driver, or a combination of both. May even be a buggy IOMMU on your motherboard triggering a bug in either of those as well, or perhaps your IOMMU is not fully supported by ESXi. VGA passthrough is very experimental and only a handful of hardware support it properly, there are simply too many variables for us to attempt to help you troubleshoot your setup. Or, you know, you could actually just be out of resources (have you actually checked that?) Anyway, regardless of what is triggering this, it is emphatically _not_ a hashcat issue.

**Comment by marukka** [comment]
The CPUs and chipset set is a pair of Xeon E5-2660 v2 and a Intel C602 (on a SuperMicro X9DAE). Both are rather common pieces of hardware, which are widely used with environments with PCIe pass through.

PCIe passthrough is not "very experimental". I'm not sure where you're getting this from. VT-d has been around for since the late 2000s, this isnt some bleeding edge feature.

No the VM isnt out of resources. It has 4 cores and 16GB RAM allocated to it with 100% resource reservations and all it is doing is running hashcat. The cards are identical, and this will happen even if I try it with a file with only a single SHA1 hash.

And there is not "too many variables" for you to attempt to determine the root cause. FFS if you even google the error message, you'll see plenty of posts from other developers talking about how it is just a generic error message Nvidia will return for OpenCL apps when any number of problems go wrong such as kernel launch time exceeding a timeout, and you're just taking it literally without consulting Nvidia's documentation.

I've been looking in to this some more and I do think I've found the root cause, which of course is a bug in hashcat. The kernel launch time is exceeding the timeout value on Windows (default of 2 seconds) and Windows is killing the driver because it thinks it crashed. The reason it works with one specific GPU is that GPU doesn't have a display attached to it, so the TDR functionality is disabled for it. Playing around with the TDRDelay registry value seems promising so far, I'll continue to test it more tomorrow and report back with more details.

See:
https://devtalk.nvidia.com/default/topic/461532/cuda-programming-and-performance/cl_out_of_resources/post/3278455/#3278455
http://mcx.sourceforge.net/cgi-bin/index.cgi?Doc/FAQ#Does_MCX_support_multiple_GPUs_in_a_single_computer
https://msdn.microsoft.com/en-us/library/windows/hardware/ff570087(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/hardware/ff569918(v=vs.85).aspx

**Comment by epixoip** [comment]
VT-d has been around for a while, yes. But it is also broken on a lot of motherboards (BIOS doesn't implement it at all, or implements it incorrectly, or has corrupt/missing/incomplete IVRS tables), and even broken in some chipsets (e.g. broken interrupt remapping) and CPUs as well (Intel shipped an entire generation of CPUs with a bad VT-d implementation, and I don't think AMD-Vi has ever _actually_ worked.) So while the concept isn't new, it's not something that's actually widely supported.

That said, I'm not aware of any issues with Ivy Bridge-E or C602, but there may be issues still with the BIOS on your board, I don't know. I do know that our Gen2 Brutalis platform had the same C602 chipset you have, and I remember experiencing constant ASIC hangs and Oopses. But that very well may have been a software issue, not a hardware issue.

Sorry, but VGA passthrough is indeed still in its infancy (and do not conflate PCI passthrough with VGA passthrough.) ESXi certainly has better support than Xen or KVM, but the last time I tried to use it (ESXi 5.5, Xen 4.2), it was either really buggy or entirely nonoperational on all of my boards.

"There are not 'too many variables'" -> "just a generic error message when any number of problems go wrong." Do I even need to comment on this?

Don't accuse us of not consulting documentation. We practically have that entire documentation memorized.

Driver timeout is hardly a bug in hashcat, the issue has been [well-documented](https://hashcat.net/wiki/doku.php?id=timeout_patch) on our Wiki for several years, which even includes both a registry patch and an xorg.conf patch. ~~Hashcat even tries to warn you if this patch has not been applied.~~ Never mind, looks like we removed the warning in 3.20 as we didn't feel it was necessary any longer with autotuning.  I suppose it is possible that autotuning is not very accurate in a virtualized environment. You could always try using a lower -w value if the timeout patch doesn't resolve the issue and you're intent on using hashcat in a vm. But I'm still not convinced this will actually fix anything. I've not had a single positive experience with VGA passthrough so I'm still leaning toward the issue lying somewhere in there.

Regardless, still not a bug in hashcat.

**Comment by marukka** [comment]
I still need to continue testing, or as you recommended disable TDR all together. But to reply to your comments on your experiences with passing through video cards, I've only noticed two issues with other applications. When playing games at 4k resolution with SLI enabled, in full screen mode the screen with have a strong purple tint and strobe effect. This can be worked around by running games in borderless windowed full screen mode or disabling SLI. The second being a compatibility issue between Nvidia's driver and the VMware SVGA driver, which causes the Nvidia driver to constantly crash. Disabling the VMware driver resolves the issue, and the only loss of functionality i've seen is that the remote console doesnt support things like automatically changing the resolution when you make it full screen. Otherwise everything works perfectly.

I'm not saying this should be a standard test environment of yours, but if you ever decide to give it another try (and assuming you'd use ESXi and a GeForce card) there are a couple things you need to. Since Nvidia didnt want to cannibalize their "professional" product line,  they added a basic virtualization check to their driver to prevent it from running in virtualized environments with GeForce series cards. If you add `hypervisor.cpuid.v0 = false` to the VMX file of the VM, you can work around this restriction. And although this shouldnt be relevant from my reading of your documentation regarding SLI, if you need to enable SLI you can patch the drivers with DifferentSLI Auto 1.5 to remove the license check. VMware doesn't present a SLI license in the VM's BIOS if one is present on the motherboard (which it is in the case of my X9DAE). Personally I think it should, see how they support Apple's OS X license checks on Apple hardware, but I digress.

**Comment by marukka** [comment]
So i've been playing around with the TDR timeout values some more. Setting it to 300 (5 minutes) allowed hashcat to run for 9 or 10 minutes before it terminated. Setting it to 600 (10 minutes) has allowed it to run for well over half an hour now. But I have noticed some unexpected behavior, and I can only assume the root cause of it (whatever it may be) is what is causing this problem. For some reason the load on the 2nd GPU is fluctuating significantly. It will be at ~100% for a while and then drop down to 0% for a while as you can see in this screenshot. It will continue to oscillate back and forth between ~100% and 0% every few minutes. Do you guys have any idea why this might happen?

![hashcat](https://cloud.githubusercontent.com/assets/3067075/23093320/86ef4aca-f5a5-11e6-9ac0-ae0a7d2b08a7.png)

Also when this happens, even though hashcat reports the load as 0% (and the card temperature seems to confirm this) it will erroneously report a large processing rate under Speed.Dev.#2. After a few minutes the Speed.Dev.#2 value begins to drop.

**Comment by jsteube** [comment]
OpenCL is a nieche product and does not have many users giving feedback. Therefore you need to expect multiple bugs in the vendor's driver and their OpenCL runtimes. When we reports bugs, they are typically silenty ignored because from a vendors perspective there's not enough money in fixing those. That's why I said that you shouldn't use a VM.

However, as @epixoid already mentioned, this is not a hashcat issue. We can't fix the vendors drivers. Also, when it comes to multiple GPU support, this is well tested by many hashcat users, even mixed types.

**Comment by marukka** [comment]
So basically what you're saying is that your code is infailable, and that everyone else must be at fault. And that your programming skills make you a god among men. We just confirmed that your code is timing out and triggering the TDR in Windows, yet you're blamining everyone else. Whats next, when hashcat segfaults you're going to blame everyone else too for your code accessing an illegal address because the kernel should simply let you access any memory address you desire? Wow you've been blown the fuck out.

**Comment by marukka** [comment]
And to comment on your claim that there is no money in GPU computing for Nvidia, please explain their Tesla line of cards.

**Comment by jsteube** [comment]
That's not what I'm saying and I think there's some misunderstand here.
We're not that kind of developer who ignore users feedback. We care
about and we feel no shame admitting bugs if there are any. You can see
that from hashcat's changelog, it's full with descriptions about fixed
bugs.

But in your case, you are wrong. The observation with the TDR settings
are just a fix to a symptom, but not the problem. The problem is that
the timing numbers from your SHA1 are ways too high (you can see it in
the screenshot after the speed). They should be around 90ms (in -w 3
mode). Also, if single GPU's randomly drop in utilization that's
something we've experienced in the past already, and it's always
something wrong on a lower level, for example the OpenCL runtime or the
device driver or on the hardware layer the MB or the PSU or even a
broken GPU. But all of this stuff is out of our reach to fix

**Comment by marukka** [comment]
I apologize as I may have been a bit rash. But my point I think still stands. Take for instance the FDIV bug in old Intel Pentiums. When it was discovered the entire x86 computing industry didnt throw its hands up in the air and say, oh well too bad, it isnt our problem its Intels. Instead they worked around it, companies like MathWorks implemented software floating point routines for their products, and companies like Microsoft added switches like /QIfdiv to their compilers to use software floating point routines when it detected it was running on an effected chip.

And although reporting a bug doesnt guarantee it will get fixed, a perfect example being my bug report right here, if _you_ never report it upstream then that is a guarantee that it will never be fixed.

Now i'll play devils advocate for a moment and assume this is a problem with a 3rd party you have no control over. You still can fix this bug. As we've discovered here, changing the TDR timeout works around the problem. All you have to do is have hashcat set a registry key and restart the driver or reboot the computer to make it take effect. As @epixoip said, hashcat used to at least display a warning in prior versions but this functionality was removed. Well as my case demonstrates, and as you say this is something "we've experienced in the past", there clearly seems to be a demand for this feature. Now of course this isnt the best fix as the GPU doesn't remain loaded constantly but some additional computing power is better than none.

**Comment by marukka** [comment]
Also it would be nice if you could address hashcat incorrectly reporting device performance. Specifically it saying Speed.Dev.#2 has a non-zero value when the load is 0% in my previous screenshot.

**Comment by jsteube** [comment]
I don't think thhat's comparable. When it comes to the OS they have
large access to the system hardware and can workaround a specific bug.
In OpenCL, all we have is an API and we have to follow the way the API
has to be used. If the path we are forced to use is broken, there's
simply no way for us to workaround.

Again, if this would be a problem that we could workaround, we'd do it.
The example you gave with modify the registry however is not possible.
For one it eventually requires administrative permissions and a user
would be confused if we ask for it. Since we're in the scope of security
software people are even more sharp about it. Another reason is that we
can not simply restart the driver because there might be other
applications already running and using the OpenCL interface (or any
other GPU related API) and we'd break those.

I've personally reported bugs to nvidia but as I said, they are ignored.
Reason is, again, because OpenCL is a nieche product and they don't care
if there are any bugs. But said so, feel free to report it yourself.

**Comment by jsteube** [comment]
There's none, but you need to understand how NVML and OpenCL measures
these units. For NVML, it's unknown because it's closed source. For
OpenCL, there's no function inside the API. We measure it simply by
dividing the number of hashes calculated with the time it took from the
start of the OpenCL kernel till it's return (and eventual copy
transactions before). So this is a blocking function which means it's
either finished or not. There's no way for us to know what's actually
going on on the GPU.

**Comment by marukka** [comment]
The FDIV bug wasnt worked around at the OS level afaik. It was worked around either in programs specifically such as MathWorks, or at the compiler level as with MS's VisualStudio compiler.

If you are concerned about user confusion regarding UAC prompts you can present a prompt beforehand. And if people are that worried about security then they'll be either running it in a VM like myself or on dedicated hardware which will be reimaged after use, which they wont care about a registry change on anyways.

Regarding other applications being broken by a driver restart, when this bug occurs it will break them anyways when the driver is restarted by TDR. And again if you are concerned about this, a prompt can be displayed before making this change.

If you dont like my ideas then fine, its your product, not mine. But at least consider re implementing the message @epixoip said was in version 3.2. It at least will help some other people.

Although this would be a much more time consuming (and thus a more unreasonable request), if you guys dont like OpenCL as much you can always try adding support for CUDA which gives the impression has better support from Nvidia.

**Comment by jsteube** [comment]
What I wanted to say is that there's simply no different path if you
have to navigate inside an API rather than a free environment like an OS
(or Application context). Therefore a workaround is sometimes possible,
but not in this case.

Such an applications break by driver restart event will not occur if the
error itself would not occur. That's why it's more important to fix the
problem rather than to try to workaround. You also have no guarantee
that the workaround will work as wanted. Whenever some situation is out
of control, everything can happen. That could be, for example, false
negatives and that's something you really don't want in a password
cracking tool. It would be not maintainable for developers because each
new error could be caused by the workaround and you can not know or not
know.

I don't think it makes sense to reimplement that error message. In the
past it had confused people more than it helped, especially new and
unexperienced users.

In case you don't know, but hashcat in the past was 50/50 OpenCL/CUDA.
There's multiple problems with CUDA from a technical perspective but the
most important difference is that CUDA does not support AMD GPU or Intel
CPU while OpenCL does.

**Comment by marukka** [comment]
It certainly is possible, not only in the ways I mentioned previously, but in the case of this error, resubmitting the workload, or detecting which GPU timed out and disabling its use. If you would rather  fix the root cause of the problem rather than work around it, then please, go open a support case with Nvidia. But as you've said repeatedly in this thread, you're not interested in doing that, or seemingly anything else about it other than say it exists, and has existed for a long time. You're in a far better position than myself to open a support case with Nvidia as you're actually familiar with the code base.

And regarding false negatives, that is a ridiculous example. The overwhelming majority of systems running hashcat wont have ECC GPU or CPU memory. In the product pics of @epixoip 's Sagitta Brutalis with its base price of $18k, it shows it uses Radeons, not Quadros or Fire Pros which have ECC memory. If anyone was worried about false negatives, it would be his customers, and he would be advertising this system with Fire Pros/Quadros/Teslas if this was a concern of his customers.
