### ISSUE TITLE
veracrypt cracking not working if password is longer than 54 characters

### ISSUE THREAD

**Issue by vvivzkqc** [hashcat/hashcat#983]
windows
VeraCrypt PBKDF2-HMAC-SHA512 + XTS 1536 bit

max characters for veracrypt gui:
64
hashcat is not working in range 55-64
otfbrutus is working fine

example
password(55 chars):
hashcathashcathashcathashcathashcathashcathashcathashca
first 512 bytes:
24CEC0FADE6589440D650D278BC88C4A1FC6627E66578B3493B06AC761450D0AB383AE99A8E3385756B1CEFEE0765EF0CCF636F85F18EA77116B9DD7FD1A507CA514F257748E3E9B2FDEA244AB18F53C8E074BC8FE3FE7BDC1D983CF533B34C7A0C0E0E9CB1F2B7A51B501ADE501B439F0A5E613A31922EE70DF1C53FBD3855D5C221D9AA5B30EAC04A56E5301EA74477088886A8759C16D1B8555E9D4DF2422E9BDC6AE885E508BEA2CCFCA4C1C4F9F390B331461277A1A34311B289792226C9B8E4C4A9B3E1B207FCDCC9EDF0C89A395E37160B81A018C33BC8E73B72D9D1B5BC0B80E9383C0211FF15984E2F46EA7138E6CB9367CA15E7C126B75CF257830F1FF1CFD1C45E3B38EFF20FB173BA1E0F5C65FFC2D0604E6F25E414723D67B029C762B9F7C64B1A8678BDC00134DFFA3CF6ED57FC29AB4BCD5D929259439F3BFE9903104E913AC09873A5385C69AEFF155318982EA451DFFE71E7F912186002619113893A3A579CC648F49CCD51052DCC218BC1CBE41126A9C62770B20856B5A84E799D4B367E00B36904AC38CF407C1889307F5A7E1013F385D4FAA0DB595D27A1DEF476BB01B4FDC7ACF5B4F6A9A19748022C6FE3423E63C295AA4CF09E2232E35FAA4BD2462A56AB4CF2BE196051C86DC51D0B503395D8774DB3458D3B6957FCE963B3027AE3CAF88268B16233B6266550911BCC63CDDF0DAE4F0F1FBE878
command:
hashcat64 -m 13723 55char.hash dict.txt

**Comment by philsmd** [comment]
This is a general limitation for password candidates, see https://hashcat.net/faq#what_is_the_maximum_supported_password_length

The reasons (in general) are that it is very difficult to crack (do not even mention brute-force) a password that is that long, the performance drop that would affect many algorithms if several transforms etc must be done because of the longer length and of course that the general user uses very short and easy to remember passwords (this might not be applicable for veracrypt, but definitely for most of the other algorithms).

I would not call this an issue. This is a known limitation and it makes sense in almost all of the cases to prefer better performance instead of absurdly long passwords (at least in the perspective of an attacker which even has difficulties to crack passwords > 8 characters) that without knowing the password (or having it in the word list) you wouldn't crack in centuries.
