### ISSUE TITLE
Hashcat 3.30 and resume

### ISSUE THREAD

**Issue by ArchWolfdale** [hashcat/hashcat#998]
# Description of the issue
There is a problem with the resume function, specifically with the current working directory saved in the resume file. Also there is an unexpected behaviour (2) of the new option in Hashcat v3.30 --restore-file-path
## Steps to reproduce the issue
I ran this command with CWD `/root/`, while hashcat folder is located at `/root/hashcat-3.30/`
```
hashcat-3.30/hashcat64.bin -m 0 -a 3 md5.txt ?l?l?l?l
```
The expected behaviour is that the .resume file, the .log file, and the .pot file will be saved in  `/root/ ` (because it is the cwd)
Instead they are saved in  `/root/hashcat-3.30`
# Description of the issue (2)
--restore-file-path has an unexpected behaviour
## Steps to reproduce the issue
The command 
```
hashcat-3.30/hashcat64.bin -m 0 -a 3 md5.txt ?l?l?l?l --restore-file-path /root/testsession
```
creates a restore file in the `/root/` folder called `testsession.restore`, which is the expected behaviour.
The problem is that when you try to resume with that file:
```
root@ubuntu:~# hashcat-3.30/hashcat64.bin --restore --session testsession
hashcat (v3.30) starting in restore mode...

Restore file '/root/hashcat-3.30/testsession.restore': No such file or directory
```
Hashcat tries to search in its directory, irrespective of where the restore file is.
## References
The forum thread of this issue
[Forum Thread](https://hashcat.net/forum/thread-6238.html)

**Comment by philsmd** [comment]
I had a quick glance at this problem and tested it, but I came to the conclusion that you just miss the --restore-file-path within the last command (the actual restore step).

Hashcat doesn't store the "last-used-restore-path" anywhere, so it doesn't have the information where the restore file that you wanted to run, is located.

You need to use something like this:
`./hashcat64.bin --session testsession --restore --restore-file-path /root/testsession`

To sum it up, hashcat either can automatically look up for the file [session_restore].restore in the default directory, but whenever you use a custom path for the restore file (--restore-file-path), you need to specify that path on both runs (the actual start of the cracking and the restore step).

Does it work for you with --restore-file-path when restoring? Do you agree that this makes sense?
Please don't forget to close the issue if you agree that this is expected behaviour.
Thanks

---

update: almost forgot about the first issue: hashcat doesn't work with the cwd, because users complained about files being created all over there file system, so it uses the path specified in the (profile directory: it is the home directory + ".hashcat/" - aka ~/.hashcat/ - per default if you use make install, or the download directory otherwise)

**Comment by ArchWolfdale** [comment]
Yeah, it's just like you said, I was using the --restore-file-path option in the wrong way. Now it's working beautifully!
Thank you for the tip about the cwd, can you tell me how to specify the path in the profile directory?
